export const vocab = {
  title: "Couleurs & Formes",
  words: [
    { word: "red", translation: "rouge", example: "The apple is red." },
    { word: "blue", translation: "bleu", example: "The sky is blue." },
    { word: "green", translation: "vert", example: "Grass is green." },
    { word: "yellow", translation: "jaune", example: "The sun is yellow." },
    { word: "black", translation: "noir", example: "I wear black shoes." },
    { word: "white", translation: "blanc", example: "Snow is white." },
    { word: "brown", translation: "marron", example: "The table is brown." },
    { word: "pink", translation: "rose", example: "She likes pink flowers." },
    { word: "purple", translation: "violet", example: "The dress is purple." },
    { word: "orange", translation: "orange", example: "The orange is orange." },
    { word: "grey", translation: "gris", example: "The cat is grey." },
    { word: "silver", translation: "argenté", example: "I have a silver ring." },
    { word: "gold", translation: "doré", example: "The watch is gold." },
    { word: "light", translation: "clair", example: "Light blue is pretty." },
    { word: "dark", translation: "foncé", example: "I prefer dark colors." },
    { word: "bright", translation: "vif", example: "This is a bright color." },
    { word: "pale", translation: "pâle", example: "She has pale skin." },
    { word: "colorful", translation: "coloré", example: "The painting is colorful." },
    { word: "color", translation: "couleur", example: "What color do you like?" },
    { word: "rainbow", translation: "arc-en-ciel", example: "I can see a rainbow." },
    { word: "circle", translation: "cercle", example: "Draw a circle on paper." },
    { word: "square", translation: "carré", example: "The box is square." },
    { word: "triangle", translation: "triangle", example: "A triangle has three sides." },
    { word: "rectangle", translation: "rectangle", example: "The window is rectangle." },
    { word: "round", translation: "rond", example: "The ball is round." },
    { word: "straight", translation: "droit", example: "Draw a straight line." },
    { word: "curved", translation: "courbé", example: "The road is curved." },
    { word: "shape", translation: "forme", example: "What shape is this?" },
    { word: "line", translation: "ligne", example: "Draw a line here." },
    { word: "corner", translation: "coin", example: "Put it in the corner." },
    { word: "edge", translation: "bord", example: "Be careful of the sharp edge." },
    { word: "side", translation: "côté", example: "This side is longer." },
    { word: "point", translation: "point", example: "The pencil has a sharp point." },
    { word: "flat", translation: "plat", example: "The table is flat." },
    { word: "pattern", translation: "motif", example: "I like this pattern." },
    { word: "big", translation: "grand", example: "The house is big." },
    { word: "small", translation: "petit", example: "The mouse is small." },
    { word: "large", translation: "grand", example: "We need a large box." },
    { word: "tiny", translation: "minuscule", example: "The ant is tiny." },
    { word: "huge", translation: "énorme", example: "The elephant is huge." },
    { word: "thick", translation: "épais", example: "The book is thick." },
    { word: "thin", translation: "mince", example: "The paper is thin." },
    { word: "wide", translation: "large", example: "The road is wide." },
    { word: "narrow", translation: "étroit", example: "The street is narrow." },
    { word: "tall", translation: "haut", example: "The building is tall." },
    { word: "short", translation: "court", example: "My hair is short." },
    { word: "long", translation: "long", example: "The rope is long." },
    { word: "deep", translation: "profond", example: "The lake is deep." },
    { word: "shallow", translation: "peu profond", example: "The water is shallow." },
    { word: "size", translation: "taille", example: "What size do you need?" },
    { word: "soft", translation: "doux", example: "The pillow is soft." },
    { word: "hard", translation: "dur", example: "The rock is hard." },
    { word: "smooth", translation: "lisse", example: "The table is smooth." },
    { word: "rough", translation: "rugueux", example: "The wall is rough." },
    { word: "hot", translation: "chaud", example: "The coffee is hot." },
    { word: "cold", translation: "froid", example: "The ice is cold." },
    { word: "warm", translation: "chaud", example: "The room is warm." },
    { word: "cool", translation: "frais", example: "The evening is cool." },
    { word: "wet", translation: "mouillé", example: "My clothes are wet." },
    { word: "dry", translation: "sec", example: "The towel is dry." },
    { word: "clean", translation: "propre", example: "My hands are clean." },
    { word: "dirty", translation: "sale", example: "The car is dirty." },
    { word: "shiny", translation: "brillant", example: "The mirror is shiny." },
    { word: "dull", translation: "terne", example: "The old coin is dull." },
    { word: "clear", translation: "transparent", example: "The water is clear." },
    { word: "blurry", translation: "flou", example: "The photo is blurry." },
    { word: "sharp", translation: "pointu", example: "The knife is sharp." }
  ]
};