version = 1

[[analyzers]]
name = "javascript"
enabled = true

# Exclure les tests et fichiers de configuration
exclude_patterns = [
  "__tests__/**",
  "**/*.test.js",
  "**/*.test.jsx",
  "**/*.spec.js",
  "**/*.spec.jsx",
  "maestro-tests/**",
  "coverage/**",
  "**/node_modules/**"
]