export const vocab = {
  title: "Économie Politique & Systèmes Mondiaux",
  words: [
    // Géopolitique économique
    { word: "geoeconomic strategy", translation: "stratégie géoéconomique", example: "The nation's geoeconomic strategy seeks to secure critical resources through international partnerships." },
    { word: "economic statecraft", translation: "diplomatie économique", example: "Sanctions are a form of economic statecraft used to influence foreign policy outcomes." },
    { word: "strategic resource", translation: "ressource stratégique", example: "Rare earth minerals have become a strategic resource in high-tech manufacturing competition." },
    { word: "economic diplomacy", translation: "diplomatie économique", example: "Economic diplomacy played a crucial role in negotiating the trade agreement." },
    { word: "economic corridor", translation: "corridor économique", example: "The Belt and Road Initiative establishes economic corridors connecting China to European markets." },
    { word: "supply chain security", translation: "sécurité de la chaîne d'approvisionnement", example: "The pandemic exposed weaknesses in global supply chain security for essential goods." },
    { word: "strategic investment", translation: "investissement stratégique", example: "Foreign direct investment in ports is often seen as strategic investment with security implications." },
    { word: "economic leverage", translation: "levier économique", example: "Market access provides economic leverage in international negotiations." },
    { word: "commercial intelligence", translation: "intelligence commerciale", example: "Commercial intelligence gathering helps companies navigate unfamiliar markets." },
    { word: "geoeconomic competition", translation: "compétition géoéconomique", example: "Geoeconomic competition between major powers has intensified in the technology sector." },
    { word: "economic coercion", translation: "coercition économique", example: "Trade restrictions can function as economic coercion to achieve political objectives." },
    { word: "market access", translation: "accès au marché", example: "Negotiations focused on improving market access for agricultural exports." },
    { word: "economic containment", translation: "endiguement économique", example: "The policy resembles economic containment of rival economic powers." },
    { word: "trade dependency", translation: "dépendance commerciale", example: "Asymmetric trade dependency creates vulnerability to economic pressure." },
    { word: "resource nationalism", translation: "nationalisme des ressources", example: "Resource nationalism has led many countries to restrict foreign ownership of minerals." },
    { word: "energy geopolitics", translation: "géopolitique énergétique", example: "Pipeline construction reflects the complex energy geopolitics of the region." },
    { word: "strategic industry", translation: "industrie stratégique", example: "Semiconductor manufacturing is considered a strategic industry with national security implications." },
    { word: "economic vulnerability", translation: "vulnérabilité économique", example: "Import dependence for critical supplies creates economic vulnerability during crises." },
    { word: "financial warfare", translation: "guerre financière", example: "Restricting access to payment systems is a form of financial warfare." },
    { word: "geoeconomic power", translation: "puissance géoéconomique", example: "China's geoeconomic power has grown substantially through strategic investments worldwide." },
    { word: "economic sphere of influence", translation: "sphère d'influence économique", example: "Regional trade agreements can establish an economic sphere of influence." },
    { word: "strategic economic partnership", translation: "partenariat économique stratégique", example: "The nations signed a strategic economic partnership focused on technology development." },
    { word: "economic interdependence", translation: "interdépendance économique", example: "Economic interdependence between the countries complicates political tensions." },
    { word: "economic intelligence", translation: "intelligence économique", example: "Economic intelligence helps identify opportunities and threats in global markets." },
    { word: "geopolitical risk", translation: "risque géopolitique", example: "Companies must factor geopolitical risk into investment decisions in unstable regions." },
    { word: "economic alignment", translation: "alignement économique", example: "Trading patterns reflect growing economic alignment with the new regional power." },
    { word: "strategic economic security", translation: "sécurité économique stratégique", example: "The policy prioritizes strategic economic security over short-term commercial gains." },
    
    { word: "resource diplomacy", translation: "diplomatie des ressources", example: "Resource diplomacy aims to secure access to critical minerals through international agreements." },
    { word: "rival economic bloc", translation: "bloc économique rival", example: "Trade tensions between rival economic blocs have increased in recent years." },
    { word: "economic decoupling", translation: "découplage économique", example: "Economic decoupling between the two largest economies would significantly disrupt global trade." },
    
    // Organisations supranationales
    { word: "multilateral institution", translation: "institution multilatérale", example: "The World Trade Organization is a multilateral institution that regulates international trade." },
    { word: "supranational governance", translation: "gouvernance supranationale", example: "The European Union represents the most developed form of supranational governance." },
    { word: "transnational network", translation: "réseau transnational", example: "Civil society organizations form transnational networks to address global challenges." },
    
    { word: "global regulatory body", translation: "organisme de régulation mondial", example: "The Basel Committee serves as a global regulatory body for banking standards." },
    { word: "collective security", translation: "sécurité collective", example: "NATO was founded on principles of collective security among member states." },
    { word: "consensus decision-making", translation: "prise de décision par consensus", example: "The organization relies on consensus decision-making, which can slow responses to crises." },
    { word: "multilateral diplomacy", translation: "diplomatie multilatérale", example: "Climate negotiations demonstrate the challenges and potential of multilateral diplomacy." },
    { word: "international secretariat", translation: "secrétariat international", example: "The international secretariat coordinates activities across member countries." },
    { word: "treaty obligation", translation: "obligation conventionnelle", example: "Member states must fulfill their treaty obligations or face potential sanctions." },
    { word: "supra-state entity", translation: "entité supra-étatique", example: "The organization functions as a supra-state entity with limited sovereignty in specific domains." },
    { word: "extraterritorial jurisdiction", translation: "juridiction extraterritoriale", example: "The court claims extraterritorial jurisdiction over certain international crimes." },
    { word: "multilevel governance", translation: "gouvernance à multiniveaux", example: "Effective climate policy requires multilevel governance from local to global scales." },
    { word: "veto power", translation: "droit de veto", example: "Permanent Security Council members can exercise veto power over resolutions." },
    { word: "international mandate", translation: "mandat international", example: "The peacekeeping mission operates under an international mandate from the United Nations." },
    { word: "regional bloc", translation: "bloc régional", example: "ASEAN functions as a regional bloc promoting economic integration in Southeast Asia." },
    { word: "representative allocation", translation: "allocation représentative", example: "The organization's voting system uses weighted representative allocation based on population." },
    { word: "governance reform", translation: "réforme de gouvernance", example: "Developing nations have called for governance reform to increase their representation." },
    { word: "conditional membership", translation: "adhésion conditionnelle", example: "EU accession involves conditional membership based on meeting specific criteria." },
    { word: "weighted voting", translation: "vote pondéré", example: "The IMF uses weighted voting that gives larger economies greater influence." },
    { word: "institutional capacity", translation: "capacité institutionnelle", example: "Building institutional capacity is crucial for implementing international agreements." },
    { word: "mutual recognition", translation: "reconnaissance mutuelle", example: "The trade agreement established mutual recognition of regulatory standards." },
    { word: "intergovernmental committee", translation: "comité intergouvernemental", example: "The intergovernmental committee meets quarterly to coordinate policy responses." },
    { word: "observer status", translation: "statut d'observateur", example: "The organization was granted observer status at UN proceedings." },
    { word: "transnational cooperation", translation: "coopération transnationale", example: "Addressing climate change requires transnational cooperation beyond individual state actions." },
    { word: "regulatory harmonization", translation: "harmonisation réglementaire", example: "Trade agreements often promote regulatory harmonization to reduce barriers." },
    { word: "supranational authority", translation: "autorité supranationale", example: "The court holds supranational authority over member states in specific legal domains." },
    { word: "compliance mechanism", translation: "mécanisme de conformité", example: "The treaty includes a compliance mechanism to ensure parties fulfill commitments." },
    
    { word: "multilateral framework", translation: "cadre multilatéral", example: "The multilateral framework establishes principles for cooperation on transboundary issues." },
    
    
    // Politiques monétaires
    
    { word: "interest rate mechanism", translation: "mécanisme de taux d'intérêt", example: "The interest rate mechanism transmits policy changes to the broader economy." },
    { word: "quantitative easing", translation: "assouplissement quantitatif", example: "The central bank implemented quantitative easing by purchasing government bonds." },
    { word: "open market operations", translation: "opérations d'open market", example: "Open market operations involve buying and selling securities to influence money supply." },
    { word: "inflation targeting", translation: "ciblage d'inflation", example: "The central bank follows an inflation targeting framework with a 2% annual target." },
    { word: "forward guidance", translation: "indications prospectives", example: "Forward guidance about future interest rates helps shape market expectations." },
    { word: "monetary transmission", translation: "transmission monétaire", example: "Monetary transmission channels include interest rates, asset prices, and exchange rates." },
    { word: "reserve requirement", translation: "réserve obligatoire", example: "The central bank lowered the reserve requirement to increase lending capacity." },
    { word: "accommodative policy", translation: "politique accommodante", example: "The central bank maintained an accommodative policy to support economic recovery." },
    { word: "contractionary policy", translation: "politique restrictive", example: "The central bank implemented contractionary policy to cool the overheating economy." },
    { word: "liquidity provision", translation: "fourniture de liquidités", example: "Emergency liquidity provision helped stabilize financial markets during the crisis." },
    { word: "policy rate", translation: "taux directeur", example: "The central bank raised its policy rate by 25 basis points at the last meeting." },
    { word: "monetary aggregate", translation: "agrégat monétaire", example: "The report tracks various monetary aggregates to assess money supply growth." },
    { word: "yield curve control", translation: "contrôle de la courbe des rendements", example: "The central bank implemented yield curve control to cap long-term interest rates." },
    { word: "currency intervention", translation: "intervention monétaire", example: "The central bank conducted currency intervention to stabilize the exchange rate." },
    { word: "monetary stance", translation: "position monétaire", example: "The committee voted to maintain the current monetary stance until their next meeting." },
    { word: "policy divergence", translation: "divergence des politiques", example: "Policy divergence between major central banks affected global capital flows." },
    { word: "inflation expectation", translation: "anticipation d'inflation", example: "Long-term inflation expectations remained well-anchored despite short-term pressures." },
    { word: "monetary authority", translation: "autorité monétaire", example: "The monetary authority acted independently of political pressure in its decision." },
    { word: "policy normalization", translation: "normalisation de la politique", example: "After years of extraordinary measures, the bank began policy normalization." },
    { word: "unconventional policy", translation: "politique non conventionnelle", example: "Negative interest rates represent an unconventional policy tool used in some economies." },
    { word: "macroprudential policy", translation: "politique macroprudentielle", example: "Macroprudential policy aims to address systemic risks in the financial system." },
    { word: "policy coordination", translation: "coordination des politiques", example: "International policy coordination helped address global financial instability." },
    { word: "sterilization", translation: "stérilisation", example: "The central bank conducted sterilization operations to offset the effects of foreign exchange intervention." },
    { word: "price stability mandate", translation: "mandat de stabilité des prix", example: "The central bank operates under a price stability mandate defined by law." },
    { word: "dual mandate", translation: "double mandat", example: "The Federal Reserve operates under a dual mandate of price stability and maximum employment." },
    { word: "policy tools", translation: "outils de politique", example: "Central banks have expanded their policy tools beyond traditional interest rate adjustments." },
    { word: "policy corridor", translation: "corridor de politique", example: "The standing facilities define the policy corridor for short-term interest rates." },
    
    { word: "monetary independence", translation: "indépendance monétaire", example: "Currency pegs typically reduce monetary independence in favor of exchange rate stability." },
    { word: "liquidity trap", translation: "trappe à liquidité", example: "The economy experienced a liquidity trap when interest rates approached zero." },
    
    // Économies émergentes
    
    
    { word: "industrial policy", translation: "politique industrielle", example: "South Korea's industrial policy focused on developing strategic export sectors." },
    { word: "developmental state", translation: "État développementaliste", example: "East Asian tigers exemplify the developmental state model of economic growth." },
    { word: "structural transformation", translation: "transformation structurelle", example: "Economic development requires structural transformation from agriculture to manufacturing." },
    { word: "export-oriented industrialization", translation: "industrialisation orientée vers l'exportation", example: "Export-oriented industrialization drove rapid growth in several Asian economies." },
    { word: "import substitution", translation: "substitution aux importations", example: "Latin American countries pursued import substitution strategies in the mid-20th century." },
    
    { word: "capital account liberalization", translation: "libéralisation du compte de capital", example: "The IMF advocated capital account liberalization for developing economies." },
    { word: "growth trajectory", translation: "trajectoire de croissance", example: "The pandemic disrupted the growth trajectory of many emerging economies." },
    { word: "catch-up growth", translation: "croissance de rattrapage", example: "Catch-up growth allows developing countries to converge toward advanced economy levels." },
    
    { word: "investment climate", translation: "climat d'investissement", example: "Regulatory reforms improved the investment climate for foreign businesses." },
    { word: "commodity dependence", translation: "dépendance aux produits de base", example: "Commodity dependence makes economies vulnerable to price fluctuations." },
    { word: "economic diversification", translation: "diversification économique", example: "The government prioritized economic diversification to reduce oil dependence." },
    { word: "informal sector", translation: "secteur informel", example: "The informal sector employs a significant portion of the workforce in developing countries." },
    { word: "capital flight", translation: "fuite des capitaux", example: "Political instability triggered capital flight from the emerging market." },
    { word: "remittance flow", translation: "flux de transferts de fonds", example: "Remittance flows provide crucial foreign exchange for many developing economies." },
    { word: "poverty reduction strategy", translation: "stratégie de réduction de la pauvreté", example: "The poverty reduction strategy focused on rural infrastructure development." },
    
    { word: "human capital development", translation: "développement du capital humain", example: "Singapore prioritized human capital development as a core economic strategy." },
    { word: "resource curse", translation: "malédiction des ressources", example: "Many oil-rich nations have struggled with the resource curse of underperformance." },
    
    { word: "urbanization rate", translation: "taux d'urbanisation", example: "The rapid urbanization rate created challenges for housing and infrastructure." },
    { word: "productivity gap", translation: "écart de productivité", example: "A substantial productivity gap remains between emerging and advanced economies." },
    { word: "special economic zone", translation: "zone économique spéciale", example: "The special economic zone offered tax incentives to attract foreign manufacturers." },
    { word: "domestic value chain", translation: "chaîne de valeur nationale", example: "The policy aims to strengthen domestic value chains in strategic industries." },
    { word: "labor-intensive manufacturing", translation: "fabrication à forte intensité de main-d'œuvre", example: "The country's development began with labor-intensive manufacturing of textiles and apparel." },
    { word: "infant industry protection", translation: "protection des industries naissantes", example: "Infant industry protection allowed domestic manufacturers to develop capabilities." },
    { word: "growth diagnostic", translation: "diagnostic de croissance", example: "The growth diagnostic identified infrastructure as the binding constraint on development." },
    { word: "industrial upgrading", translation: "modernisation industrielle", example: "Industrial upgrading requires moving from assembly to higher-value activities." },
    
    // Inégalités structurelles
    { word: "wealth concentration", translation: "concentration de richesse", example: "Wealth concentration has reached levels not seen since the Gilded Age." },
    { word: "income disparity", translation: "disparité de revenus", example: "Income disparity between urban and rural regions continues to widen." },
    
    { word: "distributional impact", translation: "impact distributif", example: "The policy analysis examined the distributional impact across income quintiles." },
    { word: "socioeconomic stratification", translation: "stratification socio-économique", example: "Residential patterns reflect socioeconomic stratification in the metropolitan area." },
    { word: "intergenerational mobility", translation: "mobilité intergénérationnelle", example: "Intergenerational mobility has declined in many advanced economies." },
    { word: "economic polarization", translation: "polarisation économique", example: "Economic polarization has increased with the decline of middle-income jobs." },
    { word: "wealth transfer", translation: "transfert de richesse", example: "Inheritance tax affects wealth transfer between generations." },
    { word: "opportunity hoarding", translation: "accaparement des opportunités", example: "Elite universities can facilitate opportunity hoarding among privileged groups." },
    { word: "regressive taxation", translation: "fiscalité régressive", example: "Consumption taxes tend to have regressive taxation effects on lower-income households." },
    { word: "asset inequality", translation: "inégalité patrimoniale", example: "Asset inequality exceeds income inequality in most developed economies." },
    
    { word: "power asymmetry", translation: "asymétrie de pouvoir", example: "Labor market regulations aim to address power asymmetry between employers and workers." },
    { word: "wealth extraction", translation: "extraction de richesse", example: "Critics argue that financial speculation enables wealth extraction rather than creation." },
    
    { word: "distributive justice", translation: "justice distributive", example: "The policy debate centered on competing conceptions of distributive justice." },
    
    { word: "rent-seeking behavior", translation: "comportement de recherche de rente", example: "Regulatory capture enables rent-seeking behavior by established firms." },
    { word: "structural discrimination", translation: "discrimination structurelle", example: "Mortgage lending patterns revealed structural discrimination in housing markets." },
    { word: "wealth disparity", translation: "disparité de richesse", example: "Racial wealth disparity reflects historical patterns of exclusion and discrimination." },
    
    { word: "spatial inequality", translation: "inégalité spatiale", example: "Investment patterns reinforce spatial inequality between regions." },
    { word: "class-based segregation", translation: "ségrégation par classe sociale", example: "Housing costs drive class-based segregation in metropolitan areas." },
    { word: "economic marginalization", translation: "marginalisation économique", example: "Deindustrialization contributed to economic marginalization of former manufacturing communities." },
    { word: "social reproduction", translation: "reproduction sociale", example: "Educational systems often facilitate social reproduction rather than mobility." },
    { word: "positional good", translation: "bien positionnel", example: "Elite education functions as a positional good conferring competitive advantage." },
    { word: "inequality persistence", translation: "persistance des inégalités", example: "Research documents inequality persistence across multiple generations." },
    { word: "socioeconomic gradient", translation: "gradient socio-économique", example: "Health outcomes follow a clear socioeconomic gradient in most societies." },
    { word: "equity gap", translation: "écart d'équité", example: "Policy reforms aim to address the equity gap in public service provision." },
    { word: "economic segregation", translation: "ségrégation économique", example: "Zoning policies contribute to economic segregation in urban housing markets." },
    { word: "social mobility barrier", translation: "barrière à la mobilité sociale", example: "Excessive credential requirements can function as social mobility barriers." },
    
    // Régulation internationale
    { word: "regulatory framework", translation: "cadre réglementaire", example: "The Basel III regulatory framework strengthens bank capital requirements." },
    
    { word: "international standard", translation: "norme internationale", example: "The International Organization for Standardization develops international standards for industries." },
    
    { word: "mutual recognition agreement", translation: "accord de reconnaissance mutuelle", example: "The mutual recognition agreement allows certification in one country to be valid in partner countries." },
    { word: "binding constraint", translation: "contrainte obligatoire", example: "Legally binding constraints on emissions were controversial during negotiations." },
    { word: "regulatory arbitrage", translation: "arbitrage réglementaire", example: "Companies exploit differences between jurisdictions through regulatory arbitrage." },
    { word: "extraterritorial application", translation: "application extraterritoriale", example: "The extraterritorial application of domestic laws creates jurisdictional conflicts." },
    { word: "compliance cost", translation: "coût de conformité", example: "Small businesses often bear disproportionate compliance costs under new regulations." },
    { word: "regulatory convergence", translation: "convergence réglementaire", example: "Digital trade requires regulatory convergence on data protection standards." },
    { word: "enforcement mechanism", translation: "mécanisme d'application", example: "The agreement lacks a strong enforcement mechanism for violations." },
    { word: "technical barrier to trade", translation: "barrière technique au commerce", example: "Different product standards create technical barriers to trade between countries." },
    { word: "regime complex", translation: "complexe de régimes", example: "International environmental governance forms a regime complex of overlapping agreements." },
    { word: "regulatory authority", translation: "autorité réglementaire", example: "The regulatory authority issued guidelines for cross-border financial services." },
    { word: "jurisdictional overlap", translation: "chevauchement juridictionnel", example: "Jurisdictional overlap between agencies complicates enforcement efforts." },
    { word: "prudential regulation", translation: "réglementation prudentielle", example: "Prudential regulation aims to ensure financial institutions manage risks appropriately." },
    { word: "sanction regime", translation: "régime de sanctions", example: "The sanction regime targets individuals and entities involved in human rights abuses." },
    { word: "transboundary regulation", translation: "réglementation transfrontalière", example: "Effective transboundary regulation requires coordination between national authorities." },
    { word: "regulatory capture", translation: "capture réglementaire", example: "Regulatory capture occurs when agencies advance industry interests over public welfare." },
    { word: "information disclosure requirement", translation: "exigence de divulgation d'information", example: "The regulation establishes information disclosure requirements for corporate emissions." },
    { word: "rule-based governance", translation: "gouvernance fondée sur des règles", example: "The WTO promotes rule-based governance of international trade." },
    { word: "implementation mechanism", translation: "mécanisme de mise en œuvre", example: "The treaty established an implementation mechanism to track progress." },
    { word: "cartel prohibition", translation: "interdiction de cartel", example: "Competition laws include cartel prohibition provisions in most jurisdictions." },
    { word: "international regulatory coordination", translation: "coordination réglementaire internationale", example: "Financial stability requires international regulatory coordination among major economies." },
    { word: "compliance regime", translation: "régime de conformité", example: "The compliance regime includes monitoring, reporting, and verification procedures." },
    { word: "regulatory spillover", translation: "débordement réglementaire", example: "EU regulations create regulatory spillover effects in neighboring countries." },
    { word: "international commitment", translation: "engagement international", example: "The country failed to meet its international commitments under the agreement." },
    { word: "multilateral enforcement", translation: "application multilatérale", example: "Multilateral enforcement improves compliance with international standards." },
    { word: "principle-based regulation", translation: "réglementation basée sur des principes", example: "The financial authority shifted toward principle-based regulation after the crisis." },
    { word: "cross-border compliance", translation: "conformité transfrontalière", example: "Global operations require addressing cross-border compliance with multiple regulatory regimes." },
    { word: "transparency provision", translation: "disposition de transparence", example: "The treaty contains transparency provisions requiring public disclosure of actions." },
    
    // Analyse conjoncturelle
    { word: "economic outlook", translation: "perspectives économiques", example: "The central bank published its quarterly economic outlook predicting modest growth." },
    { word: "leading indicator", translation: "indicateur avancé", example: "Building permits serve as a leading indicator for construction activity." },
    { word: "business cycle", translation: "cycle économique", example: "The economy appears to be in the late expansion phase of the business cycle." },
    { word: "macroeconomic forecast", translation: "prévision macroéconomique", example: "The macroeconomic forecast anticipated rising inflation due to supply constraints." },
    { word: "cyclical adjustment", translation: "ajustement cyclique", example: "The budget analysis included cyclical adjustment to identify the structural balance." },
    { word: "economic sentiment", translation: "sentiment économique", example: "Consumer surveys indicate weakening economic sentiment despite strong indicators." },
    { word: "output gap", translation: "écart de production", example: "The negative output gap suggests the economy is operating below potential." },
    { word: "growth momentum", translation: "dynamique de croissance", example: "Export growth momentum slowed in the second quarter compared to previous periods." },
    { word: "economic slowdown", translation: "ralentissement économique", example: "The data points to an economic slowdown rather than a recession." },
    { word: "economic recovery", translation: "reprise économique", example: "The economic recovery following the pandemic has been uneven across sectors." },
    { word: "conjunctural analysis", translation: "analyse conjoncturelle", example: "The report provides conjunctural analysis of current economic conditions." },
    { word: "economic projection", translation: "projection économique", example: "The economic projection shows accelerating growth in the coming quarters." },
    { word: "cyclical position", translation: "position cyclique", example: "The economy's cyclical position affects appropriate policy responses." },
    { word: "economic indicator", translation: "indicateur économique", example: "Retail sales are a key economic indicator of consumer spending." },
    { word: "recession probability", translation: "probabilité de récession", example: "The model estimates the recession probability at 30% over the next year." },
    { word: "lagging indicator", translation: "indicateur retardé", example: "Unemployment is typically a lagging indicator that peaks after a recession ends." },
    { word: "coincident indicator", translation: "indicateur coïncident", example: "Industrial production is a coincident indicator that moves with the overall economy." },
    { word: "sectoral analysis", translation: "analyse sectorielle", example: "The sectoral analysis showed diverging trends between manufacturing and services." },
    { word: "economic release", translation: "publication économique", example: "Markets reacted strongly to the economic release of inflation data." },
    
    { word: "confidence indicator", translation: "indicateur de confiance", example: "Business confidence indicators declined for the third consecutive month." },
    { word: "economic trajectory", translation: "trajectoire économique", example: "The central bank revised its view of the economic trajectory following new data." },
    { word: "cyclical upswing", translation: "reprise cyclique", example: "The cyclical upswing in manufacturing boosted employment in industrial regions." },
    { word: "downside risk", translation: "risque baissier", example: "The report highlighted trade tensions as a significant downside risk to growth." },
    { word: "growth forecast", translation: "prévision de croissance", example: "The institution revised its growth forecast downward for the coming year." },
    { word: "economic activity", translation: "activité économique", example: "High-frequency data indicates rebounding economic activity following restrictions." },
    { word: "trend growth", translation: "croissance tendancielle", example: "The economy is expected to return to trend growth by next year." },
    { word: "financial condition", translation: "condition financière", example: "Tightening financial conditions could constrain economic expansion." },
    { word: "cyclical downturn", translation: "ralentissement cyclique", example: "The cyclical downturn affected consumer discretionary spending most severely." },
    { word: "growth driver", translation: "moteur de croissance", example: "Exports have become the primary growth driver for the economy." },
    { word: "economic prognosis", translation: "pronostic économique", example: "The economic prognosis remains uncertain given geopolitical developments." }
  ]
};