export const vocab = {
  title: "Activités Quotidiennes",
  words: [
    // Routines
    { word: "to wake up", translation: "se réveiller", example: "I wake up at 7 o'clock every morning." },
    { word: "to get up", translation: "se lever", example: "I get up after my alarm rings." },
    { word: "to sleep", translation: "dormir", example: "I sleep for eight hours every night." },
    { word: "to go to bed", translation: "aller se coucher", example: "I go to bed at 11 p.m." },
    { word: "to get dressed", translation: "s'habiller", example: "I get dressed after my shower." },
    { word: "to work", translation: "travailler", example: "I work from Monday to Friday." },
    { word: "to study", translation: "étudier", example: "I study English every day." },
    { word: "to relax", translation: "se détendre", example: "I relax by watching TV." },
    { word: "to rest", translation: "se reposer", example: "I need to rest after work." },
    { word: "routine", translation: "routine", example: "I follow the same routine every day." },
    { word: "schedule", translation: "emploi du temps", example: "My schedule is very busy this week." },
    { word: "daily", translation: "quotidien", example: "This is part of my daily routine." },
    { word: "weekly", translation: "hebdomadaire", example: "I have a weekly meeting on Mondays." },
    { word: "habit", translation: "habitude", example: "Reading before bed is a good habit." },
    
    // Hygiène personnelle
    { word: "to wash", translation: "se laver", example: "I wash my hands before eating." },
    { word: "to take a shower", translation: "prendre une douche", example: "I take a shower every morning." },
    { word: "to take a bath", translation: "prendre un bain", example: "I prefer to take a bath in the evening." },
    { word: "to brush", translation: "brosser", example: "I brush my teeth twice a day." },
    { word: "to comb", translation: "peigner", example: "She combs her hair every morning." },
    { word: "to shave", translation: "se raser", example: "He shaves every morning." },
    { word: "to put on makeup", translation: "se maquiller", example: "She puts on makeup before work." },
    { word: "to clean", translation: "nettoyer", example: "I clean my face every night." },
    { word: "toothbrush", translation: "brosse à dents", example: "I need a new toothbrush." },
    { word: "toothpaste", translation: "dentifrice", example: "We're out of toothpaste." },
    { word: "soap", translation: "savon", example: "Use soap to wash your hands." },
    { word: "shampoo", translation: "shampooing", example: "This shampoo smells nice." },
    { word: "deodorant", translation: "déodorant", example: "I forgot to put on deodorant." },
    { word: "perfume", translation: "parfum", example: "She wears nice perfume." },
    
    // Activités domestiques
    { word: "to clean", translation: "nettoyer", example: "I clean my apartment on weekends." },
    { word: "to cook", translation: "cuisiner", example: "I like to cook dinner." },
    { word: "to wash up", translation: "faire la vaisselle", example: "It's your turn to wash up." },
    { word: "to do the laundry", translation: "faire la lessive", example: "I do the laundry once a week." },
    { word: "to iron", translation: "repasser", example: "I need to iron my shirt." },
    { word: "to vacuum", translation: "passer l'aspirateur", example: "I vacuum my apartment every week." },
    { word: "to dust", translation: "épousseter", example: "I dust the furniture regularly." },
    { word: "to make the bed", translation: "faire le lit", example: "I make my bed every morning." },
    { word: "to tidy up", translation: "ranger", example: "I need to tidy up my room." },
    { word: "to take out the trash", translation: "sortir les poubelles", example: "Don't forget to take out the trash." },
    { word: "to water", translation: "arroser", example: "I water the plants twice a week." },
    { word: "to repair", translation: "réparer", example: "I need to repair this chair." },
    { word: "to do the shopping", translation: "faire les courses", example: "I do the shopping on Saturdays." },
    { word: "chore", translation: "corvée", example: "Cleaning is my least favorite chore." },
    
    // Repas
    { word: "to eat", translation: "manger", example: "I eat breakfast at 8 a.m." },
    { word: "to drink", translation: "boire", example: "I drink a lot of water." },
    { word: "to have breakfast", translation: "prendre le petit-déjeuner", example: "I have breakfast at home." },
    { word: "to have lunch", translation: "déjeuner", example: "I have lunch at work." },
    { word: "to have dinner", translation: "dîner", example: "We have dinner at 7 p.m." },
    { word: "to cook", translation: "cuisiner", example: "I cook dinner for my family." },
    { word: "to prepare", translation: "préparer", example: "I prepare lunch the night before." },
    { word: "to serve", translation: "servir", example: "She serves dinner at 8 p.m." },
    { word: "to taste", translation: "goûter", example: "Taste this soup, please." },
    { word: "to be hungry", translation: "avoir faim", example: "I'm hungry. Let's eat." },
    { word: "to be thirsty", translation: "avoir soif", example: "I'm thirsty. I need water." },
    { word: "meal", translation: "repas", example: "Dinner is my favorite meal." },
    { word: "snack", translation: "goûter/en-cas", example: "I have a snack in the afternoon." },
    { word: "recipe", translation: "recette", example: "This is my grandmother's recipe." },
    
    // Déplacements simples
    { word: "to go", translation: "aller", example: "I go to work by bus." },
    { word: "to come", translation: "venir", example: "He comes to visit on weekends." },
    { word: "to walk", translation: "marcher", example: "I walk to school every day." },
    { word: "to drive", translation: "conduire", example: "She drives to work." },
    { word: "to ride", translation: "faire du vélo", example: "I ride my bike to the park." },
    { word: "to take the bus", translation: "prendre le bus", example: "I take the bus to the city center." },
    { word: "to take the train", translation: "prendre le train", example: "She takes the train to Paris." },
    { word: "to take the subway", translation: "prendre le métro", example: "It's faster to take the subway." },
    { word: "to travel", translation: "voyager", example: "I travel to London every month." },
    { word: "to arrive", translation: "arriver", example: "I arrive at work at 9 a.m." },
    { word: "to leave", translation: "partir", example: "I leave home at 8 a.m." },
    { word: "journey", translation: "trajet", example: "The journey to work takes 30 minutes." },
    { word: "trip", translation: "voyage", example: "We're planning a trip to Spain." },
    { word: "commute", translation: "trajet quotidien", example: "My daily commute is tiring." }
  ]
};