export const vocab = {
  title: "Nourriture & Boissons",
  words: [
    // Fruits courants
    { word: "apple", translation: "pomme", example: "I eat an apple every day." },
    { word: "banana", translation: "banane", example: "Monkeys like bananas." },
    { word: "orange", translation: "orange", example: "I drink orange juice for breakfast." },
    { word: "lemon", translation: "citron", example: "Add some lemon to your tea." },
    { word: "strawberry", translation: "fraise", example: "These strawberries are very sweet." },
    { word: "grape", translation: "raisin", example: "I like to eat grapes as a snack." },
    { word: "pear", translation: "poire", example: "This pear is not ripe yet." },
    { word: "peach", translation: "pêche", example: "Peaches are my favorite summer fruit." },
    { word: "watermelon", translation: "pastèque", example: "Watermelon is refreshing in hot weather." },
    { word: "pineapple", translation: "ananas", example: "Do you like pineapple on pizza?" },
    { word: "cherry", translation: "cerise", example: "She put a cherry on top of the cake." },
    { word: "kiwi", translation: "kiwi", example: "Kiwis are rich in vitamin C." },
    { word: "fruit", translation: "fruit", example: "You should eat fruit every day." },
    { word: "berry", translation: "baie", example: "I like all kinds of berries." },
    
    // Légumes courants
    { word: "potato", translation: "pomme de terre", example: "I like fried potatoes." },
    { word: "tomato", translation: "tomate", example: "Add some tomato to your salad." },
    { word: "carrot", translation: "carotte", example: "Rabbits love carrots." },
    { word: "onion", translation: "oignon", example: "Chop the onion finely." },
    { word: "lettuce", translation: "laitue", example: "We need lettuce for the salad." },
    { word: "cucumber", translation: "concombre", example: "I like cucumber sandwiches." },
    { word: "pepper", translation: "poivron", example: "Red peppers are sweet." },
    { word: "garlic", translation: "ail", example: "Add some garlic to the sauce." },
    { word: "pea", translation: "petit pois", example: "I don't like peas." },
    { word: "corn", translation: "maïs", example: "We had corn on the cob for dinner." },
    { word: "broccoli", translation: "brocoli", example: "Children often don't like broccoli." },
    { word: "mushroom", translation: "champignon", example: "I like mushrooms on my pizza." },
    { word: "cabbage", translation: "chou", example: "Cabbage soup is traditional in winter." },
    { word: "vegetable", translation: "légume", example: "You should eat more vegetables." },
    
    // Aliments de base
    { word: "bread", translation: "pain", example: "I eat bread for breakfast." },
    { word: "rice", translation: "riz", example: "Rice is a staple food in many countries." },
    { word: "pasta", translation: "pâtes", example: "Italians eat a lot of pasta." },
    { word: "cheese", translation: "fromage", example: "France is famous for its cheese." },
    { word: "butter", translation: "beurre", example: "I put butter on my bread." },
    { word: "oil", translation: "huile", example: "Cook with olive oil." },
    { word: "egg", translation: "œuf", example: "I had two eggs for breakfast." },
    { word: "sugar", translation: "sucre", example: "Would you like sugar in your coffee?" },
    { word: "salt", translation: "sel", example: "Add a little salt to the soup." },
    { word: "pepper", translation: "poivre", example: "Add salt and pepper to taste." },
    { word: "flour", translation: "farine", example: "You need flour to make bread." },
    { word: "cereal", translation: "céréale", example: "I eat cereal for breakfast." },
    { word: "honey", translation: "miel", example: "I prefer honey to sugar in my tea." },
    { word: "jam", translation: "confiture", example: "I like strawberry jam on toast." },
    { word: "chocolate", translation: "chocolat", example: "Children love chocolate." },
    { word: "ice cream", translation: "glace", example: "We eat ice cream in summer." },
    { word: "cake", translation: "gâteau", example: "It's my birthday, so I'll have cake." },
    { word: "cookie", translation: "biscuit", example: "Would you like a cookie with your tea?" },
    { word: "sandwich", translation: "sandwich", example: "I had a cheese sandwich for lunch." },
    { word: "soup", translation: "soupe", example: "Hot soup is good in winter." },
    { word: "salad", translation: "salade", example: "I'm on a diet, so I eat a lot of salad." },
    
    // Viandes & poissons simples
    { word: "meat", translation: "viande", example: "I don't eat meat." },
    { word: "chicken", translation: "poulet", example: "Chicken is my favorite meat." },
    { word: "beef", translation: "bœuf", example: "This beef is very tender." },
    { word: "pork", translation: "porc", example: "Muslims and Jews don't eat pork." },
    { word: "fish", translation: "poisson", example: "Fish is good for your health." },
    { word: "salmon", translation: "saumon", example: "Salmon is rich in omega-3." },
    { word: "tuna", translation: "thon", example: "I like tuna sandwiches." },
    { word: "ham", translation: "jambon", example: "I had a ham and cheese sandwich." },
    { word: "sausage", translation: "saucisse", example: "Germans eat a lot of sausages." },
    { word: "bacon", translation: "lard", example: "I eat bacon and eggs for breakfast." },
    { word: "seafood", translation: "fruits de mer", example: "He's allergic to seafood." },
    
    // Boissons communes
    { word: "water", translation: "eau", example: "Drink plenty of water every day." },
    { word: "coffee", translation: "café", example: "I need a coffee in the morning." },
    { word: "tea", translation: "thé", example: "The British drink a lot of tea." },
    { word: "milk", translation: "lait", example: "Children should drink milk." },
    { word: "juice", translation: "jus", example: "Orange juice is rich in vitamin C." },
    { word: "soda", translation: "soda", example: "Soda contains a lot of sugar." },
    { word: "beer", translation: "bière", example: "Would you like a beer?" },
    { word: "wine", translation: "vin", example: "France produces excellent wine." },
    { word: "drink", translation: "boisson", example: "What would you like to drink?" },
    { word: "hot chocolate", translation: "chocolat chaud", example: "Hot chocolate is perfect on a cold day." },
    { word: "lemonade", translation: "limonade", example: "I made fresh lemonade." },
    
    // Repas de la journée
    { word: "breakfast", translation: "petit-déjeuner", example: "Breakfast is the most important meal of the day." },
    { word: "lunch", translation: "déjeuner", example: "I have lunch at 1 p.m." },
    { word: "dinner", translation: "dîner", example: "We usually have dinner at 7 p.m." },
    { word: "meal", translation: "repas", example: "This restaurant serves excellent meals." },
    { word: "snack", translation: "en-cas/goûter", example: "I had a small snack in the afternoon." },
    { word: "fast food", translation: "restauration rapide", example: "I try not to eat fast food." },
    { word: "menu", translation: "menu", example: "Let's look at the menu." },
    { word: "dish", translation: "plat", example: "This is a traditional French dish." },
    { word: "dessert", translation: "dessert", example: "What's for dessert?" },
    { word: "starter", translation: "entrée", example: "We'll have soup as a starter." },
    { word: "main course", translation: "plat principal", example: "For the main course, I'll have chicken." },
    { word: "recipe", translation: "recette", example: "Can you give me the recipe for this cake?" },
    
    // Goûts basiques
    { word: "sweet", translation: "sucré", example: "I like sweet foods." },
    { word: "salty", translation: "salé", example: "These chips are very salty." },
    { word: "sour", translation: "acide", example: "Lemons are sour." },
    { word: "bitter", translation: "amer", example: "Dark chocolate is bitter." },
    { word: "spicy", translation: "épicé", example: "Thai food is often spicy." },
    { word: "hot", translation: "chaud", example: "Be careful, the soup is hot." },
    { word: "cold", translation: "froid", example: "I prefer cold drinks in summer." },
    { word: "delicious", translation: "délicieux", example: "This cake is delicious!" },
    { word: "tasty", translation: "savoureux", example: "What a tasty meal!" },
    { word: "terrible", translation: "terrible", example: "The food at that restaurant is terrible." },
    { word: "fresh", translation: "frais", example: "I only buy fresh vegetables." },
    { word: "rotten", translation: "pourri", example: "This apple is rotten." },
    { word: "to taste", translation: "goûter", example: "Taste this soup and tell me what you think." }
  ]
};