export const vocab = {
  title: "Animaux domestiques",
  words: [
    // Animaux domestiques
    { word: "pet", translation: "animal de compagnie", example: "Do you have any pets?" },
    { word: "dog", translation: "chien", example: "I have a dog named Max." },
    { word: "cat", translation: "chat", example: "Her cat sleeps all day." },
    { word: "fish", translation: "poisson", example: "They have three fish in a tank." },
    { word: "bird", translation: "oiseau", example: "The bird is singing." },
    { word: "hamster", translation: "hamster", example: "My hamster runs in his wheel." },
    { word: "rabbit", translation: "lapin", example: "The rabbit is eating a carrot." },
    { word: "turtle", translation: "tortue", example: "The turtle moves very slowly." },
    { word: "guinea pig", translation: "cochon d'Inde", example: "My sister has two guinea pigs." },
    { word: "puppy", translation: "chiot", example: "The puppy is very playful." },
    { word: "kitten", translation: "chaton", example: "The kitten is sleeping in the basket." },
    { word: "goldfish", translation: "poisson rouge", example: "I have a goldfish in a bowl." },
    { word: "parrot", translation: "perroquet", example: "The parrot can say 'hello'." },
    { word: "mouse", translation: "souris", example: "My cat caught a mouse yesterday." },
    { word: "animal", translation: "animal", example: "I love animals." },
    { word: "to feed", translation: "nourrir", example: "I feed my dog twice a day." },
    { word: "cage", translation: "cage", example: "The bird is in its cage." },
    { word: "aquarium", translation: "aquarium", example: "We have an aquarium with tropical fish." },
    { word: "collar", translation: "collier", example: "My dog has a blue collar." },
    { word: "leash", translation: "laisse", example: "Don't forget the dog's leash." },
    { word: "bowl", translation: "gamelle", example: "The cat's bowl is empty." },
    { word: "toy", translation: "jouet", example: "My dog loves his toy." },
    { word: "bone", translation: "os", example: "The dog is chewing a bone." },
    { word: "fur", translation: "fourrure", example: "The cat has soft fur." },
    { word: "to bark", translation: "aboyer", example: "The dog barks at strangers." },
    { word: "to meow", translation: "miauler", example: "The cat meows when it's hungry." },
    { word: "to purr", translation: "ronronner", example: "Cats purr when they are happy." },
    { word: "to walk", translation: "promener", example: "I walk my dog every morning." },
    { word: "pet shop", translation: "animalerie", example: "We bought the fish at the pet shop." },
    { word: "vet", translation: "vétérinaire", example: "I took my cat to the vet yesterday." }
  ]
};