export const vocab = {
  title: "Loisirs & Passe-temps Simples",
  words: [
    // Activités de loisirs basiques
    { word: "hobby", translation: "passe-temps/loisir", example: "Reading is my favorite hobby." },
    { word: "to read", translation: "lire", example: "I like to read books in the evening." },
    { word: "to watch TV", translation: "regarder la télé", example: "I watch TV after dinner." },
    { word: "to listen to music", translation: "écouter de la musique", example: "I like to listen to music when I study." },
    { word: "to play", translation: "jouer", example: "Children like to play in the park." },
    { word: "to dance", translation: "danser", example: "She loves to dance at parties." },
    { word: "to sing", translation: "chanter", example: "He sings in a choir." },
    { word: "to draw", translation: "dessiner", example: "My daughter likes to draw animals." },
    { word: "to paint", translation: "peindre", example: "I paint landscapes as a hobby." },
    { word: "to cook", translation: "cuisiner", example: "I enjoy cooking on weekends." },
    { word: "to garden", translation: "jardiner", example: "My grandfather gardens every day." },
    { word: "to take photos", translation: "prendre des photos", example: "I like to take photos when I travel." },
    { word: "to travel", translation: "voyager", example: "We love to travel during summer vacation." },
    { word: "to camp", translation: "camper", example: "We camp in the mountains every year." },
    { word: "to hike", translation: "faire de la randonnée", example: "We like to hike in the forest." },
    { word: "to fish", translation: "pêcher", example: "My father likes to fish on weekends." },
    { word: "to shop", translation: "faire du shopping", example: "My sister loves to shop for clothes." },
    { word: "free time", translation: "temps libre", example: "What do you do in your free time?" },
    { word: "weekend", translation: "week-end", example: "What are your plans for the weekend?" },
    
    // Sports communs
    { word: "sport", translation: "sport", example: "What's your favorite sport?" },
    { word: "football", translation: "football", example: "He plays football every Saturday." },
    { word: "soccer", translation: "football", example: "Soccer is very popular in Europe." },
    { word: "basketball", translation: "basketball", example: "I play basketball with my friends." },
    { word: "tennis", translation: "tennis", example: "Do you play tennis?" },
    { word: "volleyball", translation: "volleyball", example: "We play volleyball at the beach." },
    { word: "baseball", translation: "baseball", example: "Baseball is popular in the United States." },
    { word: "golf", translation: "golf", example: "My father plays golf on Sundays." },
    { word: "swimming", translation: "natation", example: "Swimming is good exercise." },
    { word: "cycling", translation: "cyclisme", example: "I go cycling on weekends." },
    { word: "running", translation: "course à pied", example: "She goes running every morning." },
    { word: "to run", translation: "courir", example: "I run three times a week." },
    { word: "to swim", translation: "nager", example: "I like to swim in the sea." },
    { word: "to play football", translation: "jouer au football", example: "The boys play football after school." },
    { word: "to ski", translation: "skier", example: "We ski in the mountains in winter." },
    { word: "team", translation: "équipe", example: "I play in a football team." },
    { word: "match", translation: "match", example: "Did you watch the football match yesterday?" },
    { word: "to win", translation: "gagner", example: "Our team won the match." },
    { word: "to lose", translation: "perdre", example: "They lost the game yesterday." },
    
    // Jeux simples
    { word: "game", translation: "jeu", example: "Let's play a game!" },
    { word: "board game", translation: "jeu de société", example: "We like to play board games on rainy days." },
    { word: "card game", translation: "jeu de cartes", example: "Do you know any card games?" },
    { word: "chess", translation: "échecs", example: "My grandfather taught me to play chess." },
    { word: "cards", translation: "cartes", example: "Do you want to play cards?" },
    { word: "puzzle", translation: "puzzle", example: "I like to do puzzles with my children." },
    { word: "video game", translation: "jeu vidéo", example: "My brother plays video games every day." },
    { word: "to play games", translation: "jouer à des jeux", example: "Children like to play games." },
    { word: "to win", translation: "gagner", example: "I always win when we play this game." },
    { word: "to lose", translation: "perdre", example: "Don't be sad when you lose a game." },
    { word: "rules", translation: "règles", example: "Do you know the rules of this game?" },
    { word: "player", translation: "joueur", example: "This game is for two players." },
    { word: "toy", translation: "jouet", example: "Children love playing with toys." },
    { word: "dice", translation: "dé", example: "Roll the dice to see who goes first." },
    { word: "to roll", translation: "lancer", example: "It's your turn to roll the dice." },
    
    // Activités culturelles basiques
    { word: "movie", translation: "film", example: "I watched a good movie last night." },
    { word: "cinema", translation: "cinéma", example: "Let's go to the cinema tonight." },
    { word: "theater", translation: "théâtre", example: "My parents go to the theater once a month." },
    { word: "museum", translation: "musée", example: "We visited a museum on Saturday." },
    { word: "concert", translation: "concert", example: "I went to a concert last weekend." },
    { word: "music", translation: "musique", example: "What kind of music do you like?" },
    { word: "book", translation: "livre", example: "I'm reading an interesting book." },
    { word: "to read", translation: "lire", example: "I like to read before going to bed." },
    { word: "to watch", translation: "regarder", example: "We watched a film last night." },
    { word: "to listen", translation: "écouter", example: "I listen to music every day." },
    { word: "to visit", translation: "visiter", example: "We visited a museum in Paris." },
    { word: "art", translation: "art", example: "I love modern art." },
    { word: "exhibition", translation: "exposition", example: "There's a new exhibition at the museum." },
    { word: "festival", translation: "festival", example: "The music festival is in July." },
    { word: "library", translation: "bibliothèque", example: "I borrow books from the library." },
    { word: "show", translation: "spectacle", example: "We saw a great show last night." },
    { word: "gallery", translation: "galerie", example: "There's a new art gallery in the city center." }
  ]
};