export const vocab = {
  title: "Environnement Urbain & Rural",
  words: [
    // Quartiers & zones urbaines
    { word: "neighborhood", translation: "quartier", example: "I live in a quiet neighborhood." },
    { word: "district", translation: "district/arrondissement", example: "The financial district is located downtown." },
    { word: "suburb", translation: "banlieue", example: "Many families prefer to live in the suburbs." },
    { word: "downtown", translation: "centre-ville", example: "We're going downtown for dinner tonight." },
    { word: "uptown", translation: "quartier nord/haut de la ville", example: "The museum is located uptown." },
    { word: "residential area", translation: "zone résidentielle", example: "They bought a house in a residential area." },
    { word: "commercial area", translation: "zone commerciale", example: "Most shops are in the commercial area." },
    { word: "industrial zone", translation: "zone industrielle", example: "The factory is located in the industrial zone." },
    { word: "historic center", translation: "centre historique", example: "The historic center attracts many tourists." },
    { word: "business district", translation: "quartier d'affaires", example: "He works in the business district." },
    { word: "slum", translation: "bidonville", example: "The government is trying to improve conditions in the slums." },
    { word: "outskirts", translation: "périphérie", example: "The new shopping mall is on the outskirts of town." },
    { word: "metropolitan area", translation: "zone métropolitaine", example: "The metropolitan area has over 5 million inhabitants." },
    { word: "urban sprawl", translation: "étalement urbain", example: "Urban sprawl has led to longer commuting times." },
    { word: "gentrification", translation: "gentrification", example: "Gentrification is changing the character of the neighborhood." },
    { word: "pedestrian zone", translation: "zone piétonne", example: "The city center is now a pedestrian zone." },
    
    // Infrastructure urbaine
    { word: "bridge", translation: "pont", example: "We crossed the bridge to reach the other side of the river." },
    { word: "tunnel", translation: "tunnel", example: "The tunnel goes under the mountain." },
    { word: "highway", translation: "autoroute", example: "Take the highway to get there faster." },
    { word: "underpass", translation: "passage souterrain", example: "Use the underpass to cross the busy road." },
    { word: "overpass", translation: "passage supérieur", example: "The overpass helps traffic flow smoothly." },
    { word: "subway system", translation: "réseau de métro", example: "London has an extensive subway system." },
    { word: "tram line", translation: "ligne de tramway", example: "The new tram line connects the suburbs to downtown." },
    { word: "bike lane", translation: "piste cyclable", example: "More bike lanes are being built to encourage cycling." },
    { word: "pedestrian crossing", translation: "passage piéton", example: "Use the pedestrian crossing to cross the street safely." },
    { word: "traffic light", translation: "feu de circulation", example: "Stop at the traffic light when it's red." },
    { word: "roundabout", translation: "rond-point", example: "Take the second exit at the roundabout." },
    { word: "junction", translation: "carrefour", example: "The accident happened at the junction of Main Street and Park Avenue." },
    { word: "bus lane", translation: "couloir de bus", example: "Only buses can use the bus lane." },
    { word: "power lines", translation: "lignes électriques", example: "The storm damaged the power lines." },
    { word: "sewage system", translation: "système d'égouts", example: "The city is upgrading its sewage system." },
    { word: "public transportation", translation: "transports en commun", example: "I use public transportation to get to work." },
    { word: "water supply", translation: "approvisionnement en eau", example: "The drought affected the city's water supply." },
    
    // Services municipaux
    { word: "town hall", translation: "mairie", example: "The meeting will take place at the town hall." },
    { word: "public library", translation: "bibliothèque municipale", example: "I borrow books from the public library." },
    { word: "fire station", translation: "caserne de pompiers", example: "The fire station is just around the corner." },
    { word: "police station", translation: "commissariat de police", example: "She went to the police station to report the theft." },
    { word: "community center", translation: "centre communautaire", example: "The community center offers activities for all ages." },
    { word: "recycling center", translation: "centre de recyclage", example: "Take your glass bottles to the recycling center." },
    { word: "waste collection", translation: "collecte des déchets", example: "Waste collection takes place on Tuesdays and Fridays." },
    { word: "public lighting", translation: "éclairage public", example: "The public lighting in this area needs improvement." },
    { word: "public works", translation: "travaux publics", example: "The department of public works is fixing the roads." },
    { word: "urban planning", translation: "urbanisme", example: "Urban planning is important for sustainable city development." },
    { word: "social services", translation: "services sociaux", example: "Contact social services if you need assistance." },
    { word: "local council", translation: "conseil municipal", example: "The local council voted on the new budget." },
    { word: "public health", translation: "santé publique", example: "Public health measures were put in place during the pandemic." },
    { word: "civic center", translation: "centre civique", example: "The exhibition is being held at the civic center." },
    { word: "city services", translation: "services municipaux", example: "Many city services are now available online." },
    
    // Environnement rural
    { word: "countryside", translation: "campagne", example: "They moved to the countryside for a quieter life." },
    { word: "farmland", translation: "terres agricoles", example: "Farmland surrounds the small village." },
    { word: "field", translation: "champ", example: "The farmer works in the fields all day." },
    { word: "meadow", translation: "prairie", example: "Wildflowers grow in the meadow." },
    { word: "orchard", translation: "verger", example: "We picked apples in the orchard." },
    { word: "vineyard", translation: "vignoble", example: "The region is famous for its vineyards." },
    { word: "barn", translation: "grange", example: "The farmer stores hay in the barn." },
    { word: "silo", translation: "silo", example: "The grain is stored in the silo." },
    { word: "stable", translation: "écurie", example: "The horses are kept in the stable." },
    { word: "pasture", translation: "pâturage", example: "The cows graze in the pasture." },
    { word: "harvest", translation: "récolte", example: "The harvest was good this year." },
    { word: "crop", translation: "culture", example: "Wheat is the main crop in this region." },
    { word: "livestock", translation: "bétail", example: "The farm has various livestock." },
    { word: "rural community", translation: "communauté rurale", example: "Rural communities often have strong traditions." },
    { word: "agricultural area", translation: "zone agricole", example: "This is primarily an agricultural area." },
    { word: "hamlet", translation: "hameau", example: "They live in a small hamlet with just a few houses." },
    { word: "farmhouse", translation: "ferme (maison)", example: "They renovated an old farmhouse." },
    
    // Orientation & direction
    { word: "intersection", translation: "intersection", example: "The accident happened at the intersection." },
    { word: "landmark", translation: "point de repère", example: "The church tower is a useful landmark." },
    { word: "signpost", translation: "panneau indicateur", example: "Follow the signpost to the museum." },
    { word: "compass point", translation: "point cardinal", example: "North, south, east, and west are compass points." },
    { word: "northwest", translation: "nord-ouest", example: "Seattle is in the northwest of the United States." },
    { word: "southeast", translation: "sud-est", example: "Florida is in the southeast of the United States." },
    { word: "directions", translation: "indications", example: "Can you give me directions to the station?" },
    { word: "route", translation: "itinéraire", example: "What's the best route to the airport?" },
    { word: "detour", translation: "détour", example: "We had to make a detour due to roadworks." },
    { word: "shortcut", translation: "raccourci", example: "I know a shortcut that will save time." },
    { word: "one-way street", translation: "rue à sens unique", example: "Be careful, this is a one-way street." },
    { word: "dead end", translation: "impasse", example: "We turned into a dead end and had to turn around." },
    { word: "destination", translation: "destination", example: "What's your final destination?" },
    { word: "crossroads", translation: "carrefour", example: "The village is at a crossroads of two main highways." },
    { word: "getting lost", translation: "se perdre", example: "I'm afraid of getting lost in the big city." },
    
    // Problèmes urbains simples
    { word: "traffic jam", translation: "embouteillage", example: "I was stuck in a traffic jam for an hour." },
    { word: "pollution", translation: "pollution", example: "Air pollution is a major problem in large cities." },
    { word: "noise", translation: "bruit", example: "The noise from the construction site is very disturbing." },
    { word: "overcrowding", translation: "surpeuplement", example: "Overcrowding is an issue in many city centers." },
    { word: "homelessness", translation: "sans-abrisme", example: "Homelessness has increased in recent years." },
    { word: "vandalism", translation: "vandalisme", example: "Vandalism is a problem in this neighborhood." },
    { word: "graffiti", translation: "graffiti", example: "There is graffiti on many walls in the area." },
    { word: "litter", translation: "détritus", example: "Please don't leave litter in the park." },
    { word: "crime", translation: "criminalité", example: "The crime rate has decreased in recent years." },
    { word: "poverty", translation: "pauvreté", example: "Urban poverty is a complex issue." },
    { word: "housing shortage", translation: "pénurie de logements", example: "There's a serious housing shortage in the capital." },
    { word: "urban decay", translation: "délabrement urbain", example: "Some areas are suffering from urban decay." },
    { word: "congestion", translation: "congestion", example: "Traffic congestion makes commuting difficult." },
    { word: "public safety", translation: "sécurité publique", example: "Public safety is a priority for the new mayor." },
    { word: "urban heat island", translation: "îlot de chaleur urbain", example: "Cities can be several degrees warmer due to the urban heat island effect." },
    { word: "cost of living", translation: "coût de la vie", example: "The cost of living is higher in major cities." },
    { word: "commuting", translation: "trajet domicile-travail", example: "Commuting takes up a lot of my time." }
  ]
};