export const vocab = {
  title: "Alimentation & Gastronomie",
  words: [
    // Cuisine internationale
    { word: "cuisine", translation: "cuisine", example: "French cuisine is famous around the world." },
    { word: "speciality", translation: "spécialité", example: "Paella is a Spanish speciality." },
    { word: "fusion food", translation: "cuisine fusion", example: "The restaurant serves fusion food combining Asian and European techniques." },
    { word: "ethnic food", translation: "cuisine ethnique", example: "The market offers ethnic food from around the world." },
    { word: "regional dish", translation: "plat régional", example: "Each province has its own regional dishes." },
    { word: "traditional recipe", translation: "recette traditionnelle", example: "She follows her grandmother's traditional recipe for bread." },
    { word: "street food", translation: "cuisine de rue", example: "You can find delicious street food in Bangkok." },
    { word: "authentic cuisine", translation: "cuisine authentique", example: "The restaurant serves authentic cuisine from southern Italy." },
    { word: "imported ingredient", translation: "ingrédient importé", example: "The chef uses imported ingredients for specific flavors." },
    { word: "culinary heritage", translation: "patrimoine culinaire", example: "France is proud of its rich culinary heritage." },
    { word: "culinary tradition", translation: "tradition culinaire", example: "These culinary traditions have been passed down for generations." },
    { word: "global influence", translation: "influence mondiale", example: "Japanese cuisine has had a global influence in recent years." },
    { word: "flavor profile", translation: "profil de saveur", example: "Thai food has a complex flavor profile combining sweet, sour, and spicy." },
    { word: "indigenous ingredient", translation: "ingrédient indigène", example: "The chef specializes in dishes using indigenous ingredients." },
    { word: "cultural significance", translation: "importance culturelle", example: "Rice has cultural significance in many Asian countries." },
    { word: "gastronomic region", translation: "région gastronomique", example: "Burgundy is a famous gastronomic region in France." },
    { word: "cooking method", translation: "méthode de cuisson", example: "Stir-frying is a common cooking method in Chinese cuisine." },
    { word: "culinary identity", translation: "identité culinaire", example: "The nation has maintained its culinary identity despite outside influences." },
    
    // Habitudes alimentaires
    { word: "food habit", translation: "habitude alimentaire", example: "Food habits vary greatly between cultures." },
    { word: "eating pattern", translation: "habitude alimentaire", example: "The study examines eating patterns in different communities." },
    { word: "meal structure", translation: "structure des repas", example: "The typical meal structure includes an appetizer, main course, and dessert." },
    { word: "dietary preference", translation: "préférence alimentaire", example: "The restaurant accommodates various dietary preferences." },
    { word: "seasonal eating", translation: "alimentation saisonnière", example: "Seasonal eating connects us to the natural cycles of food production." },
    { word: "communal dining", translation: "repas communautaire", example: "Communal dining is an important tradition in many cultures." },
    { word: "food ritual", translation: "rituel alimentaire", example: "Sunday dinner is an important food ritual in many families." },
    { word: "food taboo", translation: "tabou alimentaire", example: "Various religions have different food taboos." },
    { word: "cultural practice", translation: "pratique culturelle", example: "Fasting is a cultural practice in many traditions." },
    { word: "meal timing", translation: "horaire des repas", example: "Meal timing differs significantly between countries." },
    { word: "portion size", translation: "taille des portions", example: "American restaurants often serve large portion sizes." },
    { word: "dining etiquette", translation: "étiquette à table", example: "Different countries have different dining etiquette rules." },
    { word: "culinary custom", translation: "coutume culinaire", example: "In Japan, it's a culinary custom to say 'itadakimasu' before eating." },
    { word: "food preference", translation: "préférence alimentaire", example: "Food preferences begin developing in childhood." },
    { word: "intergenerational tradition", translation: "tradition intergénérationnelle", example: "Family recipes are intergenerational traditions." },
    
    // Restaurants & services culinaires
    { word: "fine dining", translation: "haute cuisine", example: "The city is known for its fine dining establishments." },
    { word: "Michelin star", translation: "étoile Michelin", example: "The chef's restaurant earned its first Michelin star last year." },
    { word: "tasting menu", translation: "menu dégustation", example: "The tasting menu offers small portions of the chef's specialties." },
    { word: "prix fixe menu", translation: "menu à prix fixe", example: "The restaurant offers a prix fixe menu for special occasions." },
    { word: "signature dish", translation: "plat signature", example: "The truffle pasta is the chef's signature dish." },
    { word: "food critic", translation: "critique gastronomique", example: "The food critic gave the restaurant a glowing review." },
    { word: "reservation", translation: "réservation", example: "You need to make a reservation weeks in advance." },
    { word: "dining experience", translation: "expérience gastronomique", example: "They offer a unique dining experience with entertainment." },
    { word: "culinary tourism", translation: "tourisme culinaire", example: "Culinary tourism has become increasingly popular." },
    { word: "food delivery service", translation: "service de livraison de repas", example: "Food delivery services boomed during the pandemic." },
    { word: "meal kit", translation: "kit repas", example: "Meal kit companies deliver pre-portioned ingredients and recipes." },
    { word: "catering", translation: "traiteur", example: "They hired a catering company for the wedding reception." },
    { word: "personal chef", translation: "chef personnel", example: "Celebrities often employ personal chefs." },
    { word: "cooking class", translation: "cours de cuisine", example: "The cooking class teaches local techniques and recipes." },
    { word: "food truck", translation: "camion-restaurant", example: "Food trucks offer gourmet options at lower prices." },
    { word: "pop-up restaurant", translation: "restaurant éphémère", example: "The chef is hosting a pop-up restaurant for three months." },
    { word: "hospitality industry", translation: "industrie hôtelière", example: "She works in the hospitality industry as a sommelier." },
    
    // Critique gastronomique
    { word: "restaurant review", translation: "critique de restaurant", example: "The restaurant review helped them decide where to eat." },
    { word: "culinary critique", translation: "critique culinaire", example: "His culinary critique focuses on authenticity and execution." },
    { word: "food writing", translation: "écriture gastronomique", example: "Food writing combines journalism with culinary expertise." },
    { word: "gastronomy guide", translation: "guide gastronomique", example: "The gastronomy guide recommends restaurants in each region." },
    { word: "rating system", translation: "système de notation", example: "The website uses a five-star rating system for restaurants." },
    { word: "food blog", translation: "blog culinaire", example: "Her food blog has thousands of followers." },
    { word: "culinary journalism", translation: "journalisme culinaire", example: "Culinary journalism covers more than just restaurant reviews." },
    { word: "dining recommendation", translation: "recommandation gastronomique", example: "The app provides dining recommendations based on your preferences." },
    { word: "food photography", translation: "photographie culinaire", example: "Food photography is essential for restaurant marketing." },
    { word: "taste test", translation: "test de dégustation", example: "The magazine conducted a taste test of supermarket chocolates." },
    { word: "star rating", translation: "notation par étoiles", example: "The restaurant maintained its three-star rating this year." },
    { word: "culinary award", translation: "prix culinaire", example: "The chef has won numerous culinary awards." },
    { word: "expert opinion", translation: "avis d'expert", example: "The book compiles expert opinions on regional wines." },
    { word: "food influencer", translation: "influenceur culinaire", example: "Food influencers can significantly impact a restaurant's popularity." },
    { word: "critical assessment", translation: "évaluation critique", example: "Her critical assessment noted both strengths and weaknesses." },
    { word: "culinary standard", translation: "standard culinaire", example: "The restaurant sets high culinary standards." },
    
    // Événements culinaires
    { word: "food festival", translation: "festival gastronomique", example: "The annual food festival celebrates local specialties." },
    { word: "culinary competition", translation: "concours culinaire", example: "Chefs from around the world participate in the culinary competition." },
    { word: "cooking demonstration", translation: "démonstration de cuisine", example: "The cooking demonstration shows traditional techniques." },
    { word: "food fair", translation: "salon gastronomique", example: "The food fair features artisanal producers from the region." },
    { word: "wine tasting", translation: "dégustation de vin", example: "The winery offers wine tasting tours daily." },
    { word: "chef's table", translation: "table du chef", example: "The chef's table experience includes interaction with the chef." },
    { word: "dinner party", translation: "dîner", example: "They host a dinner party for friends every month." },
    { word: "gastronomic exhibition", translation: "exposition gastronomique", example: "The gastronomic exhibition showcases international cuisines." },
    { word: "food conference", translation: "conférence sur l'alimentation", example: "The food conference addressed sustainable farming practices." },
    { word: "culinary workshop", translation: "atelier culinaire", example: "The culinary workshop focuses on bread-making techniques." },
    { word: "food and wine pairing", translation: "accord mets et vins", example: "The restaurant offers food and wine pairing events monthly." },
    { word: "harvest festival", translation: "fête des moissons", example: "The harvest festival celebrates the year's crop." },
    { word: "cooking marathon", translation: "marathon de cuisine", example: "Chefs participate in a 24-hour cooking marathon for charity." },
    { word: "culinary tour", translation: "circuit gastronomique", example: "The culinary tour includes visits to markets and restaurants." },
    { word: "food symposium", translation: "symposium alimentaire", example: "The food symposium brings together chefs, producers, and researchers." },
    
    // Nutrition & diététique
    { word: "nutritional value", translation: "valeur nutritive", example: "The nutritional value of processed foods is often lower." },
    { word: "dietary requirement", translation: "besoin diététique", example: "The menu accommodates various dietary requirements." },
    { word: "balanced diet", translation: "alimentation équilibrée", example: "A balanced diet includes a variety of food groups." },
    { word: "nutrient density", translation: "densité nutritionnelle", example: "Leafy greens have high nutrient density." },
    { word: "nutritional deficiency", translation: "carence nutritionnelle", example: "Iron deficiency is a common nutritional deficiency." },
    { word: "caloric intake", translation: "apport calorique", example: "Athletes need a higher caloric intake than sedentary individuals." },
    { word: "dietary guideline", translation: "recommandation nutritionnelle", example: "Dietary guidelines vary between countries." },
    { word: "metabolism", translation: "métabolisme", example: "Age affects how your metabolism processes food." },
    { word: "antioxidant", translation: "antioxydant", example: "Berries are rich in antioxidants." },
    { word: "food intolerance", translation: "intolérance alimentaire", example: "Lactose intolerance is a common food intolerance." },
    { word: "dietary pattern", translation: "modèle alimentaire", example: "The Mediterranean dietary pattern is associated with health benefits." },
    { word: "macronutrient", translation: "macronutriment", example: "Protein, carbohydrates, and fats are macronutrients." },
    { word: "micronutrient", translation: "micronutriment", example: "Vitamins and minerals are important micronutrients." },
    { word: "dietary fiber", translation: "fibre alimentaire", example: "Whole grains provide dietary fiber." },
    { word: "digestive health", translation: "santé digestive", example: "Probiotics can support digestive health." },
    { word: "nutritional science", translation: "science nutritionnelle", example: "Nutritional science is constantly evolving." },
    { word: "eating disorder", translation: "trouble alimentaire", example: "Eating disorders require professional treatment." },
    
    // Production alimentaire
    { word: "sustainable farming", translation: "agriculture durable", example: "Sustainable farming practices protect the environment." },
    { word: "organic production", translation: "production biologique", example: "Organic production prohibits synthetic pesticides." },
    { word: "local sourcing", translation: "approvisionnement local", example: "The restaurant emphasizes local sourcing of ingredients." },
    { word: "farm-to-table", translation: "de la ferme à la table", example: "The farm-to-table movement promotes freshness and sustainability." },
    { word: "seasonal produce", translation: "produits de saison", example: "The menu changes to feature seasonal produce." },
    { word: "artisanal production", translation: "production artisanale", example: "Artisanal production methods are often labor-intensive." },
    { word: "food supply chain", translation: "chaîne d'approvisionnement alimentaire", example: "The pandemic disrupted food supply chains globally." },
    { word: "small-batch", translation: "petite production", example: "They specialize in small-batch chocolate production." },
    { word: "GMO", translation: "OGM", example: "Some countries require labeling of GMO ingredients." },
    { word: "free-range", translation: "élevé en plein air", example: "They only use free-range eggs in their bakery." },
    { word: "fair trade", translation: "commerce équitable", example: "Fair trade ensures producers receive reasonable compensation." },
    { word: "crop rotation", translation: "rotation des cultures", example: "Crop rotation helps maintain soil health." },
    { word: "livestock farming", translation: "élevage", example: "Sustainable livestock farming practices are gaining popularity." },
    { word: "food waste", translation: "gaspillage alimentaire", example: "Restaurants are finding creative ways to reduce food waste." },
    { word: "carbon footprint", translation: "empreinte carbone", example: "The carbon footprint of food production varies by method." },
    { word: "food technology", translation: "technologie alimentaire", example: "Food technology innovations can improve shelf life." },
    { word: "food security", translation: "sécurité alimentaire", example: "Climate change threatens global food security." },
    { word: "vertical farming", translation: "agriculture verticale", example: "Vertical farming allows food production in urban environments." },
    { word: "food sovereignty", translation: "souveraineté alimentaire", example: "Food sovereignty emphasizes local control over food systems." },
    { word: "hydroponic", translation: "hydroponique", example: "Hydroponic systems grow plants without soil." }
  ]
};