export const vocab = {
  title: "Habitation & Style de Vie",
  words: [
    // Marchés immobiliers
    { word: "real estate market", translation: "marché immobilier", example: "The real estate market is booming in this area." },
    { word: "property value", translation: "valeur immobilière", example: "Property values have increased by 15% in the last year." },
    { word: "housing market", translation: "marché du logement", example: "The housing market is becoming increasingly competitive." },
    { word: "mortgage", translation: "prêt immobilier", example: "They took out a 30-year mortgage to buy their house." },
    { word: "down payment", translation: "apport personnel", example: "They saved for years to have enough for a down payment." },
    { word: "interest rate", translation: "taux d'intérêt", example: "The interest rate on their mortgage is quite low." },
    { word: "real estate agent", translation: "agent immobilier", example: "The real estate agent showed us several houses." },
    { word: "property listing", translation: "annonce immobilière", example: "I found the apartment on an online property listing." },
    { word: "housing bubble", translation: "bulle immobilière", example: "Economists are concerned about a potential housing bubble." },
    { word: "foreclosure", translation: "saisie immobilière", example: "The number of foreclosures has decreased in recent years." },
    { word: "property tax", translation: "taxe foncière", example: "Property taxes vary depending on the location." },
    { word: "housing shortage", translation: "pénurie de logements", example: "The city is experiencing a severe housing shortage." },
    { word: "market trends", translation: "tendances du marché", example: "Market trends indicate a shift toward suburban properties." },
    { word: "investment property", translation: "bien immobilier d'investissement", example: "They purchased an investment property to rent out." },
    { word: "appraisal", translation: "évaluation", example: "The bank required an appraisal before approving the loan." },
    { word: "housing affordability", translation: "accessibilité au logement", example: "Housing affordability is a major issue in many cities." },
    { word: "property deed", translation: "acte de propriété", example: "The property deed confirms legal ownership." },
    { word: "closing costs", translation: "frais de clôture", example: "Don't forget to budget for closing costs when buying a home." },
    
    // Architecture & design
    { word: "architectural style", translation: "style architectural", example: "The house has a distinctive Victorian architectural style." },
    { word: "contemporary design", translation: "design contemporain", example: "The building features contemporary design elements." },
    { word: "open floor plan", translation: "plan ouvert", example: "Modern homes often have an open floor plan." },
    { word: "minimalist", translation: "minimaliste", example: "They prefer a minimalist aesthetic for their home." },
    { word: "sustainable architecture", translation: "architecture durable", example: "Sustainable architecture focuses on environmental impact." },
    { word: "restoration", translation: "restauration", example: "The historic building underwent a careful restoration." },
    { word: "facade", translation: "façade", example: "The building's facade features ornate details." },
    { word: "blueprint", translation: "plan", example: "The architect showed us the blueprints for our house." },
    { word: "load-bearing wall", translation: "mur porteur", example: "You can't remove that load-bearing wall without structural support." },
    { word: "feng shui", translation: "feng shui", example: "They arranged their furniture according to feng shui principles." },
    { word: "ergonomic design", translation: "conception ergonomique", example: "Ergonomic design improves comfort and efficiency." },
    { word: "aesthetics", translation: "esthétique", example: "The aesthetics of a space can affect your mood." },
    { word: "spatial planning", translation: "aménagement spatial", example: "Good spatial planning maximizes functionality." },
    { word: "design elements", translation: "éléments de design", example: "The room incorporates various design elements from different periods." },
    { word: "proportion", translation: "proportion", example: "Balance and proportion are essential in good design." },
    { word: "retrofit", translation: "rénovation énergétique", example: "They retrofitted their old house with modern energy systems." },
    
    // Aménagement intérieur
    { word: "interior design", translation: "design d'intérieur", example: "She hired an interior design firm to redecorate her home." },
    { word: "color scheme", translation: "palette de couleurs", example: "The color scheme creates a calm atmosphere." },
    { word: "statement piece", translation: "pièce maîtresse", example: "The vintage chandelier serves as a statement piece in the dining room." },
    { word: "feature wall", translation: "mur d'accent", example: "They painted a feature wall in a bold color." },
    { word: "ambient lighting", translation: "éclairage d'ambiance", example: "Ambient lighting creates a warm atmosphere in the evening." },
    { word: "task lighting", translation: "éclairage fonctionnel", example: "Good task lighting is essential in a home office." },
    { word: "room divider", translation: "séparateur de pièce", example: "They used a bookshelf as a room divider in the studio apartment." },
    { word: "built-in storage", translation: "rangement intégré", example: "Built-in storage helps maximize space in small homes." },
    { word: "custom furniture", translation: "mobilier sur mesure", example: "They invested in custom furniture for their oddly-shaped living room." },
    { word: "accent piece", translation: "élément décoratif", example: "The colorful rug serves as an accent piece in the neutral room." },
    { word: "texture", translation: "texture", example: "Mixing textures adds visual interest to a space." },
    { word: "focal point", translation: "point focal", example: "The fireplace serves as the focal point of the living room." },
    { word: "flow", translation: "circulation", example: "Good design ensures a natural flow between spaces." },
    { word: "reupholster", translation: "retapisser", example: "They decided to reupholster the antique chair instead of replacing it." },
    { word: "layering", translation: "superposition", example: "Layering different textiles creates a cozy atmosphere." },
    
    // Problèmes de logement
    { word: "housing crisis", translation: "crise du logement", example: "The city is facing a severe housing crisis." },
    { word: "homelessness", translation: "sans-abrisme", example: "Homelessness is increasing in urban areas." },
    { word: "gentrification", translation: "gentrification", example: "Gentrification has changed the character of the neighborhood." },
    { word: "overcrowding", translation: "surpeuplement", example: "Overcrowding is a common issue in affordable housing." },
    { word: "inadequate housing", translation: "logement inadéquat", example: "Many families live in inadequate housing conditions." },
    { word: "eviction", translation: "expulsion", example: "Tenants received an eviction notice due to building renovation." },
    { word: "housing discrimination", translation: "discrimination au logement", example: "There are laws against housing discrimination." },
    { word: "rent control", translation: "contrôle des loyers", example: "Rent control aims to keep housing affordable." },
    { word: "slumlord", translation: "marchand de sommeil", example: "Tenants complained about the slumlord's neglect of the building." },
    { word: "habitability", translation: "habitabilité", example: "The apartment did not meet basic standards of habitability." },
    { word: "tenant rights", translation: "droits des locataires", example: "It's important to understand your tenant rights." },
    { word: "housing advocacy", translation: "défense du droit au logement", example: "Housing advocacy groups fight for affordable housing." },
    { word: "displacement", translation: "déplacement", example: "Urban renewal often leads to displacement of residents." },
    { word: "affordable housing", translation: "logement abordable", example: "The city needs more affordable housing options." },
    { word: "public housing", translation: "logement social", example: "Public housing provides homes for low-income families." },
    
    // Services résidentiels
    { word: "property management", translation: "gestion immobilière", example: "The property management company maintains the building." },
    { word: "homeowners association", translation: "syndicat de copropriété", example: "The homeowners association enforces community rules." },
    { word: "concierge service", translation: "service de conciergerie", example: "The luxury apartment building offers concierge service." },
    { word: "security system", translation: "système de sécurité", example: "They installed a comprehensive security system for peace of mind." },
    { word: "waste management", translation: "gestion des déchets", example: "The building has improved its waste management practices." },
    { word: "landscaping service", translation: "service d'aménagement paysager", example: "The landscaping service maintains the common areas." },
    { word: "building superintendent", translation: "concierge d'immeuble", example: "Report maintenance issues to the building superintendent." },
    { word: "smart home system", translation: "système de maison intelligente", example: "Their smart home system controls lighting, temperature, and security." },
    { word: "utility services", translation: "services publics", example: "Utility services are included in the monthly fees." },
    { word: "residential amenities", translation: "équipements résidentiels", example: "The building offers residential amenities like a gym and pool." },
    { word: "emergency response", translation: "intervention d'urgence", example: "The community has a rapid emergency response protocol." },
    { word: "home warranty", translation: "garantie habitation", example: "A home warranty covers repairs for major systems and appliances." },
    { word: "home inspection", translation: "inspection de maison", example: "Always get a thorough home inspection before buying." },
    
    // Déménagement & installation
    { word: "relocation", translation: "déménagement", example: "The company offered a relocation package for the new job." },
    { word: "moving company", translation: "entreprise de déménagement", example: "They hired a moving company for their cross-country move." },
    { word: "packing materials", translation: "matériel d'emballage", example: "You'll need plenty of packing materials for a big move." },
    { word: "logistics", translation: "logistique", example: "Planning the logistics of a move can be complicated." },
    { word: "transitional housing", translation: "logement transitoire", example: "They stayed in transitional housing while searching for a permanent home." },
    { word: "moving in", translation: "emménagement", example: "Moving in is exciting but stressful." },
    { word: "housewarming", translation: "pendaison de crémaillère", example: "They hosted a housewarming party for their friends." },
    { word: "settling in", translation: "s'installer", example: "It takes time to settle in to a new neighborhood." },
    { word: "forwarding address", translation: "adresse de réexpédition", example: "Don't forget to set up a forwarding address with the post office." },
    { word: "change of address", translation: "changement d'adresse", example: "Submit a change of address form for all your accounts." },
    { word: "inventory", translation: "inventaire", example: "Make an inventory of your belongings before moving." },
    { word: "setup services", translation: "services d'installation", example: "Schedule setup services for utilities and internet in advance." },
    
    // Écologie domestique
    { word: "sustainable living", translation: "mode de vie durable", example: "They practice sustainable living in their home." },
    { word: "energy efficiency", translation: "efficacité énergétique", example: "Energy efficiency reduces both costs and environmental impact." },
    { word: "carbon footprint", translation: "empreinte carbone", example: "They've taken steps to reduce their household carbon footprint." },
    { word: "renewable energy", translation: "énergie renouvelable", example: "The house uses renewable energy from solar panels." },
    { word: "greywater system", translation: "système d'eau grise", example: "A greywater system recycles water from sinks and showers." },
    { word: "composting", translation: "compostage", example: "Composting kitchen waste reduces landfill contributions." },
    { word: "zero-waste household", translation: "ménage zéro déchet", example: "They're working toward becoming a zero-waste household." },
    { word: "eco-friendly products", translation: "produits écologiques", example: "They only use eco-friendly cleaning products." },
    { word: "energy audit", translation: "audit énergétique", example: "An energy audit identified several ways to improve efficiency." },
    { word: "passive house", translation: "maison passive", example: "A passive house requires very little energy for heating and cooling." },
    { word: "insulation", translation: "isolation", example: "Good insulation is key to energy efficiency." },
    { word: "weatherization", translation: "adaptation climatique", example: "Weatherization helps protect homes from the elements." },
    { word: "indoor air quality", translation: "qualité de l'air intérieur", example: "House plants can improve indoor air quality." },
    { word: "biophilic design", translation: "design biophilique", example: "Biophilic design incorporates natural elements into living spaces." },
    { word: "upcycling", translation: "surcyclage", example: "Upcycling transforms old items into something useful or decorative." },
    { word: "energy-saving appliances", translation: "appareils à économie d'énergie", example: "Energy-saving appliances reduce electricity consumption." }
  ]
};