export const vocab = {
  title: "Voyages & Découvertes Culturelles",
  words: [
    // Préparation de voyage
    { word: "destination", translation: "destination", example: "They're trying to choose a destination for their next vacation." },
    { word: "accommodation", translation: "hébergement", example: "We need to book our accommodation well in advance." },
    { word: "travel agency", translation: "agence de voyage", example: "She works at a travel agency that specializes in Asian tours." },
    { word: "itinerary", translation: "itinéraire", example: "Our itinerary includes three days in Rome and four in Florence." },
    { word: "travel insurance", translation: "assurance voyage", example: "Always purchase travel insurance before going abroad." },
    { word: "guidebook", translation: "guide touristique", example: "I bought a guidebook to learn about the local culture and attractions." },
    { word: "language barrier", translation: "barrière linguistique", example: "The language barrier made ordering food challenging." },
    { word: "foreign exchange", translation: "bureau de change", example: "You'll find foreign exchange offices at the airport." },
    { word: "travel adapter", translation: "adaptateur de voyage", example: "Don't forget to pack a travel adapter for your electronics." },
    { word: "to pack", translation: "faire ses bagages", example: "I always pack too many clothes when I travel." },
    { word: "booking", translation: "réservation", example: "The booking confirmation should arrive by email." },
    { word: "luggage allowance", translation: "franchise de bagages", example: "Check the luggage allowance before packing your suitcase." },
    { word: "travel documents", translation: "documents de voyage", example: "Make sure you have all your travel documents before leaving." },
    { word: "last-minute deal", translation: "offre de dernière minute", example: "We found a great last-minute deal for our holiday." },
    { word: "pre-departure checklist", translation: "liste de contrôle avant départ", example: "Going through a pre-departure checklist helps ensure you don't forget anything important." },
    { word: "travel app", translation: "application de voyage", example: "This travel app helps you navigate public transportation in foreign cities." },
    { word: "emergency contact", translation: "contact d'urgence", example: "Always leave emergency contact information with family when traveling abroad." },
    { word: "vaccination", translation: "vaccination", example: "Certain vaccinations are required for travel to tropical regions." },
    { word: "to plan ahead", translation: "planifier à l'avance", example: "It's best to plan ahead when visiting popular tourist destinations." },
    { word: "weather forecast", translation: "prévisions météorologiques", example: "Check the weather forecast before packing for your trip." },
    
    // Types de tourisme
    { word: "adventure tourism", translation: "tourisme d'aventure", example: "Adventure tourism includes activities like white-water rafting and rock climbing." },
    { word: "cultural tourism", translation: "tourisme culturel", example: "Cultural tourism focuses on experiencing a region's culture and heritage." },
    { word: "sustainable tourism", translation: "tourisme durable", example: "Sustainable tourism aims to minimize impact on local environments." },
    { word: "medical tourism", translation: "tourisme médical", example: "Medical tourism involves traveling abroad for healthcare procedures." },
    { word: "gastronomic tourism", translation: "tourisme gastronomique", example: "Gastronomic tourism revolves around experiencing local cuisines." },
    { word: "religious tourism", translation: "tourisme religieux", example: "Pilgrims engage in religious tourism when visiting sacred sites." },
    { word: "educational tourism", translation: "tourisme éducatif", example: "Educational tourism combines travel with learning opportunities." },
    { word: "rural tourism", translation: "tourisme rural", example: "Rural tourism offers an escape from busy urban environments." },
    { word: "volunteer tourism", translation: "tourisme solidaire", example: "Volunteer tourism combines travel with community service projects." },
    { word: "dark tourism", translation: "tourisme macabre", example: "Dark tourism involves visiting sites associated with death and tragedy." },
    { word: "wellness tourism", translation: "tourisme de bien-être", example: "Wellness tourism focuses on improving health and well-being while traveling." },
    { word: "heritage tourism", translation: "tourisme patrimonial", example: "Heritage tourism focuses on visiting historical and cultural landmarks." },
    { word: "agritourism", translation: "agritourisme", example: "Agritourism allows visitors to experience agricultural life and activities." },
    { word: "indigenous tourism", translation: "tourisme autochtone", example: "Indigenous tourism offers insights into native cultures and traditions." },
    { word: "cruise tourism", translation: "tourisme de croisière", example: "Cruise tourism has grown significantly in popularity over the past decade." },
    
    // Expériences de voyage
    { word: "cultural immersion", translation: "immersion culturelle", example: "The program offers cultural immersion through homestays with local families." },
    { word: "authentic experience", translation: "expérience authentique", example: "Travelers often seek authentic experiences beyond typical tourist attractions." },
    { word: "local customs", translation: "coutumes locales", example: "It's important to respect local customs when traveling abroad." },
    { word: "cultural shock", translation: "choc culturel", example: "Many travelers experience cultural shock when first visiting very different countries." },
    { word: "off the beaten path", translation: "hors des sentiers battus", example: "They prefer traveling off the beaten path to discover hidden gems." },
    { word: "homestay", translation: "séjour chez l'habitant", example: "A homestay can provide deeper insights into local life than a hotel." },
    { word: "guided tour", translation: "visite guidée", example: "The guided tour offered fascinating historical information about the site." },
    { word: "self-guided tour", translation: "visite auto-guidée", example: "The museum offers self-guided tours with audio headsets." },
    { word: "scenic route", translation: "route panoramique", example: "We took the scenic route along the coast instead of the highway." },
    { word: "highlight", translation: "temps fort", example: "Seeing the Northern Lights was the highlight of our trip to Iceland." },
    { word: "hidden gem", translation: "perle méconnue", example: "This little restaurant is a hidden gem that most tourists never find." },
    { word: "tourist trap", translation: "piège à touristes", example: "The restaurant near the monument is a tourist trap with inflated prices." },
    { word: "once-in-a-lifetime experience", translation: "expérience unique", example: "Safari in the Serengeti was truly a once-in-a-lifetime experience." },
    { word: "travel journal", translation: "carnet de voyage", example: "She kept a detailed travel journal throughout her six-month journey." },
    { word: "bucket list", translation: "liste de souhaits", example: "Seeing the pyramids was at the top of his travel bucket list." },
    { word: "language exchange", translation: "échange linguistique", example: "Language exchange with locals improved her Spanish tremendously." },
    
    // Problèmes de voyage
    { word: "travel disruption", translation: "perturbation de voyage", example: "The strike caused significant travel disruption across the country." },
    { word: "flight cancellation", translation: "annulation de vol", example: "Their flight cancellation meant they had to stay an extra night." },
    { word: "lost reservation", translation: "réservation perdue", example: "The hotel had no record of their lost reservation." },
    { word: "overbooked", translation: "surréservation", example: "The flight was overbooked, so some passengers were offered compensation." },
    { word: "tourist scam", translation: "arnaque touristique", example: "Be aware of common tourist scams in this area." },
    { word: "pickpocketing", translation: "vol à la tire", example: "Pickpocketing is common in crowded tourist areas." },
    { word: "language misunderstanding", translation: "malentendu linguistique", example: "A language misunderstanding led them to the wrong location." },
    { word: "illness abroad", translation: "maladie à l'étranger", example: "Getting an illness abroad can be particularly stressful." },
    { word: "delayed baggage", translation: "bagages retardés", example: "Their delayed baggage finally arrived three days into their vacation." },
    { word: "travel advisory", translation: "avis aux voyageurs", example: "Check the government travel advisory before booking your trip." },
    { word: "emergency evacuation", translation: "évacuation d'urgence", example: "The hurricane warning triggered an emergency evacuation of tourists." },
    { word: "travel complaint", translation: "réclamation de voyage", example: "He filed a travel complaint about the misleading hotel description." },
    { word: "repatriation", translation: "rapatriement", example: "The embassy arranged for repatriation of citizens during the crisis." },
    { word: "to be stranded", translation: "être bloqué", example: "Hundreds of passengers were stranded at the airport due to the snowstorm." },
    { word: "travel warning", translation: "avertissement de voyage", example: "The government issued a travel warning for the region due to political unrest." },
    
    // Rencontres interculturelles
    { word: "cross-cultural communication", translation: "communication interculturelle", example: "Cross-cultural communication skills are essential for international business." },
    { word: "cultural understanding", translation: "compréhension culturelle", example: "Travel promotes cultural understanding and tolerance." },
    { word: "cultural sensitivity", translation: "sensibilité culturelle", example: "Cultural sensitivity is important when visiting religious sites." },
    { word: "etiquette", translation: "étiquette", example: "Different countries have different dining etiquette." },
    { word: "cultural taboo", translation: "tabou culturel", example: "It's important to learn about cultural taboos before visiting a new country." },
    { word: "intercultural exchange", translation: "échange interculturel", example: "The program fosters intercultural exchange between students from different countries." },
    { word: "global perspective", translation: "perspective mondiale", example: "Travel helps develop a global perspective on issues." },
    { word: "culture clash", translation: "choc des cultures", example: "There was some culture clash when the international team first started working together." },
    { word: "cultural relativism", translation: "relativisme culturel", example: "Cultural relativism involves understanding behaviors within their cultural context." },
    { word: "cultural appropriation", translation: "appropriation culturelle", example: "The festival was criticized for cultural appropriation of indigenous traditions." },
    { word: "cultural heritage", translation: "patrimoine culturel", example: "UNESCO works to protect cultural heritage sites worldwide." },
    { word: "indigenous culture", translation: "culture autochtone", example: "The tour offered insights into indigenous culture and traditions." },
    { word: "cultural diplomacy", translation: "diplomatie culturelle", example: "Cultural diplomacy uses cultural exchange to strengthen relationships between nations." },
    { word: "expat community", translation: "communauté d'expatriés", example: "The expat community organized weekly language exchange meetings." },
    { word: "cultural integration", translation: "intégration culturelle", example: "Moving abroad requires a period of cultural integration." },
    
    // Budget voyage
    { word: "travel expenses", translation: "frais de voyage", example: "Keep track of your travel expenses to avoid overspending." },
    { word: "exchange rate", translation: "taux de change", example: "A favorable exchange rate can make your trip more affordable." },
    { word: "budget traveler", translation: "voyageur économe", example: "Budget travelers often stay in hostels instead of hotels." },
    { word: "cost of living", translation: "coût de la vie", example: "The cost of living varies significantly between different destinations." },
    { word: "affordable destination", translation: "destination abordable", example: "Southeast Asia is known as an affordable destination for Western travelers." },
    { word: "money-saving tip", translation: "conseil pour économiser", example: "A good money-saving tip is to eat where the locals eat." },
    { word: "travel fund", translation: "fonds de voyage", example: "They set aside a travel fund each month for future trips." },
    { word: "backpacker budget", translation: "budget routard", example: "They traveled through Europe on a backpacker budget of €50 per day." },
    { word: "luxury splurge", translation: "dépense de luxe", example: "The five-star hotel was their one luxury splurge during an otherwise budget trip." },
    { word: "value for money", translation: "rapport qualité-prix", example: "This tour offers excellent value for money compared to others." },
    { word: "hidden cost", translation: "coût caché", example: "Be aware of hidden costs like tourist taxes and service charges." },
    { word: "price comparison", translation: "comparaison de prix", example: "Use price comparison websites to find the best deals on flights." },
    { word: "travel on a shoestring", translation: "voyager à petit budget", example: "After losing his job, he had to travel on a shoestring." },
    { word: "budget accommodation", translation: "hébergement économique", example: "Hostels and guesthouses are popular budget accommodation options." },
    { word: "daily allowance", translation: "allocation journalière", example: "They set a daily allowance of $100 for food and activities." },
    
    // Souvenirs & impressions
    { word: "lasting impression", translation: "impression durable", example: "The kindness of the local people left a lasting impression on me." },
    { word: "life-changing experience", translation: "expérience qui change la vie", example: "Living abroad was a life-changing experience for her." },
    { word: "travel memory", translation: "souvenir de voyage", example: "Taking photos helps preserve travel memories." },
    { word: "cultural insight", translation: "aperçu culturel", example: "The homestay provided valuable cultural insights that tourists rarely experience." },
    { word: "perspective shift", translation: "changement de perspective", example: "Travel often leads to a perspective shift on what's important in life." },
    { word: "postcard view", translation: "vue de carte postale", example: "The mountain lake offered a perfect postcard view." },
    { word: "sensory experience", translation: "expérience sensorielle", example: "The spice market was an intense sensory experience." },
    { word: "wanderlust", translation: "envie de voyager", example: "Looking at travel photos gave her wanderlust." },
    { word: "culture shock", translation: "choc culturel", example: "Returning home after a year abroad can cause reverse culture shock." },
    { word: "personal growth", translation: "développement personnel", example: "He attributes much of his personal growth to his travel experiences." },
    { word: "travel anecdote", translation: "anecdote de voyage", example: "Her travel anecdotes always entertain dinner guests." },
    { word: "photographic memory", translation: "souvenir photographique", example: "The photographic memory of sunset over the ancient ruins stayed with her." },
    { word: "keepsake", translation: "souvenir", example: "She bought a small keepsake from each country she visited." },
    { word: "travel story", translation: "récit de voyage", example: "His travel stories inspired many friends to visit Japan." },
    { word: "transformative experience", translation: "expérience transformatrice", example: "Their year traveling was a transformative experience that changed their career paths." }
  ]
};