export const vocab = {
  title: "Identité Complexe & Psychologie",
  words: [
    // Concept de soi
    { word: "self-concept", translation: "concept de soi", example: "Your self-concept develops over time through experience and reflection." },
    { word: "self-awareness", translation: "conscience de soi", example: "Meditation can increase self-awareness." },
    { word: "self-esteem", translation: "estime de soi", example: "Positive reinforcement helps build self-esteem in children." },
    { word: "self-image", translation: "image de soi", example: "Social media can significantly impact teenagers' self-image." },
    { word: "self-perception", translation: "perception de soi", example: "Our self-perception often differs from how others see us." },
    { word: "identity formation", translation: "formation de l'identité", example: "Adolescence is a critical period for identity formation." },
    { word: "self-efficacy", translation: "auto-efficacité", example: "Self-efficacy refers to your belief in your ability to succeed." },
    { word: "self-doubt", translation: "doute de soi", example: "Even accomplished professionals sometimes experience self-doubt." },
    { word: "self-actualization", translation: "accomplissement de soi", example: "Self-actualization represents the highest level in Maslow's hierarchy of needs." },
    { word: "self-reflection", translation: "autoréflexion", example: "Journaling is a useful tool for self-reflection." },
    { word: "self-determination", translation: "autodétermination", example: "Self-determination theory examines intrinsic motivation and personal choice." },
    { word: "identity crisis", translation: "crise d'identité", example: "Many people experience an identity crisis during major life transitions." },
    { word: "ego", translation: "ego", example: "In psychoanalytic theory, the ego balances the demands of the id and superego." },
    { word: "authenticity", translation: "authenticité", example: "Living with authenticity means being true to your values and beliefs." },
    { word: "core beliefs", translation: "croyances fondamentales", example: "Cognitive therapy helps identify and modify negative core beliefs." },
    { word: "self-fulfilling prophecy", translation: "prophétie autoréalisatrice", example: "His failure became a self-fulfilling prophecy because he expected to fail." },
    { word: "cognitive dissonance", translation: "dissonance cognitive", example: "Cognitive dissonance occurs when actions contradict beliefs or values." },
    { word: "self-regulation", translation: "autorégulation", example: "Self-regulation involves controlling your emotions and behaviors." },
    { word: "self-acceptance", translation: "acceptation de soi", example: "Self-acceptance is a key component of psychological well-being." },
    { word: "ideal self", translation: "moi idéal", example: "The gap between your actual self and ideal self can cause distress." },
    { word: "persona", translation: "persona", example: "People often present different personas in professional and personal settings." },
    { word: "perceived self", translation: "soi perçu", example: "Our perceived self is how we think others see us." },
    { word: "existential crisis", translation: "crise existentielle", example: "She experienced an existential crisis after the death of her mother." },
    { word: "collective identity", translation: "identité collective", example: "Religious groups often share a strong collective identity." },
    { word: "cultural identity", translation: "identité culturelle", example: "For immigrants, maintaining cultural identity can be both challenging and important." },
    
    // Personnalité approfondie
    { word: "personality trait", translation: "trait de personnalité", example: "Extraversion is a personality trait characterized by sociability and assertiveness." },
    { word: "temperament", translation: "tempérament", example: "Temperament refers to innate personality characteristics present from birth." },
    { word: "disposition", translation: "disposition", example: "She has a cheerful disposition even in difficult circumstances." },
    { word: "introversion", translation: "introversion", example: "Introversion is characterized by a focus on internal thoughts and feelings." },
    { word: "extraversion", translation: "extraversion", example: "His extraversion makes him the life of every party." },
    { word: "neuroticism", translation: "névrosisme", example: "Neuroticism is associated with emotional instability and anxiety." },
    { word: "conscientiousness", translation: "conscienciosité", example: "Conscientiousness is linked to organization, responsibility, and achievement-orientation." },
    { word: "agreeableness", translation: "agréabilité", example: "People high in agreeableness tend to be cooperative and compassionate." },
    { word: "openness to experience", translation: "ouverture à l'expérience", example: "Openness to experience correlates with creativity and intellectual curiosity." },
    { word: "personality disorder", translation: "trouble de la personnalité", example: "Borderline personality disorder affects emotional regulation and relationships." },
    { word: "narcissism", translation: "narcissisme", example: "Narcissism involves an inflated sense of self-importance and need for admiration." },
    { word: "psychopathy", translation: "psychopathie", example: "Psychopathy is characterized by lack of empathy and antisocial behavior." },
    { word: "machiavellianism", translation: "machiavélisme", example: "Machiavellianism involves manipulating others for personal gain." },
    { word: "personality assessment", translation: "évaluation de la personnalité", example: "The Myers-Briggs Type Indicator is a popular personality assessment tool." },
    { word: "character strength", translation: "force de caractère", example: "Resilience is considered an important character strength." },
    { word: "personality development", translation: "développement de la personnalité", example: "Early childhood experiences influence personality development." },
    { word: "maladaptive trait", translation: "trait inadapté", example: "Extreme perfectionism can become a maladaptive trait that causes distress." },
    { word: "adaptive trait", translation: "trait adaptatif", example: "Flexibility is an adaptive trait in changing environments." },
    { word: "personality profile", translation: "profil de personnalité", example: "Her personality profile indicated strong leadership potential." },
    { word: "personality psychology", translation: "psychologie de la personnalité", example: "Personality psychology examines individual differences in thought patterns and behaviors." },
    { word: "biopsychology", translation: "biopsychologie", example: "Biopsychology explores the relationship between genetics and personality." },
    { word: "dark triad", translation: "triade noire", example: "The dark triad consists of narcissism, psychopathy, and Machiavellianism." },
    { word: "individual differences", translation: "différences individuelles", example: "Personality research focuses on understanding individual differences." },
    { word: "social desirability bias", translation: "biais de désirabilité sociale", example: "Social desirability bias can affect the accuracy of personality assessments." },
    { word: "personality pattern", translation: "schéma de personnalité", example: "Her personality pattern shows consistency across different situations." },
    
    // Psychologie cognitive
    { word: "cognitive psychology", translation: "psychologie cognitive", example: "Cognitive psychology examines mental processes like thinking and problem-solving." },
    { word: "cognition", translation: "cognition", example: "Cognition includes all mental processes involved in acquiring knowledge." },
    { word: "perception", translation: "perception", example: "Perception involves organizing and interpreting sensory information." },
    { word: "attention", translation: "attention", example: "Attention allows us to focus on relevant information in our environment." },
    { word: "memory", translation: "mémoire", example: "Memory involves encoding, storing, and retrieving information." },
    { word: "working memory", translation: "mémoire de travail", example: "Working memory temporarily holds information for processing." },
    { word: "long-term memory", translation: "mémoire à long terme", example: "Long-term memory can store information for years or even a lifetime." },
    { word: "cognitive bias", translation: "biais cognitif", example: "Confirmation bias leads people to favor information that confirms existing beliefs." },
    { word: "heuristic", translation: "heuristique", example: "A heuristic is a mental shortcut used to make decisions quickly." },
    { word: "cognitive load", translation: "charge cognitive", example: "Complex tasks increase cognitive load and can impair performance." },
    { word: "problem-solving", translation: "résolution de problèmes", example: "Effective problem-solving requires analyzing information and generating solutions." },
    { word: "decision-making", translation: "prise de décision", example: "Emotions play a significant role in decision-making processes." },
    { word: "reasoning", translation: "raisonnement", example: "Critical thinking involves logical reasoning and evaluation of evidence." },
    { word: "mental model", translation: "modèle mental", example: "People develop mental models to understand how things work in the world." },
    { word: "schema", translation: "schéma", example: "A schema is a mental framework that helps organize and interpret information." },
    { word: "cognitive distortion", translation: "distorsion cognitive", example: "Cognitive distortions are inaccurate thoughts that reinforce negative thinking." },
    { word: "executive function", translation: "fonction exécutive", example: "Executive function includes skills like planning, organizing, and self-control." },
    { word: "metacognition", translation: "métacognition", example: "Metacognition involves thinking about your own thinking processes." },
    { word: "cognitive neuroscience", translation: "neuroscience cognitive", example: "Cognitive neuroscience examines the biological basis of mental processes." },
    { word: "information processing", translation: "traitement de l'information", example: "The information processing model compares human thinking to computer operations." },
    { word: "cognitive development", translation: "développement cognitif", example: "Piaget's theory describes stages of cognitive development in children." },
    { word: "cognitive flexibility", translation: "flexibilité cognitive", example: "Cognitive flexibility allows you to adapt your thinking to new situations." },
    { word: "cognitive reserve", translation: "réserve cognitive", example: "Education and mental stimulation build cognitive reserve that can delay dementia symptoms." },
    { word: "implicit cognition", translation: "cognition implicite", example: "Implicit cognition occurs outside conscious awareness and affects behavior." },
    { word: "cognitive architecture", translation: "architecture cognitive", example: "Cognitive architecture describes the underlying structure of mental processes." },
    
    // Émotions complexes
    { word: "emotional intelligence", translation: "intelligence émotionnelle", example: "Emotional intelligence involves recognizing and managing emotions in yourself and others." },
    { word: "emotional regulation", translation: "régulation émotionnelle", example: "Emotional regulation skills help people manage difficult feelings appropriately." },
    { word: "emotional resilience", translation: "résilience émotionnelle", example: "Emotional resilience allows you to adapt to stressful situations and adversity." },
    { word: "emotional awareness", translation: "conscience émotionnelle", example: "Emotional awareness is the ability to identify your own feelings as they occur." },
    { word: "emotional expression", translation: "expression émotionnelle", example: "Cultural norms influence acceptable emotional expression." },
    { word: "emotional contagion", translation: "contagion émotionnelle", example: "Emotional contagion explains how people unconsciously mirror others' emotions." },
    { word: "empathy", translation: "empathie", example: "Empathy allows us to understand and share the feelings of others." },
    { word: "compassion", translation: "compassion", example: "Compassion combines empathy with a desire to help alleviate suffering." },
    { word: "emotional granularity", translation: "granularité émotionnelle", example: "Emotional granularity refers to the ability to differentiate between similar emotions." },
    { word: "ambivalence", translation: "ambivalence", example: "She felt ambivalence about her decision, experiencing both excitement and fear." },
    { word: "melancholy", translation: "mélancolie", example: "Melancholy is a pensive sadness, often with a touch of fondness or pleasure." },
    { word: "nostalgia", translation: "nostalgie", example: "Nostalgia is a sentimental longing for the past." },
    { word: "serenity", translation: "sérénité", example: "Meditation can lead to feelings of serenity and inner peace." },
    { word: "contempt", translation: "mépris", example: "Contempt combines disgust with a sense of superiority." },
    { word: "schadenfreude", translation: "schadenfreude", example: "Schadenfreude is taking pleasure in another's misfortune." },
    { word: "awe", translation: "émerveillement", example: "The vast mountain landscape inspired feelings of awe." },
    { word: "emotional labor", translation: "travail émotionnel", example: "Many service jobs require significant emotional labor to manage one's feelings." },
    { word: "emotional maturity", translation: "maturité émotionnelle", example: "Emotional maturity involves taking responsibility for your feelings and actions." },
    { word: "affect", translation: "affect", example: "Researchers observed participants' affect during the experiment." },
    { word: "emotional dysregulation", translation: "dysrégulation émotionnelle", example: "Emotional dysregulation can result from childhood trauma." },
    { word: "catharsis", translation: "catharsis", example: "The intense workout provided a catharsis for his pent-up emotions." },
    { word: "emotional valence", translation: "valence émotionnelle", example: "Emotional valence refers to whether a feeling is positive or negative." },
    { word: "emotional arousal", translation: "excitation émotionnelle", example: "The suspenseful movie created high emotional arousal in viewers." },
    { word: "emotional vocabulary", translation: "vocabulaire émotionnel", example: "Developing an extensive emotional vocabulary helps with self-awareness." },
    { word: "primary emotion", translation: "émotion primaire", example: "Fear is considered a primary emotion present across cultures." },
    
    // Intelligence émotionnelle
    { word: "self-awareness", translation: "conscience de soi", example: "Self-awareness is the foundation of emotional intelligence." },
    { word: "social awareness", translation: "conscience sociale", example: "Social awareness involves recognizing others' emotions and group dynamics." },
    { word: "emotional perception", translation: "perception émotionnelle", example: "Emotional perception involves identifying emotions in facial expressions and voice tone." },
    { word: "emotional understanding", translation: "compréhension émotionnelle", example: "Emotional understanding includes recognizing how emotions blend and change over time." },
    { word: "emotional facilitation", translation: "facilitation émotionnelle", example: "Emotional facilitation uses emotions to enhance thinking and creativity." },
    { word: "emotional management", translation: "gestion émotionnelle", example: "Emotional management involves regulating your own emotions effectively." },
    { word: "interpersonal intelligence", translation: "intelligence interpersonnelle", example: "Interpersonal intelligence helps you navigate social relationships successfully." },
    { word: "intrapersonal intelligence", translation: "intelligence intrapersonnelle", example: "Intrapersonal intelligence involves understanding your own thoughts and feelings." },
    { word: "emotional quotient", translation: "quotient émotionnel", example: "Some employers measure candidates' emotional quotient during hiring." },
    { word: "relationship management", translation: "gestion des relations", example: "Relationship management includes skills like conflict resolution and collaboration." },
    { word: "emotional coaching", translation: "coaching émotionnel", example: "Parents can provide emotional coaching to help children develop emotional intelligence." },
    { word: "emotional literacy", translation: "littératie émotionnelle", example: "Schools increasingly recognize the importance of emotional literacy education." },
    { word: "social-emotional learning", translation: "apprentissage socio-émotionnel", example: "Social-emotional learning programs teach skills like empathy and self-regulation." },
    { word: "emotional competence", translation: "compétence émotionnelle", example: "Emotional competence develops throughout childhood and adolescence." },
    { word: "emotional agility", translation: "agilité émotionnelle", example: "Emotional agility involves responding flexibly to changing situations and feelings." },
    { word: "emotional authenticity", translation: "authenticité émotionnelle", example: "Leadership with emotional authenticity builds trust within teams." },
    { word: "emotion recognition", translation: "reconnaissance des émotions", example: "Children with autism may struggle with emotion recognition." },
    { word: "empathic accuracy", translation: "précision empathique", example: "Empathic accuracy refers to how correctly someone interprets others' emotions." },
    { word: "emotional resonance", translation: "résonance émotionnelle", example: "Emotional resonance between therapist and client strengthens the therapeutic alliance." },
    { word: "emotional reasoning", translation: "raisonnement émotionnel", example: "Emotional reasoning involves making decisions based on feelings rather than facts." },
    { word: "emotional climate", translation: "climat émotionnel", example: "The emotional climate of a workplace affects productivity and morale." },
    
    // Motivation & comportement
    { word: "motivation", translation: "motivation", example: "Intrinsic motivation comes from personal enjoyment rather than external rewards." },
    { word: "drive", translation: "pulsion", example: "Hunger is a primary drive that motivates food-seeking behavior." },
    { word: "incentive", translation: "incitation", example: "Financial incentives can increase productivity in the workplace." },
    { word: "reinforcement", translation: "renforcement", example: "Positive reinforcement strengthens behaviors through rewards." },
    { word: "punishment", translation: "punition", example: "Punishment aims to decrease unwanted behaviors." },
    { word: "conditioning", translation: "conditionnement", example: "Classical conditioning associates a neutral stimulus with a response." },
    { word: "operant conditioning", translation: "conditionnement opérant", example: "Operant conditioning uses consequences to modify voluntary behaviors." },
    { word: "intrinsic motivation", translation: "motivation intrinsèque", example: "Intrinsic motivation comes from within, like curiosity or enjoyment." },
    { word: "extrinsic motivation", translation: "motivation extrinsèque", example: "Extrinsic motivation involves external rewards like money or praise." },
    { word: "self-determination", translation: "autodétermination", example: "Self-determination theory focuses on autonomy, competence, and relatedness." },
    { word: "goal-setting", translation: "fixation d'objectifs", example: "Effective goal-setting increases motivation and achievement." },
    { word: "learned helplessness", translation: "impuissance apprise", example: "Learned helplessness occurs when people believe they cannot control their situation." },
    { word: "procrastination", translation: "procrastination", example: "Procrastination often results from fear of failure rather than laziness." },
    { word: "avoidance behavior", translation: "comportement d'évitement", example: "Avoidance behavior temporarily reduces anxiety but reinforces fear." },
    { word: "approach behavior", translation: "comportement d'approche", example: "Approach behavior involves moving toward desired outcomes." },
    { word: "behavioral inhibition", translation: "inhibition comportementale", example: "Behavioral inhibition makes people cautious in new situations." },
    { word: "behavioral activation", translation: "activation comportementale", example: "Behavioral activation therapy encourages engagement in positive activities." },
    { word: "habit formation", translation: "formation d'habitudes", example: "Habit formation requires consistency and repetition over time." },
    { word: "behavioral change", translation: "changement comportemental", example: "Successful behavioral change often involves small, incremental steps." },
    { word: "motivational interviewing", translation: "entretien motivationnel", example: "Motivational interviewing helps people resolve ambivalence about change." },
    { word: "self-efficacy", translation: "auto-efficacité", example: "Self-efficacy beliefs strongly influence motivation and persistence." },
    { word: "expectancy theory", translation: "théorie des attentes", example: "Expectancy theory suggests motivation depends on expected outcomes and their value." },
    { word: "attributional style", translation: "style attributionnel", example: "Your attributional style affects how you explain successes and failures." },
    { word: "locus of control", translation: "lieu de contrôle", example: "Internal locus of control means believing you control your own outcomes." },
    { word: "behavioral economics", translation: "économie comportementale", example: "Behavioral economics examines psychological factors in economic decision-making." },
    
    // Développement psychologique
    { word: "developmental psychology", translation: "psychologie du développement", example: "Developmental psychology studies psychological change throughout the lifespan." },
    { word: "cognitive development", translation: "développement cognitif", example: "Piaget's theory describes stages of cognitive development in children." },
    { word: "psychosocial development", translation: "développement psychosocial", example: "Erikson outlined eight stages of psychosocial development from infancy to late adulthood." },
    { word: "moral development", translation: "développement moral", example: "Kohlberg's theory examines how moral reasoning evolves over time." },
    { word: "attachment theory", translation: "théorie de l'attachement", example: "Attachment theory explains how early relationships affect later development." },
    { word: "secure attachment", translation: "attachement sécurisé", example: "Secure attachment provides a foundation for healthy relationships." },
    { word: "insecure attachment", translation: "attachement insécurisé", example: "Insecure attachment patterns can develop from inconsistent caregiving." },
    { word: "developmental milestone", translation: "étape de développement", example: "Walking is an important developmental milestone for toddlers." },
    { word: "critical period", translation: "période critique", example: "Language acquisition has a critical period during early childhood." },
    { word: "sensitive period", translation: "période sensible", example: "Early childhood represents a sensitive period for emotional development." },
    { word: "developmental trajectory", translation: "trajectoire développementale", example: "Each child follows a unique developmental trajectory." },
    { word: "developmental task", translation: "tâche développementale", example: "Forming a stable identity is a key developmental task of adolescence." },
    { word: "nature vs. nurture", translation: "inné contre acquis", example: "The nature vs. nurture debate examines genetic and environmental influences." },
    { word: "socialization", translation: "socialisation", example: "Socialization is the process of learning cultural norms and values." },
    { word: "scaffolding", translation: "étayage", example: "Scaffolding provides temporary support during learning and development." },
    { word: "zone of proximal development", translation: "zone proximale de développement", example: "The zone of proximal development is the gap between what a learner can do independently and with guidance." },
    { word: "developmental delay", translation: "retard de développement", example: "Early intervention helps children with developmental delays." },
    { word: "neuroplasticity", translation: "neuroplasticité", example: "Neuroplasticity allows the brain to reorganize itself throughout development." },
    { word: "resilience", translation: "résilience", example: "Resilience helps children overcome adversity and trauma." },
    { word: "developmental context", translation: "contexte développemental", example: "Understanding developmental context helps explain individual differences." },
    { word: "lifespan development", translation: "développement tout au long de la vie", example: "Lifespan development recognizes that growth continues throughout adulthood." },
    { word: "maturation", translation: "maturation", example: "Maturation involves biological growth processes that unfold naturally." },
    { word: "regression", translation: "régression", example: "Children may show regression during times of stress or major changes." },
    { word: "developmental psychology", translation: "psychologie développementale", example: "Developmental psychology examines how and why people change over time." },
    { word: "emerging adulthood", translation: "âge adulte émergent", example: "Emerging adulthood describes the transition period between adolescence and adulthood." }
  ]
};