export const vocab = {
  title: "Questions Environnementales Avancées",
  words: [
    // Politique climatique
    { word: "climate policy", translation: "politique climatique", example: "Effective climate policy requires international cooperation and commitment." },
    { word: "Paris Agreement", translation: "Accord de Paris", example: "The Paris Agreement aims to limit global warming to well below 2 degrees Celsius." },
    { word: "carbon tax", translation: "taxe carbone", example: "A carbon tax puts a price on greenhouse gas emissions to reduce their production." },
    { word: "emissions trading", translation: "échange de droits d'émission", example: "Emissions trading allows companies to buy and sell permits to emit carbon dioxide." },
    { word: "climate adaptation", translation: "adaptation climatique", example: "Climate adaptation measures help communities prepare for changing conditions." },
    { word: "climate mitigation", translation: "atténuation climatique", example: "Climate mitigation focuses on reducing greenhouse gas emissions." },
    { word: "nationally determined contributions", translation: "contributions déterminées au niveau national", example: "Nationally determined contributions outline each country's climate action plans." },
    { word: "carbon budget", translation: "budget carbone", example: "The carbon budget represents the maximum emissions to limit warming to a specific level." },
    { word: "climate finance", translation: "finance climatique", example: "Climate finance supports developing countries in addressing climate change." },
    { word: "climate justice", translation: "justice climatique", example: "Climate justice acknowledges that climate impacts affect vulnerable populations disproportionately." },
    { word: "carbon neutrality", translation: "neutralité carbone", example: "Many countries have pledged to achieve carbon neutrality by 2050." },
    { word: "climate governance", translation: "gouvernance climatique", example: "Climate governance establishes frameworks for addressing climate change." },
    { word: "climate legislation", translation: "législation climatique", example: "Climate legislation provides legal frameworks for emissions reduction." },
    { word: "carbon pricing", translation: "tarification du carbone", example: "Carbon pricing creates economic incentives to reduce greenhouse gas emissions." },
    { word: "climate diplomacy", translation: "diplomatie climatique", example: "Climate diplomacy builds international cooperation on environmental issues." },
    { word: "carbon offsetting", translation: "compensation carbone", example: "Carbon offsetting involves funding projects that reduce emissions elsewhere." },
    { word: "climate accountability", translation: "responsabilité climatique", example: "Climate accountability holds entities responsible for their emissions." },
    { word: "intergenerational equity", translation: "équité intergénérationnelle", example: "Intergenerational equity considers the rights of future generations in climate decisions." },
    { word: "climate resilience", translation: "résilience climatique", example: "Climate resilience helps communities withstand and recover from climate impacts." },
    { word: "global climate governance", translation: "gouvernance climatique mondiale", example: "Global climate governance coordinates international climate action." },
    
    // Transition énergétique
    { word: "energy transition", translation: "transition énergétique", example: "The energy transition involves shifting from fossil fuels to renewable sources." },
    { word: "renewable energy", translation: "énergie renouvelable", example: "Renewable energy comes from naturally replenishing sources like sun and wind." },
    { word: "solar power", translation: "énergie solaire", example: "Solar power technologies convert sunlight into electricity." },
    { word: "wind energy", translation: "énergie éolienne", example: "Wind energy is captured by turbines and converted to electricity." },
    { word: "hydroelectric power", translation: "énergie hydroélectrique", example: "Hydroelectric power generates electricity from flowing water." },
    { word: "geothermal energy", translation: "énergie géothermique", example: "Geothermal energy harnesses heat from within the Earth." },
    { word: "biomass energy", translation: "énergie de biomasse", example: "Biomass energy comes from organic materials like wood and crop waste." },
    { word: "energy efficiency", translation: "efficacité énergétique", example: "Energy efficiency reduces the amount of energy required for products and services." },
    { word: "smart grid", translation: "réseau intelligent", example: "Smart grids use digital technology to monitor and manage electricity delivery." },
    { word: "energy storage", translation: "stockage d'énergie", example: "Energy storage systems capture electricity for use at a later time." },
    { word: "decarbonization", translation: "décarbonisation", example: "Decarbonization involves reducing carbon emissions from energy production." },
    { word: "feed-in tariff", translation: "tarif de rachat", example: "Feed-in tariffs guarantee payments to renewable energy producers." },
    { word: "grid parity", translation: "parité réseau", example: "Grid parity occurs when renewable energy costs equal or less than conventional sources." },
    { word: "energy security", translation: "sécurité énergétique", example: "Energy security ensures reliable access to energy supplies." },
    { word: "distributed generation", translation: "production décentralisée", example: "Distributed generation produces electricity near the point of use." },
    { word: "energy democracy", translation: "démocratie énergétique", example: "Energy democracy empowers communities to control their energy systems." },
    { word: "just transition", translation: "transition juste", example: "A just transition ensures workers in fossil fuel industries aren't left behind." },
    { word: "power purchase agreement", translation: "contrat d'achat d'électricité", example: "Power purchase agreements secure long-term contracts for renewable energy." },
    { word: "carbon capture", translation: "captage du carbone", example: "Carbon capture technology removes CO₂ from industrial emissions or the atmosphere." },
    { word: "electrification", translation: "électrification", example: "Electrification replaces technologies that use fossil fuels with ones that use electricity." },
    
    // Conservation marine
    { word: "marine conservation", translation: "conservation marine", example: "Marine conservation protects ocean ecosystems and biodiversity." },
    { word: "marine protected area", translation: "aire marine protégée", example: "Marine protected areas restrict human activity for conservation purposes." },
    { word: "ocean acidification", translation: "acidification des océans", example: "Ocean acidification occurs when seawater absorbs carbon dioxide from the atmosphere." },
    { word: "coral bleaching", translation: "blanchissement des coraux", example: "Coral bleaching happens when corals expel their symbiotic algae due to stress." },
    { word: "marine biodiversity", translation: "biodiversité marine", example: "Marine biodiversity encompasses all life forms in ocean ecosystems." },
    { word: "sustainable fisheries", translation: "pêcheries durables", example: "Sustainable fisheries manage fish populations to prevent overharvesting." },
    { word: "bycatch", translation: "prises accessoires", example: "Bycatch refers to non-target species caught during fishing operations." },
    { word: "overfishing", translation: "surpêche", example: "Overfishing depletes fish populations faster than they can reproduce." },
    { word: "marine ecosystem", translation: "écosystème marin", example: "Marine ecosystems include a complex network of organisms and their environment." },
    { word: "blue carbon", translation: "carbone bleu", example: "Blue carbon is captured and stored by coastal and marine ecosystems." },
    { word: "coastal resilience", translation: "résilience côtière", example: "Coastal resilience helps shorelines withstand and recover from extreme events." },
    { word: "ecosystem-based management", translation: "gestion écosystémique", example: "Ecosystem-based management considers entire ecosystems rather than single species." },
    { word: "marine pollution", translation: "pollution marine", example: "Marine pollution includes chemicals, plastics, and excess nutrients in oceans." },
    { word: "fisheries management", translation: "gestion des pêcheries", example: "Fisheries management regulates fishing activities to maintain healthy populations." },
    { word: "sea level rise", translation: "élévation du niveau de la mer", example: "Sea level rise threatens coastal communities and ecosystems worldwide." },
    { word: "aquaculture", translation: "aquaculture", example: "Aquaculture involves farming fish, shellfish, and aquatic plants." },
    { word: "marine spatial planning", translation: "planification spatiale marine", example: "Marine spatial planning coordinates ocean uses to reduce conflicts and protect ecosystems." },
    { word: "marine habitat", translation: "habitat marin", example: "Marine habitats include coral reefs, seagrass beds, and deep-sea environments." },
    { word: "ocean governance", translation: "gouvernance des océans", example: "Ocean governance establishes rules for managing marine resources." },
    
    // Agriculture durable
    { word: "sustainable agriculture", translation: "agriculture durable", example: "Sustainable agriculture maintains productivity while protecting the environment." },
    { word: "organic farming", translation: "agriculture biologique", example: "Organic farming avoids synthetic pesticides and fertilizers." },
    { word: "agroecology", translation: "agroécologie", example: "Agroecology applies ecological principles to agricultural systems." },
    { word: "regenerative agriculture", translation: "agriculture régénératrice", example: "Regenerative agriculture focuses on rebuilding soil health and biodiversity." },
    { word: "precision agriculture", translation: "agriculture de précision", example: "Precision agriculture uses technology to optimize farming inputs and outputs." },
    { word: "crop rotation", translation: "rotation des cultures", example: "Crop rotation involves changing the type of crop grown in a field each season." },
    { word: "integrated pest management", translation: "lutte intégrée", example: "Integrated pest management combines techniques to control pests effectively and sustainably." },
    { word: "cover crops", translation: "cultures de couverture", example: "Cover crops protect soil between growing seasons and add organic matter." },
    { word: "no-till farming", translation: "agriculture sans labour", example: "No-till farming minimizes soil disturbance to prevent erosion." },
    { word: "soil carbon sequestration", translation: "séquestration du carbone dans le sol", example: "Soil carbon sequestration captures and stores atmospheric carbon dioxide in soils." },
    { word: "food security", translation: "sécurité alimentaire", example: "Food security ensures all people have access to sufficient, nutritious food." },
    { word: "agroforestry", translation: "agroforesterie", example: "Agroforestry integrates trees with crop or livestock systems." },
    { word: "permaculture", translation: "permaculture", example: "Permaculture designs agricultural systems that mimic natural ecosystems." },
    { word: "biodiversity conservation", translation: "conservation de la biodiversité", example: "Biodiversity conservation in agriculture maintains beneficial species and ecosystem services." },
    { word: "water-efficient farming", translation: "agriculture économe en eau", example: "Water-efficient farming reduces water consumption through improved techniques." },
    { word: "sustainable intensification", translation: "intensification durable", example: "Sustainable intensification aims to increase yields without environmental harm." },
    { word: "agrobiodiversity", translation: "agrobiodiversité", example: "Agrobiodiversity includes the variety of plants, animals, and microorganisms used in agriculture." },
    { word: "climate-smart agriculture", translation: "agriculture intelligente face au climat", example: "Climate-smart agriculture adapts to climate change while reducing emissions." },
    { word: "food sovereignty", translation: "souveraineté alimentaire", example: "Food sovereignty empowers communities to control their food systems." },
    { word: "sustainable food system", translation: "système alimentaire durable", example: "A sustainable food system provides healthy food with minimal environmental impact." },
    
    // Mouvements environnementaux
    { word: "environmental movement", translation: "mouvement environnemental", example: "The environmental movement advocates for the protection of natural resources." },
    { word: "climate activism", translation: "activisme climatique", example: "Climate activism urges governments and corporations to address climate change." },
    { word: "environmental justice", translation: "justice environnementale", example: "Environmental justice addresses the unequal distribution of environmental benefits and burdens." },
    { word: "grassroots movement", translation: "mouvement populaire", example: "Grassroots movements organize citizens at the local level for environmental change." },
    { word: "direct action", translation: "action directe", example: "Direct action includes protests and civil disobedience for environmental causes." },
    { word: "community organizing", translation: "organisation communautaire", example: "Community organizing mobilizes local residents to address environmental issues." },
    { word: "ecological awareness", translation: "conscience écologique", example: "Ecological awareness recognizes human impacts on natural systems." },
    { word: "environmental advocacy", translation: "plaidoyer environnemental", example: "Environmental advocacy promotes policies that protect natural resources." },
    { word: "conservation movement", translation: "mouvement de conservation", example: "The conservation movement works to protect biodiversity and natural habitats." },
    { word: "environmental coalition", translation: "coalition environnementale", example: "Environmental coalitions bring together organizations with common goals." },
    { word: "environmental campaign", translation: "campagne environnementale", example: "The environmental campaign raised awareness about plastic pollution." },
    { word: "nature rights", translation: "droits de la nature", example: "Nature rights recognize legal rights of ecosystems to exist and flourish." },
    { word: "civil society", translation: "société civile", example: "Civil society organizations play a crucial role in environmental governance." },
    { word: "ecological citizenship", translation: "citoyenneté écologique", example: "Ecological citizenship emphasizes environmental responsibilities in civic participation." },
    { word: "environmental protest", translation: "manifestation environnementale", example: "Environmental protests demonstrate public concern about ecological issues." },
    { word: "climate strike", translation: "grève pour le climat", example: "Climate strikes mobilize students and workers to demand climate action." },
    { word: "indigenous environmentalism", translation: "environnementalisme autochtone", example: "Indigenous environmentalism integrates traditional knowledge with conservation practices." },
    { word: "intergenerational activism", translation: "activisme intergénérationnel", example: "Intergenerational activism unites people of all ages for environmental protection." },
    
    // Économie circulaire
    { word: "circular economy", translation: "économie circulaire", example: "A circular economy aims to eliminate waste through continual use of resources." },
    { word: "resource efficiency", translation: "efficacité des ressources", example: "Resource efficiency maximizes the utility of materials and energy." },
    { word: "closed-loop system", translation: "système en boucle fermée", example: "Closed-loop systems recycle materials continuously without external inputs." },
    { word: "product lifecycle", translation: "cycle de vie du produit", example: "Understanding the product lifecycle helps identify opportunities for circularity." },
    { word: "industrial symbiosis", translation: "symbiose industrielle", example: "Industrial symbiosis involves facilities exchanging materials, energy, and resources." },
    { word: "upcycling", translation: "surcyclage", example: "Upcycling transforms waste materials into products of higher value." },
    { word: "remanufacturing", translation: "refabrication", example: "Remanufacturing restores used products to their original condition or better." },
    { word: "product-as-a-service", translation: "produit en tant que service", example: "Product-as-a-service models provide access to products without ownership." },
    { word: "extended producer responsibility", translation: "responsabilité élargie du producteur", example: "Extended producer responsibility makes manufacturers responsible for post-consumer waste." },
    { word: "design for disassembly", translation: "conception pour le démontage", example: "Design for disassembly enables easier maintenance, repair, and recycling." },
    { word: "cradle-to-cradle", translation: "du berceau au berceau", example: "Cradle-to-cradle design creates products with continuous material recovery in mind." },
    { word: "material passport", translation: "passeport matériel", example: "Material passports document the composition of products to facilitate future recycling." },
    { word: "reverse logistics", translation: "logistique inverse", example: "Reverse logistics manages the return of products for reuse, repair, or recycling." },
    { word: "zero waste", translation: "zéro déchet", example: "Zero waste systems eliminate the production of waste through thoughtful design." },
    { word: "collaborative consumption", translation: "consommation collaborative", example: "Collaborative consumption involves sharing, trading, or renting products." },
    { word: "repair economy", translation: "économie de la réparation", example: "A repair economy prioritizes fixing products rather than replacing them." },
    { word: "resource recovery", translation: "récupération des ressources", example: "Resource recovery extracts valuable materials from waste streams." },
    { word: "sustainable procurement", translation: "approvisionnement durable", example: "Sustainable procurement considers environmental impacts in purchasing decisions." },
    
    // Gestion des ressources
    { word: "resource management", translation: "gestion des ressources", example: "Resource management ensures sustainable use of natural resources." },
    { word: "natural resource", translation: "ressource naturelle", example: "Natural resources include water, forests, minerals, and land." },
    { word: "water management", translation: "gestion de l'eau", example: "Water management addresses the collection, distribution, and conservation of water resources." },
    { word: "forest management", translation: "gestion forestière", example: "Sustainable forest management balances ecological and economic objectives." },
    { word: "land use planning", translation: "planification de l'utilisation des terres", example: "Land use planning coordinates development while protecting natural areas." },
    { word: "ecosystem services", translation: "services écosystémiques", example: "Ecosystem services are benefits that nature provides to people." },
    { word: "resource scarcity", translation: "rareté des ressources", example: "Resource scarcity occurs when demand exceeds available supply." },
    { word: "integrated resource management", translation: "gestion intégrée des ressources", example: "Integrated resource management coordinates different sectors that affect natural resources." },
    { word: "natural capital", translation: "capital naturel", example: "Natural capital represents the world's stock of natural resources." },
    { word: "environmental accounting", translation: "comptabilité environnementale", example: "Environmental accounting incorporates natural resource values into economic decisions." },
    { word: "sustainable yield", translation: "rendement durable", example: "Sustainable yield harvests resources at a rate that allows regeneration." },
    { word: "carrying capacity", translation: "capacité de charge", example: "Carrying capacity is the maximum population an environment can support indefinitely." },
    { word: "ecological footprint", translation: "empreinte écologique", example: "An ecological footprint measures human demand on natural resources." },
    { word: "resource depletion", translation: "épuisement des ressources", example: "Resource depletion occurs when consumption exceeds regeneration rates." },
    { word: "watershed management", translation: "gestion des bassins versants", example: "Watershed management coordinates water-related activities within a drainage basin." },
    { word: "common-pool resource", translation: "ressource commune", example: "Common-pool resources like fisheries require collaborative management approaches." },
    { word: "sustainable consumption", translation: "consommation durable", example: "Sustainable consumption uses products and services with minimal environmental impact." }
  ]
};