export const vocab = {
  title: "Éducation Supérieure & Recherche",
  words: [
    // Disciplines académiques
    { word: "academic discipline", translation: "discipline académique", example: "Anthropology is an academic discipline that studies human cultures and societies." },
    { word: "liberal arts", translation: "arts libéraux", example: "A liberal arts education covers a broad range of humanities, social sciences, and natural sciences." },
    { word: "humanities", translation: "sciences humaines", example: "Philosophy, literature, and history are core subjects in the humanities." },
    { word: "social sciences", translation: "sciences sociales", example: "Psychology, sociology, and economics are major social sciences." },
    { word: "natural sciences", translation: "sciences naturelles", example: "Physics, chemistry, and biology comprise the natural sciences." },
    { word: "applied sciences", translation: "sciences appliquées", example: "Engineering and medicine are applied sciences that use scientific knowledge for practical purposes." },
    { word: "interdisciplinary studies", translation: "études interdisciplinaires", example: "Environmental science is an interdisciplinary study combining aspects of biology, chemistry, and social sciences." },
    { word: "STEM", translation: "STIM", example: "Many universities emphasize STEM education (Science, Technology, Engineering, and Mathematics)." },
    { word: "cross-disciplinary", translation: "transdisciplinaire", example: "The research project took a cross-disciplinary approach, drawing from sociology and economics." },
    { word: "field of study", translation: "domaine d'étude", example: "Quantum computing is an emerging field of study that combines physics and computer science." },
    { word: "specialization", translation: "spécialisation", example: "After completing core courses, students choose a specialization based on their interests." },
    { word: "major", translation: "spécialité principale", example: "She pursued a major in psychology with a minor in statistics." },
    { word: "minor", translation: "spécialité secondaire", example: "Many students add a minor to complement their major or explore additional interests." },
    { word: "elective course", translation: "cours optionnel", example: "Elective courses allow students to customize their education beyond required subjects." },
    { word: "prerequisite", translation: "prérequis", example: "Organic chemistry is a prerequisite for most medical school programs." },
    
    // Méthodologie de recherche
    { word: "research methodology", translation: "méthodologie de recherche", example: "The thesis proposal outlined the research methodology that would be employed." },
    { word: "qualitative research", translation: "recherche qualitative", example: "Qualitative research explores subjective experiences through interviews and observations." },
    { word: "quantitative research", translation: "recherche quantitative", example: "Quantitative research relies on numerical data and statistical analysis." },
    { word: "mixed methods", translation: "méthodes mixtes", example: "The study used mixed methods, combining surveys with in-depth interviews." },
    { word: "data collection", translation: "collecte de données", example: "Data collection included surveys, interviews, and field observations." },
    { word: "data analysis", translation: "analyse de données", example: "Statistical software was used for data analysis of the experimental results." },
    { word: "literature review", translation: "revue de littérature", example: "A thorough literature review revealed gaps in current knowledge on the topic." },
    { word: "hypothesis", translation: "hypothèse", example: "The researcher formulated a hypothesis to be tested through experimentation." },
    { word: "experimental design", translation: "conception expérimentale", example: "The experimental design included control and variable groups to isolate effects." },
    { word: "control group", translation: "groupe témoin", example: "The control group received a placebo to compare against the treatment group." },
    { word: "variable", translation: "variable", example: "The study measured several variables, including age, income, and education level." },
    { word: "reliability", translation: "fiabilité", example: "Test-retest procedures ensured the reliability of the measurement instruments." },
    { word: "validity", translation: "validité", example: "The study's validity depends on how well it measures what it claims to measure." },
    { word: "sampling", translation: "échantillonnage", example: "Random sampling helps ensure that research findings can be generalized to the broader population." },
    { word: "longitudinal study", translation: "étude longitudinale", example: "The longitudinal study followed participants over twenty years to observe long-term effects." },
    { word: "cross-sectional study", translation: "étude transversale", example: "The cross-sectional study compared different age groups at a single point in time." },
    { word: "case study", translation: "étude de cas", example: "The in-depth case study examined a single organization's transformation process." },
    { word: "ethnography", translation: "ethnographie", example: "Ethnography involves immersion in a community to understand its culture from the inside." },
    { word: "grounded theory", translation: "théorie ancrée", example: "Grounded theory develops theoretical frameworks from collected data rather than testing existing theories." },
    { word: "action research", translation: "recherche-action", example: "Action research aims to solve practical problems while advancing theoretical knowledge." },
    
    // Systèmes universitaires
    { word: "higher education", translation: "enseignement supérieur", example: "Higher education encompasses universities, colleges, and professional schools." },
    { word: "university", translation: "université", example: "The university offers undergraduate and graduate programs across multiple disciplines." },
    { word: "college", translation: "faculté", example: "She teaches at the college of engineering within the university." },
    { word: "community college", translation: "collège communautaire", example: "Community colleges provide affordable educational opportunities and vocational training." },
    { word: "undergraduate", translation: "premier cycle", example: "Undergraduate students typically pursue a bachelor's degree." },
    { word: "graduate", translation: "diplômé", example: "After completing her undergraduate degree, she became a graduate student in physics." },
    { word: "postgraduate", translation: "troisième cycle", example: "Postgraduate education includes master's and doctoral programs." },
    { word: "bachelor's degree", translation: "licence", example: "A bachelor's degree typically requires four years of full-time study." },
    { word: "master's degree", translation: "master", example: "She earned her master's degree after completing a research thesis." },
    { word: "doctorate", translation: "doctorat", example: "A doctorate is the highest academic degree in most fields." },
    { word: "Ph.D.", translation: "doctorat", example: "His Ph.D. in economics required original research and a dissertation defense." },
    { word: "tenure", translation: "titularisation", example: "Professors work toward tenure to secure academic freedom and job security." },
    { word: "academic freedom", translation: "liberté académique", example: "Academic freedom protects scholars' rights to research controversial topics." },
    { word: "faculty", translation: "corps enseignant", example: "The university's faculty includes world-renowned experts in their fields." },
    { word: "dean", translation: "doyen", example: "The dean oversees all academic departments within the college." },
    { word: "department chair", translation: "directeur de département", example: "The department chair manages faculty and curriculum for their academic unit." },
    { word: "accreditation", translation: "accréditation", example: "Accreditation ensures that institutions meet established standards of quality." },
    { word: "academic calendar", translation: "calendrier universitaire", example: "The academic calendar divides the year into semesters or quarters." },
    { word: "tuition", translation: "frais de scolarité", example: "Tuition costs have risen significantly at many universities in recent years." },
    
    // Publications & diffusion
    { word: "academic publication", translation: "publication académique", example: "Academic publications undergo peer review before being accepted by journals." },
    { word: "peer review", translation: "évaluation par les pairs", example: "Peer review ensures research meets disciplinary standards before publication." },
    { word: "journal article", translation: "article de revue", example: "Her journal article presented findings from her latest experiment." },
    { word: "scholarly journal", translation: "revue académique", example: "The scholarly journal publishes original research in quantum physics." },
    { word: "impact factor", translation: "facteur d'impact", example: "A journal's impact factor measures the average number of citations its articles receive." },
    { word: "citation", translation: "citation", example: "Academic writing requires proper citations to acknowledge sources." },
    { word: "bibliography", translation: "bibliographie", example: "The bibliography listed all sources consulted during the research." },
    { word: "literature", translation: "littérature", example: "The existing literature on climate change is extensive and growing." },
    { word: "monograph", translation: "monographie", example: "The professor published a monograph on medieval trade routes." },
    { word: "edited volume", translation: "ouvrage collectif", example: "The edited volume contained chapters from leading experts in the field." },
    { word: "proceedings", translation: "actes", example: "Conference proceedings compile papers presented at academic meetings." },
    { word: "preprint", translation: "prépublication", example: "Researchers share preprints to receive feedback before formal publication." },
    { word: "open access", translation: "libre accès", example: "Open access publications are available to readers without subscription fees." },
    { word: "dissemination", translation: "diffusion", example: "Knowledge dissemination is a core mission of research institutions." },
    { word: "academic conference", translation: "conférence académique", example: "Researchers present their work at academic conferences to share findings and receive feedback." },
    { word: "symposium", translation: "symposium", example: "The symposium brought together experts to discuss emerging research in neuroscience." },
    
    // Financement de la recherche
    { word: "research funding", translation: "financement de la recherche", example: "Research funding comes from government agencies, foundations, and private industry." },
    { word: "grant", translation: "subvention", example: "The scientist secured a grant to support her innovative research project." },
    { word: "grant proposal", translation: "demande de subvention", example: "Writing a successful grant proposal requires clear objectives and methodology." },
    { word: "research budget", translation: "budget de recherche", example: "The research budget allocated funds for equipment, personnel, and materials." },
    { word: "funding agency", translation: "organisme de financement", example: "The National Science Foundation is a major funding agency for basic research." },
    { word: "endowment", translation: "dotation", example: "The university's endowment provides ongoing support for research initiatives." },
    { word: "fellowship", translation: "bourse de recherche", example: "The fellowship provided financial support during her doctoral studies." },
    { word: "scholarship", translation: "bourse d'études", example: "Merit-based scholarships recognize academic achievement and potential." },
    { word: "sponsorship", translation: "parrainage", example: "Corporate sponsorship funded the laboratory's new equipment." },
    { word: "public funding", translation: "financement public", example: "Public funding for scientific research varies significantly between countries." },
    { word: "private funding", translation: "financement privé", example: "Private funding from foundations supports research that might not receive government grants." },
    { word: "crowdfunding", translation: "financement participatif", example: "Some researchers use crowdfunding to support projects with public appeal." },
    { word: "cost-sharing", translation: "partage des coûts", example: "The research partnership involved cost-sharing between the university and industry." },
    
    // Éthique scientifique
    { word: "research ethics", translation: "éthique de la recherche", example: "Research ethics guides responsible conduct in scientific investigation." },
    { word: "informed consent", translation: "consentement éclairé", example: "Researchers must obtain informed consent from human participants before studies begin." },
    { word: "ethics committee", translation: "comité d'éthique", example: "The ethics committee reviews research proposals involving human subjects." },
    { word: "institutional review board", translation: "comité d'éthique institutionnel", example: "The institutional review board ensures studies protect participants' rights and welfare." },
    { word: "scientific integrity", translation: "intégrité scientifique", example: "Scientific integrity requires honesty in data collection, analysis, and reporting." },
    { word: "research misconduct", translation: "inconduite en recherche", example: "Research misconduct includes fabrication, falsification, and plagiarism." },
    { word: "plagiarism", translation: "plagiat", example: "Plagiarism involves presenting others' ideas or words as one's own." },
    { word: "conflict of interest", translation: "conflit d'intérêts", example: "Researchers must disclose any conflict of interest that might affect their objectivity." },
    { word: "data fabrication", translation: "fabrication de données", example: "Data fabrication—creating false data—is a serious breach of scientific ethics." },
    { word: "responsible conduct", translation: "conduite responsable", example: "Training in responsible conduct is required for researchers receiving federal funding." },
    { word: "transparency", translation: "transparence", example: "Transparency in methods and results is essential for scientific credibility." },
    { word: "data management", translation: "gestion des données", example: "Proper data management ensures research data remains secure and accessible." },
    
    // Pédagogie avancée
    { word: "pedagogy", translation: "pédagogie", example: "Effective pedagogy engages students in active learning processes." },
    { word: "andragogy", translation: "andragogie", example: "Andragogy focuses on teaching methods appropriate for adult learners." },
    { word: "curriculum development", translation: "élaboration de programme", example: "Curriculum development involves designing learning objectives, content, and assessments." },
    { word: "learning outcome", translation: "résultat d'apprentissage", example: "Clear learning outcomes specify what students should know or be able to do." },
    { word: "assessment", translation: "évaluation", example: "Both formative and summative assessment methods measure student learning." },
    { word: "rubric", translation: "grille d'évaluation", example: "A well-designed rubric clarifies expectations and criteria for assignments." },
    { word: "active learning", translation: "apprentissage actif", example: "Active learning techniques engage students directly in the learning process." },
    { word: "problem-based learning", translation: "apprentissage par problèmes", example: "Problem-based learning challenges students to solve real-world issues." },
    { word: "student-centered learning", translation: "apprentissage centré sur l'étudiant", example: "Student-centered learning approaches focus on learners' needs and interests." },
    { word: "flipped classroom", translation: "classe inversée", example: "In a flipped classroom, students review content at home and apply concepts in class." },
    { word: "blended learning", translation: "apprentissage hybride", example: "Blended learning combines online and face-to-face instructional approaches." },
    { word: "instructional design", translation: "conception pédagogique", example: "Instructional design creates effective learning experiences based on educational theories." },
    { word: "learning analytics", translation: "analytique d'apprentissage", example: "Learning analytics uses data to understand and optimize student learning." }
  ]
};