export const vocab = {
  title: "Systèmes Juridiques Comparés",
  words: [
    // Traditions juridiques
    { word: "legal tradition", translation: "tradition juridique", example: "Civil law and common law represent distinct legal traditions with different historical origins." },
    { word: "common law system", translation: "système de common law", example: "The common law system evolved in England and relies heavily on judicial precedent." },
    { word: "civil law system", translation: "système de droit civil", example: "The civil law system, predominant in continental Europe, prioritizes codified statutes." },
    { word: "legal transplant", translation: "transplant juridique", example: "The legal transplant adapted foreign legal concepts to fit within the domestic system." },
    { word: "mixed jurisdiction", translation: "juridiction mixte", example: "Louisiana represents a mixed jurisdiction combining elements of civil and common law." },
    { word: "customary law", translation: "droit coutumier", example: "Customary law continues to govern family relations in many rural communities." },
    { word: "religious legal system", translation: "système juridique religieux", example: "Islamic law is a religious legal system that guides governance in several countries." },
    { word: "legal pluralism", translation: "pluralisme juridique", example: "Legal pluralism acknowledges multiple coexisting normative orders within a society." },
    { word: "legal culture", translation: "culture juridique", example: "Legal culture influences how formal rules are interpreted and applied in practice." },
    { word: "socialist legal tradition", translation: "tradition juridique socialiste", example: "The socialist legal tradition emphasized collective interests over individual rights." },
    { word: "legal formalism", translation: "formalisme juridique", example: "Legal formalism stresses strict adherence to established rules and categories." },
    { word: "legal realism", translation: "réalisme juridique", example: "Legal realism emphasizes how judicial decisions reflect social and psychological factors." },
    { word: "legal positivism", translation: "positivisme juridique", example: "Legal positivism separates law from morality, focusing on rules established by authorities." },
    { word: "natural law theory", translation: "théorie du droit naturel", example: "Natural law theory argues that legal validity depends partly on moral considerations." },
    { word: "indigenous legal system", translation: "système juridique autochtone", example: "Indigenous legal systems offer alternative approaches to dispute resolution." },
    { word: "legal syncretism", translation: "syncrétisme juridique", example: "Legal syncretism occurs when different legal traditions blend and influence each other." },
    { word: "customary practice", translation: "pratique coutumière", example: "Local customary practices often coexist with formal state law." },
    { word: "legal evolution", translation: "évolution juridique", example: "Legal evolution reflects changing social norms and technological developments." },
    { word: "legal family", translation: "famille juridique", example: "Scandinavian legal systems constitute a distinct legal family within civil law." },
    { word: "legal heritage", translation: "héritage juridique", example: "Many former colonies retained elements of their colonial legal heritage after independence." },
    { word: "hybrid legal system", translation: "système juridique hybride", example: "South Africa's hybrid legal system combines Roman-Dutch civil law with English common law." },
    { word: "legal convergence", translation: "convergence juridique", example: "Globalization has accelerated legal convergence in commercial regulations." },
    { word: "legal harmonization", translation: "harmonisation juridique", example: "The European Union promotes legal harmonization across member states." },
    { word: "juridical approach", translation: "approche juridique", example: "Different traditions employ distinct juridical approaches to similar problems." },
    { word: "tribal law", translation: "droit tribal", example: "Tribal law continues to govern social relations in many indigenous communities." },
    { word: "codification tradition", translation: "tradition de codification", example: "The Napoleonic Code established a codification tradition that spread throughout Europe." },
    { word: "transsystemic law", translation: "droit transsystémique", example: "Transsystemic law programs teach multiple legal traditions simultaneously." },
    { word: "legal archetype", translation: "archétype juridique", example: "The contract represents a legal archetype found across diverse traditions." },
    { word: "comparative perspective", translation: "perspective comparative", example: "A comparative perspective reveals structural similarities beneath apparent differences." },
    
    // Jurisprudence analytique
    { word: "analytical jurisprudence", translation: "jurisprudence analytique", example: "Analytical jurisprudence examines the nature and structure of legal concepts." },
    { word: "legal reasoning", translation: "raisonnement juridique", example: "Legal reasoning involves applying abstract principles to concrete factual situations." },
    { word: "legal concept", translation: "concept juridique", example: "Ownership is a complex legal concept with multiple dimensions and attributes." },
    { word: "jurisprudential theory", translation: "théorie jurisprudentielle", example: "Hart's jurisprudential theory distinguished between primary and secondary rules." },
    { word: "legal interpretation", translation: "interprétation juridique", example: "Legal interpretation methods vary between textualism and purposive approaches." },
    { word: "judicial discretion", translation: "discrétion judiciaire", example: "Hard cases involve significant judicial discretion in applying abstract principles." },
    { word: "legal authority", translation: "autorité juridique", example: "Legal authority stems from constitutional recognition and social acceptance." },
    { word: "legal validity", translation: "validité juridique", example: "Legal validity depends on whether a norm was properly enacted according to higher rules." },
    { word: "legal right", translation: "droit subjectif", example: "A legal right typically implies corresponding duties from others." },
    { word: "legal obligation", translation: "obligation juridique", example: "Legal obligation differs from moral obligation in its source and enforcement." },
    { word: "legal doctrine", translation: "doctrine juridique", example: "Legal doctrine systematizes rules and principles within a specific domain." },
    { word: "legal principle", translation: "principe juridique", example: "Legal principles provide normative guidance when specific rules are unclear." },
    { word: "rule of recognition", translation: "règle de reconnaissance", example: "The rule of recognition identifies which norms qualify as valid law in a system." },
    { word: "conceptual analysis", translation: "analyse conceptuelle", example: "Conceptual analysis clarifies the meaning and structure of legal concepts." },
    { word: "normative theory", translation: "théorie normative", example: "Normative theory addresses how judges should decide cases in principle." },
    { word: "stare decisis", translation: "stare decisis", example: "Stare decisis requires courts to follow precedent in similar future cases." },
    { word: "ratio decidendi", translation: "ratio decidendi", example: "The ratio decidendi constitutes the binding element of a judicial decision." },
    { word: "judicial review", translation: "contrôle juridictionnel", example: "Judicial review allows courts to invalidate legislation contradicting constitutional principles." },
    { word: "judicial methodology", translation: "méthodologie judiciaire", example: "Judicial methodology differs significantly between civil and common law systems." },
    { word: "judicial constraint", translation: "contrainte judiciaire", example: "Legal formalism promotes judicial constraint through strict adherence to rules." },
    { word: "interpretive theory", translation: "théorie interprétative", example: "Dworkin's interpretive theory views law as constructive interpretation of legal practice." },
    { word: "legal norm", translation: "norme juridique", example: "Legal norms include both specific rules and broader principles." },
    { word: "jurisprudential approach", translation: "approche jurisprudentielle", example: "Different jurisprudential approaches offer competing accounts of legal reasoning." },
    { word: "legal fiction", translation: "fiction juridique", example: "Legal fictions treat something as true for specific legal purposes despite factual inaccuracy." },
    { word: "legal formality", translation: "formalité juridique", example: "Legal formality serves important functions despite appearing unnecessarily rigid." },
    { word: "interpretive community", translation: "communauté interprétative", example: "Judges belong to an interpretive community sharing certain methodological assumptions." },
    { word: "statutory construction", translation: "interprétation des lois", example: "Statutory construction involves multiple techniques for determining legislative intent." },
    { word: "justiciability", translation: "justiciabilité", example: "Justiciability doctrines determine which disputes courts will consider decidable." },
    { word: "legal methodology", translation: "méthodologie juridique", example: "Legal methodology encompasses approaches to identifying, interpreting, and applying law." },
    
    // Droit constitutionnel
    { word: "constitutional framework", translation: "cadre constitutionnel", example: "The constitutional framework establishes fundamental governmental structures and constraints." },
    { word: "separation of powers", translation: "séparation des pouvoirs", example: "Separation of powers distributes authority among independent governmental branches." },
    { word: "judicial independence", translation: "indépendance judiciaire", example: "Judicial independence safeguards courts from political interference." },
    { word: "constitutional review", translation: "contrôle de constitutionnalité", example: "Constitutional review mechanisms vary from specialized courts to diffuse systems." },
    { word: "fundamental rights", translation: "droits fondamentaux", example: "Constitutions typically enumerate fundamental rights protected from governmental infringement." },
    { word: "constitutional amendment", translation: "amendement constitutionnel", example: "Constitutional amendment procedures balance stability with adaptability." },
    { word: "constitutional interpretation", translation: "interprétation constitutionnelle", example: "Constitutional interpretation approaches include originalism and living constitutionalism." },
    { word: "constitutional court", translation: "cour constitutionnelle", example: "The constitutional court has final authority on constitutional questions." },
    { word: "federal system", translation: "système fédéral", example: "A federal system divides sovereignty between central and regional governments." },
    { word: "unitary state", translation: "État unitaire", example: "A unitary state centralizes authority in the national government." },
    { word: "parliamentary sovereignty", translation: "souveraineté parlementaire", example: "Parliamentary sovereignty empowers the legislature to enact any law without judicial invalidation." },
    { word: "constitutional tradition", translation: "tradition constitutionnelle", example: "Britain's constitutional tradition relies on unwritten conventions and precedents." },
    { word: "constitutional democracy", translation: "démocratie constitutionnelle", example: "Constitutional democracy constrains majority rule through protected rights." },
    { word: "constitutional identity", translation: "identité constitutionnelle", example: "Constitutional identity reflects core principles resistant to fundamental alteration." },
    { word: "constitutional adjudication", translation: "contentieux constitutionnel", example: "Constitutional adjudication resolves disputes about governmental powers and limits." },
    { word: "constitutional convention", translation: "convention constitutionnelle", example: "Constitutional conventions are unwritten rules that regulate governmental conduct." },
    { word: "constitutional principle", translation: "principe constitutionnel", example: "The rule of law represents a fundamental constitutional principle." },
    { word: "abstract review", translation: "contrôle abstrait", example: "Abstract review examines legislation's constitutionality independent of concrete disputes." },
    { word: "concrete review", translation: "contrôle concret", example: "Concrete review addresses constitutional questions arising in specific cases." },
    { word: "constitutional complaint", translation: "recours constitutionnel", example: "The constitutional complaint mechanism allows individuals to directly petition the court." },
    { word: "constitutional jurisprudence", translation: "jurisprudence constitutionnelle", example: "Constitutional jurisprudence develops incrementally through successive decisions." },
    { word: "proportionality principle", translation: "principe de proportionnalité", example: "The proportionality principle requires restrictions on rights to be necessary and balanced." },
    { word: "constitutional dialogue", translation: "dialogue constitutionnel", example: "Constitutional dialogue involves ongoing interaction between courts and legislatures." },
    { word: "constitutional evolution", translation: "évolution constitutionnelle", example: "Constitutional evolution occurs through formal amendments and interpretive changes." },
    { word: "constitutional supremacy", translation: "suprématie constitutionnelle", example: "Constitutional supremacy makes the constitution the highest law in the hierarchy." },
    { word: "constitutional constraint", translation: "contrainte constitutionnelle", example: "Constitutional constraints limit governmental authority to protect individual liberty." },
    { word: "constitutional development", translation: "développement constitutionnel", example: "Constitutional development reflects changing societal values and political realities." },
    { word: "constitutional safeguard", translation: "garantie constitutionnelle", example: "Judicial review serves as a constitutional safeguard against legislative overreach." },
    { word: "constitutional structure", translation: "structure constitutionnelle", example: "The constitutional structure defines institutional relationships and authority." },
    
    // Justice transitionnelle
    { word: "transitional justice", translation: "justice transitionnelle", example: "Transitional justice addresses human rights violations during democratic transitions." },
    { word: "truth commission", translation: "commission de vérité", example: "The truth commission documented abuses without necessarily pursuing prosecutions." },
    { word: "historical reckoning", translation: "règlement de comptes historique", example: "The trials initiated a historical reckoning with the authoritarian past." },
    { word: "reconciliation process", translation: "processus de réconciliation", example: "The reconciliation process aimed to heal societal divisions after conflict." },
    { word: "reparation program", translation: "programme de réparation", example: "The reparation program provided compensation to victims of state violence." },
    { word: "institutional reform", translation: "réforme institutionnelle", example: "Transitional justice included institutional reform to prevent recurrence of abuses." },
    { word: "amnesty provision", translation: "disposition d'amnistie", example: "The peace agreement contained controversial amnesty provisions for political crimes." },
    { word: "victim-centered approach", translation: "approche centrée sur les victimes", example: "A victim-centered approach prioritizes the needs and perspectives of those harmed." },
    { word: "transitional period", translation: "période transitionnelle", example: "The transitional period bridged authoritarian rule and democratic governance." },
    { word: "historical memory", translation: "mémoire historique", example: "Monuments and memorials preserved historical memory of human rights violations." },
    { word: "post-conflict justice", translation: "justice post-conflit", example: "Post-conflict justice mechanisms addressed war crimes after hostilities ended." },
    { word: "accountability measure", translation: "mesure de responsabilisation", example: "Accountability measures included both criminal trials and truth-telling processes." },
    { word: "restorative justice", translation: "justice restaurative", example: "Restorative justice focused on repairing harm rather than merely punishing offenders." },
    { word: "transitional governance", translation: "gouvernance transitionnelle", example: "Transitional governance arrangements guided the shift to democratic institutions." },
    { word: "lustration law", translation: "loi de lustration", example: "Lustration laws restricted former regime officials from holding public office." },
    { word: "memory politics", translation: "politique mémorielle", example: "Memory politics shaped how historical atrocities were commemorated and taught." },
    { word: "symbolic reparation", translation: "réparation symbolique", example: "Official apologies served as symbolic reparation acknowledging state wrongdoing." },
    { word: "non-recurrence guarantee", translation: "garantie de non-répétition", example: "Institutional reforms provided non-recurrence guarantees to prevent future abuses." },
    { word: "collective memory", translation: "mémoire collective", example: "Transitional justice processes influenced the formation of collective memory." },
    { word: "retroactive justice", translation: "justice rétroactive", example: "Critics questioned the legitimacy of retroactive justice for previously legal actions." },
    { word: "societal reconciliation", translation: "réconciliation sociétale", example: "Dialogue forums promoted societal reconciliation between formerly opposed groups." },
    { word: "transitional jurisprudence", translation: "jurisprudence transitionnelle", example: "Transitional jurisprudence addressed unique legal challenges during political transitions." },
    { word: "historical clarification", translation: "clarification historique", example: "The commission's report provided historical clarification about contested events." },
    { word: "peace-versus-justice debate", translation: "débat paix-contre-justice", example: "The peace-versus-justice debate centered on whether prosecutions might destabilize fragile transitions." },
    { word: "judicial reckoning", translation: "règlement judiciaire", example: "The judicial reckoning involved prosecuting those most responsible for atrocities." },
    { word: "transformative justice", translation: "justice transformative", example: "Transformative justice addressed structural inequalities underlying the conflict." },
    { word: "memorial site", translation: "site mémoriel", example: "The former detention center became a memorial site educating visitors about past abuses." },
    { word: "testimonial project", translation: "projet testimonial", example: "The testimonial project recorded survivors' accounts of human rights violations." },
    
    // Arbitrage international
    { word: "international arbitration", translation: "arbitrage international", example: "International arbitration offers a neutral forum for resolving cross-border disputes." },
    { word: "arbitral tribunal", translation: "tribunal arbitral", example: "The arbitral tribunal consisted of three arbitrators with expertise in construction law." },
    { word: "arbitration clause", translation: "clause d'arbitrage", example: "The contract included an arbitration clause specifying UNCITRAL rules for disputes." },
    { word: "institutional arbitration", translation: "arbitrage institutionnel", example: "Institutional arbitration follows procedures established by organizations like the ICC." },
    { word: "ad hoc arbitration", translation: "arbitrage ad hoc", example: "The parties chose ad hoc arbitration without institutional administration." },
    { word: "arbitration award", translation: "sentence arbitrale", example: "The arbitration award ordered compensation for breach of contract." },
    { word: "seat of arbitration", translation: "siège d'arbitrage", example: "Singapore served as the seat of arbitration, determining the applicable procedural law." },
    { word: "New York Convention", translation: "Convention de New York", example: "The New York Convention facilitates enforcement of arbitral awards internationally." },
    { word: "arbitration proceeding", translation: "procédure d'arbitrage", example: "Arbitration proceedings typically include written submissions and oral hearings." },
    { word: "investor-state arbitration", translation: "arbitrage investisseur-État", example: "Investor-state arbitration allows foreign investors to sue host governments." },
    { word: "recognition and enforcement", translation: "reconnaissance et exécution", example: "Recognition and enforcement of awards varies based on national legislation." },
    { word: "commercial arbitration", translation: "arbitrage commercial", example: "International commercial arbitration resolves disputes between private businesses." },
    { word: "arbitrability", translation: "arbitrabilité", example: "Arbitrability refers to whether a dispute can legally be resolved through arbitration." },
    { word: "arbitration rules", translation: "règles d'arbitrage", example: "The arbitration rules governed procedural aspects of the dispute resolution." },
    { word: "challenge of arbitrator", translation: "récusation d'arbitre", example: "The party filed a challenge of arbitrator based on alleged conflicts of interest." },
    { word: "arbitration agreement", translation: "convention d'arbitrage", example: "The validity of the arbitration agreement was contested in preliminary proceedings." },
    { word: "interim measures", translation: "mesures provisoires", example: "The tribunal granted interim measures preserving disputed assets during proceedings." },
    { word: "arbitral jurisdiction", translation: "compétence arbitrale", example: "The tribunal first determined its arbitral jurisdiction to hear the claims." },
    { word: "applicable law", translation: "loi applicable", example: "The contract specified Swiss law as the applicable law for substantive disputes." },
    { word: "model law", translation: "loi type", example: "Many countries have adopted the UNCITRAL Model Law on International Arbitration." },
    { word: "arbitration institute", translation: "institut d'arbitrage", example: "The Stockholm Chamber of Commerce is a prominent arbitration institute." },
    { word: "enforcement proceeding", translation: "procédure d'exécution", example: "Enforcement proceedings were initiated in multiple jurisdictions where assets were located." },
    { word: "procedural order", translation: "ordonnance de procédure", example: "The tribunal issued a procedural order regarding document production." },
    { word: "terms of reference", translation: "acte de mission", example: "The terms of reference outlined the scope of issues for the tribunal to resolve." },
    { word: "annulment proceeding", translation: "procédure d'annulation", example: "The losing party initiated annulment proceedings in courts of the seat country." },
    { word: "arbitration cost", translation: "coût d'arbitrage", example: "Arbitration costs include arbitrators' fees, administrative expenses, and legal representation." },
    { word: "arbitral immunity", translation: "immunité arbitrale", example: "Arbitral immunity protects arbitrators from liability for decisions made in good faith." },
    { word: "public policy exception", translation: "exception d'ordre public", example: "Courts may refuse enforcement based on the public policy exception." },
    
    // Droits spécialisés
    { word: "intellectual property law", translation: "droit de la propriété intellectuelle", example: "Intellectual property law protects creative works and inventions." },
    { word: "environmental law", translation: "droit de l'environnement", example: "Environmental law regulates human impact on the natural environment." },
    { word: "competition law", translation: "droit de la concurrence", example: "Competition law prohibits anti-competitive business practices and mergers." },
    { word: "labor law", translation: "droit du travail", example: "Labor law governs employment relationships and working conditions." },
    { word: "tax law", translation: "droit fiscal", example: "Tax law determines revenue collection obligations for individuals and entities." },
    { word: "administrative law", translation: "droit administratif", example: "Administrative law regulates governmental agency actions and procedures." },
    { word: "corporate law", translation: "droit des sociétés", example: "Corporate law establishes rules for business entity formation and operation." },
    { word: "bankruptcy law", translation: "droit des faillites", example: "Bankruptcy law provides procedures for resolving insolvency situations." },
    { word: "maritime law", translation: "droit maritime", example: "Maritime law addresses legal issues related to shipping and sea transport." },
    { word: "aviation law", translation: "droit aérien", example: "Aviation law governs aircraft operation and air transportation." },
    { word: "media law", translation: "droit des médias", example: "Media law balances free expression with privacy and reputational interests." },
    { word: "telecommunications law", translation: "droit des télécommunications", example: "Telecommunications law regulates communication networks and services." },
    { word: "banking law", translation: "droit bancaire", example: "Banking law establishes regulatory frameworks for financial institutions." },
    { word: "international trade law", translation: "droit du commerce international", example: "International trade law governs cross-border commercial transactions." },
    { word: "health law", translation: "droit de la santé", example: "Health law addresses medical practice, patient rights, and healthcare systems." },
    { word: "sports law", translation: "droit du sport", example: "Sports law encompasses regulations governing athletic competitions and organizations." },
    { word: "cybersecurity law", translation: "droit de la cybersécurité", example: "Cybersecurity law addresses threats to digital systems and information." },
    { word: "energy law", translation: "droit de l'énergie", example: "Energy law regulates production, distribution and use of electricity and fuels." },
    { word: "family law", translation: "droit de la famille", example: "Family law governs marriage, divorce, adoption, and child custody." },
    { word: "education law", translation: "droit de l'éducation", example: "Education law addresses rights and responsibilities in academic settings." },
    { word: "water law", translation: "droit de l'eau", example: "Water law determines access rights and usage of water resources." },
    { word: "construction law", translation: "droit de la construction", example: "Construction law governs building projects and related disputes." },
    { word: "immigration law", translation: "droit de l'immigration", example: "Immigration law regulates entry, residence, and citizenship for foreigners." },
    { word: "agricultural law", translation: "droit agricole", example: "Agricultural law addresses farming operations and food production." },
    { word: "insurance law", translation: "droit des assurances", example: "Insurance law governs contracts transferring risk between parties." },
    { word: "privacy law", translation: "droit à la vie privée", example: "Privacy law protects personal information from unauthorized access or use." },
    { word: "consumer protection law", translation: "droit de la protection des consommateurs", example: "Consumer protection law prevents unfair business practices targeting customers." },
    { word: "securities law", translation: "droit des valeurs mobilières", example: "Securities law regulates financial investment instruments and markets." },
    
    // Réforme juridique
    { word: "legal reform", translation: "réforme juridique", example: "Legal reform modernized outdated provisions in the criminal code." },
    { word: "law reform commission", translation: "commission de réforme du droit", example: "The law reform commission recommended comprehensive changes to family legislation." },
    { word: "legislative overhaul", translation: "refonte législative", example: "The legislative overhaul replaced fragmented regulations with a unified code." },
    { word: "judicial reform", translation: "réforme judiciaire", example: "Judicial reform strengthened court independence and efficiency." },
    { word: "regulatory modernization", translation: "modernisation réglementaire", example: "Regulatory modernization addressed challenges posed by technological innovation." },
    { word: "legal transplantation", translation: "transplantation juridique", example: "Legal transplantation adapted foreign regulatory models to domestic contexts." },
    { word: "reform implementation", translation: "mise en œuvre de la réforme", example: "Reform implementation faced resistance from established legal practitioners." },
    { word: "law revision", translation: "révision juridique", example: "Law revision eliminated contradictions and outdated provisions." },
    { word: "substantive reform", translation: "réforme substantielle", example: "Substantive reform changed fundamental legal principles governing liability." },
    { word: "procedural reform", translation: "réforme procédurale", example: "Procedural reform streamlined court processes to reduce delays." },
    { word: "legal development", translation: "développement juridique", example: "Legal development programs strengthened rule of law in transitional democracies." },
    { word: "harmonization effort", translation: "effort d'harmonisation", example: "The harmonization effort aligned national regulations with international standards." },
    { word: "reform initiative", translation: "initiative de réforme", example: "The reform initiative addressed systemic problems in the justice system." },
    { word: "codification project", translation: "projet de codification", example: "The codification project consolidated scattered provisions into a coherent framework." },
    { word: "legal system overhaul", translation: "refonte du système juridique", example: "The legal system overhaul modernized colonial-era institutions." },
    { word: "reform agenda", translation: "programme de réforme", example: "The justice minister announced an ambitious reform agenda for her term." },
    { word: "structural reform", translation: "réforme structurelle", example: "Structural reform reorganized court hierarchies and jurisdictional boundaries." },
    { word: "progressive reform", translation: "réforme progressive", example: "Progressive reform expanded legal protections for vulnerable populations." },
    { word: "legal infrastructure", translation: "infrastructure juridique", example: "Development programs strengthened legal infrastructure in post-conflict regions." },
    { word: "reform outcome", translation: "résultat de la réforme", example: "Reform outcomes varied significantly across different jurisdictions." },
    { word: "legal advancement", translation: "avancement juridique", example: "Legal advancement involves both normative improvement and institutional development." },
    { word: "reform strategy", translation: "stratégie de réforme", example: "The reform strategy prioritized high-impact changes to essential institutions." },
    { word: "institutional renovation", translation: "rénovation institutionnelle", example: "Institutional renovation modernized archaic court administration practices." },
    { word: "legal innovation", translation: "innovation juridique", example: "Legal innovation developed novel approaches to emerging regulatory challenges." },
    { word: "reform resistance", translation: "résistance à la réforme", example: "Reform resistance came primarily from groups benefiting from existing arrangements." },
    { word: "capacity building", translation: "renforcement des capacités", example: "Capacity building programs trained judicial personnel on reformed procedures." },
    { word: "modernization initiative", translation: "initiative de modernisation", example: "The modernization initiative introduced digital systems for case management." }
  ]
};