export const vocab = {
  title: "Innovation et Transformation Numérique",
  words: [
    // Technologies émergentes et innovation (50 mots)
    { word: "digital transformation", translation: "transformation numérique", example: "The company's digital transformation initiative required rethinking core business processes and customer engagement models." },
    { word: "disruptive innovation", translation: "innovation disruptive", example: "Disruptive innovation often emerges from the market periphery before displacing established technologies." },
    { word: "technological convergence", translation: "convergence technologique", example: "Technological convergence between AI, IoT, and cloud computing creates unprecedented capabilities and business models." },
    { word: "exponential technology", translation: "technologie exponentielle", example: "Exponential technologies follow accelerating growth curves rather than linear improvement patterns." },
    { word: "innovation ecosystem", translation: "écosystème d'innovation", example: "Silicon Valley's innovation ecosystem combines capital, talent, research institutions, and entrepreneurial culture." },
    { word: "digital maturity", translation: "maturité numérique", example: "The organization's digital maturity assessment revealed strengths in data analytics but gaps in customer experience." },
    { word: "technology adoption curve", translation: "courbe d'adoption technologique", example: "The technology adoption curve illustrates progression from early adopters to mainstream acceptance." },
    { word: "innovation diffusion", translation: "diffusion de l'innovation", example: "Innovation diffusion varies significantly across different organizational and cultural contexts." },
    { word: "emerging technology", translation: "technologie émergente", example: "The firm specializes in commercializing emerging technologies from university research labs." },
    { word: "innovation lifecycle", translation: "cycle de vie de l'innovation", example: "Different funding mechanisms support various stages of the innovation lifecycle from concept to commercialization." },
    { word: "technology readiness level", translation: "niveau de maturité technologique", example: "The prototype advanced from technology readiness level 4 to 6 following successful field testing." },
    { word: "innovation strategy", translation: "stratégie d'innovation", example: "Their innovation strategy balances incremental improvements with more speculative breakthrough initiatives." },
    { word: "open innovation", translation: "innovation ouverte", example: "Open innovation collaboration with external partners accelerated their development timeline significantly." },
    { word: "closed innovation", translation: "innovation fermée", example: "The company historically preferred closed innovation approaches to protect intellectual property." },
    { word: "knowledge spillover", translation: "retombées de connaissances", example: "Industrial clusters benefit from knowledge spillover between competing and complementary firms." },
    { word: "cross-pollination", translation: "pollinisation croisée", example: "Cross-pollination between seemingly unrelated disciplines often sparks breakthrough innovations." },
    { word: "innovation pipeline", translation: "pipeline d'innovation", example: "The corporate innovation pipeline manages concepts from ideation through development to implementation." },
    { word: "technology stack", translation: "pile technologique", example: "The company rebuilt its technology stack to enable greater flexibility and integration capabilities." },
    { word: "technology ecosystem", translation: "écosystème technologique", example: "Platform companies cultivate technology ecosystems of complementary products and services." },
    { word: "digital ecosystem", translation: "écosystème numérique", example: "Competing digital ecosystems create increasing lock-in effects for both businesses and consumers." },
    { word: "proof of concept", translation: "preuve de concept", example: "The successful proof of concept demonstrated technical feasibility but not yet commercial viability." },
    { word: "minimum viable product", translation: "produit minimum viable", example: "The minimum viable product focused on core functionality to enable rapid market testing." },
    { word: "rapid prototyping", translation: "prototypage rapide", example: "Rapid prototyping techniques accelerated the feedback cycle between developers and potential users." },
    { word: "agile methodology", translation: "méthodologie agile", example: "Agile methodology replaced rigid planning with iterative development cycles and continuous feedback." },
    { word: "innovation metrics", translation: "métriques d'innovation", example: "Effective innovation metrics balance leading indicators of future success with current performance measures." },
    { word: "digital pioneer", translation: "pionnier numérique", example: "The company established itself as a digital pioneer in an otherwise traditional industry." },
    { word: "incremental innovation", translation: "innovation incrémentale", example: "Incremental innovation improves existing products rather than creating entirely new categories." },
    { word: "breakthrough innovation", translation: "innovation de rupture", example: "Breakthrough innovation transforms markets and renders previous technologies obsolete." },
    { word: "sustaining innovation", translation: "innovation de maintien", example: "Established companies typically focus on sustaining innovation that reinforces existing business models." },
    { word: "radical innovation", translation: "innovation radicale", example: "Radical innovation introduces fundamentally new approaches rather than improving existing systems." },
    { word: "technological paradigm", translation: "paradigme technologique", example: "The shift represents a fundamental technological paradigm change rather than incremental improvement." },
    { word: "innovation catalyst", translation: "catalyseur d'innovation", example: "The organization created innovation catalyst roles to stimulate creative thinking across departments." },
    { word: "creative destruction", translation: "destruction créatrice", example: "Schumpeter's concept of creative destruction explains how new technologies displace established market leaders." },
    { word: "innovation mindset", translation: "état d'esprit d'innovation", example: "Cultivating an innovation mindset requires psychological safety and tolerance for calculated risks." },
    { word: "digital divide", translation: "fracture numérique", example: "The digital divide creates disparity in opportunity between connected and underserved populations." },
    { word: "leapfrogging", translation: "saut technologique", example: "Developing economies often achieve leapfrogging by adopting latest technologies without legacy infrastructure constraints." },
    { word: "frugal innovation", translation: "innovation frugale", example: "Frugal innovation develops high-value solutions using minimal resources to address accessibility challenges." },
    { word: "reverse innovation", translation: "innovation inverse", example: "Reverse innovation develops solutions for emerging markets before adapting them for developed economies." },
    { word: "grassroots innovation", translation: "innovation populaire", example: "Grassroots innovation emerges from community problem-solving rather than formal research institutions." },
    { word: "user-driven innovation", translation: "innovation centrée sur l'utilisateur", example: "User-driven innovation incorporates feedback loops throughout the development process." },
    { word: "co-creation", translation: "co-création", example: "The platform enables co-creation between the company and its most engaged customers." },
    { word: "experimentation culture", translation: "culture d'expérimentation", example: "Building an experimentation culture requires normalizing failure as a learning opportunity." },
    { word: "ambidextrous organization", translation: "organisation ambidextre", example: "Ambidextrous organizations simultaneously exploit existing capabilities while exploring new possibilities." },
    { word: "innovation hub", translation: "centre d'innovation", example: "The innovation hub provides resources and mentorship for emerging technology ventures." },
    { word: "innovation sandbox", translation: "bac à sable d'innovation", example: "The innovation sandbox provides a controlled environment for testing disruptive concepts." },
    { word: "technological determinism", translation: "déterminisme technologique", example: "Technological determinism assumes social changes are driven primarily by technological development." },
    { word: "appropriate technology", translation: "technologie appropriée", example: "Appropriate technology solutions consider local context rather than imposing standardized approaches." },
    { word: "technology assessment", translation: "évaluation technologique", example: "Technology assessment examines potential social, ethical, and environmental implications before widespread adoption." },
    { word: "technology adoption lifecycle", translation: "cycle d'adoption technologique", example: "Different market segments along the technology adoption lifecycle require distinct marketing approaches." },
    { word: "innovation accelerator", translation: "accélérateur d'innovation", example: "The innovation accelerator program provides mentoring, funding, and connections to early-stage ventures." },
    
    // Transformation des affaires et économie numérique (50 mots)
    { word: "platform economy", translation: "économie de plateforme", example: "The platform economy creates value through facilitating interactions rather than producing goods directly." },
    { word: "digital business model", translation: "modèle d'affaires numérique", example: "Their digital business model leverages network effects and data analytics for competitive advantage." },
    { word: "business model innovation", translation: "innovation du modèle d'affaires", example: "Business model innovation often creates more sustainable advantage than product innovation alone." },
    { word: "digital disruption", translation: "perturbation numérique", example: "Traditional retailers experienced digital disruption as consumer purchasing shifted online." },
    { word: "digital native organization", translation: "organisation numérique native", example: "Digital native organizations build processes around technology rather than adapting technology to existing workflows." },
    { word: "digital quotient", translation: "quotient numérique", example: "The company's digital quotient assessment revealed gaps in technological capabilities requiring investment." },
    { word: "digital strategy", translation: "stratégie numérique", example: "An effective digital strategy aligns technological investments with core business objectives." },
    { word: "digital business transformation", translation: "transformation numérique des entreprises", example: "Digital business transformation requires fundamental rethinking of value creation rather than merely automating existing processes." },
    { word: "organizational agility", translation: "agilité organisationnelle", example: "Organizational agility enables rapid response to technological and market shifts." },
    { word: "network effect", translation: "effet de réseau", example: "Platforms with strong network effects become increasingly valuable as user numbers grow." },
    { word: "multi-sided platform", translation: "plateforme multiface", example: "The multi-sided platform connects service providers, customers, and advertisers in a single ecosystem." },
    { word: "platform business", translation: "entreprise plateforme", example: "Platform businesses create value by facilitating exchanges rather than producing goods." },
    { word: "digital marketplace", translation: "place de marché numérique", example: "The digital marketplace connects buyers and sellers while collecting valuable transaction data." },
    { word: "sharing economy", translation: "économie du partage", example: "Sharing economy platforms enable monetization of underutilized assets and spare capacity." },
    { word: "distributed ledger technology", translation: "technologie des registres distribués", example: "Distributed ledger technology enables secure transactions without centralized verification." },
    { word: "blockchain application", translation: "application de la chaîne de blocs", example: "The blockchain application creates immutable records of supply chain transactions." },
    { word: "smart contract", translation: "contrat intelligent", example: "Smart contracts automatically execute agreements when predefined conditions are met." },
    { word: "tokenization", translation: "tokenisation", example: "Asset tokenization converts physical value into digital tokens that can be fractionalized and traded." },
    { word: "decentralized finance", translation: "finance décentralisée", example: "Decentralized finance systems operate without traditional financial intermediaries through blockchain protocols." },
    { word: "digital currency", translation: "monnaie numérique", example: "Central bank digital currency development accelerated following private cryptocurrency adoption." },
    { word: "digital economy", translation: "économie numérique", example: "The digital economy now represents a significant portion of total economic activity." },
    { word: "data-driven business", translation: "entreprise axée sur les données", example: "Data-driven businesses leverage analytics for improved decision-making and personalization." },
    { word: "data monetization", translation: "monétisation des données", example: "Their data monetization strategy identifies valuable insights while respecting privacy constraints." },
    { word: "algorithmic business", translation: "entreprise algorithmique", example: "Algorithmic businesses automate core decisions through machine learning and artificial intelligence." },
    { word: "servitization", translation: "servicisation", example: "Servitization transforms product-based companies into service providers with recurring revenue streams." },
    { word: "subscription economy", translation: "économie de l'abonnement", example: "The subscription economy creates predictable revenue and ongoing customer relationships." },
    { word: "on-demand economy", translation: "économie à la demande", example: "On-demand economy services provide immediate fulfillment through digital coordination." },
    { word: "outcome economy", translation: "économie des résultats", example: "The outcome economy shifts focus from selling products to delivering guaranteed results." },
    { word: "experience economy", translation: "économie de l'expérience", example: "In the experience economy, memorable interactions command premium prices over mere services or goods." },
    { word: "attention economy", translation: "économie de l'attention", example: "The attention economy treats user focus as a scarce and valuable commodity." },
    { word: "open banking", translation: "services bancaires ouverts", example: "Open banking regulations enable third-party services to access financial data with customer consent." },
    { word: "fintech", translation: "technologie financière", example: "Fintech innovations challenge traditional banking services through digital-first approaches." },
    { word: "insurtech", translation: "technologie de l'assurance", example: "Insurtech startups leverage data analytics for more personalized risk assessment and pricing." },
    { word: "regtech", translation: "technologie réglementaire", example: "Regtech solutions automate compliance processes to reduce risk and operating costs." },
    { word: "proptech", translation: "technologie immobilière", example: "Proptech innovations transform property management, transactions, and financing through digital platforms." },
    { word: "e-commerce evolution", translation: "évolution du commerce électronique", example: "E-commerce evolution continues with immersive experiences and frictionless transactions." },
    { word: "omnichannel strategy", translation: "stratégie omnicanale", example: "Omnichannel strategy creates seamless experiences across digital and physical touchpoints." },
    { word: "headless commerce", translation: "commerce découplé", example: "Headless commerce separates frontend experiences from backend functionality for greater flexibility." },
    { word: "conversational commerce", translation: "commerce conversationnel", example: "Conversational commerce enables transactions through messaging and voice interfaces." },
    { word: "digital supply chain", translation: "chaîne d'approvisionnement numérique", example: "Digital supply chain technologies provide real-time visibility and predictive intelligence." },
    { word: "digital twin", translation: "jumeau numérique", example: "The digital twin simulates physical assets to optimize performance and predict maintenance needs." },
    { word: "predictive maintenance", translation: "maintenance prédictive", example: "Predictive maintenance analyzes sensor data to address equipment issues before failure occurs." },
    { word: "machine-to-machine communication", translation: "communication machine à machine", example: "Machine-to-machine communication enables autonomous coordination between connected devices." },
    { word: "smart factory", translation: "usine intelligente", example: "The smart factory uses automation, sensors, and analytics to optimize production processes." },
    { word: "digital workplace", translation: "lieu de travail numérique", example: "The digital workplace integrates collaboration tools with core business systems for seamless operation." },
    { word: "remote work infrastructure", translation: "infrastructure de travail à distance", example: "Investing in remote work infrastructure became a strategic priority during the pandemic." },
    { word: "distributed workforce", translation: "main-d'œuvre distribuée", example: "Managing a distributed workforce requires different leadership approaches and communication patterns." },
    { word: "location-independent work", translation: "travail indépendant de l'emplacement", example: "Digital tools enable location-independent work for many knowledge-based professions." },
    { word: "talent marketplace", translation: "marché des talents", example: "Digital talent marketplaces connect specialized skills with project needs across geographic boundaries." },
    
    // Intelligence artificielle et analyse avancée (50 mots)
    { word: "artificial intelligence implementation", translation: "mise en œuvre de l'intelligence artificielle", example: "Successful artificial intelligence implementation requires clear use cases and robust data foundations." },
    { word: "machine learning application", translation: "application d'apprentissage automatique", example: "The machine learning application improved decision accuracy by 40% compared to rule-based approaches." },
    { word: "neural network", translation: "réseau neuronal", example: "The neural network identifies complex patterns in customer behavior that traditional analytics missed." },
    { word: "deep learning model", translation: "modèle d'apprentissage profond", example: "Their deep learning model recognizes visual brand elements across diverse marketing materials." },
    { word: "predictive analytics", translation: "analyse prédictive", example: "Predictive analytics identifies customers most likely to purchase specific product categories." },
    { word: "prescriptive analytics", translation: "analyse prescriptive", example: "Prescriptive analytics recommends optimal pricing strategies for maximizing revenue without eroding market share." },
    { word: "natural language processing", translation: "traitement du langage naturel", example: "Natural language processing enables the system to understand and respond to customer inquiries in conversational language." },
    { word: "computer vision", translation: "vision par ordinateur", example: "Computer vision algorithms automatically identify quality defects in manufacturing processes." },
    { word: "autonomous system", translation: "système autonome", example: "The autonomous system makes real-time decisions without human intervention using predefined parameters." },
    { word: "intelligent automation", translation: "automatisation intelligente", example: "Intelligent automation applies AI capabilities to workflow execution rather than simply replicating human actions." },
    { word: "robotic process automation", translation: "automatisation robotisée des processus", example: "Robotic process automation handles repetitive tasks across multiple legacy systems without API integrations." },
    { word: "conversational AI", translation: "IA conversationnelle", example: "The conversational AI system handles routine customer interactions while escalating complex issues to human agents." },
    { word: "large language model", translation: "grand modèle de langage", example: "The large language model generates human-quality content based on minimal input prompts." },
    { word: "recommender system", translation: "système de recommandation", example: "The recommender system increased average order value through contextually relevant suggestions." },
    { word: "reinforcement learning", translation: "apprentissage par renforcement", example: "Reinforcement learning optimized energy consumption by continuously adapting to changing conditions." },
    { word: "supervised learning", translation: "apprentissage supervisé", example: "The supervised learning algorithm classified incoming communications by department using labeled examples." },
    { word: "unsupervised learning", translation: "apprentissage non supervisé", example: "Unsupervised learning identified distinct customer segments without predefined categories." },
    { word: "synthetic data", translation: "données synthétiques", example: "Synthetic data enabled algorithm training while addressing privacy concerns regarding sensitive information." },
    { word: "data annotation", translation: "annotation de données", example: "The data annotation process created labeled examples for supervised learning applications." },
    { word: "augmented intelligence", translation: "intelligence augmentée", example: "Their augmented intelligence approach combines human expertise with AI processing capabilities." },
    { word: "human-in-the-loop", translation: "humain dans la boucle", example: "The human-in-the-loop system leverages machine efficiency while maintaining human judgment for critical decisions." },
    { word: "algorithm bias", translation: "biais algorithmique", example: "Regular audits detect and mitigate algorithm bias that could affect fairness in automated decisions." },
    { word: "explainable AI", translation: "IA explicable", example: "Explainable AI methods provide transparency into how algorithmic conclusions are reached." },
    { word: "AI ethics", translation: "éthique de l'IA", example: "The organization established AI ethics principles to guide responsible technology development and deployment." },
    { word: "algorithmic transparency", translation: "transparence algorithmique", example: "Regulatory requirements for algorithmic transparency are increasing in high-impact decision contexts." },
    { word: "cognitive computing", translation: "informatique cognitive", example: "Cognitive computing systems mimic human thought processes to solve complex problems." },
    { word: "edge AI", translation: "IA en périphérie", example: "Edge AI processes data locally on devices rather than sending everything to cloud servers." },
    { word: "federated learning", translation: "apprentissage fédéré", example: "Federated learning trains algorithms across distributed devices without centralizing sensitive data." },
    { word: "transfer learning", translation: "apprentissage par transfert", example: "Transfer learning applies knowledge from one domain to improve performance in another with limited training data." },
    { word: "neural architecture", translation: "architecture neuronale", example: "Researchers optimized the neural architecture to balance computational efficiency with prediction accuracy." },
    { word: "data pipeline", translation: "pipeline de données", example: "The automated data pipeline transforms raw information into analysis-ready formats." },
    { word: "big data architecture", translation: "architecture de mégadonnées", example: "Their big data architecture enables real-time processing of streaming information sources." },
    { word: "data lake", translation: "lac de données", example: "The data lake stores raw, unprocessed information in its native format until needed for specific analyses." },
    { word: "data warehouse", translation: "entrepôt de données", example: "The data warehouse integrates information from multiple systems in structured, analysis-ready formats." },
    { word: "data mining", translation: "exploration de données", example: "Data mining techniques revealed unexpected patterns in customer purchasing behaviors." },
    { word: "knowledge graph", translation: "graphe de connaissances", example: "The knowledge graph represents relationships between entities to enable more contextual understanding." },
    { word: "cognitive search", translation: "recherche cognitive", example: "Cognitive search understands natural language queries and user intent rather than simple keyword matching." },
    { word: "business intelligence", translation: "intelligence d'affaires", example: "Advanced business intelligence capabilities provide interactive data exploration rather than static reports." },
    { word: "data storytelling", translation: "narration de données", example: "Data storytelling transforms complex analytics into compelling narratives for decision-makers." },
    { word: "data visualization", translation: "visualisation de données", example: "Interactive data visualization enables intuitive pattern recognition and insight discovery." },
    { word: "real-time analytics", translation: "analyse en temps réel", example: "Real-time analytics processes incoming data streams for immediate operational decisions." },
    { word: "sentiment analysis", translation: "analyse des sentiments", example: "Sentiment analysis tracks customer perception across social media and review platforms." },
    { word: "voice analytics", translation: "analyse vocale", example: "Voice analytics identifies customer emotion and engagement during service interactions." },
    { word: "behavioral analytics", translation: "analyse comportementale", example: "Behavioral analytics examines patterns in user actions to predict future decisions and preferences." },
    { word: "anomaly detection", translation: "détection d'anomalies", example: "The anomaly detection system identifies unusual patterns that may indicate fraud or security breaches." },
    { word: "root cause analysis", translation: "analyse des causes fondamentales", example: "Advanced analytics support root cause analysis by revealing relationships between seemingly unrelated factors." },
    { word: "trend prediction", translation: "prédiction de tendances", example: "The algorithm's trend prediction capabilities inform inventory planning and product development." },
    { word: "scenario modeling", translation: "modélisation de scénarios", example: "Scenario modeling simulates potential outcomes under different market and operational conditions." },
    { word: "cognitive bias", translation: "biais cognitif", example: "Advanced analytics helps identify cognitive biases that affect human decision-making processes." },
    { word: "decision intelligence", translation: "intelligence décisionnelle", example: "Decision intelligence combines data science with decision theory to improve organizational choices." },
    
    // Transformation numérique et impact sociétal (50 mots)
    { word: "digital leadership", translation: "leadership numérique", example: "Digital leadership requires understanding both technological possibilities and organizational dynamics." },
    { word: "change management", translation: "gestion du changement", example: "Effective change management addresses human factors in digital transformation rather than focusing solely on technology." },
    { word: "digital adoption", translation: "adoption numérique", example: "Digital adoption efforts focus on helping employees integrate new tools into daily workflows." },
    { word: "technology acceptance", translation: "acceptation de la technologie", example: "The technology acceptance model identifies factors influencing user adoption of new systems." },
    { word: "resistance to change", translation: "résistance au changement", example: "Understanding specific reasons for resistance to change enables more effective intervention strategies." },
    { word: "digital mindset", translation: "état d'esprit numérique", example: "Developing a digital mindset involves embracing experimentation, continuous learning, and data-driven decisions." },
    { word: "transformational leadership", translation: "leadership transformationnel", example: "Transformational leadership inspires commitment to change through compelling vision and personal example." },
    { word: "digital culture", translation: "culture numérique", example: "Creating a digital culture requires aligning rewards, processes, and leadership behaviors with transformation goals." },
    { word: "digital competency", translation: "compétence numérique", example: "The organization mapped critical digital competency requirements across different roles and functions." },
    { word: "digital fluency", translation: "aisance numérique", example: "Digital fluency enables employees to confidently leverage technology tools for maximum productivity." },
    { word: "digital talent", translation: "talent numérique", example: "The company implemented multiple strategies to attract and retain scarce digital talent." },
    { word: "digital literacy", translation: "littératie numérique", example: "Digital literacy programs ensure all employees can effectively participate in the transformed organization." },
    { word: "digital dexterity", translation: "dextérité numérique", example: "Digital dexterity refers to the ability to adapt quickly to changing technological environments and tools." },
    { word: "digital capability", translation: "capacité numérique", example: "The assessment identified specific digital capability gaps requiring targeted investment." },
    { word: "digital governance", translation: "gouvernance numérique", example: "Digital governance establishes decision frameworks for technology investments, standards, and policies." },
    { word: "digital operating model", translation: "modèle opérationnel numérique", example: "The digital operating model redefines organizational structure, processes, and performance metrics." },
    { word: "technological unemployment", translation: "chômage technologique", example: "Automation raises concerns about technological unemployment in routine cognitive and manual roles." },
    { word: "reskilling", translation: "reconversion professionnelle", example: "The reskilling initiative prepares employees for roles less vulnerable to automation." },
    { word: "upskilling", translation: "perfectionnement professionnel", example: "Continuous upskilling programs help employees adapt to evolving technological requirements." },
    { word: "human-machine collaboration", translation: "collaboration homme-machine", example: "The future workplace will feature increasing human-machine collaboration rather than simple replacement." },
    { word: "digital ethics", translation: "éthique numérique", example: "Digital ethics frameworks address questions regarding data use, algorithmic decisions, and technology impacts." },
    { word: "responsible innovation", translation: "innovation responsable", example: "Responsible innovation considers potential unintended consequences during development rather than afterward." },
    { word: "algorithmic accountability", translation: "responsabilité algorithmique", example: "Algorithmic accountability requires clear ownership and oversight of automated decision systems." },
    { word: "data sovereignty", translation: "souveraineté des données", example: "Data sovereignty concerns involve both individual rights and national control over information resources." },
    { word: "data governance", translation: "gouvernance des données", example: "Robust data governance establishes policies for collection, quality, access, and protection of information assets." },
    { word: "privacy by design", translation: "protection de la vie privée dès la conception", example: "Privacy by design integrates data protection principles throughout product development." },
    { word: "information privacy", translation: "confidentialité des informations", example: "Evolving regulations strengthen information privacy protections for consumers worldwide." },
    { word: "technology regulation", translation: "réglementation technologique", example: "Technology regulation increasingly addresses algorithmic transparency and digital market power." },
    { word: "digital inclusion", translation: "inclusion numérique", example: "Digital inclusion initiatives address barriers including access, affordability, skills, and relevant content." },
    { word: "digital equality", translation: "égalité numérique", example: "Digital equality ensures all population segments can benefit from technological advancement." },
    { word: "digital public goods", translation: "biens publics numériques", example: "Digital public goods provide open-source solutions for development challenges worldwide." },
    { word: "digital commons", translation: "biens communs numériques", example: "Digital commons create shared resources through distributed contributions and governance." },
    { word: "platform governance", translation: "gouvernance des plateformes", example: "Platform governance addresses content moderation, competition, and algorithmic transparency issues." },
    { word: "technology assessment", translation: "évaluation technologique", example: "Technology assessment examines potential societal impacts before widespread deployment." },
    { word: "digital sustainability", translation: "durabilité numérique", example: "Digital sustainability addresses environmental impacts of technology throughout its lifecycle." },
    { word: "green computing", translation: "informatique écologique", example: "Green computing strategies reduce energy consumption and electronic waste generation." },
    { word: "tech for good", translation: "technologie pour le bien", example: "Tech for good initiatives apply digital innovations to address social and environmental challenges." },
    { word: "digital democracy", translation: "démocratie numérique", example: "Digital democracy tools enable broader citizen participation in governance processes." },
    { word: "civic technology", translation: "technologie civique", example: "Civic technology applications improve government services and citizen engagement." },
    { word: "digital identity", translation: "identité numérique", example: "Secure digital identity systems balance access to services with privacy protections." },
    { word: "social innovation", translation: "innovation sociale", example: "Social innovation applies new approaches to persistent community challenges." },
    { word: "digital accessibility", translation: "accessibilité numérique", example: "Digital accessibility ensures people with disabilities can effectively use technology products and services." },
    { word: "inclusive design", translation: "conception inclusive", example: "Inclusive design considers diverse user needs throughout the development process." },
    { word: "digital wellbeing", translation: "bien-être numérique", example: "Digital wellbeing features help users maintain healthy relationships with technology." },
    { word: "technology addiction", translation: "dépendance technologique", example: "Product designers now consider how to minimize technology addiction risks in engagement features." },
    { word: "surveillance capitalism", translation: "capitalisme de surveillance", example: "The term surveillance capitalism describes business models monetizing behavioral data for prediction and influence." },
    { word: "data extractivism", translation: "extractivisme des données", example: "Critics compare data extractivism to resource exploitation in historically colonized regions." },
    { word: "digital colonialism", translation: "colonialisme numérique", example: "Digital colonialism concerns relate to global power imbalances in technology ownership and data flows." },
    { word: "algorithmic discrimination", translation: "discrimination algorithmique", example: "Algorithmic discrimination occurs when seemingly neutral systems produce biased outcomes for protected groups." },
    { word: "digital trust", translation: "confiance numérique", example: "Organizations increasingly recognize digital trust as a critical competitive differentiator." }
  ]
};