export const vocab = {
  title: "Expression Idiomatique & Culturelle",
  words: [
    // Expressions figurées
    { word: "to bite the bullet", translation: "prendre son courage à deux mains", example: "After postponing the difficult conversation for weeks, she finally bit the bullet and confronted her colleague." },
    { word: "to beat around the bush", translation: "tourner autour du pot", example: "Stop beating around the bush and tell me what really happened at the meeting." },
    { word: "to cost an arm and a leg", translation: "coûter les yeux de la tête", example: "Their wedding cost an arm and a leg, but they felt it was worth every penny." },
    { word: "to hit the nail on the head", translation: "mettre dans le mille", example: "Her analysis hit the nail on the head, identifying precisely what was wrong with the proposal." },
    { word: "to burn the midnight oil", translation: "travailler tard dans la nuit", example: "During exam period, students are often burning the midnight oil to prepare." },
    { word: "to throw in the towel", translation: "jeter l'éponge", example: "After three failed attempts, he threw in the towel and admitted defeat." },
    { word: "to add fuel to the fire", translation: "jeter de l'huile sur le feu", example: "His inflammatory comments only added fuel to the fire during the heated debate." },
    { word: "to be on thin ice", translation: "être sur la corde raide", example: "After missing three deadlines, she was on thin ice with her supervisor." },
    { word: "to let the cat out of the bag", translation: "vendre la mèche", example: "She accidentally let the cat out of the bag about the surprise party." },
    { word: "to kill two birds with one stone", translation: "faire d'une pierre deux coups", example: "By taking his laptop to the café, he killed two birds with one stone: working while enjoying his favorite coffee." },
    { word: "to pull someone's leg", translation: "faire marcher quelqu'un", example: "Don't worry, I'm just pulling your leg—I didn't actually sell your car." },
    { word: "to see eye to eye", translation: "être sur la même longueur d'onde", example: "Despite their different backgrounds, the two experts see eye to eye on climate policy." },
    { word: "to spill the beans", translation: "vendre la mèche", example: "Who spilled the beans about the company merger before the official announcement?" },
    { word: "to face the music", translation: "affronter les conséquences", example: "After his irresponsible behavior, he had to face the music with the board of directors." },
    { word: "to be in the same boat", translation: "être dans le même bateau", example: "Don't complain to me about the deadline—we're all in the same boat." },
    { word: "to jump on the bandwagon", translation: "suivre le mouvement", example: "Once the technology proved successful, competitors quickly jumped on the bandwagon." },
    { word: "to cut corners", translation: "prendre des raccourcis", example: "The investigation revealed the company had been cutting corners on safety procedures." },
    { word: "to bite off more than one can chew", translation: "voir trop grand", example: "By taking on three major projects simultaneously, she bit off more than she could chew." },
    { word: "to get a taste of one's own medicine", translation: "goûter à sa propre médecine", example: "The notoriously harsh critic got a taste of his own medicine when his book was poorly reviewed." },
    { word: "to miss the boat", translation: "rater le coche", example: "Investors who hesitated missed the boat on the cryptocurrency boom." },
    { word: "to turn a blind eye", translation: "fermer les yeux sur", example: "Regulators turned a blind eye to the bank's questionable practices for years." },
    { word: "to put all eggs in one basket", translation: "mettre tous ses œufs dans le même panier", example: "Financial advisors warn against putting all your eggs in one basket when investing." },
    { word: "to break the ice", translation: "briser la glace", example: "The team-building exercise helped break the ice among the new employees." },
    { word: "to be caught between a rock and a hard place", translation: "être entre le marteau et l'enclume", example: "The diplomat was caught between a rock and a hard place, facing pressure from both countries." },
    { word: "to add insult to injury", translation: "ajouter l'insulte à l'injure", example: "To add insult to injury, they charged us a cancellation fee after providing terrible service." },
    { word: "to take with a grain of salt", translation: "prendre avec des pincettes", example: "You should take his promises with a grain of salt, given his track record." },
    { word: "to open a can of worms", translation: "ouvrir la boîte de Pandore", example: "The investigation into campaign finances opened a can of worms that implicated several officials." },
    { word: "to go out on a limb", translation: "prendre un risque", example: "The analyst went out on a limb with her bold market predictions." },
    { word: "to be on cloud nine", translation: "être aux anges", example: "Since receiving the job offer, she's been on cloud nine." },
    { word: "to play devil's advocate", translation: "jouer l'avocat du diable", example: "Let me play devil's advocate for a moment and consider potential objections to the plan." },
    { word: "to hit a nerve", translation: "toucher un point sensible", example: "His comment about work-life balance clearly hit a nerve with the overworked team." },
    { word: "to cut to the chase", translation: "aller droit au but", example: "Let's cut to the chase—are you interested in the partnership or not?" },
    { word: "to pour oil on troubled waters", translation: "apaiser les tensions", example: "The mediator poured oil on troubled waters during the heated negotiation." },
    { word: "to be barking up the wrong tree", translation: "faire fausse route", example: "If you think she's responsible for the leak, you're barking up the wrong tree." },
    { word: "to take the bull by the horns", translation: "prendre le taureau par les cornes", example: "Rather than waiting for directions, she took the bull by the horns and initiated the project herself." },
    { word: "to be a double-edged sword", translation: "être une arme à double tranchant", example: "Social media visibility is a double-edged sword for public figures, offering both opportunity and scrutiny." },
    { word: "to hit rock bottom", translation: "toucher le fond", example: "After losing his job and home, he hit rock bottom before starting to rebuild his life." },
    { word: "to keep someone at arm's length", translation: "tenir quelqu'un à distance", example: "She keeps her colleagues at arm's length, rarely sharing personal information." },
    { word: "to take center stage", translation: "occuper le devant de la scène", example: "Climate concerns have taken center stage in recent political debates." },
    { word: "to kick the bucket", translation: "casser sa pipe", example: "The old expression 'kick the bucket' is a somewhat light-hearted way to refer to death." },
    
    // Références culturelles
    { word: "Achilles' heel", translation: "talon d'Achille", example: "Overconfidence has always been his Achilles' heel in business negotiations." },
    { word: "Catch-22", translation: "situation sans issue", example: "Job seekers face a Catch-22: needing experience to get hired, but needing a job to gain experience." },
    { word: "Pandora's box", translation: "boîte de Pandore", example: "The discovery opened a Pandora's box of ethical questions about genetic engineering." },
    { word: "Big Brother", translation: "Big Brother", example: "Privacy advocates warn about Big Brother surveillance through digital technologies." },
    { word: "Kafkaesque", translation: "kafkaïen", example: "The immigration process was Kafkaesque—complex, disorienting, and seemingly designed to frustrate." },
    { word: "Freudian slip", translation: "lapsus révélateur", example: "When the CEO called the new product 'terrible' instead of 'terrific,' everyone recognized the Freudian slip." },
    { word: "Trojan horse", translation: "cheval de Troie", example: "The seemingly beneficial proposal was actually a Trojan horse for controversial policy changes." },
    { word: "Herculean task", translation: "tâche herculéenne", example: "Reforming the healthcare system is a Herculean task that has challenged multiple administrations." },
    { word: "Pyrrhic victory", translation: "victoire à la Pyrrhus", example: "The company won the lawsuit but the legal costs were so high it was ultimately a Pyrrhic victory." },
    { word: "Midas touch", translation: "toucher de Midas", example: "The entrepreneur seemed to have the Midas touch, turning every venture into a success." },
    { word: "Sisyphean effort", translation: "travail de Sisyphe", example: "Maintaining order in the classroom sometimes felt like a Sisyphean effort for the teacher." },
    { word: "Orwellian", translation: "orwellien", example: "Critics described the surveillance program as Orwellian in its scope and invasiveness." },
    { word: "Machiavellian", translation: "machiavélique", example: "Her Machiavellian approach to office politics made colleagues distrustful of her motives." },
    { word: "Shakespearean tragedy", translation: "tragédie shakespearienne", example: "The downfall of the once-respected leader had elements of a Shakespearean tragedy." },
    { word: "Dickensian conditions", translation: "conditions dickensiennes", example: "The report revealed Dickensian conditions in some of the country's aging prisons." },
    { word: "Gordian knot", translation: "nœud gordien", example: "The complex legal dispute represented a Gordian knot that required bold action to resolve." },
    { word: "Platonic relationship", translation: "relation platonique", example: "They maintained a Platonic relationship despite others assuming they were romantically involved." },
    { word: "Socratic method", translation: "méthode socratique", example: "The professor used the Socratic method, guiding students through questions rather than providing answers." },
    { word: "Pavlovian response", translation: "réponse pavlovienne", example: "The marketing campaign hoped to create a Pavlovian response associating the brand with positive emotions." },
    { word: "Messianic complex", translation: "complexe messianique", example: "The leader's Messianic complex led him to believe only he could save the organization." },
    { word: "Cartesian doubt", translation: "doute cartésien", example: "Scientists apply Cartesian doubt by questioning established theories and seeking empirical evidence." },
    { word: "Faustian bargain", translation: "pacte faustien", example: "The rapid development came at environmental costs—a Faustian bargain the community now regretted." },
    { word: "Cassandra warning", translation: "avertissement de Cassandre", example: "Her Cassandra warnings about financial instability went unheeded before the crisis." },
    { word: "Procrustean approach", translation: "approche procrustéenne", example: "The standardized testing regime represents a Procrustean approach to education." },
    { word: "Occam's razor", translation: "rasoir d'Occam", example: "Applying Occam's razor to the problem suggests the simplest explanation is most likely correct." },
    { word: "Zeitgeist", translation: "esprit du temps", example: "Her novels perfectly captured the zeitgeist of post-war America." },
    { word: "Quixotic endeavor", translation: "entreprise chimérique", example: "Many considered his pursuit of renewable energy in the 1970s a quixotic endeavor." },
    { word: "Potemkin village", translation: "village Potemkine", example: "The economic reforms were dismissed as a Potemkin village that created the illusion of progress." },
    { word: "Hobson's choice", translation: "choix de Hobson", example: "Voters faced a Hobson's choice between two deeply unpopular candidates." },
    { word: "Murphy's Law", translation: "loi de Murphy", example: "As if demonstrating Murphy's Law, everything that could go wrong during the presentation did." },
    { word: "Groundhog Day situation", translation: "situation du jour de la marmotte", example: "Budget negotiations had become a Groundhog Day situation, with the same arguments repeated annually." },
    { word: "Frankenstein's monster", translation: "monstre de Frankenstein", example: "The hastily designed social media platform became Frankenstein's monster, causing unintended social problems." },
    { word: "Jekyll and Hyde personality", translation: "personnalité de Jekyll et Hyde", example: "His Jekyll and Hyde personality made him charming in public but abusive in private." },
    { word: "Schrödinger's cat", translation: "chat de Schrödinger", example: "The merger exists in a Schrödinger's cat state—simultaneously proceeding and suspended until the regulatory decision." },
    { word: "Tipping point", translation: "point de bascule", example: "Climate scientists warn we are approaching a tipping point beyond which certain changes become irreversible." },
    { word: "Ivory tower", translation: "tour d'ivoire", example: "Academics are often accused of remaining in their ivory tower, disconnected from practical realities." },
    { word: "Cinderella story", translation: "histoire de Cendrillon", example: "The company's rise from a garage startup to global corporation is a classic Cinderella story." },
    { word: "Catch-22", translation: "situation sans issue", example: "The refugee faced a Catch-22: needing documentation to apply for asylum but requiring asylum status to get documentation." },
    { word: "Kafkaesque nightmare", translation: "cauchemar kafkaïen", example: "Dealing with insurance claims after the accident became a Kafkaesque nightmare of bureaucracy." },
    { word: "Orwellian doublespeak", translation: "double langage orwellien", example: "The memo used Orwellian doublespeak, describing layoffs as 'workforce optimization'." },
    
    // Humour linguistique
    { word: "pun", translation: "jeu de mots", example: "The vegetarian's favorite pun was 'I find that joke very a-peeling' when shown pictures of bananas." },
    { word: "wordplay", translation: "jeu de mots", example: "The headline 'Local Dairy Owner is Udder Failure' used wordplay to lighten the economic news." },
    { word: "malapropism", translation: "malapropisme", example: "Her malapropism—saying 'He's a wolf in cheap clothing' instead of 'sheep's clothing'—amused the entire room." },
    { word: "double entendre", translation: "double sens", example: "The advertisement relied on a double entendre that could be interpreted innocently by children but differently by adults." },
    { word: "innuendo", translation: "insinuation", example: "The politician's speech was filled with innuendo about his opponent's financial backers." },
    { word: "spoonerism", translation: "contrepèterie", example: "A classic spoonerism switches initial sounds, turning 'crushing blow' into 'blushing crow'." },
    { word: "paraprosdokian", translation: "paraprosdokian", example: "The comedian specialized in paraprosdokians like 'I've had a perfectly wonderful evening, but this wasn't it'." },
    { word: "oxymoron", translation: "oxymore", example: "'Clearly confused' is an oxymoron that effectively describes many students before exams." },
    { word: "irony", translation: "ironie", example: "The fire station burning down represented situational irony at its most unfortunate." },
    { word: "sarcasm", translation: "sarcasme", example: "When he said 'Oh, fantastic, another meeting,' his sarcasm was evident to everyone." },
    { word: "satire", translation: "satire", example: "The novel is a brilliant satire of corporate culture and consumer society." },
    { word: "parody", translation: "parodie", example: "The comedy show's parody of the serious historical drama exaggerated its melodramatic elements." },
    { word: "wit", translation: "esprit", example: "Her quick wit made her a favorite guest on late-night talk shows." },
    { word: "repartee", translation: "repartie", example: "The siblings engaged in clever repartee throughout dinner, amusing the entire family." },
    { word: "hyperbole", translation: "hyperbole", example: "Claiming 'I've told you a million times' is a common hyperbole expressing frustration." },
    { word: "understatement", translation: "litote", example: "Describing a catastrophic system failure as 'a slight technical issue' is quite an understatement." },
    { word: "deadpan delivery", translation: "ton pince-sans-rire", example: "His deadpan delivery made it difficult to tell whether he was joking or serious." },
    { word: "gallows humor", translation: "humour noir", example: "Medical professionals often use gallows humor to cope with stressful situations." },
    { word: "self-deprecating humor", translation: "humour autodérisoire", example: "Her self-deprecating humor about her cooking skills made everyone comfortable at the dinner party." },
    { word: "tongue-in-cheek", translation: "au second degré", example: "The article offered tongue-in-cheek advice on 'How to Look Busy While Doing Nothing at Work'." },
    { word: "facetious remark", translation: "remarque facétieuse", example: "His facetious remark about needing a vacation halfway through the first workday wasn't appreciated by management." },
    { word: "mordant wit", translation: "esprit mordant", example: "The critic was known for her mordant wit when reviewing particularly pretentious works." },
    { word: "ribbing", translation: "taquinerie", example: "The gentle ribbing between teammates strengthened their camaraderie." },
    { word: "droll humor", translation: "humour pince-sans-rire", example: "The narrator's droll humor made the documentary on accounting surprisingly entertaining." },
    { word: "sardonic comment", translation: "remarque sardonique", example: "He made a sardonic comment about the 'efficiency' of the bureaucratic process after waiting four hours." },
    { word: "acerbic wit", translation: "esprit acerbe", example: "The reviewer was famous for her acerbic wit when discussing poorly executed performances." },
    { word: "wisecrack", translation: "plaisanterie", example: "The student's wisecrack about the principal's new policy earned both laughs and detention." },
    { word: "quip", translation: "trait d'esprit", example: "Her quip about the extravagant budget made everyone laugh but the finance director." },
    { word: "banter", translation: "badinage", example: "The lively banter between the co-hosts made the podcast especially engaging." },
    { word: "wry observation", translation: "observation ironique", example: "He made a wry observation about how meetings to improve efficiency always ran overtime." },
    { word: "lampoon", translation: "satire", example: "The comedy sketch lampooned the self-importance of awards ceremonies." },
    { word: "send-up", translation: "parodie", example: "The film was a brilliant send-up of superhero movie clichés." },
    { word: "spoof", translation: "parodie", example: "Their spoof of classic detective novels exaggerated all the genre's familiar tropes." },
    { word: "roast", translation: "raillerie", example: "The charity roast featured celebrities making jokes at each other's expense for a good cause." },
    { word: "zinger", translation: "pique", example: "Her unexpected zinger about the company's strategy left the boardroom momentarily silent." },
    { word: "bon mot", translation: "bon mot", example: "The diplomat was known for delivering the perfect bon mot in tense situations." },
    { word: "riposte", translation: "riposte", example: "His clever riposte to the criticism turned what could have been an awkward moment into shared laughter." },
    { word: "jest", translation: "plaisanterie", example: "What began as a jest about starting their own business eventually led to a successful startup." },
    { word: "crack wise", translation: "faire de l'esprit", example: "The new employee quickly learned when it was appropriate to crack wise during team meetings." },
    { word: "dry humor", translation: "humour pince-sans-rire", example: "British comedies often feature dry humor that might be missed by inattentive viewers." },
    
    // Registres spécialisés
    { word: "legalese", translation: "jargon juridique", example: "The contract was written in dense legalese that obscured its actual implications." },
    { word: "medicalese", translation: "jargon médical", example: "Doctors sometimes forget to translate medicalese into plain language for patients." },
    { word: "corporatespeak", translation: "jargon d'entreprise", example: "The memo was full of corporatespeak about 'synergizing cross-platform initiatives'." },
    { word: "academese", translation: "jargon académique", example: "The professor's article was written in such impenetrable academese that even colleagues struggled to understand it." },
    { word: "bureaucratese", translation: "jargon bureaucratique", example: "The government form was written in classic bureaucratese, making simple questions unnecessarily complex." },
    { word: "technobabble", translation: "charabia technique", example: "The IT presentation was filled with technobabble that confused the non-technical audience." },
    { word: "journalese", translation: "style journalistique", example: "The headline used typical journalese: 'Shock Tax Hike Slams Homeowners'." },
    { word: "sportspeak", translation: "jargon sportif", example: "Sportspeak includes phrases like 'giving 110 percent' and 'taking it one game at a time'." },
    { word: "psychobabble", translation: "psycho-jargon", example: "The self-help book was criticized for its psychobabble about 'inner child healing journeys'." },
    { word: "militaryese", translation: "jargon militaire", example: "Military briefings often contain militaryese like 'strategic reassessment of tactical positioning'." },
    { word: "diplomatese", translation: "langue diplomatique", example: "The ambassador's statement was classic diplomatese that expressed concern without making commitments." },
    { word: "econospeak", translation: "jargon économique", example: "The financial analyst's report was full of econospeak about 'lagging indicators' and 'productivity differentials'." },
    { word: "pedagoguese", translation: "jargon pédagogique", example: "The education policy was written in pedagoguese about 'scaffolded learning experiences' and 'metacognitive strategies'." },
    { word: "art speak", translation: "jargon artistique", example: "The gallery catalog contained typical art speak describing the exhibition as 'an interrogation of post-modern spatial dynamics'." },
    { word: "marketing jargon", translation: "jargon marketing", example: "The presentation was filled with marketing jargon like 'brand ambassadors' and 'conversion optimization'." },
    { word: "political rhetoric", translation: "rhétorique politique", example: "His speech employed standard political rhetoric about 'a new era' and 'reclaiming our values'." },
    { word: "scientific nomenclature", translation: "nomenclature scientifique", example: "Biologists rely on scientific nomenclature like 'Homo sapiens' to precisely identify species." },
    { word: "financial terminology", translation: "terminologie financière", example: "Investment advisors often use financial terminology that confuses their clients." },
    { word: "culinary vocabulary", translation: "vocabulaire culinaire", example: "The recipe used culinary vocabulary like 'julienne' and 'deglaze' without explanation." },
    { word: "architectural terms", translation: "termes architecturaux", example: "The guide described the building using architectural terms like 'flying buttress' and 'fenestration'." },
    { word: "theatrical language", translation: "langage théâtral", example: "Theatrical language includes terms like 'blocking,' 'upstaging,' and 'breaking the fourth wall'." },
    { word: "nautical terminology", translation: "terminologie nautique", example: "Sailors communicate using nautical terminology about 'port,' 'starboard,' and 'fore'." },
    { word: "gaming lexicon", translation: "lexique du jeu vidéo", example: "Online players develop a gaming lexicon including terms like 'spawning,' 'boss fight,' and 'grinding'." },
    { word: "technical jargon", translation: "jargon technique", example: "The manual was full of technical jargon that made it difficult for beginners to understand." },
    { word: "professional parlance", translation: "langage professionnel", example: "Each industry develops its own professional parlance that signals insider status." },
    { word: "specialized terminology", translation: "terminologie spécialisée", example: "Understanding specialized terminology is crucial when entering a new field." },
    { word: "industry-specific language", translation: "langage spécifique à l'industrie", example: "Job descriptions often contain industry-specific language that intimidates outsiders." },
    { word: "insider vocabulary", translation: "vocabulaire d'initié", example: "Learning the insider vocabulary is part of becoming accepted in professional communities." },
    { word: "professional shorthand", translation: "sténographie professionnelle", example: "Medical professionals use professional shorthand in their notes to save time." },
    { word: "field-specific expressions", translation: "expressions spécifiques au domaine", example: "Understanding field-specific expressions is crucial for effective communication between specialists." },
    
    // Jargons professionnels
    { word: "scope creep", translation: "dérive du périmètre", example: "The project manager warned about scope creep as clients requested additional features." },
    { word: "low-hanging fruit", translation: "objectifs faciles à atteindre", example: "Let's focus on the low-hanging fruit first to show quick progress on the initiative." },
    { word: "burn rate", translation: "taux de consommation des ressources", example: "The startup's high burn rate meant they needed another funding round within six months." },
    { word: "mission-critical", translation: "critique pour la mission", example: "The backup system is mission-critical and must function during the upgrade." },
    { word: "deep dive", translation: "analyse approfondie", example: "We'll need to do a deep dive into the customer data to understand the trend." },
    { word: "bandwidth", translation: "capacité disponible", example: "I don't have the bandwidth to take on another project this quarter." },
    { word: "pivot", translation: "pivoter", example: "After the initial product failed, the company decided to pivot toward enterprise solutions." },
    { word: "scalable", translation: "évolutif", example: "We need a more scalable solution as our user base grows exponentially." },
    { word: "circle back", translation: "revenir sur", example: "Let's circle back to that topic after we've reviewed the quarterly results." },
    { word: "deliverable", translation: "livrable", example: "The project timeline lists all expected deliverables and their due dates." },
    { word: "value-add", translation: "valeur ajoutée", example: "The consultant struggled to articulate the value-add of the proposed services." },
    { word: "blue-sky thinking", translation: "réflexion sans contraintes", example: "The innovation workshop encouraged blue-sky thinking without practical limitations." },
    { word: "pain point", translation: "point de douleur", example: "The survey identified customer service as the main pain point in the user experience." },
    { word: "leverage", translation: "tirer parti de", example: "We should leverage our existing client relationships to enter the new market." },
    { word: "onboarding", translation: "intégration", example: "The company improved its onboarding process to help new employees become productive faster." },
    { word: "KPI (Key Performance Indicator)", translation: "indicateur clé de performance", example: "The team's primary KPI is customer retention rate, which improved last quarter." },
    { word: "drill down", translation: "approfondir", example: "Let's drill down into the regional sales figures to understand the discrepancy." },
    { word: "best practice", translation: "meilleure pratique", example: "Following industry best practices will minimize compliance risks." },
    { word: "due diligence", translation: "diligence raisonnable", example: "The investors performed extensive due diligence before committing to the deal." },
    { word: "actionable insights", translation: "perspectives exploitables", example: "The data analysis provided actionable insights for improving campaign performance." },
    { word: "boil the ocean", translation: "entreprendre l'impossible", example: "Let's focus our efforts—we don't need to boil the ocean with this initial phase." },
    { word: "thought leadership", translation: "leadership intellectuel", example: "Publishing the research established the company's thought leadership in cybersecurity." },
    { word: "bleeding edge", translation: "technologie ultramoderne", example: "Their development team works with bleeding edge technologies not yet widely adopted." },
    { word: "agile methodology", translation: "méthodologie agile", example: "The team implemented agile methodology to improve responsiveness to changing requirements." },
    { word: "paradigm shift", translation: "changement de paradigme", example: "Remote work represents a paradigm shift in how companies approach office space." },
    { word: "ballpark figure", translation: "estimation approximative", example: "I need a ballpark figure for the project cost by tomorrow's meeting." },
    { word: "change management", translation: "gestion du changement", example: "Effective change management is crucial when implementing new systems." },
    { word: "value proposition", translation: "proposition de valeur", example: "The marketing team refined the value proposition to clearly communicate product benefits." },
    { word: "customer journey", translation: "parcours client", example: "Mapping the customer journey revealed several opportunities to improve the experience." },
    { word: "disruptive innovation", translation: "innovation disruptive", example: "The company's disruptive innovation completely transformed the traditional industry model." },
    { word: "elevator pitch", translation: "argumentaire éclair", example: "She practiced her elevator pitch before the networking event." },
    { word: "proof of concept", translation: "preuve de concept", example: "The successful proof of concept secured additional funding for full development." },
    { word: "user-centric design", translation: "conception centrée sur l'utilisateur", example: "User-centric design principles guided the app's interface development." },
    { word: "vertical integration", translation: "intégration verticale", example: "The company pursued vertical integration by acquiring its main supplier." },
    { word: "digital transformation", translation: "transformation numérique", example: "The digital transformation initiative modernized outdated paper-based processes." },
    { word: "legacy system", translation: "système hérité", example: "The legacy system's limitations were hindering the company's ability to innovate." },
    { word: "change agent", translation: "agent de changement", example: "She served as a change agent, championing new approaches within the conservative organization." },
    { word: "bottom line", translation: "résultat net", example: "While the initiative improves employee satisfaction, how will it affect the bottom line?" },
    { word: "stakeholder management", translation: "gestion des parties prenantes", example: "Effective stakeholder management was crucial to the project's success." },
    { word: "technical debt", translation: "dette technique", example: "The development team needed time to address mounting technical debt in the codebase." },
    
    // Variations dialectales
    { word: "y'all", translation: "vous tous (dialecte du Sud des États-Unis)", example: "Y'all should come over for dinner sometime next week." },
    { word: "wee", translation: "petit (dialecte écossais)", example: "Just a wee bit more sugar in my tea, please." },
    { word: "aye", translation: "oui (dialecte écossais/nord de l'Angleterre)", example: "Aye, I'll be attending the meeting tomorrow morning." },
    { word: "bloke", translation: "type, mec (dialecte britannique)", example: "He seems like a decent bloke from what I've heard." },
    { word: "kerfuffle", translation: "agitation, remue-ménage (dialecte britannique)", example: "There was quite a kerfuffle when the new policy was announced." },
    { word: "jawn", translation: "chose, truc (dialecte de Philadelphie)", example: "That jawn over there is exactly what I've been looking for." },
    { word: "bairn", translation: "enfant (dialecte écossais)", example: "She's at home looking after the bairns today." },
    { word: "whinge", translation: "se plaindre (dialecte britannique/australien)", example: "He's always whinging about the weather regardless of the season." },
    { word: "wicked", translation: "excellent, super (dialecte de Nouvelle-Angleterre)", example: "That concert last night was wicked awesome." },
    { word: "fair dinkum", translation: "authentique, véritable (dialecte australien)", example: "She's fair dinkum about her commitment to environmental causes." },
    { word: "chuffed", translation: "très content (dialecte britannique)", example: "I'm really chuffed about getting the promotion." },
    { word: "janky", translation: "de mauvaise qualité (dialecte américain)", example: "The software is so janky it crashes every few minutes." },
    { word: "cheers", translation: "merci/au revoir (dialecte britannique)", example: "Cheers for helping me move the furniture yesterday." },
    { word: "skint", translation: "fauché (dialecte britannique)", example: "I'm completely skint until payday next week." },
    { word: "deadly", translation: "excellent (dialecte irlandais)", example: "That was a deadly performance by the band last night." },
    { word: "proper", translation: "très, vraiment (dialecte britannique)", example: "I was proper exhausted after the marathon." },
    { word: "pop", translation: "soda (dialecte du Midwest américain)", example: "Would you like a pop with your sandwich?" },
    { word: "fortnight", translation: "deux semaines (dialecte britannique)", example: "We're going on holiday for a fortnight in July." },
    { word: "dag", translation: "personne amusante/ringarde (dialecte australien)", example: "You're such a dag with those jokes of yours." },
    { word: "bodega", translation: "épicerie de quartier (dialecte new-yorkais)", example: "I'm just going to the bodega to pick up some milk." },
    { word: "chur", translation: "merci/super (dialecte néo-zélandais)", example: "Chur bro, I really appreciate the help." },
    { word: "ken", translation: "savoir (dialecte écossais)", example: "I dinnae ken what time the meeting starts." },
    { word: "soda fountain", translation: "distributeur de soda (dialecte du Sud des États-Unis)", example: "We used to hang out at the soda fountain after school." },
    { word: "buggy", translation: "caddie (dialecte de Pittsburgh)", example: "I need to get a buggy before I start shopping." },
    { word: "bubbler", translation: "fontaine à eau (dialecte du Wisconsin)", example: "There's a bubbler down the hall if you're thirsty." },
    { word: "soaking", translation: "très (dialecte de l'Utah)", example: "That movie was soaking good!" },
    { word: "yinz", translation: "vous tous (dialecte de Pittsburgh)", example: "Are yinz coming to the game on Sunday?" },
    { word: "fixin' to", translation: "s'apprêter à (dialecte du Sud des États-Unis)", example: "I'm fixin' to head out to the store in a few minutes." },
    { word: "give out", translation: "se plaindre (dialecte irlandais)", example: "She was giving out about the poor service at the restaurant." },
    { word: "sanger", translation: "sandwich (dialecte australien)", example: "I packed a vegemite sanger for lunch today." },
    
    // Néologismes
    { word: "doomscrolling", translation: "défilement anxiogène", example: "She realized she'd spent an hour doomscrolling through negative news headlines." },
    { word: "phubbing", translation: "snober par téléphone", example: "Their relationship suffered because of his constant phubbing during their conversations." },
    { word: "hangry", translation: "irritable par faim", example: "I apologized for being short-tempered and explained I was just hangry." },
    { word: "adulting", translation: "se comporter en adulte", example: "I'm exhausted from adulting all week—paying bills, working overtime, and meal prepping." },
    { word: "FOMO", translation: "peur de manquer quelque chose", example: "Despite being tired, FOMO made him accept the party invitation." },
    { word: "ghosting", translation: "disparition soudaine", example: "After three great dates, she experienced ghosting when he stopped responding to messages." },
    { word: "humble-brag", translation: "auto-glorification déguisée", example: "His post about being 'exhausted from all the job offers' was a classic humble-brag." },
    { word: "mansplaining", translation: "explication condescendante masculine", example: "She was frustrated by the mansplaining she encountered at the technical conference." },
    { word: "rage-quit", translation: "abandonner par colère", example: "He rage-quit the game after losing for the third time." },
    { word: "clickbait", translation: "piège à clics", example: "The misleading headline was pure clickbait designed to generate advertising revenue." },
    { word: "bromance", translation: "amitié masculine proche", example: "The two actors developed a bromance while filming the action movie." },
    { word: "webinar", translation: "séminaire en ligne", example: "The company offers free educational webinars to potential customers." },
    { word: "infodemic", translation: "infodémie", example: "The health crisis was accompanied by an infodemic of misinformation on social media." },
    { word: "doxing", translation: "divulgation de données personnelles", example: "The online harassment included doxing that revealed his home address." },
    { word: "fintech", translation: "technologie financière", example: "The fintech startup developed an app that simplifies investment for beginners." },
    { word: "freemium", translation: "service partiellement gratuit", example: "The app uses a freemium model, offering basic features free while charging for advanced capabilities." },
    { word: "crowdfunding", translation: "financement participatif", example: "They launched a crowdfunding campaign to finance their documentary film." },
    { word: "binge-watch", translation: "visionner en rafale", example: "I binge-watched the entire series over the weekend." },
    { word: "upcycling", translation: "surcyclage", example: "The designer specializes in upcycling vintage clothing into modern fashion." },
    { word: "flexitarian", translation: "flexitarien", example: "She describes herself as a flexitarian, primarily eating plant-based foods but occasionally consuming meat." },
    { word: "microaggression", translation: "micro-agression", example: "The workshop addressed common microaggressions in workplace communication." },
    { word: "digital nomad", translation: "nomade numérique", example: "As a digital nomad, she works remotely while traveling around Southeast Asia." },
    { word: "catfishing", translation: "usurpation d'identité en ligne", example: "The documentary explored catfishing techniques used to deceive people on dating apps." },
    { word: "cryptocurrency", translation: "cryptomonnaie", example: "Investors debated the long-term viability of various cryptocurrency options." },
    { word: "deepfake", translation: "hypertrucage", example: "Researchers developed tools to identify deepfake videos created with artificial intelligence." },
    { word: "cancel culture", translation: "culture de l'annulation", example: "The debate examined whether cancel culture discourages open dialogue or promotes accountability." },
    { word: "hustle culture", translation: "culture de l'hyperactivité professionnelle", example: "Younger employees are increasingly rejecting hustle culture and prioritizing work-life balance." },
    { word: "influencer", translation: "influenceur", example: "Brands collaborate with social media influencers to reach targeted audiences." },
    { word: "gig economy", translation: "économie des petits boulots", example: "The gig economy offers flexibility but often lacks traditional employment benefits." },
    { word: "doomism", translation: "catastrophisme", example: "Climate scientists warn against doomism that leads to inaction rather than solutions." }
  ]
};