export const vocab = {
  title: "Médias Internationaux & Communication Globale",
  words: [
    // Systèmes médiatiques comparés
    { word: "media system", translation: "système médiatique", example: "Different media systems reflect varying relationships between government, market, and journalism." },
    { word: "press freedom", translation: "liberté de la presse", example: "The annual report documented declining press freedom in several regions." },
    { word: "public broadcasting", translation: "radiodiffusion publique", example: "Public broadcasting provides an alternative to commercial media in many democracies." },
    { word: "media ownership", translation: "propriété des médias", example: "Media ownership concentration has raised concerns about viewpoint diversity." },
    { word: "regulatory framework", translation: "cadre réglementaire", example: "Each country develops its own regulatory framework governing media operations." },
    { word: "media pluralism", translation: "pluralisme médiatique", example: "Media pluralism ensures diverse perspectives are represented in public discourse." },
    { word: "state-controlled media", translation: "médias contrôlés par l'État", example: "State-controlled media dominate news coverage in authoritarian systems." },
    { word: "commercial media model", translation: "modèle médiatique commercial", example: "The commercial media model depends primarily on advertising revenue." },
    { word: "independent journalism", translation: "journalisme indépendant", example: "Independent journalism faces challenges in systems with limited legal protections." },
    { word: "media market", translation: "marché médiatique", example: "Digitalization has disrupted traditional media markets worldwide." },
    { word: "media policy", translation: "politique médiatique", example: "Media policy balances freedom of expression with other societal values." },
    { word: "journalistic autonomy", translation: "autonomie journalistique", example: "Editorial independence depends on journalistic autonomy from external pressures." },
    { word: "media conglomerate", translation: "conglomérat médiatique", example: "Global media conglomerates operate across multiple countries and platforms." },
    { word: "media accountability", translation: "responsabilité médiatique", example: "Press councils promote media accountability through ethical standards." },
    { word: "fourth estate", translation: "quatrième pouvoir", example: "The press functions as a fourth estate monitoring government activities." },
    { word: "media ecosystem", translation: "écosystème médiatique", example: "Digital platforms have transformed the media ecosystem in most countries." },
    { word: "comparative media studies", translation: "études médiatiques comparées", example: "Comparative media studies examine structural differences across national systems." },
    { word: "media polarization", translation: "polarisation médiatique", example: "Media polarization reflects and reinforces political divisions in society." },
    { word: "liberal media model", translation: "modèle médiatique libéral", example: "The United States exemplifies the liberal media model with limited state intervention." },
    { word: "democratic corporatist model", translation: "modèle corporatiste démocratique", example: "Northern European countries often feature democratic corporatist media models." },
    { word: "polarized pluralist model", translation: "modèle pluraliste polarisé", example: "Mediterranean countries frequently exhibit polarized pluralist media systems." },
    { word: "media concentration", translation: "concentration médiatique", example: "Media concentration limits the diversity of voices in public discourse." },
    { word: "information environment", translation: "environnement informationnel", example: "Each society cultivates a unique information environment shaped by historical factors." },
    { word: "media governance", translation: "gouvernance médiatique", example: "Media governance includes formal regulations and informal professional norms." },
    { word: "cross-ownership", translation: "propriété croisée", example: "Cross-ownership restrictions prevent single entities from controlling multiple media outlets." },
    { word: "media subsidies", translation: "subventions médiatiques", example: "Some governments provide media subsidies to support diverse content production." },
    
    // Analyse du discours médiatique
    { word: "media discourse", translation: "discours médiatique", example: "Media discourse shapes public perceptions of political issues and events." },
    { word: "framing analysis", translation: "analyse de cadrage", example: "Framing analysis examines how news coverage defines problems and suggests solutions." },
    { word: "agenda setting", translation: "établissement de l'agenda", example: "Media organizations engage in agenda setting by determining which issues receive attention." },
    { word: "content analysis", translation: "analyse de contenu", example: "Content analysis methodology quantifies patterns in media coverage." },
    { word: "discourse structure", translation: "structure du discours", example: "News stories follow conventional discourse structures organizing information hierarchically." },
    { word: "narrative analysis", translation: "analyse narrative", example: "Narrative analysis examines the storytelling elements in news coverage." },
    { word: "media representation", translation: "représentation médiatique", example: "The study documented media representation of minority communities in television news." },
    { word: "critical discourse analysis", translation: "analyse critique du discours", example: "Critical discourse analysis explores how media language reinforces power relationships." },
    { word: "rhetorical strategy", translation: "stratégie rhétorique", example: "Politicians employ specific rhetorical strategies when addressing media questions." },
    { word: "discourse community", translation: "communauté de discours", example: "Specialized publications serve particular discourse communities with shared knowledge." },
    { word: "visual framing", translation: "cadrage visuel", example: "Visual framing through image selection influences audience interpretations of events." },
    { word: "discursive construction", translation: "construction discursive", example: "News coverage provides discursive construction of complex social issues." },
    { word: "media bias", translation: "parti pris médiatique", example: "Content analysis identified patterns of media bias in election coverage." },
    { word: "linguistic analysis", translation: "analyse linguistique", example: "Linguistic analysis revealed subtle differences in how media described similar events." },
    { word: "thematic analysis", translation: "analyse thématique", example: "Thematic analysis identified recurring motifs in coverage of the crisis." },
    { word: "ideological positioning", translation: "positionnement idéologique", example: "Editorial choices reflect the ideological positioning of media organizations." },
    { word: "semantic network", translation: "réseau sémantique", example: "The research mapped semantic networks connecting key terms in policy coverage." },
    { word: "discourse markers", translation: "marqueurs de discours", example: "Analysts identified specific discourse markers signaling editorial perspective." },
    { word: "metaphorical framing", translation: "cadrage métaphorique", example: "Metaphorical framing of immigration as a 'flood' influences public perception." },
    { word: "textual analysis", translation: "analyse textuelle", example: "Textual analysis revealed patterns across multiple news sources during the campaign." },
    { word: "discourse dynamics", translation: "dynamique du discours", example: "Research tracks discourse dynamics as media narratives evolve during crises." },
    { word: "interpretive community", translation: "communauté interprétative", example: "Journalists form an interpretive community sharing professional practices and values." },
    { word: "intertextual analysis", translation: "analyse intertextuelle", example: "Intertextual analysis examines how news stories reference and build upon previous coverage." },
    { word: "discursive strategy", translation: "stratégie discursive", example: "Political actors employ discursive strategies to influence media framing of issues." },
    { word: "multimodal analysis", translation: "analyse multimodale", example: "Multimodal analysis considers both textual and visual elements of digital news." },
    { word: "corpus linguistics", translation: "linguistique de corpus", example: "Corpus linguistics applies computational methods to analyze large media datasets." },
    
    // Communication interculturelle
    { word: "intercultural communication", translation: "communication interculturelle", example: "Effective diplomacy depends on skillful intercultural communication." },
    { word: "cultural context", translation: "contexte culturel", example: "Messages are interpreted differently depending on the cultural context." },
    { word: "high-context culture", translation: "culture à contexte fort", example: "Japan represents a high-context culture where much communication is implicit." },
    { word: "low-context culture", translation: "culture à contexte faible", example: "Germanic cultures tend toward low-context communication with explicit messaging." },
    { word: "cultural dimension", translation: "dimension culturelle", example: "Hofstede identified several cultural dimensions including individualism-collectivism." },
    { word: "cultural adaptation", translation: "adaptation culturelle", example: "Successful expatriates develop cultural adaptation strategies for their host country." },
    { word: "cross-cultural competence", translation: "compétence interculturelle", example: "International business requires cross-cultural competence for effective negotiations." },
    { word: "cultural sensitivity", translation: "sensibilité culturelle", example: "The training program aimed to develop cultural sensitivity among diplomatic staff." },
    { word: "non-verbal communication", translation: "communication non verbale", example: "Non-verbal communication patterns vary significantly across cultures." },
    { word: "cultural barrier", translation: "barrière culturelle", example: "Language differences create cultural barriers in international collaboration." },
    { word: "cultural intelligence", translation: "intelligence culturelle", example: "Cultural intelligence enables effective interaction across diverse contexts." },
    { word: "cultural misunderstanding", translation: "malentendu culturel", example: "The diplomatic incident resulted from a cultural misunderstanding regarding protocol." },
    { word: "cultural relativism", translation: "relativisme culturel", example: "Cultural relativism encourages evaluating practices within their appropriate context." },
    { word: "culture shock", translation: "choc culturel", example: "Students studying abroad often experience culture shock during their first months." },
    { word: "ethnocentrism", translation: "ethnocentrisme", example: "Ethnocentrism hinders effective intercultural communication by assuming universal norms." },
    { word: "intercultural dialogue", translation: "dialogue interculturel", example: "The foundation promotes intercultural dialogue through exchange programs." },
    { word: "cultural value orientation", translation: "orientation des valeurs culturelles", example: "Cultural value orientations influence communication styles and expectations." },
    { word: "cultural negotiation", translation: "négociation culturelle", example: "International agreements require cultural negotiation beyond substantive issues." },
    { word: "cosmopolitan communication", translation: "communication cosmopolite", example: "Global media organizations employ cosmopolitan communication addressing diverse audiences." },
    { word: "cultural humility", translation: "humilité culturelle", example: "Cultural humility involves recognizing the limitations of one's cultural perspective." },
    { word: "intercultural mediation", translation: "médiation interculturelle", example: "Translators provide intercultural mediation beyond linguistic conversion." },
    { word: "cultural distance", translation: "distance culturelle", example: "Cultural distance between negotiating parties can complicate reaching agreement." },
    { word: "cross-cultural adaptation", translation: "adaptation interculturelle", example: "The research documented cross-cultural adaptation processes among immigrants." },
    { word: "intercultural relationship", translation: "relation interculturelle", example: "Successful intercultural relationships develop mutual understanding and accommodation." },
    { word: "communication accommodation", translation: "accommodation communicative", example: "Communication accommodation involves adjusting speech patterns to conversation partners." },
    { word: "cultural code", translation: "code culturel", example: "Understanding implicit cultural codes is essential for overseas business success." },
    
    // Diplomatie publique
    { word: "public diplomacy", translation: "diplomatie publique", example: "Public diplomacy efforts target foreign populations rather than just governments." },
    { word: "cultural diplomacy", translation: "diplomatie culturelle", example: "The arts festival represented cultural diplomacy promoting international understanding." },
    { word: "soft power", translation: "puissance douce", example: "Educational exchanges build soft power through personal relationships." },
    { word: "nation branding", translation: "image de marque nationale", example: "Nation branding campaigns aim to improve international perceptions and tourism." },
    { word: "digital diplomacy", translation: "diplomatie numérique", example: "Embassies increasingly employ digital diplomacy through social media platforms." },
    { word: "strategic communication", translation: "communication stratégique", example: "The foreign ministry developed strategic communication addressing regional tensions." },
    { word: "international broadcasting", translation: "radiodiffusion internationale", example: "International broadcasting services provide news and cultural content worldwide." },
    { word: "public opinion", translation: "opinion publique", example: "Diplomatic initiatives consider foreign public opinion beyond governmental relations." },
    { word: "citizen diplomacy", translation: "diplomatie citoyenne", example: "Exchange programs promote citizen diplomacy through personal interactions." },
    { word: "foreign audience", translation: "public étranger", example: "The campaign effectively reached foreign audiences in priority regions." },
    { word: "international image", translation: "image internationale", example: "Hosting international events can enhance a country's international image." },
    { word: "reputation management", translation: "gestion de réputation", example: "Nations engage in reputation management following crises or controversies." },
    { word: "foreign policy narrative", translation: "récit de politique étrangère", example: "Public diplomacy articulates foreign policy narratives for international audiences." },
    { word: "people-to-people diplomacy", translation: "diplomatie interpersonnelle", example: "People-to-people diplomacy builds relationships beyond official channels." },
    { word: "diplomatic outreach", translation: "sensibilisation diplomatique", example: "The embassy conducted diplomatic outreach through community events." },
    { word: "public affairs", translation: "affaires publiques", example: "The public affairs section manages media relations and public engagement." },
    { word: "international exchange", translation: "échange international", example: "Academic international exchange programs promote cross-cultural understanding." },
    { word: "diaspora diplomacy", translation: "diplomatie de diaspora", example: "Countries leverage diaspora diplomacy through emigrant communities abroad." },
    { word: "information campaign", translation: "campagne d'information", example: "The ministry launched an information campaign addressing policy misconceptions." },
    { word: "international dialogue", translation: "dialogue international", example: "The forum promoted international dialogue on shared challenges." },
    { word: "perception management", translation: "gestion de la perception", example: "Nations invest in perception management to improve international standing." },
    { word: "cultural exchange", translation: "échange culturel", example: "The program facilitated cultural exchange through artistic collaborations." },
    { word: "diplomatic messaging", translation: "messagerie diplomatique", example: "Effective diplomatic messaging considers cultural context and sensitivities." },
    { word: "relationship building", translation: "établissement de relations", example: "Public diplomacy focuses on relationship building for long-term influence." },
    { word: "narrative strategy", translation: "stratégie narrative", example: "The diplomatic initiative required a coherent narrative strategy across platforms." },
    { word: "public engagement", translation: "engagement public", example: "The embassy measured public engagement through event attendance and media reach." },
    
    // Nouvelles technologies médiatiques
    { word: "digital platform", translation: "plateforme numérique", example: "Digital platforms have transformed how news content is produced and distributed." },
    { word: "social media network", translation: "réseau de médias sociaux", example: "Each social media network features distinct communication affordances and norms." },
    { word: "mobile journalism", translation: "journalisme mobile", example: "Mobile journalism allows reporters to produce content from remote locations." },
    { word: "algorithm curation", translation: "conservation algorithmique", example: "Algorithm curation influences which news stories reach individual users." },
    { word: "artificial intelligence journalism", translation: "journalisme par intelligence artificielle", example: "Artificial intelligence journalism automates content creation for routine stories." },
    { word: "data visualization", translation: "visualisation de données", example: "Data visualization helps audiences understand complex statistical information." },
    { word: "virtual reality reporting", translation: "reportage en réalité virtuelle", example: "Virtual reality reporting immerses viewers in distant news environments." },
    { word: "livestreaming", translation: "diffusion en direct", example: "Livestreaming allows immediate coverage of developing events." },
    { word: "content personalization", translation: "personnalisation du contenu", example: "Content personalization tailors news feeds to individual preference patterns." },
    { word: "digital storytelling", translation: "narration numérique", example: "Digital storytelling incorporates multimedia elements into journalistic narratives." },
    { word: "news aggregator", translation: "agrégateur de nouvelles", example: "News aggregators compile content from multiple sources into unified interfaces." },
    { word: "citizen journalism", translation: "journalisme citoyen", example: "Smartphone technology enables citizen journalism during breaking news events." },
    { word: "immersive journalism", translation: "journalisme immersif", example: "Immersive journalism allows audiences to experience stories through advanced technologies." },
    { word: "content curation", translation: "conservation de contenu", example: "Media organizations employ content curation to organize information for audiences." },
    { word: "digital paywall", translation: "mur payant numérique", example: "Many news outlets implement digital paywalls to generate subscription revenue." },
    { word: "podcast journalism", translation: "journalisme de podcast", example: "Podcast journalism has revitalized audio storytelling for digital audiences." },
    { word: "native advertising", translation: "publicité native", example: "Native advertising mimics editorial content while promoting commercial messages." },
    { word: "media convergence", translation: "convergence médiatique", example: "Media convergence blurs boundaries between previously distinct communication forms." },
    { word: "transmedia storytelling", translation: "narration transmédiatique", example: "Transmedia storytelling extends narratives across multiple platforms and formats." },
    { word: "news app", translation: "application d'actualités", example: "News apps deliver customized content directly to mobile devices." },
    { word: "engagement metrics", translation: "mesures d'engagement", example: "Digital newsrooms monitor engagement metrics to evaluate content performance." },
    { word: "interactive media", translation: "médias interactifs", example: "Interactive media allows audience participation rather than passive consumption." },
    { word: "distributed content", translation: "contenu distribué", example: "Publishers increasingly rely on distributed content across external platforms." },
    { word: "audience analytics", translation: "analyse d'audience", example: "Audience analytics provide detailed insights into content consumption patterns." },
    { word: "news bot", translation: "robot d'information", example: "News bots automatically generate and distribute updates on specific topics." },
    { word: "augmented reality journalism", translation: "journalisme en réalité augmentée", example: "Augmented reality journalism enhances stories with digital overlays on physical environments." },
    
    // Journalisme d'investigation
    { word: "investigative journalism", translation: "journalisme d'investigation", example: "Investigative journalism requires extended research into hidden or complex topics." },
    { word: "in-depth reporting", translation: "reportage approfondi", example: "In-depth reporting examines issues more thoroughly than daily news coverage." },
    { word: "watchdog journalism", translation: "journalisme de surveillance", example: "Watchdog journalism scrutinizes powerful institutions and individuals." },
    { word: "source protection", translation: "protection des sources", example: "Legal shields for source protection vary significantly between countries." },
    { word: "whistleblower", translation: "lanceur d'alerte", example: "The investigation began with information provided by an anonymous whistleblower." },
    { word: "public interest reporting", translation: "reportage d'intérêt public", example: "Public interest reporting addresses issues with significant societal implications." },
    { word: "document leak", translation: "fuite de documents", example: "The document leak revealed previously unknown government activities." },
    { word: "data journalism", translation: "journalisme de données", example: "Data journalism analyzes large datasets to identify patterns and stories." },
    { word: "forensic reporting", translation: "reportage médico-légal", example: "Forensic reporting reconstructs events through detailed evidence examination." },
    { word: "accountability journalism", translation: "journalisme de responsabilisation", example: "Accountability journalism holds powerful entities responsible for their actions." },
    { word: "cross-border investigation", translation: "enquête transfrontalière", example: "The financial scandal required cross-border investigation by reporter networks." },
    { word: "follow-the-money reporting", translation: "reportage en suivant l'argent", example: "Follow-the-money reporting traces financial connections between entities." },
    { word: "open-source investigation", translation: "enquête à source ouverte", example: "Open-source investigation analyzes publicly available digital information." },
    { word: "undercover reporting", translation: "reportage sous couverture", example: "Undercover reporting raises ethical questions despite exposing hidden abuses." },
    { word: "muckraking", translation: "journalisme d'investigation", example: "Early muckraking journalists exposed corruption in government and business." },
    { word: "freedom of information", translation: "liberté d'information", example: "The investigation utilized freedom of information requests to access records." },
    { word: "adversarial reporting", translation: "reportage contradictoire", example: "Adversarial reporting challenges official narratives with independent evidence." },
    { word: "exposé", translation: "exposé", example: "The newspaper published a three-part exposé on healthcare fraud." },
    { word: "public records research", translation: "recherche dans les registres publics", example: "Public records research revealed inconsistencies in the official account." },
    { word: "enterprise reporting", translation: "reportage d'initiative", example: "Enterprise reporting goes beyond coverage of scheduled events and announcements." },
    { word: "long-form journalism", translation: "journalisme long format", example: "Long-form journalism provides space for complex narrative development." },
    { word: "corruption investigation", translation: "enquête sur la corruption", example: "The corruption investigation implicated officials at multiple government levels." },
    { word: "editorial independence", translation: "indépendance éditoriale", example: "Editorial independence protects investigative functions from external pressure." },
    { word: "evidence-based reporting", translation: "reportage fondé sur des preuves", example: "Evidence-based reporting requires verification through multiple sources." },
    { word: "high-impact journalism", translation: "journalisme à fort impact", example: "High-impact journalism drives policy change and public awareness." },
    
    // Influence médiatique
    { word: "media influence", translation: "influence médiatique", example: "Research examines media influence on public opinion formation." },
    { word: "agenda setting", translation: "établissement de l'agenda", example: "News coverage exhibits agenda setting effects by determining which issues receive attention." },
    { word: "information flow", translation: "flux d'information", example: "Global information flow remains uneven between regions and countries." },
    { word: "public sphere", translation: "sphère publique", example: "Digital media has transformed the structure of the public sphere." },
    { word: "media effect", translation: "effet médiatique", example: "Researchers debate the extent and nature of media effects on audience attitudes." },
    { word: "opinion leader", translation: "leader d'opinion", example: "Opinion leaders amplify messages across their social networks." },
    { word: "media dependency", translation: "dépendance médiatique", example: "Media dependency increases during crisis situations and breaking news." },
    { word: "persuasive communication", translation: "communication persuasive", example: "Political campaigns employ persuasive communication techniques across media channels." },
    { word: "cultivation theory", translation: "théorie de la cultivation", example: "Cultivation theory examines how media exposure shapes perceptions of social reality." },
    { word: "spiral of silence", translation: "spirale du silence", example: "The spiral of silence theory explains how perceived public opinion affects expression." },
    { word: "framing effect", translation: "effet de cadrage", example: "Framing effects influence how audiences interpret and remember news information." },
    { word: "gatekeeping", translation: "contrôle d'accès", example: "Editorial gatekeeping determines which stories reach public attention." },
    { word: "information disorder", translation: "désordre informationnel", example: "Researchers categorize information disorder into misinformation, disinformation, and malinformation." },
    { word: "media literacy", translation: "littératie médiatique", example: "Media literacy education helps audiences critically evaluate news content." },
    { word: "echo chamber", translation: "chambre d'écho", example: "Digital media can create echo chambers where users encounter only confirming viewpoints." },
    { word: "filter bubble", translation: "bulle de filtre", example: "Algorithmic curation creates filter bubbles that limit exposure to diverse perspectives." },
    { word: "attention economy", translation: "économie de l'attention", example: "Media organizations compete within an attention economy for audience engagement." },
    { word: "viral content", translation: "contenu viral", example: "Emotional triggers often characterize viral content that spreads rapidly online." },
    { word: "propaganda", translation: "propagande", example: "Digital propaganda techniques have evolved with communication technologies." },
    { word: "media manipulation", translation: "manipulation médiatique", example: "Media manipulation techniques exploit journalistic practices and platform vulnerabilities." },
    { word: "cognitive bias", translation: "biais cognitif", example: "Media literacy addresses how cognitive biases affect information processing." },
    { word: "information cascade", translation: "cascade d'information", example: "Social media can produce information cascades where beliefs spread rapidly." },
    { word: "narrative persuasion", translation: "persuasion narrative", example: "Narrative persuasion can be more effective than explicit argumentation." },
    { word: "selective exposure", translation: "exposition sélective", example: "Individuals practice selective exposure by choosing information matching existing beliefs." },
    { word: "two-step flow", translation: "flux à deux étapes", example: "The two-step flow theory describes how information moves from media through opinion leaders." }
  ]
};