export const vocab = {
  title: "Technologies Émergentes",
  words: [
    // Intelligence artificielle (25 mots)
    { word: "artificial intelligence", translation: "intelligence artificielle", example: "Artificial intelligence systems can recognize patterns and make decisions with minimal human intervention." },
    { word: "machine learning", translation: "apprentissage automatique", example: "Machine learning algorithms improve performance with experience without explicit programming." },
    { word: "deep learning", translation: "apprentissage profond", example: "Deep learning models use neural networks with multiple layers to process complex data." },
    { word: "neural network", translation: "réseau neuronal", example: "The neural network identified cancer cells with greater accuracy than human pathologists." },
    { word: "natural language processing", translation: "traitement du langage naturel", example: "Natural language processing enables computers to understand and generate human language." },
    { word: "computer vision", translation: "vision par ordinateur", example: "Computer vision systems interpret and analyze visual information from the world." },
    { word: "reinforcement learning", translation: "apprentissage par renforcement", example: "Reinforcement learning agents learn optimal behaviors through trial and error." },
    { word: "supervised learning", translation: "apprentissage supervisé", example: "Supervised learning algorithms are trained on labeled examples to make predictions." },
    { word: "unsupervised learning", translation: "apprentissage non supervisé", example: "Unsupervised learning discovers patterns in data without predefined categories." },
    { word: "generative AI", translation: "IA générative", example: "Generative AI creates new content, from images to text, based on training examples." },
    { word: "cognitive computing", translation: "informatique cognitive", example: "Cognitive computing systems mimic human thought processes to solve complex problems." },
    { word: "AI ethics", translation: "éthique de l'IA", example: "AI ethics addresses questions of fairness, transparency, and accountability in intelligent systems." },
    { word: "autonomous system", translation: "système autonome", example: "Autonomous systems operate independently without direct human control." },
    { word: "algorithmic bias", translation: "biais algorithmique", example: "Algorithmic bias occurs when systems make unfair decisions due to flawed training data." },
    { word: "explainable AI", translation: "IA explicable", example: "Explainable AI provides transparency into how algorithms reach specific conclusions." },
    { word: "facial recognition", translation: "reconnaissance faciale", example: "Facial recognition technology identifies individuals based on facial features." },
    { word: "predictive analytics", translation: "analyse prédictive", example: "Predictive analytics forecasts future outcomes based on historical data patterns." },
    { word: "recommendation system", translation: "système de recommandation", example: "Recommendation systems suggest products or content based on user preferences." },
    { word: "sentiment analysis", translation: "analyse de sentiment", example: "Sentiment analysis determines emotional tone in text communications." },
    { word: "federated learning", translation: "apprentissage fédéré", example: "Federated learning trains algorithms across devices without centralizing sensitive data." },
    { word: "transfer learning", translation: "apprentissage par transfert", example: "Transfer learning applies knowledge from one domain to improve performance in another." },
    { word: "decision support system", translation: "système d'aide à la décision", example: "The decision support system provided treatment recommendations based on patient data." },
    { word: "edge AI", translation: "IA en périphérie", example: "Edge AI processes data locally on devices rather than in cloud data centers." },
    { word: "computer reasoning", translation: "raisonnement informatique", example: "Computer reasoning systems make logical inferences from available information." },
    { word: "autonomous agent", translation: "agent autonome", example: "Autonomous agents interact with environments to achieve specified goals." },
    
    // Robotique et automatisation (25 mots)
    { word: "robotics", translation: "robotique", example: "Robotics combines engineering and computer science to create machines that perform tasks." },
    { word: "autonomous robot", translation: "robot autonome", example: "Autonomous robots navigate environments and make decisions without human control." },
    { word: "collaborative robot", translation: "robot collaboratif", example: "Collaborative robots work alongside humans in shared workspaces." },
    { word: "industrial automation", translation: "automatisation industrielle", example: "Industrial automation systems perform manufacturing processes with minimal human intervention." },
    { word: "robotic process automation", translation: "automatisation robotisée des processus", example: "Robotic process automation software handles repetitive digital tasks." },
    { word: "swarm robotics", translation: "robotique en essaim", example: "Swarm robotics coordinates multiple simple robots to perform complex tasks." },
    { word: "human-robot interaction", translation: "interaction homme-robot", example: "Human-robot interaction studies how people engage with robotic systems." },
    { word: "actuator", translation: "actionneur", example: "Actuators convert control signals into physical movement in robotic systems." },
    { word: "robotic manipulation", translation: "manipulation robotique", example: "Robotic manipulation involves gripping, moving, and modifying objects." },
    { word: "locomotion system", translation: "système de locomotion", example: "The robot's locomotion system enables movement across varied terrain." },
    { word: "automation technology", translation: "technologie d'automatisation", example: "Automation technology replaces manual processes with software-controlled systems." },
    { word: "humanoid robot", translation: "robot humanoïde", example: "Humanoid robots feature physical structures resembling human bodies." },
    { word: "autonomous vehicle", translation: "véhicule autonome", example: "Autonomous vehicles navigate roadways without human drivers." },
    { word: "industrial robot", translation: "robot industriel", example: "Industrial robots perform precise, repetitive tasks in manufacturing environments." },
    { word: "service robot", translation: "robot de service", example: "Service robots assist humans in commercial and domestic settings." },
    { word: "drone technology", translation: "technologie des drones", example: "Drone technology enables aerial monitoring, delivery, and imaging applications." },
    { word: "robot sensor", translation: "capteur robotique", example: "Robot sensors gather environmental data for navigation and interaction." },
    { word: "robotic arm", translation: "bras robotique", example: "The robotic arm performed precise assembly operations on the production line." },
    { word: "autonomous navigation", translation: "navigation autonome", example: "Autonomous navigation systems plan and execute movement paths independently." },
    { word: "smart automation", translation: "automatisation intelligente", example: "Smart automation systems adapt processes based on changing conditions." },
    { word: "robotic exoskeleton", translation: "exosquelette robotique", example: "Robotic exoskeletons enhance human strength and endurance." },
    { word: "path planning", translation: "planification de trajectoire", example: "Path planning algorithms determine optimal routes through environments." },
    { word: "autonomous system", translation: "système autonome", example: "Autonomous systems function without direct human intervention." },
    { word: "robot programming", translation: "programmation robotique", example: "Robot programming defines behaviors and responses to environmental conditions." },
    { word: "telepresence robot", translation: "robot de téléprésence", example: "Telepresence robots enable remote interaction with distant environments." },
    
    // Biotechnologie et sciences médicales (25 mots)
    { word: "biotechnology", translation: "biotechnologie", example: "Biotechnology applies biological systems to develop medical treatments and agricultural products." },
    { word: "genetic engineering", translation: "génie génétique", example: "Genetic engineering modifies DNA to produce organisms with desired traits." },
    { word: "CRISPR technology", translation: "technologie CRISPR", example: "CRISPR technology enables precise editing of genetic sequences." },
    { word: "genomics", translation: "génomique", example: "Genomics studies the structure, function, and mapping of complete genetic material." },
    { word: "bioinformatics", translation: "bio-informatique", example: "Bioinformatics applies computational methods to analyze biological data." },
    { word: "precision medicine", translation: "médecine de précision", example: "Precision medicine tailors treatments to individual genetic profiles." },
    { word: "regenerative medicine", translation: "médecine régénératrice", example: "Regenerative medicine develops methods to replace damaged tissues and organs." },
    { word: "stem cell therapy", translation: "thérapie par cellules souches", example: "Stem cell therapy uses undifferentiated cells to treat or prevent diseases." },
    { word: "gene therapy", translation: "thérapie génique", example: "Gene therapy introduces genetic material to treat or prevent disease." },
    { word: "synthetic biology", translation: "biologie synthétique", example: "Synthetic biology redesigns organisms for useful purposes not found in nature." },
    { word: "bioprinting", translation: "bio-impression", example: "Bioprinting creates tissue structures through layer-by-layer deposition of cells." },
    { word: "nanomedicine", translation: "nanomédecine", example: "Nanomedicine applies nanotechnology to diagnosis and treatment of disease." },
    { word: "medical imaging", translation: "imagerie médicale", example: "Advanced medical imaging techniques provide detailed views of internal structures." },
    { word: "telemedicine", translation: "télémédecine", example: "Telemedicine delivers healthcare services remotely using telecommunications technology." },
    { word: "wearable health monitor", translation: "moniteur de santé portable", example: "Wearable health monitors track vital signs and physical activity continuously." },
    { word: "biopharmaceutical", translation: "biopharmaceutique", example: "Biopharmaceuticals are medical drugs produced using biotechnology." },
    { word: "immunotherapy", translation: "immunothérapie", example: "Immunotherapy enhances the body's immune response against diseases." },
    { word: "molecular diagnostics", translation: "diagnostic moléculaire", example: "Molecular diagnostics identifies disease by detecting specific genetic sequences." },
    { word: "personalized medicine", translation: "médecine personnalisée", example: "Personalized medicine tailors healthcare to individual characteristics." },
    { word: "digital therapeutics", translation: "thérapeutiques numériques", example: "Digital therapeutics deliver medical interventions through software applications." },
    { word: "bioengineering", translation: "bio-ingénierie", example: "Bioengineering applies engineering principles to biological systems and healthcare." },
    { word: "microbiome", translation: "microbiome", example: "Research on the microbiome examines how microbial communities affect health." },
    { word: "drug delivery system", translation: "système d'administration de médicaments", example: "Advanced drug delivery systems target specific tissues while minimizing side effects." },
    { word: "computational biology", translation: "biologie computationnelle", example: "Computational biology simulates biological processes to accelerate research." },
    { word: "biomarker", translation: "biomarqueur", example: "Biomarkers indicate normal biological processes, pathogenic processes, or responses to treatments." },
    
    // Informatique quantique (25 mots)
    { word: "quantum computing", translation: "informatique quantique", example: "Quantum computing leverages quantum mechanics to process information in novel ways." },
    { word: "quantum bit", translation: "bit quantique", example: "Quantum bits or qubits can exist in multiple states simultaneously unlike classical bits." },
    { word: "quantum superposition", translation: "superposition quantique", example: "Quantum superposition allows particles to exist in multiple states at once." },
    { word: "quantum entanglement", translation: "intrication quantique", example: "Quantum entanglement creates correlations between particles regardless of distance." },
    { word: "quantum supremacy", translation: "suprématie quantique", example: "Quantum supremacy occurs when quantum computers solve problems beyond classical capabilities." },
    { word: "quantum algorithm", translation: "algorithme quantique", example: "Quantum algorithms exploit quantum effects to solve specific problems efficiently." },
    { word: "quantum error correction", translation: "correction d'erreur quantique", example: "Quantum error correction protects quantum information from environmental interference." },
    { word: "quantum gate", translation: "porte quantique", example: "Quantum gates are the basic quantum circuit operations on qubits." },
    { word: "quantum annealing", translation: "recuit quantique", example: "Quantum annealing finds optimal solutions to problems by exploiting quantum fluctuations." },
    { word: "quantum advantage", translation: "avantage quantique", example: "Quantum advantage describes when quantum computers outperform classical systems." },
    { word: "quantum processor", translation: "processeur quantique", example: "The quantum processor maintained coherence long enough to complete the calculation." },
    { word: "quantum coherence", translation: "cohérence quantique", example: "Quantum coherence allows quantum systems to exist in multiple states simultaneously." },
    { word: "quantum simulation", translation: "simulation quantique", example: "Quantum simulation models quantum systems that are difficult to study directly." },
    { word: "quantum cryptography", translation: "cryptographie quantique", example: "Quantum cryptography provides secure communication protected by quantum mechanics." },
    { word: "quantum internet", translation: "internet quantique", example: "The quantum internet will connect quantum processors using entangled particles." },
    { word: "quantum compiler", translation: "compilateur quantique", example: "Quantum compilers transform algorithms into executable quantum circuit instructions." },
    { word: "quantum decoherence", translation: "décohérence quantique", example: "Quantum decoherence refers to the loss of quantum behavior due to environmental interaction." },
    { word: "quantum teleportation", translation: "téléportation quantique", example: "Quantum teleportation transfers quantum states between distant locations using entanglement." },
    { word: "quantum sensor", translation: "capteur quantique", example: "Quantum sensors detect minute changes in electromagnetic fields, gravity, or time." },
    { word: "quantum logic gate", translation: "porte logique quantique", example: "Quantum logic gates transform quantum states in defined ways." },
    { word: "quantum information", translation: "information quantique", example: "Quantum information theory extends classical information theory to quantum systems." },
    { word: "quantum machine learning", translation: "apprentissage automatique quantique", example: "Quantum machine learning applies quantum algorithms to improve pattern recognition." },
    { word: "quantum phase", translation: "phase quantique", example: "The quantum phase encodes information critical to the computation process." },
    { word: "quantum memory", translation: "mémoire quantique", example: "Quantum memory stores quantum information for later retrieval." },
    { word: "quantum programming", translation: "programmation quantique", example: "Quantum programming requires new paradigms distinct from classical computing." },
    
    // Réalité virtuelle et augmentée (25 mots)
    { word: "virtual reality", translation: "réalité virtuelle", example: "Virtual reality immerses users in computer-generated environments." },
    { word: "augmented reality", translation: "réalité augmentée", example: "Augmented reality overlays digital information onto the physical world." },
    { word: "mixed reality", translation: "réalité mixte", example: "Mixed reality blends physical and digital environments for interactive experiences." },
    { word: "immersive technology", translation: "technologie immersive", example: "Immersive technologies create sensory experiences that alter perception of environments." },
    { word: "head-mounted display", translation: "visiocasque", example: "The head-mounted display tracked eye movements to adjust rendered perspectives." },
    { word: "spatial computing", translation: "informatique spatiale", example: "Spatial computing integrates digital content with physical spaces." },
    { word: "haptic feedback", translation: "retour haptique", example: "Haptic feedback provides tactile sensations in virtual environments." },
    { word: "motion tracking", translation: "suivi de mouvement", example: "Motion tracking systems capture and translate physical movements into digital actions." },
    { word: "virtual environment", translation: "environnement virtuel", example: "The virtual environment simulated complex scenarios for training purposes." },
    { word: "digital twin", translation: "jumeau numérique", example: "Digital twins create virtual replicas of physical objects or processes." },
    { word: "AR overlay", translation: "superposition en RA", example: "The AR overlay displayed real-time information about nearby landmarks." },
    { word: "VR headset", translation: "casque de RV", example: "The VR headset delivered high-resolution visuals with minimal latency." },
    { word: "spatial awareness", translation: "conscience spatiale", example: "Spatial awareness enables devices to understand physical surroundings." },
    { word: "photogrammetry", translation: "photogrammétrie", example: "Photogrammetry creates 3D models from multiple 2D photographs." },
    { word: "visual rendering", translation: "rendu visuel", example: "Advanced visual rendering creates photorealistic virtual environments." },
    { word: "extended reality", translation: "réalité étendue", example: "Extended reality encompasses virtual, augmented, and mixed reality technologies." },
    { word: "field of view", translation: "champ de vision", example: "A wider field of view increases immersion in virtual environments." },
    { word: "positional tracking", translation: "suivi de position", example: "Positional tracking monitors the user's location within physical space." },
    { word: "AR glasses", translation: "lunettes de RA", example: "AR glasses display contextual information without obstructing normal vision." },
    { word: "volumetric capture", translation: "capture volumétrique", example: "Volumetric capture records three-dimensional representations of people and objects." },
    { word: "spatial mapping", translation: "cartographie spatiale", example: "Spatial mapping creates digital representations of physical environments." },
    { word: "AR cloud", translation: "nuage de RA", example: "The AR cloud provides persistent digital content anchored to physical locations." },
    { word: "gesture recognition", translation: "reconnaissance gestuelle", example: "Gesture recognition interprets hand movements as control inputs." },
    { word: "immersive learning", translation: "apprentissage immersif", example: "Immersive learning uses virtual environments for educational experiences." },
    { word: "virtual collaboration", translation: "collaboration virtuelle", example: "Virtual collaboration tools connect remote teams in shared digital spaces." },
    
    // Internet des objets (25 mots)
    { word: "Internet of Things", translation: "Internet des objets", example: "The Internet of Things connects everyday objects to networks for data exchange." },
    { word: "connected device", translation: "appareil connecté", example: "Connected devices communicate with each other and central systems." },
    { word: "smart sensor", translation: "capteur intelligent", example: "Smart sensors collect and transmit environmental data for analysis." },
    { word: "IoT platform", translation: "plateforme IdO", example: "IoT platforms manage device connectivity, data collection, and application development." },
    { word: "edge computing", translation: "informatique en périphérie", example: "Edge computing processes data near its source rather than in centralized locations." },
    { word: "device provisioning", translation: "provisionnement d'appareils", example: "Device provisioning configures new IoT devices for secure network integration." },
    { word: "smart home", translation: "maison intelligente", example: "Smart home systems automate lighting, climate control, and security functions." },
    { word: "industrial IoT", translation: "IdO industriel", example: "Industrial IoT applications monitor equipment performance and predict maintenance needs." },
    { word: "IoT gateway", translation: "passerelle IdO", example: "IoT gateways connect sensor networks to the internet and manage data transmission." },
    { word: "device authentication", translation: "authentification d'appareil", example: "Device authentication ensures only authorized devices connect to IoT networks." },
    { word: "smart city", translation: "ville intelligente", example: "Smart city initiatives use IoT sensors to improve urban services and quality of life." },
    { word: "mesh network", translation: "réseau maillé", example: "Mesh networks provide reliable communication paths between IoT devices." },
    { word: "predictive maintenance", translation: "maintenance prédictive", example: "Predictive maintenance uses IoT data to identify equipment issues before failures occur." },
    { word: "wearable technology", translation: "technologie portable", example: "Wearable technology includes fitness trackers, smartwatches, and health monitors." },
    { word: "IoT analytics", translation: "analytique de l'IdO", example: "IoT analytics processes device data to extract actionable insights." },
    { word: "device management", translation: "gestion d'appareils", example: "Device management platforms monitor and update connected devices remotely." },
    { word: "low-power wide-area network", translation: "réseau étendu à faible consommation", example: "Low-power wide-area networks support long-range IoT communications efficiently." },
    { word: "digital twin", translation: "jumeau numérique", example: "Digital twins create virtual models of physical objects with real-time data." },
    { word: "smart agriculture", translation: "agriculture intelligente", example: "Smart agriculture uses IoT sensors to optimize irrigation and monitor crop health." },
    { word: "asset tracking", translation: "suivi des actifs", example: "Asset tracking systems monitor location and condition of equipment and inventory." },
    { word: "IoT security", translation: "sécurité de l'IdO", example: "IoT security protects connected devices and their data from unauthorized access." },
    { word: "smart grid", translation: "réseau électrique intelligent", example: "Smart grids use IoT technology to manage energy distribution efficiently." },
    { word: "device interoperability", translation: "interopérabilité des appareils", example: "Device interoperability allows products from different manufacturers to work together." },
    { word: "environmental monitoring", translation: "surveillance environnementale", example: "Environmental monitoring applications track air quality, water levels, and weather conditions." },
    { word: "remote diagnostics", translation: "diagnostics à distance", example: "Remote diagnostics assess equipment status without on-site inspections." },
    
    // Blockchain et technologies distribuées (25 mots)
    { word: "blockchain technology", translation: "technologie blockchain", example: "Blockchain technology creates tamper-resistant records across distributed systems." },
    { word: "distributed ledger", translation: "registre distribué", example: "Distributed ledgers maintain synchronized data across multiple locations." },
    { word: "smart contract", translation: "contrat intelligent", example: "Smart contracts execute agreements automatically when predefined conditions are met." },
    { word: "decentralized application", translation: "application décentralisée", example: "Decentralized applications operate on distributed networks rather than central servers." },
    { word: "consensus mechanism", translation: "mécanisme de consensus", example: "Consensus mechanisms determine how blockchain participants agree on valid transactions." },
    { word: "proof of work", translation: "preuve de travail", example: "Proof of work requires computational effort to validate blockchain transactions." },
    { word: "proof of stake", translation: "preuve d'enjeu", example: "Proof of stake validates transactions based on the quantity of cryptocurrency held." },
    { word: "cryptocurrency", translation: "cryptomonnaie", example: "Cryptocurrencies are digital assets secured by cryptography and blockchain." },
    { word: "tokenization", translation: "tokenisation", example: "Tokenization converts rights to assets into digital tokens on blockchains." },
    { word: "decentralized finance", translation: "finance décentralisée", example: "Decentralized finance applications provide financial services without central authorities." },
    { word: "digital wallet", translation: "portefeuille numérique", example: "Digital wallets store cryptographic keys for blockchain transactions." },
    { word: "hash function", translation: "fonction de hachage", example: "Hash functions create fixed-size outputs from variable-size inputs in blockchain systems." },
    { word: "peer-to-peer network", translation: "réseau pair à pair", example: "Blockchain operates on peer-to-peer networks without central coordination." },
    { word: "private blockchain", translation: "blockchain privée", example: "Private blockchains restrict participation to authorized entities." },
    { word: "public blockchain", translation: "blockchain publique", example: "Public blockchains allow anyone to participate in the network." },
    { word: "blockchain governance", translation: "gouvernance de blockchain", example: "Blockchain governance determines how protocols evolve and decisions are made." },
    { word: "immutable record", translation: "registre immuable", example: "Blockchains create immutable records that cannot be altered retroactively." },
    { word: "distributed application", translation: "application distribuée", example: "Distributed applications operate across multiple computing resources." },
    { word: "digital signature", translation: "signature numérique", example: "Digital signatures verify identity and authenticity in blockchain transactions." },
    { word: "blockchain oracle", translation: "oracle blockchain", example: "Blockchain oracles connect smart contracts with external data sources." },
    { word: "non-fungible token", translation: "jeton non fongible", example: "Non-fungible tokens represent unique digital assets on blockchains." },
    { word: "interoperability", translation: "interopérabilité", example: "Blockchain interoperability enables different networks to exchange information." },
    { word: "sidechain", translation: "chaîne latérale", example: "Sidechains are separate blockchains connected to parent chains for specific functions." },
    { word: "cryptographic hash", translation: "hachage cryptographique", example: "Cryptographic hashes provide data integrity verification in blockchain systems." },
    { word: "distributed consensus", translation: "consensus distribué", example: "Distributed consensus ensures agreement across decentralized systems." },
    
    // Cybersécurité avancée (25 mots)
    { word: "cybersecurity", translation: "cybersécurité", example: "Cybersecurity protects systems, networks, and programs from digital attacks." },
    { word: "advanced persistent threat", translation: "menace persistante avancée", example: "Advanced persistent threats involve sophisticated, long-term attacks by skilled adversaries." },
    { word: "zero-day vulnerability", translation: "vulnérabilité zero-day", example: "Zero-day vulnerabilities are software weaknesses unknown to vendors or patch developers." },
    { word: "ransomware", translation: "rançongiciel", example: "Ransomware encrypts victim data and demands payment for decryption keys." },
    { word: "endpoint security", translation: "sécurité des terminaux", example: "Endpoint security protects networks when accessed via remote devices." },
    { word: "security information and event management", translation: "gestion des informations et des événements de sécurité", example: "Security information and event management systems analyze security alerts in real-time." },
    { word: "penetration testing", translation: "test d'intrusion", example: "Penetration testing evaluates system security by simulating attacks." },
    { word: "threat intelligence", translation: "renseignement sur les menaces", example: "Threat intelligence provides information about current and emerging cyberthreats." },
    { word: "zero trust security", translation: "sécurité zéro confiance", example: "Zero trust security requires verification for all users, regardless of location." },
    { word: "security operations center", translation: "centre des opérations de sécurité", example: "Security operations centers monitor and analyze an organization's security posture." },
    { word: "vulnerability management", translation: "gestion des vulnérabilités", example: "Vulnerability management identifies and remedies security weaknesses." },
    { word: "intrusion detection", translation: "détection d'intrusion", example: "Intrusion detection systems identify unauthorized access attempts." },
    { word: "security orchestration", translation: "orchestration de sécurité", example: "Security orchestration automates security tools and incident response." },
    { word: "cyber threat hunting", translation: "chasse aux cybermenaces", example: "Cyber threat hunting proactively searches for hidden adversaries within networks." },
    { word: "attack surface", translation: "surface d'attaque", example: "Attack surface refers to all points where unauthorized users could access systems." },
    { word: "secure access service edge", translation: "périmètre de service d'accès sécurisé", example: "Secure access service edge combines network security functions with wide area network capabilities." },
    { word: "security posture", translation: "posture de sécurité", example: "Security posture describes an organization's overall cybersecurity strength." },
    { word: "red team assessment", translation: "évaluation par équipe rouge", example: "Red team assessments simulate real-world attacks to test defenses." },
    { word: "phishing simulation", translation: "simulation de hameçonnage", example: "Phishing simulations test employee awareness of social engineering tactics." },
    { word: "incident response", translation: "réponse aux incidents", example: "Incident response plans establish procedures for addressing security breaches." },
    { word: "secure development lifecycle", translation: "cycle de développement sécurisé", example: "Secure development lifecycle integrates security practices throughout software creation." },
    { word: "data loss prevention", translation: "prévention des pertes de données", example: "Data loss prevention tools identify and block unauthorized data transfers." },
    { word: "security automation", translation: "automatisation de la sécurité", example: "Security automation reduces manual effort in threat detection and response." },
    { word: "security compliance", translation: "conformité de sécurité", example: "Security compliance ensures adherence to regulatory and policy requirements." },
    { word: "deception technology", translation: "technologie de leurre", example: "Deception technology deploys decoys to detect and analyze attack methods." },
    
    // Cloud computing avancé (25 mots)
    { word: "cloud computing", translation: "informatique en nuage", example: "Cloud computing delivers computing services over the internet on demand." },
    { word: "multi-cloud strategy", translation: "stratégie multi-cloud", example: "Multi-cloud strategies distribute workloads across multiple cloud providers." },
    { word: "cloud-native application", translation: "application cloud-native", example: "Cloud-native applications are designed specifically for cloud environments." },
    { word: "infrastructure as code", translation: "infrastructure en tant que code", example: "Infrastructure as code manages computing resources through machine-readable definition files." },
    { word: "serverless computing", translation: "informatique sans serveur", example: "Serverless computing executes code without provisioning specific servers." },
    { word: "containerization", translation: "conteneurisation", example: "Containerization packages applications with dependencies for consistent deployment." },
    { word: "microservices architecture", translation: "architecture de microservices", example: "Microservices architecture structures applications as independent, loosely coupled services." },
    { word: "cloud orchestration", translation: "orchestration cloud", example: "Cloud orchestration automates arrangement, coordination, and management of complex services." },
    { word: "service mesh", translation: "maillage de services", example: "Service mesh manages communication between microservices in distributed applications." },
    { word: "cloud security posture management", translation: "gestion de la posture de sécurité cloud", example: "Cloud security posture management identifies and remedies cloud configuration risks." },
    { word: "hybrid cloud", translation: "cloud hybride", example: "Hybrid cloud environments combine private and public cloud resources." },
    { word: "cloud migration", translation: "migration vers le cloud", example: "Cloud migration transfers applications and data from on-premises systems to cloud platforms." },
    { word: "cloud optimization", translation: "optimisation cloud", example: "Cloud optimization maximizes performance while minimizing costs in cloud environments." },
    { word: "auto-scaling", translation: "mise à l'échelle automatique", example: "Auto-scaling adjusts resources automatically based on application demand." },
    { word: "cloud governance", translation: "gouvernance cloud", example: "Cloud governance establishes policies for efficient, secure cloud resource usage." },
    { word: "DevOps", translation: "DevOps", example: "DevOps practices integrate development and operations teams for faster delivery." },
    { word: "continuous integration", translation: "intégration continue", example: "Continuous integration automatically verifies code changes through building and testing." },
    { word: "continuous deployment", translation: "déploiement continu", example: "Continuous deployment automatically releases validated code to production environments." },
    { word: "platform as a service", translation: "plateforme en tant que service", example: "Platform as a service provides development and deployment environments in the cloud." },
    { word: "software as a service", translation: "logiciel en tant que service", example: "Software as a service delivers applications over the internet on a subscription basis." },
    { word: "container orchestration", translation: "orchestration de conteneurs", example: "Container orchestration tools automate deployment and management of containerized applications." },
    { word: "FinOps", translation: "FinOps", example: "FinOps aligns technology, finance, and business for cloud financial management." },
    { word: "cloud compliance", translation: "conformité cloud", example: "Cloud compliance ensures cloud services meet regulatory requirements." },
    { word: "edge cloud", translation: "cloud en périphérie", example: "Edge cloud distributes computing resources closer to data sources." },
    { word: "API gateway", translation: "passerelle d'API", example: "API gateways manage, secure, and optimize application programming interfaces." },
    
    // Technologie 5G et communications (25 mots)
    { word: "5G technology", translation: "technologie 5G", example: "5G technology provides faster speeds and lower latency than previous cellular networks." },
    { word: "network slicing", translation: "découpage de réseau", example: "Network slicing creates multiple virtual networks on shared physical infrastructure." },
    { word: "massive MIMO", translation: "MIMO massif", example: "Massive MIMO uses multiple antennas to improve network capacity and efficiency." },
    { word: "millimeter wave spectrum", translation: "spectre d'ondes millimétriques", example: "Millimeter wave spectrum enables ultra-high-speed short-range 5G communications." },
    { word: "beamforming", translation: "formation de faisceaux", example: "Beamforming focuses wireless signals toward specific devices rather than broadcasting widely." },
    { word: "ultra-reliable low-latency communication", translation: "communication ultra-fiable à faible latence", example: "Ultra-reliable low-latency communication enables critical applications like autonomous vehicles." },
    { word: "private 5G network", translation: "réseau 5G privé", example: "Private 5G networks provide dedicated wireless connectivity for industrial applications." },
    { word: "edge computing", translation: "informatique en périphérie", example: "Edge computing processes data near its source to reduce latency." },
    { word: "spectrum sharing", translation: "partage de spectre", example: "Spectrum sharing allows multiple users to access the same frequency bands." },
    { word: "small cell", translation: "petite cellule", example: "Small cells extend network coverage and capacity in localized areas." },
    { word: "fixed wireless access", translation: "accès sans fil fixe", example: "Fixed wireless access provides internet connectivity to premises using wireless networks." },
    { word: "radio access network", translation: "réseau d'accès radio", example: "The radio access network connects devices to the core network in cellular systems." },
    { word: "network function virtualization", translation: "virtualisation des fonctions réseau", example: "Network function virtualization replaces dedicated hardware with software applications." },
    { word: "software-defined networking", translation: "réseau défini par logiciel", example: "Software-defined networking separates network control from data forwarding functions." },
    { word: "enhanced mobile broadband", translation: "haut débit mobile amélioré", example: "Enhanced mobile broadband provides significantly faster data speeds for consumer applications." },
    { word: "massive machine-type communication", translation: "communication massive de type machine", example: "Massive machine-type communication supports large-scale IoT deployments." },
    { word: "network densification", translation: "densification du réseau", example: "Network densification increases the number of transmitters within a geographic area." },
    { word: "mobile edge computing", translation: "informatique en périphérie mobile", example: "Mobile edge computing brings processing capabilities closer to cellular users." },
    { word: "non-terrestrial network", translation: "réseau non terrestre", example: "Non-terrestrial networks include satellite and high-altitude platform systems." },
    { word: "cellular vehicle-to-everything", translation: "communication véhiculaire cellulaire", example: "Cellular vehicle-to-everything technology enables cars to communicate with surrounding infrastructure." },
    { word: "fronthaul network", translation: "réseau de liaison frontale", example: "Fronthaul networks connect baseband units to remote radio heads in cellular systems." },
    { word: "backhaul network", translation: "réseau de liaison arrière", example: "Backhaul networks connect cell sites to the core network." },
    { word: "open RAN", translation: "RAN ouvert", example: "Open RAN standardizes radio access network interfaces for multi-vendor deployments." },
    { word: "dynamic spectrum access", translation: "accès dynamique au spectre", example: "Dynamic spectrum access allows opportunistic use of available frequency bands." },
    { word: "self-organizing network", translation: "réseau auto-organisé", example: "Self-organizing networks automatically configure, optimize, and heal cellular networks." }
  ]
};