export const vocab = {
  title: "Management et Stratégie d'Entreprise",
  words: [
    // Leadership et gouvernance (25 mots)
    { word: "strategic leadership", translation: "leadership stratégique", example: "Strategic leadership aligns organizational capabilities with market opportunities." },
    { word: "transformational leadership", translation: "leadership transformationnel", example: "Transformational leadership inspires employees to exceed performance expectations." },
    { word: "executive decision-making", translation: "prise de décision exécutive", example: "Executive decision-making balances analytical and intuitive approaches." },
    { word: "corporate governance", translation: "gouvernance d'entreprise", example: "Effective corporate governance protects stakeholder interests while enabling value creation." },
    { word: "board dynamics", translation: "dynamique du conseil d'administration", example: "Board dynamics influence the quality of strategic oversight and guidance." },
    { word: "servant leadership", translation: "leadership de service", example: "Servant leadership prioritizes employee development and empowerment." },
    { word: "leadership pipeline", translation: "vivier de leaders", example: "The leadership pipeline ensures succession readiness at all organizational levels." },
    { word: "executive presence", translation: "présence exécutive", example: "Executive presence combines communication skills with credibility and confidence." },
    { word: "ethical leadership", translation: "leadership éthique", example: "Ethical leadership demonstrates integrity in all business decisions." },
    { word: "strategic alignment", translation: "alignement stratégique", example: "Strategic alignment connects operational activities with organizational objectives." },
    { word: "collaborative leadership", translation: "leadership collaboratif", example: "Collaborative leadership engages diverse perspectives for better decisions." },
    { word: "vision statement", translation: "énoncé de vision", example: "The vision statement articulates the organization's aspirational future state." },
    { word: "mission statement", translation: "énoncé de mission", example: "Their mission statement defines their core purpose and reason for existing." },
    { word: "stakeholder management", translation: "gestion des parties prenantes", example: "Stakeholder management balances competing interests and priorities." },
    { word: "leadership competency", translation: "compétence de leadership", example: "Leadership competency models define essential capabilities for executives." },
    { word: "stewardship", translation: "intendance", example: "Stewardship emphasizes responsible management of company resources." },
    { word: "distributed leadership", translation: "leadership distribué", example: "Distributed leadership shares responsibility across organizational levels." },
    { word: "executive coaching", translation: "coaching exécutif", example: "Executive coaching develops leadership effectiveness through personalized guidance." },
    { word: "authentic leadership", translation: "leadership authentique", example: "Authentic leadership builds trust through transparency and self-awareness." },
    { word: "board composition", translation: "composition du conseil", example: "Board composition should reflect diverse expertise and perspectives." },
    { word: "leadership agility", translation: "agilité du leadership", example: "Leadership agility enables effective response to rapidly changing conditions." },
    { word: "thought leadership", translation: "leadership d'opinion", example: "Thought leadership positions the organization as an industry authority." },
    { word: "executive team effectiveness", translation: "efficacité de l'équipe dirigeante", example: "Executive team effectiveness requires both individual excellence and collaborative dynamics." },
    { word: "leadership development", translation: "développement du leadership", example: "Leadership development accelerates the growth of high-potential talent." },
    { word: "governance structure", translation: "structure de gouvernance", example: "The governance structure establishes clear decision rights and accountability." },
    
    // Planification stratégique (25 mots)
    { word: "strategic planning", translation: "planification stratégique", example: "Strategic planning defines long-term objectives and implementation paths." },
    { word: "competitive strategy", translation: "stratégie concurrentielle", example: "Their competitive strategy emphasizes service differentiation rather than price." },
    { word: "strategic intent", translation: "intention stratégique", example: "Strategic intent articulates aspirational goals that stretch organizational capabilities." },
    { word: "environmental scanning", translation: "analyse de l'environnement", example: "Environmental scanning identifies emerging trends and potential disruptions." },
    { word: "strategic positioning", translation: "positionnement stratégique", example: "Strategic positioning establishes a unique value proposition in the market." },
    { word: "value proposition", translation: "proposition de valeur", example: "Their value proposition clearly articulates benefits to target customers." },
    { word: "core competency", translation: "compétence fondamentale", example: "Innovation remains the organization's core competency and competitive advantage." },
    { word: "strategic objective", translation: "objectif stratégique", example: "Each strategic objective includes specific metrics and timeframes." },
    { word: "strategic implementation", translation: "mise en œuvre stratégique", example: "Strategic implementation translates plans into operational activities." },
    { word: "strategic initiative", translation: "initiative stratégique", example: "The strategic initiative aimed to penetrate emerging markets in Southeast Asia." },
    { word: "scenario planning", translation: "planification par scénarios", example: "Scenario planning prepares organizations for alternative future conditions." },
    { word: "strategic alignment", translation: "alignement stratégique", example: "Strategic alignment ensures coherence between decisions across organizational levels." },
    { word: "growth strategy", translation: "stratégie de croissance", example: "Their growth strategy combines organic expansion with strategic acquisitions." },
    { word: "corporate strategy", translation: "stratégie d'entreprise", example: "Corporate strategy determines which businesses to operate and how to allocate resources." },
    { word: "business-level strategy", translation: "stratégie au niveau commercial", example: "Business-level strategy focuses on competitive advantage within specific markets." },
    { word: "functional strategy", translation: "stratégie fonctionnelle", example: "Functional strategy aligns departmental activities with broader business objectives." },
    { word: "strategic control", translation: "contrôle stratégique", example: "Strategic control monitors implementation progress against planned objectives." },
    { word: "competitive advantage", translation: "avantage concurrentiel", example: "Technological innovation provided sustainable competitive advantage." },
    { word: "strategic planning cycle", translation: "cycle de planification stratégique", example: "The strategic planning cycle ensures regular review and adaptation." },
    { word: "strategic analysis", translation: "analyse stratégique", example: "Strategic analysis evaluates internal capabilities and external factors." },
    { word: "strategic risk", translation: "risque stratégique", example: "The expansion presented significant strategic risk but greater potential rewards." },
    { word: "strategic alternatives", translation: "alternatives stratégiques", example: "Management evaluated strategic alternatives before selecting the acquisition path." },
    { word: "blue ocean strategy", translation: "stratégie océan bleu", example: "Blue ocean strategy seeks uncontested market spaces rather than fierce competition." },
    { word: "strategic vision", translation: "vision stratégique", example: "Their strategic vision guided decision-making through market turbulence." },
    { word: "strategic thinking", translation: "pensée stratégique", example: "Strategic thinking combines analytical and creative approaches to opportunity identification." },
    
    // Innovation et gestion du changement (25 mots)
    { word: "innovation management", translation: "gestion de l'innovation", example: "Innovation management establishes processes for generating and implementing new ideas." },
    { word: "disruptive innovation", translation: "innovation disruptive", example: "Disruptive innovation transforms markets by introducing simpler, more accessible solutions." },
    { word: "change management", translation: "gestion du changement", example: "Change management facilitates organizational transitions while minimizing disruption." },
    { word: "organizational transformation", translation: "transformation organisationnelle", example: "The organizational transformation realigned structures with evolving customer needs." },
    { word: "incremental innovation", translation: "innovation incrémentale", example: "Incremental innovation continuously improves existing products and services." },
    { word: "breakthrough innovation", translation: "innovation de rupture", example: "The breakthrough innovation revolutionized industry manufacturing processes." },
    { word: "innovation pipeline", translation: "pipeline d'innovation", example: "Their robust innovation pipeline ensures continuous product development." },
    { word: "innovation culture", translation: "culture d'innovation", example: "Creating an innovation culture requires encouraging experimentation and tolerating failure." },
    { word: "change resistance", translation: "résistance au changement", example: "Change resistance stemmed from inadequate communication about benefits." },
    { word: "innovation strategy", translation: "stratégie d'innovation", example: "The innovation strategy balanced internal development with external partnerships." },
    { word: "digital transformation", translation: "transformation numérique", example: "Digital transformation revolutionized customer engagement and operational efficiency." },
    { word: "innovation portfolio", translation: "portefeuille d'innovation", example: "The innovation portfolio balances short-term improvements with long-term breakthroughs." },
    { word: "change readiness", translation: "préparation au changement", example: "Assessments measured organizational change readiness before implementation." },
    { word: "open innovation", translation: "innovation ouverte", example: "Open innovation leverages external partners to accelerate development." },
    { word: "business model innovation", translation: "innovation de modèle d'affaires", example: "Business model innovation transformed how they created and delivered value." },
    { word: "change leadership", translation: "leadership du changement", example: "Change leadership requires vision, communication, and persistence." },
    { word: "innovation metrics", translation: "indicateurs d'innovation", example: "Innovation metrics track both activities and outcomes across the portfolio." },
    { word: "organizational agility", translation: "agilité organisationnelle", example: "Organizational agility enables rapid adaptation to market shifts." },
    { word: "change initiative", translation: "initiative de changement", example: "The change initiative transformed operational processes across divisions." },
    { word: "innovation ecosystem", translation: "écosystème d'innovation", example: "Their innovation ecosystem includes startups, universities, and industry partners." },
    { word: "design thinking", translation: "pensée design", example: "Design thinking puts customer needs at the center of innovation processes." },
    { word: "change communication", translation: "communication du changement", example: "Effective change communication addresses both rational and emotional factors." },
    { word: "reverse innovation", translation: "innovation inverse", example: "Reverse innovation develops solutions in emerging markets for global application." },
    { word: "change sustainability", translation: "durabilité du changement", example: "Change sustainability requires embedding new behaviors in organizational systems." },
    { word: "innovation capability", translation: "capacité d'innovation", example: "Innovation capability combines creative processes with disciplined implementation." },
    
    // Gestion des opérations (25 mots)
    { word: "operations management", translation: "gestion des opérations", example: "Operations management optimizes processes for efficiency and quality." },
    { word: "supply chain management", translation: "gestion de la chaîne d'approvisionnement", example: "Supply chain management coordinates product flows from suppliers to customers." },
    { word: "operational excellence", translation: "excellence opérationnelle", example: "Operational excellence initiatives reduced costs while improving quality." },
    { word: "process optimization", translation: "optimisation des processus", example: "Process optimization eliminated redundant steps and reduced cycle time." },
    { word: "lean management", translation: "gestion allégée", example: "Lean management principles eliminated waste throughout the production system." },
    { word: "quality management", translation: "gestion de la qualité", example: "Quality management systems ensure consistent product standards." },
    { word: "capacity planning", translation: "planification de la capacité", example: "Capacity planning matches resources with anticipated demand fluctuations." },
    { word: "inventory management", translation: "gestion des stocks", example: "Improved inventory management reduced carrying costs by 15%." },
    { word: "operational efficiency", translation: "efficacité opérationnelle", example: "Operational efficiency initiatives increased productivity while reducing costs." },
    { word: "business process management", translation: "gestion des processus d'affaires", example: "Business process management structures workflows for optimal results." },
    { word: "continuous improvement", translation: "amélioration continue", example: "The continuous improvement program empowers employees to suggest process enhancements." },
    { word: "performance measurement", translation: "mesure de la performance", example: "Performance measurement systems track operational effectiveness against targets." },
    { word: "six sigma methodology", translation: "méthodologie six sigma", example: "Six sigma methodology reduces process variation and defects." },
    { word: "operational risk", translation: "risque opérationnel", example: "The assessment identified operational risks in the logistics network." },
    { word: "value stream mapping", translation: "cartographie de la chaîne de valeur", example: "Value stream mapping visualizes process flows to identify improvement opportunities." },
    { word: "just-in-time production", translation: "production juste-à-temps", example: "Just-in-time production minimizes inventory costs while meeting customer demand." },
    { word: "total quality management", translation: "gestion de la qualité totale", example: "Total quality management embeds quality principles throughout the organization." },
    { word: "service operations", translation: "opérations de service", example: "Service operations balance efficiency with personalized customer experiences." },
    { word: "bottleneck analysis", translation: "analyse des goulots d'étranglement", example: "Bottleneck analysis identified capacity constraints in the manufacturing process." },
    { word: "operational strategy", translation: "stratégie opérationnelle", example: "Their operational strategy emphasized flexibility and responsiveness." },
    { word: "process standardization", translation: "standardisation des processus", example: "Process standardization ensures consistent approaches across locations." },
    { word: "productivity improvement", translation: "amélioration de la productivité", example: "The automation initiative delivered substantial productivity improvement." },
    { word: "operations metrics", translation: "indicateurs opérationnels", example: "Operations metrics track efficiency, quality, and customer satisfaction." },
    { word: "production planning", translation: "planification de la production", example: "Production planning coordinates resources to meet delivery schedules." },
    { word: "operational resilience", translation: "résilience opérationnelle", example: "Operational resilience enables quick recovery from disruptions." },
    
    // Comportement organisationnel (25 mots)
    { word: "organizational behavior", translation: "comportement organisationnel", example: "Organizational behavior studies how individuals and groups interact within companies." },
    { word: "corporate culture", translation: "culture d'entreprise", example: "Corporate culture significantly influences employee engagement and performance." },
    { word: "employee engagement", translation: "engagement des employés", example: "Employee engagement correlates with productivity and retention." },
    { word: "organizational structure", translation: "structure organisationnelle", example: "Their organizational structure evolved from functional to matrix design." },
    { word: "team dynamics", translation: "dynamique d'équipe", example: "Team dynamics influence collaboration effectiveness and innovation." },
    { word: "organizational learning", translation: "apprentissage organisationnel", example: "Organizational learning processes translate experiences into improved practices." },
    { word: "conflict management", translation: "gestion des conflits", example: "Effective conflict management transforms disagreements into productive discussions." },
    { word: "organizational development", translation: "développement organisationnel", example: "Organizational development interventions improve system effectiveness." },
    { word: "psychological safety", translation: "sécurité psychologique", example: "Psychological safety enables team members to take interpersonal risks." },
    { word: "cultural diversity", translation: "diversité culturelle", example: "Cultural diversity brings multiple perspectives to problem-solving." },
    { word: "organizational change", translation: "changement organisationnel", example: "Organizational change requires addressing both structural and human factors." },
    { word: "employee motivation", translation: "motivation des employés", example: "Understanding employee motivation helps design effective incentive systems." },
    { word: "workplace climate", translation: "climat de travail", example: "The workplace climate survey revealed improving satisfaction scores." },
    { word: "professional development", translation: "développement professionnel", example: "Professional development opportunities enhance retention of key talent." },
    { word: "performance feedback", translation: "rétroaction sur la performance", example: "Regular performance feedback accelerates employee development." },
    { word: "organizational identity", translation: "identité organisationnelle", example: "Organizational identity shapes how employees interpret and respond to challenges." },
    { word: "group cohesion", translation: "cohésion de groupe", example: "Group cohesion strengthens collaboration and mutual support." },
    { word: "organizational politics", translation: "politique organisationnelle", example: "Organizational politics influences decision-making and resource allocation." },
    { word: "power dynamics", translation: "dynamiques de pouvoir", example: "Understanding power dynamics helps navigate complex organizational environments." },
    { word: "employee wellbeing", translation: "bien-être des employés", example: "Employee wellbeing programs address physical, mental, and social health." },
    { word: "organizational climate", translation: "climat organisationnel", example: "The organizational climate reflects shared perceptions of workplace practices." },
    { word: "team building", translation: "consolidation d'équipe", example: "Team building activities strengthen relationships and trust." },
    { word: "organizational commitment", translation: "engagement organisationnel", example: "Organizational commitment reflects employee loyalty and identification." },
    { word: "workplace communication", translation: "communication en milieu de travail", example: "Effective workplace communication prevents misunderstandings and builds trust." },
    { word: "emotional intelligence", translation: "intelligence émotionnelle", example: "Emotional intelligence enhances leadership effectiveness and team collaboration." },
    
    // Marketing et gestion de la clientèle (25 mots)
    { word: "strategic marketing", translation: "marketing stratégique", example: "Strategic marketing aligns offerings with target customer needs and company capabilities." },
    { word: "customer relationship management", translation: "gestion de la relation client", example: "Customer relationship management systems track interactions across touchpoints." },
    { word: "brand management", translation: "gestion de marque", example: "Brand management ensures consistent positioning across communication channels." },
    { word: "market segmentation", translation: "segmentation du marché", example: "Market segmentation divides customers into groups with similar needs and behaviors." },
    { word: "customer experience", translation: "expérience client", example: "Exceptional customer experience drives loyalty and positive word-of-mouth." },
    { word: "digital marketing", translation: "marketing numérique", example: "Digital marketing leverages online channels for targeted customer engagement." },
    { word: "marketing analytics", translation: "analytique marketing", example: "Marketing analytics measures campaign effectiveness and customer behavior." },
    { word: "customer acquisition", translation: "acquisition de clients", example: "Customer acquisition costs decreased following the new marketing strategy." },
    { word: "customer retention", translation: "fidélisation de la clientèle", example: "Customer retention initiatives increased average relationship duration." },
    { word: "market positioning", translation: "positionnement sur le marché", example: "Their market positioning emphasizes premium quality and superior service." },
    { word: "customer insights", translation: "connaissances client", example: "Customer insights drive product development and marketing strategies." },
    { word: "brand equity", translation: "capital de marque", example: "Strong brand equity commands premium pricing and customer loyalty." },
    { word: "customer journey", translation: "parcours client", example: "Mapping the customer journey identifies critical touchpoints for experience enhancement." },
    { word: "omnichannel marketing", translation: "marketing omnicanal", example: "Omnichannel marketing delivers seamless experiences across physical and digital interactions." },
    { word: "content marketing", translation: "marketing de contenu", example: "Content marketing attracts prospects through valuable information rather than direct promotion." },
    { word: "customer lifetime value", translation: "valeur vie client", example: "Customer lifetime value calculations justify higher acquisition investments for premium segments." },
    { word: "market development", translation: "développement de marché", example: "Market development strategies expand the customer base for existing products." },
    { word: "customer segmentation", translation: "segmentation client", example: "Customer segmentation enables personalized marketing approaches for different groups." },
    { word: "marketing strategy", translation: "stratégie de marketing", example: "Their marketing strategy prioritized digital engagement with millennial consumers." },
    { word: "competitive intelligence", translation: "intelligence concurrentielle", example: "Competitive intelligence monitors rival offerings and strategic moves." },
    { word: "brand positioning", translation: "positionnement de marque", example: "Brand positioning differentiates the company in a crowded marketplace." },
    { word: "customer feedback", translation: "rétroaction client", example: "Customer feedback mechanisms provide continuous improvement insights." },
    { word: "market penetration", translation: "pénétration du marché", example: "Market penetration strategies increase share within existing segments." },
    { word: "brand identity", translation: "identité de marque", example: "Brand identity encompasses visual elements and personality characteristics." },
    { word: "marketing mix", translation: "mix marketing", example: "The marketing mix optimizes product, price, place, and promotion decisions." },
    
    // Gestion de projet (25 mots)
    { word: "project management", translation: "gestion de projet", example: "Project management coordinates activities to deliver specific objectives within constraints." },
    { word: "scope management", translation: "gestion de la portée", example: "Scope management prevents feature creep and maintains project focus." },
    { word: "project planning", translation: "planification de projet", example: "Project planning establishes activities, resources, and timelines." },
    { word: "risk management", translation: "gestion des risques", example: "Risk management identifies, assesses, and mitigates potential project threats." },
    { word: "stakeholder management", translation: "gestion des parties prenantes", example: "Stakeholder management ensures support from all affected groups." },
    { word: "project schedule", translation: "calendrier de projet", example: "The project schedule defines activity sequence and completion dates." },
    { word: "critical path", translation: "chemin critique", example: "Delays in critical path activities directly impact project completion dates." },
    { word: "agile methodology", translation: "méthodologie agile", example: "Agile methodology embraces iterative development and customer collaboration." },
    { word: "project governance", translation: "gouvernance de projet", example: "Project governance establishes decision-making authorities and oversight processes." },
    { word: "project budget", translation: "budget de projet", example: "The project budget tracks planned versus actual expenditures." },
    { word: "waterfall methodology", translation: "méthodologie en cascade", example: "Waterfall methodology follows sequential phases from requirements through delivery." },
    { word: "sprint planning", translation: "planification de sprint", example: "Sprint planning defines deliverables for the upcoming development cycle." },
    { word: "resource allocation", translation: "allocation des ressources", example: "Resource allocation optimizes staff and equipment utilization across projects." },
    { word: "milestone", translation: "jalon", example: "Project milestones mark significant achievement points and progress measurement." },
    { word: "project portfolio management", translation: "gestion de portefeuille de projets", example: "Project portfolio management aligns initiatives with strategic priorities." },
    { word: "project charter", translation: "charte de projet", example: "The project charter formally authorizes the project and defines high-level parameters." },
    { word: "earned value management", translation: "gestion de la valeur acquise", example: "Earned value management integrates scope, schedule, and cost performance measurement." },
    { word: "project stakeholder", translation: "partie prenante du projet", example: "Project stakeholders include anyone affected by or influencing the initiative." },
    { word: "project deliverable", translation: "livrable de projet", example: "Project deliverables include all products or results produced during execution." },
    { word: "scope creep", translation: "dérive du périmètre", example: "Scope creep introduces unplanned requirements that extend timelines and budgets." },
    { word: "project management office", translation: "bureau de gestion de projets", example: "The project management office standardizes project governance across the organization." },
    { word: "project lifecycle", translation: "cycle de vie du projet", example: "The project lifecycle encompasses initiation through closure phases." },
    { word: "work breakdown structure", translation: "structure de découpage du projet", example: "The work breakdown structure hierarchically organizes project deliverables and activities." },
    { word: "project communication", translation: "communication de projet", example: "Effective project communication ensures stakeholder awareness and alignment." },
    { word: "project prioritization", translation: "priorisation de projet", example: "Project prioritization ensures resource allocation to highest-value initiatives." },
    
    // Négociation et résolution de conflits (25 mots)
    { word: "negotiation strategy", translation: "stratégie de négociation", example: "Effective negotiation strategy balances value creation with value claiming." },
    { word: "conflict resolution", translation: "résolution de conflits", example: "Conflict resolution transforms disagreements into constructive solutions." },
    { word: "mediation", translation: "médiation", example: "Mediation involves neutral third parties facilitating agreement between disputants." },
    { word: "arbitration", translation: "arbitrage", example: "Binding arbitration provides final resolution to contractual disputes." },
    { word: "BATNA", translation: "MESORE", example: "Understanding your BATNA (Best Alternative To Negotiated Agreement) strengthens negotiating position." },
    { word: "distributive negotiation", translation: "négociation distributive", example: "Distributive negotiation focuses on claiming value in zero-sum situations." },
    { word: "integrative negotiation", translation: "négociation intégrative", example: "Integrative negotiation seeks mutual value creation through creative solutions." },
    { word: "conflict management", translation: "gestion des conflits", example: "Conflict management approaches include avoidance, accommodation, competition, compromise, and collaboration." },
    { word: "collaborative problem-solving", translation: "résolution collaborative de problèmes", example: "Collaborative problem-solving identifies solutions meeting all parties' interests." },
    { word: "negotiation tactic", translation: "tactique de négociation", example: "The negotiation tactic aimed to determine the other party's reservation price." },
    { word: "active listening", translation: "écoute active", example: "Active listening demonstrates understanding of others' perspectives and concerns." },
    { word: "principled negotiation", translation: "négociation raisonnée", example: "Principled negotiation separates people from problems and focuses on interests rather than positions." },
    { word: "conflict escalation", translation: "escalade des conflits", example: "Avoiding conflict escalation requires early intervention and de-escalation techniques." },
    { word: "conflict of interest", translation: "conflit d'intérêts", example: "The apparent conflict of interest required recusal from decision-making." },
    { word: "dispute resolution", translation: "règlement des différends", example: "The contract specified dispute resolution procedures to avoid litigation." },
    { word: "win-win solution", translation: "solution gagnant-gagnant", example: "The negotiation produced a win-win solution benefiting both organizations." },
    { word: "negotiation preparation", translation: "préparation à la négociation", example: "Thorough negotiation preparation establishes objectives, strategies, and fallback positions." },
    { word: "relationship management", translation: "gestion des relations", example: "Maintaining relationships while negotiating substance creates long-term value." },
    { word: "positional bargaining", translation: "négociation positionnelle", example: "Positional bargaining often creates suboptimal agreements by overlooking interests." },
    { word: "consensus building", translation: "recherche de consensus", example: "Consensus building aligns multiple stakeholders behind shared solutions." },
    { word: "team negotiation", translation: "négociation d'équipe", example: "Team negotiation requires clear roles and coordination strategies." },
    { word: "cross-cultural negotiation", translation: "négociation interculturelle", example: "Cross-cultural negotiation demands awareness of varying communication styles and expectations." },
    { word: "facilitation", translation: "facilitation", example: "Skilled facilitation helps groups navigate complex discussions productively." },
    { word: "negotiation power", translation: "pouvoir de négociation", example: "Information asymmetry affects relative negotiation power between parties." },
    { word: "conflict prevention", translation: "prévention des conflits", example: "Clear communication and expectations support conflict prevention." },
    
    // Éthique des affaires et responsabilité sociale (25 mots)
    { word: "business ethics", translation: "éthique des affaires", example: "Business ethics establishes principles for responsible corporate conduct." },
    { word: "corporate social responsibility", translation: "responsabilité sociale des entreprises", example: "Corporate social responsibility integrates social and environmental concerns into operations." },
    { word: "stakeholder theory", translation: "théorie des parties prenantes", example: "Stakeholder theory argues corporations should serve all groups affected by their activities." },
    { word: "environmental sustainability", translation: "durabilité environnementale", example: "Environmental sustainability initiatives reduced carbon emissions by 35%." },
    { word: "ethical leadership", translation: "leadership éthique", example: "Ethical leadership demonstrates integrity in all business decisions." },
    { word: "corporate citizenship", translation: "citoyenneté d'entreprise", example: "Corporate citizenship programs support community development and social causes." },
    { word: "ethical dilemma", translation: "dilemme éthique", example: "The ethical dilemma pitted short-term profitability against long-term environmental impact." },
    { word: "code of conduct", translation: "code de conduite", example: "The code of conduct establishes behavioral expectations for all employees." },
    { word: "social impact", translation: "impact social", example: "Measuring social impact quantifies program effects on community well-being." },
    { word: "sustainable development", translation: "développement durable", example: "Sustainable development meets present needs without compromising future generations." },
    { word: "triple bottom line", translation: "triple bilan", example: "The triple bottom line evaluates performance across economic, social, and environmental dimensions." },
    { word: "ethical supply chain", translation: "chaîne d'approvisionnement éthique", example: "Ethical supply chain management ensures fair labor practices and environmental responsibility." },
    { word: "corporate transparency", translation: "transparence d'entreprise", example: "Corporate transparency builds stakeholder trust through open communication." },
    { word: "compliance program", translation: "programme de conformité", example: "The compliance program ensures adherence to regulatory requirements and ethical standards." },
    { word: "community engagement", translation: "engagement communautaire", example: "Community engagement programs created shared value with local stakeholders." },
    { word: "diversity and inclusion", translation: "diversité et inclusion", example: "Diversity and inclusion initiatives enhance organizational performance and innovation." },
    { word: "ethical culture", translation: "culture éthique", example: "Building an ethical culture requires consistent leadership example and accountability." },
    { word: "social responsibility", translation: "responsabilité sociale", example: "Their approach to social responsibility extends beyond philanthropy to core business practices." },
    { word: "ethical decision-making", translation: "prise de décision éthique", example: "Ethical decision-making frameworks help navigate complex situations." },
    { word: "whistleblower protection", translation: "protection des lanceurs d'alerte", example: "Whistleblower protection encourages reporting of potential misconduct." },
    { word: "shared value", translation: "valeur partagée", example: "Creating shared value generates economic benefits while addressing societal challenges." },
    { word: "ethical investing", translation: "investissement éthique", example: "Ethical investing applies moral criteria to portfolio decisions." },
    { word: "human rights", translation: "droits humains", example: "The company's human rights policy applies to all operations and suppliers." },
    { word: "corporate philanthropy", translation: "philanthropie d'entreprise", example: "Corporate philanthropy targets educational access in underserved communities." },
    { word: "ESG factors", translation: "facteurs ESG", example: "Investment decisions increasingly consider environmental, social, and governance factors." },
    
    // Entrepreneuriat et innovation (25 mots)
    { word: "entrepreneurship", translation: "entrepreneuriat", example: "Entrepreneurship creates new ventures to exploit identified opportunities." },
    { word: "startup", translation: "entreprise en démarrage", example: "The technology startup secured first-round venture funding." },
    { word: "business model", translation: "modèle d'affaires", example: "Their business model generates revenue through subscription services." },
    { word: "value proposition", translation: "proposition de valeur", example: "A compelling value proposition addresses significant customer needs." },
    { word: "venture capital", translation: "capital-risque", example: "Venture capital provides funding for early-stage companies with growth potential." },
    { word: "disruptive innovation", translation: "innovation disruptive", example: "Disruptive innovation challenges industry incumbents with new approaches." },
    { word: "scalability", translation: "évolutivité", example: "The business plan demonstrated scalability without proportional cost increases." },
    { word: "lean startup", translation: "startup allégée", example: "Lean startup methodology emphasizes experimentation and iterative development." },
    { word: "minimum viable product", translation: "produit minimum viable", example: "The minimum viable product tests core features with early customers." },
    { word: "pivot", translation: "pivot", example: "Their strategic pivot refocused the business on enterprise rather than consumer markets." },
    { word: "angel investor", translation: "investisseur providentiel", example: "Angel investors provided seed capital for the early development phase." },
    { word: "entrepreneurial ecosystem", translation: "écosystème entrepreneurial", example: "A thriving entrepreneurial ecosystem includes funding sources, mentors, and support services." },
    { word: "business incubator", translation: "incubateur d'entreprises", example: "The business incubator provides office space and advisory services to startups." },
    { word: "accelerator program", translation: "programme d'accélération", example: "The accelerator program compressed years of growth into months of intensive development." },
    { word: "market validation", translation: "validation de marché", example: "Market validation confirms actual customer demand for the concept." },
    { word: "bootstrap", translation: "autofinancement", example: "They chose to bootstrap the company rather than seek external funding." },
    { word: "business plan", translation: "plan d'affaires", example: "The business plan documented the market opportunity and implementation strategy." },
    { word: "product-market fit", translation: "adéquation produit-marché", example: "Achieving product-market fit indicates solution alignment with customer needs." },
    { word: "growth hacking", translation: "growth hacking", example: "Growth hacking strategies accelerated customer acquisition with minimal spending." },
    { word: "serial entrepreneur", translation: "entrepreneur en série", example: "The serial entrepreneur had successfully launched three previous ventures." },
    { word: "social entrepreneurship", translation: "entrepreneuriat social", example: "Social entrepreneurship applies business principles to address societal problems." },
    { word: "intellectual property", translation: "propriété intellectuelle", example: "The patent strategy protected their intellectual property from competitors." },
    { word: "burn rate", translation: "taux de consommation du capital", example: "Their current burn rate gave them eighteen months of operational runway." },
    { word: "pitch deck", translation: "présentation d'investissement", example: "The pitch deck communicated the value proposition and growth potential." },
    { word: "user experience", translation: "expérience utilisateur", example: "Exceptional user experience differentiated their product in the market." }
  ]
};