export const vocab = {
  title: "Enjeux Sociaux Complexes",
  words: [
    // Inégalités et justice sociale (50 mots)
    { word: "systemic inequality", translation: "inégalité systémique", example: "Systemic inequality persists through institutional structures despite formal legal equality." },
    { word: "socioeconomic disparities", translation: "disparités socio-économiques", example: "The pandemic exacerbated existing socioeconomic disparities in healthcare access and outcomes." },
    { word: "income inequality", translation: "inégalité de revenus", example: "Income inequality has increased substantially in most advanced economies since the 1980s." },
    { word: "wealth concentration", translation: "concentration des richesses", example: "Wealth concentration accelerated following financial deregulation and tax policy changes." },
    { word: "social stratification", translation: "stratification sociale", example: "Educational access reflects broader social stratification patterns across generations." },
    { word: "social mobility", translation: "mobilité sociale", example: "Social mobility varies significantly across countries with similar economic development." },
    { word: "intergenerational mobility", translation: "mobilité intergénérationnelle", example: "Intergenerational mobility has declined as economic opportunity becomes more concentrated." },
    { word: "opportunity gap", translation: "écart d'opportunités", example: "The opportunity gap begins early in childhood through differential access to resources and support." },
    { word: "social determinants", translation: "déterminants sociaux", example: "Health outcomes reflect social determinants including education, income, and neighborhood conditions." },
    { word: "structural barriers", translation: "barrières structurelles", example: "Structural barriers to advancement persist despite anti-discrimination legislation." },
    { word: "social exclusion", translation: "exclusion sociale", example: "Digital transformation risks deepening social exclusion of communities lacking connectivity." },
    { word: "marginalized communities", translation: "communautés marginalisées", example: "Policy development must include voices from marginalized communities most affected by decisions." },
    { word: "social capital", translation: "capital social", example: "Professional advancement often depends on social capital accumulated through networks and relationships." },
    { word: "cultural capital", translation: "capital culturel", example: "Educational institutions reward cultural capital acquired through privileged family backgrounds." },
    { word: "privilege", translation: "privilège", example: "Understanding privilege requires recognizing unearned advantages conferred by social position." },
    { word: "intersectionality", translation: "intersectionnalité", example: "Intersectionality examines how multiple forms of disadvantage interact rather than simply accumulate." },
    { word: "social justice", translation: "justice sociale", example: "Social justice frameworks address both distributive fairness and recognition of identity-based exclusion." },
    { word: "distributive justice", translation: "justice distributive", example: "Distributive justice concerns the allocation of resources, opportunities, and burdens in society." },
    { word: "procedural justice", translation: "justice procédurale", example: "Procedural justice focuses on fairness in decision-making processes rather than just outcomes." },
    { word: "restorative justice", translation: "justice restaurative", example: "Restorative justice approaches prioritize healing harm rather than merely punishing offenders." },
    { word: "social contract", translation: "contrat social", example: "The pandemic prompted reassessment of the social contract between citizens, employers, and government." },
    { word: "collective responsibility", translation: "responsabilité collective", example: "Addressing historical injustices requires acknowledging collective responsibility beyond individual actions." },
    { word: "societal transformation", translation: "transformation sociétale", example: "Meaningful societal transformation demands changes in both institutional structures and cultural norms." },
    { word: "empowerment", translation: "autonomisation", example: "Community empowerment strategies build capacity for self-determination rather than dependency." },
    { word: "capabilities approach", translation: "approche par les capabilités", example: "The capabilities approach measures well-being through substantive freedoms rather than income alone." },
    { word: "human flourishing", translation: "épanouissement humain", example: "Policy should ultimately promote human flourishing beyond economic metrics." },
    { word: "social welfare", translation: "bien-être social", example: "Comprehensive social welfare systems provide support throughout the life course." },
    { word: "social safety net", translation: "filet de sécurité sociale", example: "The pandemic revealed inadequacies in the social safety net for contingent workers." },
    { word: "universal basic income", translation: "revenu universel de base", example: "Universal basic income proposals address both poverty and technological displacement concerns." },
    { word: "economic insecurity", translation: "insécurité économique", example: "Economic insecurity affects household formation, consumption, and social cohesion." },
    { word: "precarious employment", translation: "emploi précaire", example: "Precarious employment relationships transfer risk from employers to individual workers." },
    { word: "labor market polarization", translation: "polarisation du marché du travail", example: "Labor market polarization increases demand for both high-skill and low-skill workers while hollowing the middle." },
    { word: "working poor", translation: "travailleurs pauvres", example: "The working poor remain in poverty despite full-time employment due to inadequate wages." },
    { word: "housing insecurity", translation: "insécurité du logement", example: "Housing insecurity affects educational outcomes and family stability beyond homelessness." },
    { word: "food insecurity", translation: "insécurité alimentaire", example: "Food insecurity persists in wealthy nations despite agricultural abundance." },
    { word: "healthcare disparity", translation: "disparité en matière de soins de santé", example: "Healthcare disparities manifest in both access and quality of treatment across population groups." },
    { word: "environmental justice", translation: "justice environnementale", example: "Environmental justice movements highlight disproportionate pollution exposure in disadvantaged communities." },
    { word: "climate vulnerability", translation: "vulnérabilité climatique", example: "Climate vulnerability reflects both geographical exposure and socioeconomic capacity to adapt." },
    { word: "spatial inequality", translation: "inégalité spatiale", example: "Spatial inequality concentrates opportunities in prosperous regions while others experience disinvestment." },
    { word: "rural-urban divide", translation: "fracture rurale-urbaine", example: "The rural-urban divide increasingly defines political alignments in many democracies." },
    { word: "disenfranchisement", translation: "privation des droits", example: "Voter identification requirements risk disenfranchisement of marginalized communities." },
    { word: "social cohesion", translation: "cohésion sociale", example: "Rising inequality threatens social cohesion by eroding shared experiences and mutual understanding." },
    { word: "intergenerational equity", translation: "équité intergénérationnelle", example: "Climate policy debates center on intergenerational equity between current and future citizens." },
    { word: "digital divide", translation: "fracture numérique", example: "The digital divide encompasses access, skills, and meaningful usage of technology." },
    { word: "opportunity hoarding", translation: "accaparement des opportunités", example: "Elite institutions perpetuate advantage through opportunity hoarding mechanisms like legacy admissions." },
    { word: "cumulative disadvantage", translation: "désavantage cumulatif", example: "Cumulative disadvantage compounds across the life course through interconnected systems." },
    { word: "meritocratic ideology", translation: "idéologie méritocratique", example: "Meritocratic ideology legitimizes inequality by attributing outcomes to individual effort rather than structural factors." },
    { word: "inherited privilege", translation: "privilège hérité", example: "Inherited privilege functions through both material wealth and cultural advantages transmitted across generations." },
    { word: "intergenerational poverty", translation: "pauvreté intergénérationnelle", example: "Breaking cycles of intergenerational poverty requires early intervention and sustained support." },
    { word: "progressive taxation", translation: "fiscalité progressive", example: "Progressive taxation structures distribute burden according to ability to pay rather than equally." },
    
    // Transformations sociales et identitaires (50 mots)
    { word: "demographic transition", translation: "transition démographique", example: "Advanced economies face challenges following demographic transition to aging, low-fertility populations." },
    { word: "aging society", translation: "société vieillissante", example: "Aging society dynamics reshape labor markets, healthcare systems, and intergenerational transfers." },
    { word: "population decline", translation: "déclin démographique", example: "Regional population decline threatens economic sustainability in rural and post-industrial areas." },
    { word: "migration patterns", translation: "schémas migratoires", example: "Contemporary migration patterns reflect both opportunity-seeking and displacement from conflict and climate impacts." },
    { word: "urbanization", translation: "urbanisation", example: "Rapid urbanization creates infrastructure challenges while offering economic concentration benefits." },
    { word: "megacity", translation: "mégalopole", example: "Governance of megacities requires innovative approaches beyond traditional municipal models." },
    { word: "gentrification", translation: "gentrification", example: "Gentrification processes displace long-term residents while increasing property values and changing neighborhood character." },
    { word: "urban renewal", translation: "rénovation urbaine", example: "Urban renewal initiatives risk reinforcing existing inequalities without inclusive planning processes." },
    { word: "social fabric", translation: "tissu social", example: "Community institutions strengthen the social fabric through relationship building and mutual assistance." },
    { word: "civic engagement", translation: "engagement civique", example: "Declining civic engagement raises concerns about democratic legitimacy and social connectedness." },
    { word: "social atomization", translation: "atomisation sociale", example: "Technology platforms may exacerbate social atomization despite superficial connectivity." },
    { word: "communal bonds", translation: "liens communautaires", example: "Traditional communal bonds weaken through geographic mobility and individualistic value shifts." },
    { word: "social integration", translation: "intégration sociale", example: "Social integration requires both structural opportunity and cultural inclusion." },
    { word: "cultural assimilation", translation: "assimilation culturelle", example: "Cultural assimilation expectations have shifted toward multicultural accommodation in diverse societies." },
    { word: "multiculturalism", translation: "multiculturalisme", example: "Multiculturalism policies recognize cultural diversity as societal strength rather than threat." },
    { word: "cultural pluralism", translation: "pluralisme culturel", example: "Cultural pluralism enables multiple traditions to coexist within shared civic frameworks." },
    { word: "cosmopolitanism", translation: "cosmopolitisme", example: "Cosmopolitanism emphasizes global citizenship and cross-cultural ethical responsibilities." },
    { word: "cultural relativism", translation: "relativisme culturel", example: "Cultural relativism argues practices should be understood within their contextual meaning systems." },
    { word: "intercultural dialogue", translation: "dialogue interculturel", example: "Intercultural dialogue builds mutual understanding across different worldviews and traditions." },
    { word: "identity politics", translation: "politique identitaire", example: "Identity politics mobilizes around shared experiences of marginalization and recognition demands." },
    { word: "nationalism", translation: "nationalisme", example: "Resurgent nationalism reacts against perceived threats to national sovereignty and cultural identity." },
    { word: "ethnocentrism", translation: "ethnocentrisme", example: "Ethnocentrism judges other cultures according to one's own cultural standards and assumptions." },
    { word: "cultural appropriation", translation: "appropriation culturelle", example: "Cultural appropriation debates address power relationships in cultural borrowing and representation." },
    { word: "inclusive representation", translation: "représentation inclusive", example: "Media organizations increasingly prioritize inclusive representation in content creation and distribution." },
    { word: "diversity, equity and inclusion", translation: "diversité, équité et inclusion", example: "Organizational DEI initiatives address representation, opportunity, and belonging dimensions." },
    { word: "unconscious bias", translation: "biais inconscient", example: "Training programs address unconscious bias in decision-making processes despite conscious egalitarian values." },
    { word: "microaggression", translation: "micro-agression", example: "Microaggressions communicate hostile or derogatory attitudes through seemingly minor interactions." },
    { word: "allyship", translation: "alliance", example: "Effective allyship involves using privilege to challenge systemic inequities rather than merely expressing sympathy." },
    { word: "decolonization", translation: "décolonisation", example: "Institutional decolonization examines how colonial legacies persist in knowledge systems and governance structures." },
    { word: "indigeneity", translation: "indigénéité", example: "Indigenous movements assert rights based on historical continuity with pre-colonial societies." },
    { word: "cultural heritage", translation: "patrimoine culturel", example: "Cultural heritage preservation balances protection with avoiding essentialist representations." },
    { word: "historical memory", translation: "mémoire historique", example: "Contested historical memory shapes contemporary identity and political alignments." },
    { word: "cultural trauma", translation: "traumatisme culturel", example: "Cultural trauma transmits collective injury experiences across generations through narratives and commemoration." },
    { word: "reconciliation", translation: "réconciliation", example: "Meaningful reconciliation processes address historical injustices through acknowledgment, reparation, and institutional reform." },
    { word: "transitional justice", translation: "justice transitionnelle", example: "Transitional justice mechanisms balance accountability for past abuses with forward-looking social healing." },
    { word: "reparations", translation: "réparations", example: "Reparations proposals address historical injustices through financial compensation and structural reforms." },
    { word: "social construction", translation: "construction sociale", example: "Understanding gender as social construction distinguishes between biological characteristics and cultural norms." },
    { word: "gender norms", translation: "normes de genre", example: "Gender norms vary across cultures but typically prescribe different behaviors and expectations based on perceived gender." },
    { word: "heteronormativity", translation: "hétéronormativité", example: "Heteronormativity assumes heterosexuality as default and organizing principle for social institutions." },
    { word: "gender equity", translation: "équité de genre", example: "Gender equity initiatives address both formal barriers and informal exclusionary practices." },
    { word: "intersectional feminism", translation: "féminisme intersectionnel", example: "Intersectional feminism examines how gender interacts with race, class, and other identity dimensions." },
    { word: "LGBTQ+ rights", translation: "droits LGBTQ+", example: "LGBTQ+ rights have advanced unevenly globally, with progress in some regions amid continued criminalization elsewhere." },
    { word: "toxic masculinity", translation: "masculinité toxique", example: "The concept of toxic masculinity identifies harmful behavioral norms rather than condemning masculinity itself." },
    { word: "patriarchal structures", translation: "structures patriarcales", example: "Patriarchal structures persist through both explicit discrimination and implicit assumptions about leadership and authority." },
    { word: "religious pluralism", translation: "pluralisme religieux", example: "Democratic societies navigate religious pluralism through balancing free exercise with secular governance." },
    { word: "secularization", translation: "sécularisation", example: "Secularization trends vary significantly across different regions and cultural contexts." },
    { word: "religious fundamentalism", translation: "fondamentalisme religieux", example: "Religious fundamentalism often emerges as defensive reaction against perceived threats to traditional values." },
    { word: "traditionalism", translation: "traditionalisme", example: "Traditionalism emphasizes continuity with established cultural practices and historical norms." },
    { word: "cultural conservatism", translation: "conservatisme culturel", example: "Cultural conservatism prioritizes preservation of traditional values and social structures amid rapid change." },
    { word: "progressive values", translation: "valeurs progressistes", example: "Progressive values emphasize equality, individual autonomy, and openness to social change." },
    
    // Défis contemporains et perspectives critiques (50 mots)
    { word: "techno-social transformation", translation: "transformation techno-sociale", example: "Digital platforms drive techno-social transformation through reshaping communication patterns and market structures." },
    { word: "algorithmic governance", translation: "gouvernance algorithmique", example: "Algorithmic governance shifts decision authority from human judgment to automated systems." },
    { word: "platform economy", translation: "économie des plateformes", example: "The platform economy reorganizes industries through intermediaries rather than direct service provision." },
    { word: "digital capitalism", translation: "capitalisme numérique", example: "Digital capitalism relies on data extraction and behavioral prediction as core business models." },
    { word: "surveillance capitalism", translation: "capitalisme de surveillance", example: "Surveillance capitalism monetizes behavioral data for prediction and influence of future behavior." },
    { word: "digital sovereignty", translation: "souveraineté numérique", example: "Nations increasingly assert digital sovereignty through data localization and infrastructure control." },
    { word: "automation", translation: "automatisation", example: "Workplace automation displaces routine tasks while potentially creating new complementary roles." },
    { word: "algorithmic bias", translation: "biais algorithmique", example: "Algorithmic bias reflects and potentially amplifies existing social inequalities in automated decisions." },
    { word: "technological determinism", translation: "déterminisme technologique", example: "Technological determinism overstates technology's independent influence while understating social and political factors." },
    { word: "social construction of technology", translation: "construction sociale de la technologie", example: "The social construction of technology emphasizes how cultural values and power relationships shape technological development." },
    { word: "techno-utopianism", translation: "techno-utopisme", example: "Techno-utopianism overestimates technology's capacity to solve complex social problems." },
    { word: "digital divide", translation: "fracture numérique", example: "The digital divide encompasses access, skills, and beneficial usage of information technologies." },
    { word: "information disorder", translation: "désordre informationnel", example: "Information disorder includes misinformation, disinformation, and malinformation in digital ecosystems." },
    { word: "epistemic crisis", translation: "crise épistémique", example: "Social media dynamics contribute to epistemic crisis through undermining shared factual foundations." },
    { word: "echo chamber", translation: "chambre d'écho", example: "Echo chambers reinforce existing beliefs through exposure to confirming information and viewpoints." },
    { word: "polarization", translation: "polarisation", example: "Political polarization increases through both ideological sorting and affective hostility toward opponents." },
    { word: "media fragmentation", translation: "fragmentation médiatique", example: "Media fragmentation enables customized information environments reflecting individual preferences." },
    { word: "civic discourse", translation: "discours civique", example: "Healthy civic discourse requires both exposure to diverse perspectives and shared commitment to factual accuracy." },
    { word: "epistemic community", translation: "communauté épistémique", example: "Scientific epistemic communities establish knowledge through rigorous methodology and peer review." },
    { word: "public sphere", translation: "sphère publique", example: "The digital public sphere operates differently from traditional media environments in structure and norms." },
    { word: "institutional trust", translation: "confiance institutionnelle", example: "Declining institutional trust affects both government legitimacy and social cooperation capacity." },
    { word: "crisis of expertise", translation: "crise de l'expertise", example: "The crisis of expertise reflects contested authority of specialized knowledge in public decision-making." },
    { word: "post-truth politics", translation: "politique post-vérité", example: "Post-truth politics prioritizes emotional resonance over factual accuracy in public discourse." },
    { word: "democracy erosion", translation: "érosion démocratique", example: "Democracy erosion occurs gradually through institutional weakening rather than dramatic regime change." },
    { word: "populism", translation: "populisme", example: "Populist movements position 'the people' against corrupt elites while claiming exclusive representation legitimacy." },
    { word: "nativism", translation: "nativisme", example: "Nativist rhetoric defines national identity through exclusion of perceived outsiders and minorities." },
    { word: "illiberal democracy", translation: "démocratie illibérale", example: "Illiberal democracy maintains electoral processes while undermining independent institutions and minority rights." },
    { word: "constitutional regression", translation: "régression constitutionnelle", example: "Constitutional regression involves systematic weakening of checks and balances and rule of law principles." },
    { word: "authoritarianism", translation: "autoritarisme", example: "Modern authoritarianism maintains democratic façades while ensuring ruling party dominance." },
    { word: "civil society", translation: "société civile", example: "Vibrant civil society provides both government accountability and social capital development." },
    { word: "civic space", translation: "espace civique", example: "Protecting civic space ensures citizens' rights to organize, speak freely, and participate in governance." },
    { word: "deliberative democracy", translation: "démocratie délibérative", example: "Deliberative democracy emphasizes informed discussion and reasoning rather than mere preference aggregation." },
    { word: "participatory governance", translation: "gouvernance participative", example: "Participatory governance includes citizens directly in decision processes beyond periodic voting." },
    { word: "community resilience", translation: "résilience communautaire", example: "Community resilience develops through both social connections and material resource access." },
    { word: "climate justice", translation: "justice climatique", example: "Climate justice addresses inequitable distribution of both climate impacts and transition costs." },
    { word: "just transition", translation: "transition juste", example: "Just transition frameworks protect vulnerable workers and communities during environmental policy shifts." },
    { word: "sustainable development", translation: "développement durable", example: "Sustainable development balances current needs with preserving options for future generations." },
    { word: "post-growth economics", translation: "économie post-croissance", example: "Post-growth economics questions perpetual expansion assumptions in traditional economic models." },
    { word: "wellbeing economy", translation: "économie du bien-être", example: "Wellbeing economy frameworks prioritize quality of life indicators beyond GDP growth." },
    { word: "financialization", translation: "financiarisation", example: "Financialization shifts economic activity from production toward financial instruments and services." },
    { word: "neoliberalism", translation: "néolibéralisme", example: "Neoliberal policies emphasize market mechanisms, privatization, and limited state intervention." },
    { word: "economic orthodoxy", translation: "orthodoxie économique", example: "Challenging economic orthodoxy requires questioning fundamental assumptions about markets and efficiency." },
    { word: "market fundamentalism", translation: "fondamentalisme du marché", example: "Market fundamentalism attributes greater efficiency to private enterprise regardless of context." },
    { word: "public goods", translation: "biens publics", example: "Public goods create shared benefit without rivalry or exclusion, complicating market provision." },
    { word: "commons", translation: "biens communs", example: "Managing commons sustainably requires governance beyond both state control and privatization." },
    { word: "solidarity economy", translation: "économie solidaire", example: "Solidarity economy models prioritize cooperation and social value over profit maximization." },
    { word: "community wealth building", translation: "construction de richesse communautaire", example: "Community wealth building strategies develop local ownership and asset democratization." },
    { word: "stakeholder capitalism", translation: "capitalisme des parties prenantes", example: "Stakeholder capitalism considers interests beyond shareholders including workers, communities, and environment." },
    { word: "corporate social responsibility", translation: "responsabilité sociale des entreprises", example: "Meaningful corporate social responsibility integrates social concerns into core business rather than peripheral initiatives." },
    { word: "path dependency", translation: "dépendance au sentier", example: "Path dependency explains how historical decisions constrain future options through established systems." },
    
    // Approches et solutions (50 mots)
    { word: "systems thinking", translation: "pensée systémique", example: "Systems thinking addresses complex social challenges by examining interconnections rather than isolated factors." },
    { word: "holistic approach", translation: "approche holistique", example: "Homelessness requires holistic approaches addressing housing, mental health, employment, and social support." },
    { word: "interdisciplinary perspective", translation: "perspective interdisciplinaire", example: "Climate solutions require interdisciplinary perspectives integrating scientific, economic, and social dimensions." },
    { word: "evidence-based policy", translation: "politique fondée sur des données probantes", example: "Evidence-based policy prioritizes empirical research over ideological assumptions or anecdote." },
    { word: "policy innovation", translation: "innovation politique", example: "Policy innovation adapts governance approaches to emerging challenges and contextual realities." },
    { word: "best practices", translation: "meilleures pratiques", example: "Identifying best practices requires careful contextual adaptation rather than simple replication." },
    { word: "scaling solutions", translation: "mise à l'échelle des solutions", example: "Scaling solutions beyond pilot programs requires addressing institutional and resource constraints." },
    { word: "social innovation", translation: "innovation sociale", example: "Social innovation develops novel approaches to persistent challenges unaddressed by existing systems." },
    { word: "cross-sector collaboration", translation: "collaboration intersectorielle", example: "Complex social problems require cross-sector collaboration between government, business, and civil society." },
    { word: "collective impact", translation: "impact collectif", example: "Collective impact frameworks coordinate multiple stakeholders toward shared objectives with mutually reinforcing activities." },
    { word: "social entrepreneurship", translation: "entrepreneuriat social", example: "Social entrepreneurship applies business approaches to addressing social and environmental challenges." },
    { word: "community development", translation: "développement communautaire", example: "Effective community development builds on existing assets rather than imposing external solutions." },
    { word: "grassroots mobilization", translation: "mobilisation populaire", example: "Grassroots mobilization harnesses local knowledge and relationships for collective action." },
    { word: "participatory approach", translation: "approche participative", example: "Participatory approaches involve affected communities throughout problem definition and solution development." },
    { word: "co-production", translation: "co-production", example: "Service co-production engages users as active participants rather than passive recipients." },
    { word: "community-based organization", translation: "organisation communautaire", example: "Community-based organizations operate with deep local knowledge and relational networks." },
    { word: "capacity building", translation: "renforcement des capacités", example: "Capacity building develops local skills and infrastructure for sustainable problem-solving." },
    { word: "human-centered design", translation: "conception centrée sur l'humain", example: "Human-centered design begins with understanding affected people's experiences and perspectives." },
    { word: "design thinking", translation: "pensée design", example: "Design thinking employs iterative prototyping and testing to refine solutions based on user feedback." },
    { word: "change management", translation: "gestion du changement", example: "Institutional transformation requires structured change management addressing both technical and adaptive challenges." },
    { word: "adaptive leadership", translation: "leadership adaptatif", example: "Adaptive leadership mobilizes people to address challenges requiring behavioral and value changes." },
    { word: "technical problem", translation: "problème technique", example: "Technical problems can be solved through existing knowledge and authority structures." },
    { word: "adaptive challenge", translation: "défi adaptatif", example: "Adaptive challenges require changes in values, relationships, and perspectives rather than technical expertise alone." },
    { word: "transformational change", translation: "changement transformationnel", example: "Transformational change addresses root causes rather than symptoms of social problems." },
    { word: "incremental change", translation: "changement incrémental", example: "Incremental change accumulates small improvements while maintaining system stability." },
    { word: "theory of change", translation: "théorie du changement", example: "A robust theory of change articulates logical connections between activities and intended outcomes." },
    { word: "impact assessment", translation: "évaluation d'impact", example: "Rigorous impact assessment distinguishes correlation from causal effects of interventions." },
    { word: "implementation science", translation: "science de la mise en œuvre", example: "Implementation science examines how interventions translate from controlled studies to real-world contexts." },
    { word: "social impact measurement", translation: "mesure de l'impact social", example: "Social impact measurement captures both intended and unintended consequences across stakeholders." },
    { word: "evaluation framework", translation: "cadre d'évaluation", example: "Comprehensive evaluation frameworks include process, outcome, and impact dimensions." },
    { word: "outcome metrics", translation: "indicateurs de résultats", example: "Selecting appropriate outcome metrics requires balancing measurement feasibility with meaningful representation." },
    { word: "strategic philanthropy", translation: "philanthropie stratégique", example: "Strategic philanthropy addresses root causes through systemic change rather than symptomatic relief." },
    { word: "venture philanthropy", translation: "philanthropie de risque", example: "Venture philanthropy applies investment principles to social impact through long-term engagement and capacity building." },
    { word: "impact investing", translation: "investissement à impact", example: "Impact investing seeks both financial returns and measurable social or environmental benefits." },
    { word: "ethical consumerism", translation: "consommation éthique", example: "Ethical consumerism leverages purchasing decisions to promote social and environmental responsibility." },
    { word: "corporate accountability", translation: "responsabilité des entreprises", example: "Corporate accountability mechanisms include both regulatory requirements and stakeholder pressure." },
    { word: "social license", translation: "permis social", example: "Operating without social license risks community opposition despite formal regulatory approval." },
    { word: "multi-stakeholder initiative", translation: "initiative multipartite", example: "Multi-stakeholder initiatives develop standards and accountability mechanisms across industry participants." },
    { word: "public-private partnership", translation: "partenariat public-privé", example: "Public-private partnerships leverage complementary capabilities toward shared objectives." },
    { word: "systemic intervention", translation: "intervention systémique", example: "Systemic interventions address underlying structures rather than individual cases or symptoms." },
    { word: "leverage point", translation: "point de levier", example: "Effective change strategies identify leverage points where modest efforts produce significant system effects." },
    { word: "root cause analysis", translation: "analyse des causes profondes", example: "Root cause analysis distinguishes underlying drivers from proximate symptoms or triggers." },
    { word: "systemic barrier", translation: "barrière systémique", example: "Addressing systemic barriers requires institutional reform rather than individual accommodation." },
    { word: "emergence", translation: "émergence", example: "Complex systems exhibit emergence where collective patterns arise from decentralized interactions." },
    { word: "unintended consequence", translation: "conséquence imprévue", example: "Policy interventions often produce unintended consequences through system adaptation and feedback loops." },
    { word: "stakeholder engagement", translation: "engagement des parties prenantes", example: "Meaningful stakeholder engagement involves co-creation rather than mere consultation." },
    { word: "bottom-up approach", translation: "approche ascendante", example: "Bottom-up approaches harness local knowledge and agency rather than imposing external solutions." },
    { word: "community ownership", translation: "appropriation communautaire", example: "Sustainable interventions foster community ownership rather than dependency on external support." },
    { word: "social cohesion", translation: "cohésion sociale", example: "Building social cohesion requires both bridging divides and addressing structural inequalities." },
    { word: "societal resilience", translation: "résilience sociétale", example: "Societal resilience enables adaptive response to shocks through both social capital and institutional capacity." }
  ]
};