export const vocab = {
  title: "Nuances Linguistiques et Registres",
  words: [
    // Registres de langue et variations stylistiques (50 mots)
    { word: "formal register", translation: "registre soutenu", example: "Diplomatic correspondence employs a formal register characterized by conventional phrasing and circumlocution." },
    { word: "informal register", translation: "registre familier", example: "Team meetings often employ an informal register to foster open communication." },
    { word: "colloquial language", translation: "langage familier", example: "The advertisement deliberately used colloquial language to appear relatable to younger consumers." },
    { word: "vernacular", translation: "vernaculaire", example: "The local vernacular includes specific terms for environmental features not found elsewhere." },
    { word: "slang", translation: "argot", example: "Professional communities develop specialized slang that serves as both shorthand and marker of group identity." },
    { word: "jargon", translation: "jargon", example: "Medical jargon creates precision for practitioners but can confuse patients without proper explanation." },
    { word: "euphemism", translation: "euphémisme", example: "Corporate communications often employ euphemisms like 'workforce adjustment' instead of 'layoffs'." },
    { word: "dysphemism", translation: "dysphémisme", example: "Political rhetoric sometimes uses dysphemisms to negatively characterize opponents' policies." },
    { word: "colloquialism", translation: "expression familière", example: "The presentation was peppered with colloquialisms that didn't translate well for the international audience." },
    { word: "bureaucratese", translation: "langage administratif", example: "Government documents written in impenetrable bureaucratese often obscure rather than clarify policies." },
    { word: "legalese", translation: "jargon juridique", example: "The contract's legalese required translation into plain language for non-specialist stakeholders." },
    { word: "academese", translation: "jargon académique", example: "Scientific breakthroughs described in dense academese remain inaccessible to the general public." },
    { word: "corporate speak", translation: "langage d'entreprise", example: "The memo was filled with corporate speak about 'synergies' and 'strategic alignment'." },
    { word: "technobabble", translation: "jargon technique", example: "The IT presentation contained unnecessary technobabble that confused rather than informed executives." },
    { word: "officialese", translation: "langage officiel", example: "Government communications written in stilted officialese often fail to engage citizens effectively." },
    { word: "regionalisms", translation: "régionalismes", example: "His speech contained subtle regionalisms that identified his geographic origins." },
    { word: "sociolect", translation: "sociolecte", example: "Each professional community develops its own sociolect reflecting specialized knowledge and priorities." },
    { word: "idiolect", translation: "idiolecte", example: "Authors develop a distinctive idiolect that makes their writing recognizable even without attribution." },
    { word: "argot", translation: "argot", example: "Street argot evolves rapidly, with terms gaining and losing currency within months." },
    { word: "cant", translation: "jargon spécialisé", example: "The philosophical cant employed by the speakers excluded those without specialized education." },
    { word: "technical vocabulary", translation: "vocabulaire technique", example: "Effective science communication translates technical vocabulary into accessible explanations." },
    { word: "specialized terminology", translation: "terminologie spécialisée", example: "Medical translators must master specialized terminology in both languages." },
    { word: "archaic language", translation: "langage archaïque", example: "Legal documents often preserve archaic language for its precise established meanings." },
    { word: "neologism", translation: "néologisme", example: "Technology companies frequently coin neologisms to describe their innovative products." },
    { word: "buzzword", translation: "mot à la mode", example: "The presentation was filled with industry buzzwords but lacked substantive content." },
    { word: "platitude", translation: "platitude", example: "The speech relied on political platitudes rather than addressing specific policy questions." },
    { word: "cliché", translation: "cliché", example: "Effective writing avoids clichés, which signal intellectual laziness to sophisticated readers." },
    { word: "idiom", translation: "expression idiomatique", example: "Non-native speakers may understand individual words but misinterpret idioms with figurative meanings." },
    { word: "proverb", translation: "proverbe", example: "Traditional proverbs encode cultural wisdom in memorable, often metaphorical language." },
    { word: "aphorism", translation: "aphorisme", example: "Business leaders often favor concise aphorisms that distill complex principles into quotable phrases." },
    { word: "malapropism", translation: "malapropisme", example: "His unintentional malapropism, using 'defunct' instead of 'distinct', created momentary confusion." },
    { word: "spoonerism", translation: "contrepèterie", example: "The nervous speaker produced an unfortunate spoonerism that amused rather than informed the audience." },
    { word: "eggcorn", translation: "substitution phonétique", example: "The document contained several eggcorns like 'for all intensive purposes' instead of 'for all intents and purposes'." },
    { word: "mondegreen", translation: "interprétation erronée", example: "Misheard lyrics are classic mondegreens that often persist despite correction." },
    { word: "catachresis", translation: "catachrèse", example: "The mixed metaphor represented a striking catachresis: 'This groundbreaking market will open new doors'." },
    { word: "calque", translation: "calque", example: "Many French technology terms are calques from English, literally translating component words." },
    { word: "portmanteau", translation: "mot-valise", example: "Business environments create portmanteaus like 'webinar' combining 'web' and 'seminar'." },
    { word: "back-formation", translation: "dérivation régressive", example: "'Edit' is a back-formation from 'editor', reversing the normal pattern of derivation." },
    { word: "blend", translation: "mot-valise", example: "'Brunch' is a blend that efficiently combines 'breakfast' and 'lunch'." },
    { word: "clipping", translation: "abréviation", example: "'Lab' is a common clipping of 'laboratory' in both technical and casual contexts." },
    { word: "diminutive", translation: "diminutif", example: "Using diminutives like 'Johnny' instead of 'John' creates a sense of informality or intimacy." },
    { word: "honorific", translation: "terme honorifique", example: "Different cultures have specific honorifics that acknowledge status and relationship in communication." },
    { word: "appellation", translation: "appellation", example: "Formal contexts require appropriate appellations when addressing distinguished individuals." },
    { word: "pseudonym", translation: "pseudonyme", example: "Authors may adopt pseudonyms for creative freedom or market positioning." },
    { word: "heteronym", translation: "hétéronyme", example: "Some writers develop heteronyms with distinct personalities and writing styles." },
    { word: "code-switching", translation: "alternance codique", example: "Bilingual professionals often engage in code-switching when technical terms are more precise in one language." },
    { word: "diglossia", translation: "diglossie", example: "Many societies exhibit diglossia, with different language varieties used in formal versus everyday contexts." },
    { word: "register variation", translation: "variation de registre", example: "Effective communicators employ register variation appropriate to different audiences and situations." },
    { word: "tonal shift", translation: "changement de ton", example: "The speaker employed a deliberate tonal shift to signal transition from information to persuasion." },
    { word: "collocation", translation: "collocation", example: "Non-native speakers often struggle with natural collocations like 'heavy rain' rather than 'strong rain'." },
    
    // Nuances sémantiques et pragmatiques (50 mots)
    { word: "semantic field", translation: "champ sémantique", example: "The report repeatedly drew from the semantic field of warfare, with 'strategies', 'targets', and 'campaigns'." },
    { word: "semantic range", translation: "étendue sémantique", example: "The semantic range of 'sustainability' has expanded beyond environmental concerns to include social and governance dimensions." },
    { word: "connotation", translation: "connotation", example: "Though 'stubborn' and 'persistent' denote similar traits, their connotations differ significantly." },
    { word: "denotation", translation: "dénotation", example: "The legal document focused on the precise denotation of terms rather than their emotional associations." },
    { word: "nuance", translation: "nuance", example: "Diplomatic language requires awareness of subtle nuances that may be interpreted differently across cultures." },
    { word: "undertone", translation: "sous-entendu", example: "Her critique carried an undertone of disapproval despite the superficially neutral language." },
    { word: "overtone", translation: "connotation", example: "The proposal's militaristic overtones provoked resistance from more pacifist board members." },
    { word: "subtext", translation: "sous-texte", example: "The negotiation's subtext concerned market position, though the explicit discussion focused on terms." },
    { word: "implication", translation: "implication", example: "The statement's legal implications weren't immediately apparent to non-specialist readers." },
    { word: "inference", translation: "inférence", example: "Readers make inferences based on cultural knowledge that may not transfer across contexts." },
    { word: "pragmatics", translation: "pragmatique", example: "Understanding pragmatics—how context affects meaning—is essential for cross-cultural communication." },
    { word: "presupposition", translation: "présupposition", example: "The question 'When did you stop manipulating data?' contains the presupposition that manipulation occurred." },
    { word: "implicature", translation: "implicature", example: "Saying 'The report is certainly thorough' may carry the implicature that it's excessively detailed." },
    { word: "hedging", translation: "atténuation", example: "Academic writing often employs hedging with phrases like 'may suggest' rather than definitive claims." },
    { word: "hyperbole", translation: "hyperbole", example: "Marketing materials frequently employ hyperbole that sophisticated consumers mentally adjust." },
    { word: "understatement", translation: "litote", example: "British communication often features understatement, describing major problems as 'a bit challenging'." },
    { word: "irony", translation: "ironie", example: "His ironic compliment on the 'efficiently designed' interface clearly conveyed his frustration with its complexity." },
    { word: "verbal irony", translation: "ironie verbale", example: "Her verbal irony—'Brilliant timing!'—made clear her displeasure with the late delivery." },
    { word: "situational irony", translation: "ironie situationnelle", example: "The cybersecurity firm experiencing a data breach represents perfect situational irony." },
    { word: "sarcasm", translation: "sarcasme", example: "His sarcastic 'Thanks for the prompt response' highlighted the three-week delay." },
    { word: "satire", translation: "satire", example: "The company newsletter included gentle satire of management buzzwords and initiatives." },
    { word: "parody", translation: "parodie", example: "The team created a parody of corporate training videos that highlighted absurd workplace policies." },
    { word: "ambiguity", translation: "ambiguïté", example: "Contract language should avoid ambiguity that could lead to multiple interpretations." },
    { word: "polysemy", translation: "polysémie", example: "The word 'development' exhibits polysemy, with different meanings in real estate, software, and humanitarian contexts." },
    { word: "homonymy", translation: "homonymie", example: "Financial documents must clarify potential homonymy, as terms like 'interest' have multiple meanings." },
    { word: "vagueness", translation: "imprécision", example: "Strategic vagueness in diplomacy allows flexibility, while in contracts it creates liability." },
    { word: "equivocation", translation: "équivoque", example: "The statement contained deliberate equivocation to maintain deniability while implying commitment." },
    { word: "semantic shift", translation: "glissement sémantique", example: "The term 'literally' has undergone semantic shift to sometimes mean its opposite, 'figuratively'." },
    { word: "amelioration", translation: "amélioration sémantique", example: "The word 'awesome' underwent amelioration from inspiring dread to expressing enthusiasm." },
    { word: "pejoration", translation: "péjoration", example: "Many terms for social groups have undergone pejoration, acquiring negative connotations over time." },
    { word: "generalization", translation: "généralisation", example: "The term 'hacker' underwent semantic generalization, expanding beyond enthusiasts to include malicious actors." },
    { word: "specialization", translation: "spécialisation", example: "The word 'influencer' has undergone specialization to refer specifically to social media personalities." },
    { word: "semantic narrowing", translation: "restriction sémantique", example: "'Meat' once meant any solid food but underwent semantic narrowing to mean animal flesh specifically." },
    { word: "semantic widening", translation: "élargissement sémantique", example: "The term 'green' underwent semantic widening from a color to environmental responsibility." },
    { word: "semantic bleaching", translation: "désémantisation", example: "The intensifier 'very' has undergone semantic bleaching, losing much of its original force." },
    { word: "metaphorical extension", translation: "extension métaphorique", example: "Financial terminology includes metaphorical extensions like 'market collapse' and 'bubble bursting'." },
    { word: "etymological fallacy", translation: "erreur étymologique", example: "Insisting 'decimate' must mean 'reduce by one-tenth' commits the etymological fallacy, ignoring current usage." },
    { word: "euphemistic treadmill", translation: "treadmill euphémistique", example: "Terms for disabilities exemplify the euphemistic treadmill, as each new term eventually acquires negative associations." },
    { word: "auto-antonym", translation: "auto-antonyme", example: "'Sanction' is an auto-antonym, meaning both 'to permit' and 'to penalize'." },
    { word: "contronym", translation: "contronyme", example: "'Oversight' is a contronym, meaning both 'supervision' and 'failure to notice'." },
    { word: "false friend", translation: "faux ami", example: "Between English and French, 'actuellement' is a false friend, meaning 'currently' not 'actually'." },
    { word: "false cognate", translation: "faux cognat", example: "English 'sensible' and French 'sensible' are false cognates despite appearing similar." },
    { word: "calque", translation: "calque", example: "The phrase 'losing face' entered English as a calque from Chinese expressions about dignity and reputation." },
    { word: "loan translation", translation: "calque", example: "'Skyscraper' has loan translations in many languages, such as French 'gratte-ciel' (scrape-sky)." },
    { word: "semantic loan", translation: "emprunt sémantique", example: "The computing sense of 'mouse' represents a semantic loan translated into many languages." },
    { word: "hypernym", translation: "hyperonyme", example: "'Vehicle' serves as a hypernym for more specific terms like 'car', 'truck', and 'motorcycle'." },
    { word: "hyponym", translation: "hyponyme", example: "'Smartphone' functions as a hyponym of the broader category 'mobile device'." },
    { word: "meronym", translation: "méronyme", example: "'Keyboard' is a meronym related to the whole 'computer' in part-whole relationships." },
    { word: "holonym", translation: "holonyme", example: "'Corporation' is a holonym containing meronyms like 'department', 'team', and 'employee'." },
    { word: "synonym", translation: "synonyme", example: "Precise writing chooses among synonyms based on subtle connotative differences." },
    
    // Figures de style et rhétorique (50 mots)
    { word: "metaphor", translation: "métaphore", example: "The executive described the merger as 'a marriage of complementary strengths' rather than a mere business transaction." },
    { word: "simile", translation: "comparaison", example: "The analyst described the market correction as 'like a pressure valve releasing built-up steam'." },
    { word: "analogy", translation: "analogie", example: "The professor explained neural networks through an analogy to the human brain's structure." },
    { word: "personification", translation: "personnification", example: "The report personified the economy as 'struggling to recover its footing' after the recession." },
    { word: "anthropomorphism", translation: "anthropomorphisme", example: "The company's anthropomorphism of its AI assistant created unrealistic expectations about its capabilities." },
    { word: "zoomorphism", translation: "zoomorphisme", example: "The critic's zoomorphism likened aggressive market actors to 'wolves preying on retail investors'." },
    { word: "synecdoche", translation: "synecdoque", example: "Referring to 'boots on the ground' uses synecdoche to represent soldiers by one item of their equipment." },
    { word: "metonymy", translation: "métonymie", example: "'The White House announced' employs metonymy, with the building representing the executive branch." },
    { word: "litotes", translation: "litote", example: "The British assessment that competition was 'not inconsiderable' employed litotes to convey significant threat." },
    { word: "hyperbole", translation: "hyperbole", example: "The advertisement's claim to 'revolutionize your entire life' was obvious hyperbole to sophisticated consumers." },
    { word: "meiosis", translation: "méiose", example: "Describing the catastrophic failure as 'a slight hiccup' was meiosis intended to downplay its severity." },
    { word: "oxymoron", translation: "oxymore", example: "The report described the situation as one of 'deafening silence' from regulatory authorities." },
    { word: "paradox", translation: "paradoxe", example: "The consultant noted the paradox that increased efficiency sometimes reduced overall productivity." },
    { word: "antithesis", translation: "antithèse", example: "The campaign slogan juxtaposed 'Less expense, more results' in a compelling antithesis." },
    { word: "parallelism", translation: "parallélisme", example: "The speech employed parallelism in 'Today we plan, tomorrow we build, and in the future we lead'." },
    { word: "anaphora", translation: "anaphore", example: "Each paragraph began with the anaphora 'We believe' to emphasize corporate values." },
    { word: "epistrophe", translation: "épistrophe", example: "The speech concluded each key point with the epistrophe 'and that matters' to reinforce importance." },
    { word: "chiasmus", translation: "chiasme", example: "The advertising slogan used chiasmus effectively: 'You don't own luxury; luxury owns you'." },
    { word: "asyndeton", translation: "asyndète", example: "The description employed asyndeton, eliminating conjunctions: 'Fast, efficient, reliable, proven'." },
    { word: "polysyndeton", translation: "polysyndète", example: "The contract used polysyndeton to emphasize inclusiveness: 'and profits and losses and risks and opportunities'." },
    { word: "ellipsis", translation: "ellipse", example: "The headline used ellipsis to create brevity: 'Markets Down, Investors [Are] Concerned'." },
    { word: "euphemism", translation: "euphémisme", example: "Corporate announcements referred to 'workforce optimization' rather than layoffs." },
    { word: "dysphemism", translation: "dysphémisme", example: "The critic used dysphemism, calling the gentle market decline a 'bloodbath'." },
    { word: "circumlocution", translation: "circonlocution", example: "The spokesperson employed circumlocution to avoid directly addressing the controversial policy change." },
    { word: "periphrasis", translation: "périphrase", example: "Instead of naming the competitor directly, the CEO used periphrasis: 'that firm across the river'." },
    { word: "tautology", translation: "tautologie", example: "The statement contained tautology: 'Free gift with purchase' (as gifts are inherently free)." },
    { word: "pleonasm", translation: "pléonasme", example: "The instructions included pleonasm for emphasis: 'Completely eliminate all instances'." },
    { word: "amplification", translation: "amplification", example: "The speech used amplification, expanding on each point with supporting details and examples." },
    { word: "enumeration", translation: "énumération", example: "The presentation employed enumeration to outline multiple benefits: 'First... Second... Finally...'." },
    { word: "climax", translation: "gradation", example: "The pitch built through climax: 'Good, better, best—never let it rest'." },
    { word: "anticlimax", translation: "anti-climax", example: "After listing major global problems, the anticlimax 'and slightly inconvenient parking' created comic effect." },
    { word: "bathos", translation: "bathos", example: "The serious presentation descended into unintentional bathos with an awkward joke about accounting practices." },
    { word: "pathos", translation: "pathos", example: "The charity appeal relied on pathos, showing emotional images of those needing assistance." },
    { word: "ethos", translation: "ethos", example: "The company established ethos by highlighting their decades of experience and industry recognition." },
    { word: "logos", translation: "logos", example: "The scientific presentation emphasized logos through data, statistics, and logical reasoning." },
    { word: "apostrophe", translation: "apostrophe", example: "The advertisement employed apostrophe, addressing the absent concept of 'Freedom' directly." },
    { word: "rhetorical question", translation: "question rhétorique", example: "The editorial asked, 'Can we truly afford to ignore climate change?' expecting no literal answer." },
    { word: "alliteration", translation: "allitération", example: "The marketing slogan used alliteration effectively: 'Performance, Power, Prestige'." },
    { word: "assonance", translation: "assonance", example: "The tagline employed assonance with repeated 'i' sounds: 'Quick thinking in critical minutes'." },
    { word: "consonance", translation: "consonance", example: "The brand name featured consonance with repeated 't' sounds: 'Bright Right Light'." },
    { word: "onomatopoeia", translation: "onomatopée", example: "The advertisement used onomatopoeia to represent the product's sound: 'The engine purrs perfectly'." },
    { word: "imagery", translation: "imagerie", example: "The report's vivid imagery described the market as 'awakening from hibernation'." },
    { word: "symbolism", translation: "symbolisme", example: "The corporate logo employed symbolism, with upward arrows representing growth and progress." },
    { word: "allusion", translation: "allusion", example: "The speech included an allusion to Churchill's famous 'blood, toil, tears and sweat' to evoke determination." },
    { word: "repetition", translation: "répétition", example: "The campaign repeatedly emphasized 'Trust' to establish brand association with reliability." },
    { word: "hypophora", translation: "hypophore", example: "The presentation used hypophora, raising questions then immediately answering them." },
    { word: "aposiopesis", translation: "aposiopèse", example: "The negotiator employed aposiopesis, trailing off with 'If you cannot meet our terms then...' to imply consequences." },
    { word: "anastrophe", translation: "anastrophe", example: "The slogan used anastrophe, inverting normal word order: 'Powerful it stands, efficient it runs'." },
    { word: "hypallage", translation: "hypallage", example: "The report contained hypallage in 'anxious markets' (markets don't feel anxiety; people do)." },
    { word: "zeugma", translation: "zeugme", example: "The executive's zeugma connected disparate items: 'She arrived with determination and a detailed plan'." },
    
    // Communication interculturelle et traduction (50 mots)
    { word: "high-context communication", translation: "communication à contexte fort", example: "Japanese business culture relies on high-context communication where much meaning is implicit rather than explicitly stated." },
    { word: "low-context communication", translation: "communication à contexte faible", example: "Germanic cultures typically employ low-context communication with explicit statements and limited reliance on implicit understanding." },
    { word: "cultural filter", translation: "filtre culturel", example: "Messages pass through cultural filters that affect how their meaning is interpreted across different societies." },
    { word: "pragmatic equivalence", translation: "équivalence pragmatique", example: "Effective translation maintains pragmatic equivalence, ensuring the text functions similarly in the target culture." },
    { word: "cultural adaptation", translation: "adaptation culturelle", example: "Marketing materials require cultural adaptation beyond mere linguistic translation." },
    { word: "localization", translation: "localisation", example: "Software localization involves adapting both language and cultural references for specific markets." },
    { word: "internationalization", translation: "internationalisation", example: "Effective internationalization designs products to accommodate multiple languages and cultural norms." },
    { word: "transcreation", translation: "transcréation", example: "Advertising campaigns often require transcreation rather than direct translation to maintain impact." },
    { word: "domestication", translation: "domestication", example: "This translation approach employs domestication, replacing foreign concepts with familiar cultural equivalents." },
    { word: "foreignization", translation: "foreignisation", example: "The translator preferred foreignization, preserving original cultural elements to expand readers' horizons." },
    { word: "cultural sensitivity", translation: "sensibilité culturelle", example: "Communications intended for global audiences require cultural sensitivity to avoid unintended offense." },
    { word: "cultural transferability", translation: "transférabilité culturelle", example: "Humor has limited cultural transferability, often requiring significant adaptation." },
    { word: "communication style", translation: "style de communication", example: "Americans typically employ a direct communication style, while many Asian cultures prefer indirect approaches." },
    { word: "cultural connotation", translation: "connotation culturelle", example: "Colors carry different cultural connotations—white signifies purity in Western contexts but mourning in some Eastern cultures." },
    { word: "cultural context", translation: "contexte culturel", example: "Messages must be interpreted within their cultural context rather than through the receiver's cultural lens." },
    { word: "linguistic relativity", translation: "relativité linguistique", example: "The concept of linguistic relativity suggests language influences perception and thought patterns." },
    { word: "untranslatability", translation: "intraduisibilité", example: "Some concepts exhibit untranslatability, requiring explanation rather than direct equivalent terms." },
    { word: "cultural competence", translation: "compétence culturelle", example: "Developing cultural competence requires awareness, knowledge, and adaptability in cross-cultural contexts." },
    { word: "cultural intelligence", translation: "intelligence culturelle", example: "Executives with high cultural intelligence adapt effectively to diverse business environments." },
    { word: "cultural dimension", translation: "dimension culturelle", example: "Hofstede's cultural dimensions provide frameworks for understanding cross-cultural differences in values." },
    { word: "power distance", translation: "distance hiérarchique", example: "Countries with high power distance maintain stricter hierarchical business structures with centralized decision-making." },
    { word: "uncertainty avoidance", translation: "évitement de l'incertitude", example: "Cultures with strong uncertainty avoidance typically prefer detailed contracts and explicit instructions." },
    { word: "individualism-collectivism", translation: "individualisme-collectivisme", example: "Western negotiation approaches reflect individualism, while East Asian approaches often reflect collectivism." },
    { word: "masculinity-femininity", translation: "masculinité-féminité", example: "Scandinavian cultures score low on masculinity, prioritizing cooperation over competition." },
    { word: "long-term orientation", translation: "orientation à long terme", example: "East Asian business strategies often reflect long-term orientation, focusing on sustainable growth over immediate profits." },
    { word: "indulgence versus restraint", translation: "indulgence contre retenue", example: "Marketing strategies must consider whether target markets lean toward indulgence or restraint." },
    { word: "monochronic culture", translation: "culture monochrone", example: "Germanic cultures tend to be monochronic, focusing on one task at a time and strict adherence to schedules." },
    { word: "polychronic culture", translation: "culture polychrone", example: "Mediterranean cultures often exhibit polychronic tendencies, comfortable with simultaneous activities and flexible scheduling." },
    { word: "direct communication", translation: "communication directe", example: "Northern European business communication values direct expression of viewpoints and explicit disagreement." },
    { word: "indirect communication", translation: "communication indirecte", example: "East Asian cultures often employ indirect communication to preserve harmony and avoid causing others to lose face." },
    { word: "ritualistic communication", translation: "communication rituelle", example: "Japanese business meetings follow ritualistic communication patterns with prescribed exchanges and formalities." },
    { word: "cultural frame of reference", translation: "cadre de référence culturel", example: "Effective cross-cultural communication requires awareness of differing cultural frames of reference." },
    { word: "linguistic determinism", translation: "déterminisme linguistique", example: "Strong linguistic determinism suggests language structures determine thought patterns and perception." },
    { word: "linguistic bias", translation: "biais linguistique", example: "Terminology often contains linguistic bias reflecting cultural assumptions and historical power dynamics." },
    { word: "code-switching", translation: "alternance codique", example: "Multilingual speakers engage in code-switching based on context, topic, and communication partners." },
    { word: "semantic gap", translation: "écart sémantique", example: "Translators navigate semantic gaps where concepts exist in one language but lack direct equivalents in another." },
    { word: "false cognate", translation: "faux ami", example: "'Actuellement' in French is a false cognate for English speakers, meaning 'currently' not 'actually'." },
    { word: "linguistic etiquette", translation: "étiquette linguistique", example: "Japanese linguistic etiquette includes complex honorifics reflecting social hierarchy and relationship." },
    { word: "cultural metaphor", translation: "métaphore culturelle", example: "Sports serve as cultural metaphors in American business language, with terms like 'touchdown' and 'home run'." },
    { word: "face-saving", translation: "préservation de la face", example: "Asian business communication prioritizes face-saving, avoiding direct criticism in public contexts." },
    { word: "ethnocentrism", translation: "ethnocentrisme", example: "Ethnocentrism in communication assumes one's cultural norms and values apply universally." },
    { word: "cultural relativism", translation: "relativisme culturel", example: "Cultural relativism evaluates practices within their own cultural context rather than by external standards." },
    { word: "enculturation", translation: "enculturation", example: "Communication styles reflect enculturation—the absorption of cultural norms through social experience." },
    { word: "acculturation", translation: "acculturation", example: "Expatriates undergo acculturation, adapting their communication to local norms over time." },
    { word: "cultural appropriation", translation: "appropriation culturelle", example: "Marketing campaigns must avoid cultural appropriation that uses cultural elements disrespectfully." },
    { word: "intercultural rhetoric", translation: "rhétorique interculturelle", example: "Intercultural rhetoric examines how argument structures and persuasive approaches vary across cultures." },
    { word: "contrastive rhetoric", translation: "rhétorique contrastive", example: "Contrastive rhetoric reveals that paragraph structure and argument development differ significantly across languages." },
    { word: "translation shift", translation: "transposition traductive", example: "Translation shifts occur when grammatical structures must change between source and target languages." },
    { word: "functional equivalence", translation: "équivalence fonctionnelle", example: "Translators seek functional equivalence, ensuring the text serves the same purpose in the target language." },
    { word: "communicative translation", translation: "traduction communicative", example: "Communicative translation prioritizes natural expression in the target language over literal accuracy." },
    
    // Style d'écriture et ton (50 mots)
    { word: "tone", translation: "ton", example: "The annual report maintained a confident tone despite acknowledging market challenges." },
    { word: "voice", translation: "voix", example: "The company developed a distinctive brand voice combining authority with accessibility." },
    { word: "register", translation: "registre", example: "Customer communications employ a conversational register while investor materials maintain formal language." },
    { word: "formality", translation: "formalité", example: "Email communications have evolved toward reduced formality, especially in technology sectors." },
    { word: "informality", translation: "informalité", example: "Strategic informality in executive communications can create impressions of authenticity and approachability." },
    { word: "active voice", translation: "voix active", example: "Effective documentation uses active voice to clarify responsibility: 'The team completed the project'." },
    { word: "passive voice", translation: "voix passive", example: "Legal documents often employ passive voice to emphasize actions rather than actors: 'Payments will be processed'." },
    { word: "direct address", translation: "adresse directe", example: "Marketing materials use direct address ('you') to create immediate connection with consumers." },
    { word: "third-person perspective", translation: "perspective à la troisième personne", example: "Academic writing traditionally maintains an objective third-person perspective." },
    { word: "authorial presence", translation: "présence auctoriale", example: "Modern business communications often feature stronger authorial presence than traditional corporate writing." },
    { word: "authorial intrusion", translation: "intrusion auctoriale", example: "The report's occasional authorial intrusion provided insight into the research process." },
    { word: "narrative voice", translation: "voix narrative", example: "Case studies employ narrative voice to transform data into engaging customer stories." },
    { word: "expository writing", translation: "écriture explicative", example: "Technical documentation uses expository writing to clarify complex processes and relationships." },
    { word: "descriptive writing", translation: "écriture descriptive", example: "Product specifications combine technical detail with descriptive writing to convey experiential qualities." },
    { word: "persuasive writing", translation: "écriture persuasive", example: "The proposal employed persuasive writing techniques including evidence, emotion, and credibility appeals." },
    { word: "conciseness", translation: "concision", example: "Executive summaries prioritize conciseness, distilling complex information into essential points." },
    { word: "verbosity", translation: "verbosité", example: "Legal documents often suffer from unnecessary verbosity that obscures meaning for non-specialists." },
    { word: "prolixity", translation: "prolixité", example: "The consultant's prolixity undermined his message despite his evident expertise." },
    { word: "succinctness", translation: "concision", example: "Crisis communications require succinctness to ensure key information receives attention." },
    { word: "brevity", translation: "brièveté", example: "Social media communications value brevity while conveying complete messages." },
    { word: "economy of language", translation: "économie de langage", example: "Advertising copy demonstrates economy of language, maximizing impact with minimal text." },
    { word: "redundancy", translation: "redondance", example: "Technical writing sometimes employs strategic redundancy to reinforce critical information." },
    { word: "circumlocution", translation: "circonlocution", example: "Political statements often use circumlocution to avoid direct commitment on controversial issues." },
    { word: "directness", translation: "franchise", example: "Northern European business communication values directness over diplomatic ambiguity." },
    { word: "indirectness", translation: "caractère indirect", example: "Asian business communication often employs indirectness to preserve harmony and face." },
    { word: "precision", translation: "précision", example: "Scientific writing requires terminological precision to prevent misinterpretation." },
    { word: "vagueness", translation: "imprécision", example: "Some diplomatic language intentionally employs vagueness to maintain flexibility in interpretation." },
    { word: "specificity", translation: "spécificité", example: "Contract language requires specificity to prevent disputes over implementation." },
    { word: "ambiguity", translation: "ambiguïté", example: "Negotiators sometimes strategically employ ambiguity to create space for later interpretation." },
    { word: "clarity", translation: "clarté", example: "Effective instructions prioritize clarity over stylistic elegance." },
    { word: "obscurity", translation: "obscurité", example: "Academic writing is often criticized for unnecessary obscurity that limits accessibility." },
    { word: "accessibility", translation: "accessibilité", example: "Public health communications must maintain accessibility for diverse education levels." },
    { word: "simplicity", translation: "simplicité", example: "Design documentation balances simplicity with comprehensive information." },
    { word: "complexity", translation: "complexité", example: "Some legal complexity is unavoidable when addressing nuanced regulatory requirements." },
    { word: "technical density", translation: "densité technique", example: "Research papers exhibit high technical density appropriate for specialist audiences." },
    { word: "jargon density", translation: "densité de jargon", example: "Effective science communication reduces jargon density for general audiences." },
    { word: "readability", translation: "lisibilité", example: "Content strategists analyze readability metrics to ensure appropriateness for target audiences." },
    { word: "cadence", translation: "cadence", example: "Effective speeches employ varied cadence to maintain audience engagement." },
    { word: "rhythm", translation: "rythme", example: "Professional writers develop distinctive rhythm through sentence length variation and strategic pauses." },
    { word: "flow", translation: "fluidité", example: "Well-structured documents maintain logical flow between concepts and sections." },
    { word: "coherence", translation: "cohérence", example: "Effective reports maintain coherence through clear reasoning and transitional elements." },
    { word: "cohesion", translation: "cohésion", example: "Document cohesion depends on appropriate connector words and referential clarity." },
    { word: "transitional elements", translation: "éléments de transition", example: "Sophisticated writing uses varied transitional elements beyond simple sequential markers." },
    { word: "signposting", translation: "balisage", example: "Complex presentations require explicit signposting to guide audience understanding." },
    { word: "parallelism", translation: "parallélisme", example: "Effective lists maintain strict parallelism in grammatical structure." },
    { word: "sentence variety", translation: "variété phrastique", example: "Professional writing employs sentence variety to maintain reader engagement." },
    { word: "sentence complexity", translation: "complexité phrastique", example: "Legal documents often feature extreme sentence complexity that challenges comprehension." },
    { word: "syntactic sophistication", translation: "sophistication syntaxique", example: "Advanced writing demonstrates syntactic sophistication without sacrificing clarity." },
    { word: "paragraph structure", translation: "structure des paragraphes", example: "Effective persuasive writing employs strategic paragraph structure with strong topic sentences." }
  ]
};