export const vocab = {
  title: "Géopolitique Contemporaine",
  words: [
    // Relations internationales et ordre mondial (50 mots)
    { word: "power dynamics", translation: "dynamiques de pouvoir", example: "Shifting power dynamics in the Indo-Pacific region have prompted strategic realignments among regional actors." },
    { word: "multipolarity", translation: "multipolarité", example: "The emerging multipolarity challenges the post-Cold War international order established in the 1990s." },
    { word: "strategic autonomy", translation: "autonomie stratégique", example: "The European Union pursues strategic autonomy while maintaining transatlantic cooperation on security matters." },
    { word: "hegemonic decline", translation: "déclin hégémonique", example: "Scholars debate whether current global tensions reflect American hegemonic decline or strategic retrenchment." },
    { word: "balance of power", translation: "équilibre des puissances", example: "Regional security architectures aim to maintain a balance of power to prevent any single actor's dominance." },
    { word: "spheres of influence", translation: "sphères d'influence", example: "Major powers increasingly assert spheres of influence in their geographical proximity." },
    { word: "geopolitical rivalry", translation: "rivalité géopolitique", example: "Sino-American geopolitical rivalry has intensified across diplomatic, economic, and technological domains." },
    { word: "great power competition", translation: "compétition entre grandes puissances", example: "Great power competition has replaced terrorism as the primary focus of security strategies." },
    { word: "strategic partnership", translation: "partenariat stratégique", example: "The strategic partnership between the countries encompasses defense cooperation and intelligence sharing." },
    { word: "rules-based order", translation: "ordre fondé sur des règles", example: "Democratic nations advocate for preserving the rules-based order against authoritarian challenges." },
    { word: "revisionist power", translation: "puissance révisionniste", example: "Revisionist powers seek to reshape international norms and institutions to better serve their interests." },
    { word: "status quo power", translation: "puissance du statu quo", example: "Status quo powers typically defend existing international arrangements that benefit their position." },
    { word: "multilateralism", translation: "multilatéralisme", example: "Effective climate action requires renewed commitment to multilateralism despite nationalist headwinds." },
    { word: "unilateralism", translation: "unilatéralisme", example: "The country's unilateralism undermined coalition-building efforts for the regional initiative." },
    { word: "intergovernmental organization", translation: "organisation intergouvernementale", example: "Intergovernmental organizations face legitimacy challenges in addressing transnational problems." },
    { word: "supranational institution", translation: "institution supranationale", example: "Supranational institutions like the European Union exercise authority partially independent from member states." },
    { word: "institutional architecture", translation: "architecture institutionnelle", example: "The post-war institutional architecture requires modernization to address contemporary challenges." },
    { word: "global governance", translation: "gouvernance mondiale", example: "Effective global governance remains elusive despite the proliferation of international organizations." },
    { word: "security dilemma", translation: "dilemme de sécurité", example: "Arms buildups reflect the security dilemma where defensive measures appear threatening to others." },
    { word: "deterrence", translation: "dissuasion", example: "Nuclear deterrence remains a cornerstone of strategic doctrine despite non-proliferation efforts." },
    { word: "strategic ambiguity", translation: "ambiguïté stratégique", example: "Strategic ambiguity characterizes policy toward the contested territory, neither confirming nor denying defense commitments." },
    { word: "coercive diplomacy", translation: "diplomatie coercitive", example: "The administration employed coercive diplomacy, combining economic sanctions with military posturing." },
    { word: "soft power", translation: "puissance douce", example: "The country's soft power derives from its cultural exports and educational institutions rather than military capabilities." },
    { word: "hard power", translation: "puissance dure", example: "Hard power deployment including naval exercises demonstrated resolve in the territorial dispute." },
    { word: "smart power", translation: "puissance intelligente", example: "Effective foreign policy requires smart power, strategically combining diplomatic, economic, and military tools." },
    { word: "sharp power", translation: "puissance incisive", example: "Authoritarian regimes employ sharp power to manipulate information environments in democratic societies." },
    { word: "proxy conflict", translation: "conflit par procuration", example: "Regional powers wage proxy conflicts to advance interests without direct military confrontation." },
    { word: "hybrid warfare", translation: "guerre hybride", example: "Hybrid warfare combines conventional military action with cyber operations and disinformation campaigns." },
    { word: "gray zone operations", translation: "opérations en zone grise", example: "Gray zone operations remain deliberately below the threshold of open warfare while advancing strategic objectives." },
    { word: "asymmetric threat", translation: "menace asymétrique", example: "Non-state actors pose asymmetric threats that conventional military doctrines struggle to address." },
    { word: "strategic communication", translation: "communication stratégique", example: "Strategic communication coordinates messaging across diplomatic, military, and public channels." },
    { word: "diplomatic leverage", translation: "levier diplomatique", example: "Economic ties provide diplomatic leverage in negotiations over security arrangements." },
    { word: "power projection", translation: "projection de puissance", example: "Naval modernization enhances the country's power projection capabilities in disputed waters." },
    { word: "nuclear proliferation", translation: "prolifération nucléaire", example: "International regimes aim to prevent nuclear proliferation while permitting civilian energy development." },
    { word: "arms control", translation: "contrôle des armements", example: "Arms control agreements establish verification mechanisms to build mutual confidence." },
    { word: "collective security", translation: "sécurité collective", example: "The alliance operates on collective security principles where an attack on one constitutes an attack on all." },
    { word: "peace dividend", translation: "dividendes de la paix", example: "The anticipated peace dividend after conflict resolution was redirected to security sector reform." },
    { word: "security architecture", translation: "architecture de sécurité", example: "Regional security architecture includes formal alliances and informal consultative mechanisms." },
    { word: "defensive realism", translation: "réalisme défensif", example: "Defensive realism suggests states prioritize security rather than power maximization in foreign policy." },
    { word: "offensive realism", translation: "réalisme offensif", example: "Offensive realism posits that uncertainty compels states to maximize power for survival." },
    { word: "constructivist approach", translation: "approche constructiviste", example: "Constructivist approaches emphasize how shared ideas and identities shape international relations." },
    { word: "institutional liberalism", translation: "libéralisme institutionnel", example: "Institutional liberalism highlights how international organizations constrain state behavior through rules-based cooperation." },
    { word: "polarity", translation: "polarité", example: "Analysts debate whether current international polarity is best described as bipolar, multipolar, or nonpolar." },
    { word: "grand strategy", translation: "grande stratégie", example: "The nation's grand strategy coordinates diplomatic, economic, and military instruments toward long-term objectives." },
    { word: "strategic culture", translation: "culture stratégique", example: "Strategic culture shapes how political leaders perceive threats and appropriate responses based on historical experience." },
    { word: "zero-sum perspective", translation: "perspective à somme nulle", example: "Zero-sum perspectives in international relations view one state's gain as necessarily another's loss." },
    { word: "geopolitical forecasting", translation: "prospective géopolitique", example: "Geopolitical forecasting employs scenario planning to anticipate future international developments." },
    { word: "diplomatic mission", translation: "mission diplomatique", example: "The diplomatic mission engaged in back-channel negotiations while public positions remained unchanged." },
    { word: "rapprochement", translation: "rapprochement", example: "The rapprochement between former adversaries altered regional security calculations." },
    
    // Défis géopolitiques régionaux (50 mots)
    { word: "territorial dispute", translation: "différend territorial", example: "Overlapping maritime claims fuel the territorial dispute despite international arbitration efforts." },
    { word: "contested sovereignty", translation: "souveraineté contestée", example: "The region's contested sovereignty complicates international recognition and development assistance." },
    { word: "secessionist movement", translation: "mouvement sécessionniste", example: "The secessionist movement gained momentum following the government's centralization policies." },
    { word: "irredentism", translation: "irrédentisme", example: "Historical irredentism continues to influence nationalist rhetoric and territorial claims." },
    { word: "strategic chokepoint", translation: "point d'étranglement stratégique", example: "Control over the strategic chokepoint provides leverage over international shipping routes." },
    { word: "buffer state", translation: "État tampon", example: "The small nation has historically functioned as a buffer state between competing regional powers." },
    { word: "frozen conflict", translation: "conflit gelé", example: "The frozen conflict persists without active hostilities but without formal resolution." },
    { word: "ethnic enclave", translation: "enclave ethnique", example: "The ethnic enclave maintains cultural and political ties to neighboring states despite territorial separation." },
    { word: "regional hegemony", translation: "hégémonie régionale", example: "The country's pursuit of regional hegemony alarms smaller neighbors and external powers." },
    { word: "strategic depth", translation: "profondeur stratégique", example: "Mountainous terrain provides strategic depth against potential invaders despite limited territorial size." },
    { word: "forward deployment", translation: "déploiement avancé", example: "Forward deployment positions military assets near potential conflict zones as a deterrent measure." },
    { word: "anti-access/area denial", translation: "déni d'accès et interdiction de zone", example: "Anti-access/area denial capabilities aim to prevent adversaries from operating freely in contested regions." },
    { word: "freedom of navigation", translation: "liberté de navigation", example: "Naval patrols assert freedom of navigation rights in disputed maritime zones." },
    { word: "exclusive economic zone", translation: "zone économique exclusive", example: "Overlapping claims to exclusive economic zones generate tensions over resource exploitation rights." },
    { word: "insurgency", translation: "insurrection", example: "The rural insurgency exploits government weaknesses and local grievances to mobilize support." },
    { word: "counterinsurgency", translation: "contre-insurrection", example: "Effective counterinsurgency combines security operations with political and economic development." },
    { word: "asymmetric warfare", translation: "guerre asymétrique", example: "Non-state actors employ asymmetric warfare tactics against conventionally superior forces." },
    { word: "strategic patience", translation: "patience stratégique", example: "The policy of strategic patience aims to avoid provocative actions while maintaining defensive readiness." },
    { word: "humanitarian intervention", translation: "intervention humanitaire", example: "Debates over humanitarian intervention balance sovereignty concerns against protection responsibilities." },
    { word: "responsibility to protect", translation: "responsabilité de protéger", example: "The responsibility to protect doctrine justifies international action to prevent mass atrocities." },
    { word: "peacekeeping operation", translation: "opération de maintien de la paix", example: "The UN peacekeeping operation monitors ceasefire compliance and protects civilian populations." },
    { word: "peace enforcement", translation: "imposition de la paix", example: "Peace enforcement mandates authorize military force to compel compliance with peace agreements." },
    { word: "nation-building", translation: "construction nationale", example: "Post-conflict nation-building requires coordinated security, governance, and economic development." },
    { word: "state-building", translation: "consolidation de l'État", example: "State-building efforts focus on developing effective institutions and legitimate governance." },
    { word: "failed state", translation: "État défaillant", example: "The failed state lacks effective governmental control over significant portions of its territory." },
    { word: "fragile state", translation: "État fragile", example: "International engagement with the fragile state prioritizes institutional capacity building." },
    { word: "ungoverned space", translation: "espace non gouverné", example: "Terrorist groups exploit ungoverned spaces beyond effective state control for training and organization." },
    { word: "political transition", translation: "transition politique", example: "The political transition from authoritarian rule faces institutional and societal obstacles." },
    { word: "democratic backsliding", translation: "recul démocratique", example: "Democratic backsliding involves gradual erosion of institutions and norms rather than dramatic regime change." },
    { word: "authoritarian consolidation", translation: "consolidation autoritaire", example: "Authoritarian consolidation occurs as regimes eliminate remaining democratic constraints on power." },
    { word: "competitive authoritarianism", translation: "autoritarisme compétitif", example: "Competitive authoritarianism maintains democratic façades while ensuring ruling party dominance." },
    { word: "regime stability", translation: "stabilité du régime", example: "International actors prioritize regime stability over democratic reform in volatile regions." },
    { word: "political legitimacy", translation: "légitimité politique", example: "The government's political legitimacy eroded following disputed elections and corruption scandals." },
    { word: "power vacuum", translation: "vide de pouvoir", example: "The power vacuum following regime collapse enabled non-state armed groups to seize territory." },
    { word: "strategic realignment", translation: "réalignement stratégique", example: "Changing threat perceptions prompted strategic realignment between former adversaries." },
    { word: "regional integration", translation: "intégration régionale", example: "Regional integration mechanisms facilitate coordinated responses to transnational challenges." },
    { word: "security cooperation", translation: "coopération sécuritaire", example: "Bilateral security cooperation includes joint military exercises and intelligence sharing." },
    { word: "security sector reform", translation: "réforme du secteur de la sécurité", example: "Security sector reform aims to create professional, accountable defense and law enforcement institutions." },
    { word: "border dispute", translation: "différend frontalier", example: "The historical border dispute periodically escalates into limited military confrontations." },
    { word: "ethno-religious conflict", translation: "conflit ethno-religieux", example: "Ethno-religious conflict complicates political solutions that ensure minority rights protection." },
    { word: "cross-border militancy", translation: "militantisme transfrontalier", example: "Cross-border militancy necessitates coordinated responses from affected states." },
    { word: "transnational terrorism", translation: "terrorisme transnational", example: "Transnational terrorism exploits governance gaps and ideological grievances across multiple countries." },
    { word: "extremist ideology", translation: "idéologie extrémiste", example: "Countering extremist ideology requires addressing both security threats and underlying socioeconomic factors." },
    { word: "radicalization", translation: "radicalisation", example: "Online radicalization accelerates through social media echo chambers and targeted recruitment." },
    { word: "deradicalization", translation: "déradicalisation", example: "Deradicalization programs combine religious counseling with psychological support and socioeconomic reintegration." },
    { word: "counterterrorism", translation: "contre-terrorisme", example: "Effective counterterrorism balances security measures with addressing root causes of violent extremism." },
    { word: "sectarian tension", translation: "tension sectaire", example: "Sectarian tensions increase vulnerability to external manipulation by regional powers." },
    { word: "political Islam", translation: "islam politique", example: "Political Islam encompasses diverse movements with varying positions on democracy and violence." },
    { word: "ethnic polarization", translation: "polarisation ethnique", example: "Ethnic polarization intensified following political entrepreneurs' exploitation of historical grievances." },
    
    // Géoéconomie et ressources (50 mots)
    { word: "geoeconomics", translation: "géoéconomie", example: "Geoeconomics increasingly shapes international relations as states weaponize economic interdependence." },
    { word: "economic statecraft", translation: "diplomatie économique", example: "Economic statecraft employs trade, investment, and financial tools to advance foreign policy objectives." },
    { word: "economic coercion", translation: "coercition économique", example: "Targeted sanctions constitute economic coercion designed to alter state behavior without military force." },
    { word: "sanctions regime", translation: "régime de sanctions", example: "The multilateral sanctions regime restricts access to international financial systems and key technologies." },
    { word: "secondary sanctions", translation: "sanctions secondaires", example: "Secondary sanctions target third parties conducting business with sanctioned entities." },
    { word: "economic leverage", translation: "levier économique", example: "Infrastructure financing provides economic leverage over recipient countries' foreign policy choices." },
    { word: "strategic interdependence", translation: "interdépendance stratégique", example: "Energy relationships create strategic interdependence between supplier and consumer nations." },
    { word: "resource nationalism", translation: "nationalisme des ressources", example: "Resource nationalism prioritizes state control over natural resources rather than market mechanisms." },
    { word: "resource curse", translation: "malédiction des ressources", example: "The resource curse describes how natural resource wealth paradoxically undermines economic development." },
    { word: "rentier state", translation: "État rentier", example: "The rentier state derives most government revenue from external resource rents rather than domestic taxation." },
    { word: "trade dependency", translation: "dépendance commerciale", example: "Asymmetric trade dependency creates vulnerability to economic pressure from dominant partners." },
    { word: "supply chain vulnerability", translation: "vulnérabilité des chaînes d'approvisionnement", example: "The pandemic exposed supply chain vulnerabilities in critical sectors including medical supplies." },
    { word: "economic resilience", translation: "résilience économique", example: "Strategic industries pursue economic resilience through diversified sourcing and domestic capacity." },
    { word: "strategic decoupling", translation: "découplage stratégique", example: "Technological competition drives strategic decoupling in sensitive sectors like semiconductors." },
    { word: "reshoring", translation: "relocalisation", example: "National security concerns accelerate reshoring of critical manufacturing capabilities." },
    { word: "nearshoring", translation: "délocalisation de proximité", example: "Companies pursue nearshoring to balance efficiency with reduced geopolitical and supply chain risks." },
    { word: "friend-shoring", translation: "délocalisation amicale", example: "Friend-shoring relocates production to geopolitically aligned countries rather than potential adversaries." },
    { word: "economic corridor", translation: "corridor économique", example: "The infrastructure initiative establishes economic corridors connecting major industrial centers across multiple countries." },
    { word: "geo-economic fragmentation", translation: "fragmentation géoéconomique", example: "Geo-economic fragmentation creates parallel systems for trade, finance, and technology standards." },
    { word: "debt-trap diplomacy", translation: "diplomatie du piège de la dette", example: "Critics allege debt-trap diplomacy uses unsustainable financing to acquire strategic assets in developing nations." },
    { word: "economic statecraft", translation: "manœuvre économique", example: "The country employs economic statecraft to expand regional influence without military confrontation." },
    { word: "strategic infrastructure", translation: "infrastructure stratégique", example: "Port facilities constitute strategic infrastructure with both commercial and military applications." },
    { word: "developmental state", translation: "État développeur", example: "The developmental state coordinates public and private resources toward strategic industrial objectives." },
    { word: "industrial policy", translation: "politique industrielle", example: "Advanced economies increasingly embrace industrial policy to maintain technological leadership." },
    { word: "economic nationalism", translation: "nationalisme économique", example: "Economic nationalism prioritizes domestic interests over multilateral cooperation and free trade principles." },
    { word: "protectionism", translation: "protectionnisme", example: "Rising protectionism reflects both economic insecurity and strategic competition concerns." },
    { word: "strategic industry", translation: "industrie stratégique", example: "Semiconductor manufacturing represents a strategic industry central to economic and military competitiveness." },
    { word: "critical minerals", translation: "minéraux critiques", example: "Competition for critical minerals intensifies as clean energy technologies increase demand." },
    { word: "resource security", translation: "sécurité des ressources", example: "National strategies prioritize resource security through diversification and strategic reserves." },
    { word: "energy geopolitics", translation: "géopolitique énergétique", example: "Energy geopolitics influences pipeline routing decisions and maritime security priorities." },
    { word: "energy weaponization", translation: "armement énergétique", example: "Energy weaponization uses supply manipulation to extract political concessions from dependent consumers." },
    { word: "energy transition", translation: "transition énergétique", example: "The energy transition toward renewable sources reshapes traditional producer-consumer relationships." },
    { word: "maritime trade route", translation: "route commerciale maritime", example: "Naval deployments secure maritime trade routes against piracy and potential blockades." },
    { word: "choke point", translation: "point d'étranglement", example: "The narrow strait constitutes a strategic choke point for global energy transportation." },
    { word: "sea lane of communication", translation: "voie maritime de communication", example: "Naval strategy prioritizes protecting sea lanes of communication essential to international commerce." },
    { word: "flag of convenience", translation: "pavillon de complaisance", example: "Ships registered under flags of convenience evade regulatory oversight and taxation." },
    { word: "technology transfer", translation: "transfert de technologie", example: "Investment screening mechanisms prevent unwanted technology transfer to strategic competitors." },
    { word: "intellectual property theft", translation: "vol de propriété intellectuelle", example: "Intellectual property theft through cyber espionage targets high-value commercial technologies." },
    { word: "indigenous innovation", translation: "innovation indigène", example: "The national strategy emphasizes indigenous innovation to reduce dependence on foreign technology." },
    { word: "dual-use technology", translation: "technologie à double usage", example: "Export controls restrict dual-use technologies with both civilian and military applications." },
    { word: "technology decoupling", translation: "découplage technologique", example: "Technology decoupling creates parallel standards and supply chains in strategic sectors." },
    { word: "digital sovereignty", translation: "souveraineté numérique", example: "Digital sovereignty initiatives aim to reduce reliance on foreign platforms and infrastructure." },
    { word: "cyber espionage", translation: "cyberespionnage", example: "State-sponsored cyber espionage targets commercial and defense-related intellectual property." },
    { word: "cyber deterrence", translation: "cyberdissuasion", example: "Cyber deterrence capabilities signal potential consequences for hostile digital operations." },
    { word: "digital infrastructure", translation: "infrastructure numérique", example: "Competition over digital infrastructure deployment extends geopolitical rivalries into new domains." },
    { word: "surveillance capitalism", translation: "capitalisme de surveillance", example: "Surveillance capitalism commodifies personal data extraction for prediction and behavior modification." },
    { word: "data colonialism", translation: "colonialisme des données", example: "Critics characterize data colonialism as resource extraction from developing nations without appropriate compensation." },
    { word: "digital authoritarianism", translation: "autoritarisme numérique", example: "Digital authoritarianism employs advanced surveillance technologies to monitor and control populations." },
    { word: "information warfare", translation: "guerre informationnelle", example: "Information warfare campaigns target democratic processes through manipulation of public opinion." },
    
    // Sécurité transnationale et gouvernance mondiale (50 mots)
    { word: "transnational threat", translation: "menace transnationale", example: "Climate change represents a transnational threat requiring coordinated international response." },
    { word: "non-traditional security", translation: "sécurité non traditionnelle", example: "Non-traditional security concerns include environmental degradation, pandemic disease, and food insecurity." },
    { word: "human security", translation: "sécurité humaine", example: "Human security frameworks prioritize individual welfare over traditional state-centric approaches." },
    { word: "environmental security", translation: "sécurité environnementale", example: "Environmental security links ecological degradation to conflict, migration, and instability." },
    { word: "climate security", translation: "sécurité climatique", example: "Climate security assesses how global warming impacts political stability and military operations." },
    { word: "resource scarcity", translation: "rareté des ressources", example: "Water resource scarcity intensifies competitive dynamics between riparian states." },
    { word: "climate migration", translation: "migration climatique", example: "Projections indicate climate migration will increase as agricultural zones shift and sea levels rise." },
    { word: "planetary boundaries", translation: "limites planétaires", example: "Exceeding planetary boundaries risks irreversible environmental changes with profound security implications." },
    { word: "anthropocene", translation: "anthropocène", example: "The anthropocene concept recognizes humanity's dominant influence on Earth's geological and ecological systems." },
    { word: "food security", translation: "sécurité alimentaire", example: "Food security vulnerabilities increase during supply chain disruptions and extreme weather events." },
    { word: "water security", translation: "sécurité hydrique", example: "Transboundary water security requires cooperative management of shared river basins." },
    { word: "health security", translation: "sécurité sanitaire", example: "Health security preparedness includes early warning systems and strategic medical stockpiles." },
    { word: "pandemic preparedness", translation: "préparation aux pandémies", example: "Pandemic preparedness requires sustained institutional capacity between crisis periods." },
    { word: "biosecurity", translation: "biosécurité", example: "Advanced biosecurity protocols protect against both natural outbreaks and deliberate biological threats." },
    { word: "global health governance", translation: "gouvernance mondiale de la santé", example: "Global health governance institutions coordinate international response to emerging diseases." },
    { word: "forced displacement", translation: "déplacement forcé", example: "Conflict-induced forced displacement creates humanitarian challenges and regional instability." },
    { word: "irregular migration", translation: "migration irrégulière", example: "Irregular migration flows respond to both push factors in origin countries and pull factors in destinations." },
    { word: "refugee crisis", translation: "crise des réfugiés", example: "The refugee crisis overwhelmed regional host countries' absorption capacity and social services." },
    { word: "human trafficking", translation: "traite des êtres humains", example: "Transnational criminal networks profit from human trafficking across porous borders." },
    { word: "organized crime", translation: "crime organisé", example: "Organized crime groups exploit governance gaps and establish parallel power structures." },
    { word: "illicit financial flows", translation: "flux financiers illicites", example: "Illicit financial flows undermine development by diverting resources from legitimate economic activity." },
    { word: "threat convergence", translation: "convergence des menaces", example: "Threat convergence occurs when terrorist groups, criminal organizations, and corrupt officials develop symbiotic relationships." },
    { word: "corruption", translation: "corruption", example: "Systemic corruption undermines institutional legitimacy and enables transnational criminal activities." },
    { word: "kleptocracy", translation: "kleptocratie", example: "Kleptocratic governance structures systematically extract public resources for private gain." },
    { word: "narco-state", translation: "narco-État", example: "The territory exhibits narco-state characteristics with drug trafficking organizations influencing political processes." },
    { word: "critical infrastructure protection", translation: "protection des infrastructures critiques", example: "Critical infrastructure protection safeguards essential systems against physical and cyber threats." },
    { word: "non-state actor", translation: "acteur non étatique", example: "Non-state actors including corporations and advocacy networks influence international outcomes." },
    { word: "transnational advocacy network", translation: "réseau transnational de plaidoyer", example: "Transnational advocacy networks mobilize across borders to promote normative change." },
    { word: "civil society organization", translation: "organisation de la société civile", example: "Civil society organizations monitor government compliance with international commitments." },
    { word: "global governance", translation: "gouvernance mondiale", example: "Global governance mechanisms address challenges exceeding individual state capacities." },
    { word: "international regime", translation: "régime international", example: "The environmental protection international regime includes both binding treaties and voluntary standards." },
    { word: "norm entrepreneur", translation: "entrepreneur de normes", example: "Norm entrepreneurs advocate emerging principles like environmental justice and corporate responsibility." },
    { word: "epistemic community", translation: "communauté épistémique", example: "The scientific epistemic community provides technical expertise informing international regulations." },
    { word: "norm diffusion", translation: "diffusion des normes", example: "Norm diffusion occurs through international organizations, advocacy networks, and state socialization." },
    { word: "soft law", translation: "droit souple", example: "Soft law instruments lack formal enforcement mechanisms but establish behavioral expectations." },
    { word: "hard law", translation: "droit contraignant", example: "Hard law creates binding obligations with formalized compliance mechanisms." },
    { word: "legal sovereignty", translation: "souveraineté juridique", example: "Legal sovereignty remains the foundational principle of international relations despite practical limitations." },
    { word: "sovereignty gap", translation: "déficit de souveraineté", example: "The sovereignty gap between formal authority and effective governance capacity grows in fragile states." },
    { word: "sovereignty pooling", translation: "mise en commun de la souveraineté", example: "European integration demonstrates sovereignty pooling to address shared challenges." },
    { word: "extraterritorial jurisdiction", translation: "compétence extraterritoriale", example: "Extraterritorial jurisdiction extends domestic legal authority beyond national boundaries." },
    { word: "universal jurisdiction", translation: "compétence universelle", example: "Universal jurisdiction principles allow prosecution of certain crimes regardless of where they occurred." },
    { word: "transboundary governance", translation: "gouvernance transfrontalière", example: "Transboundary governance mechanisms manage shared resources like river basins and marine environments." },
    { word: "international arbitration", translation: "arbitrage international", example: "International arbitration provides dispute resolution mechanisms outside national court systems." },
    { word: "global public good", translation: "bien public mondial", example: "Climate stability constitutes a global public good requiring collective action to maintain." },
    { word: "global commons", translation: "biens communs mondiaux", example: "Governance regimes for global commons include oceans, atmosphere, and outer space." },
    { word: "tragedy of the commons", translation: "tragédie des biens communs", example: "Overfishing exemplifies the tragedy of the commons when individual interests deplete shared resources." },
    { word: "regulatory arbitrage", translation: "arbitrage réglementaire", example: "Multinational corporations engage in regulatory arbitrage to minimize compliance requirements." },
    { word: "race to the bottom", translation: "nivellement par le bas", example: "Environmental standards face race to the bottom pressures from international competition." },
    { word: "negative externality", translation: "externalité négative", example: "Carbon emissions create negative externalities affecting all countries regardless of source." },
    { word: "international public finance", translation: "finance publique internationale", example: "International public finance mobilizes resources for development and climate adaptation." }
  ]
};