export const vocab = {
  title: "Intelligence Artificielle et Éthique Technologique",
  words: [
    // Fondements de l'intelligence artificielle (25 mots)
    { word: "artificial intelligence", translation: "intelligence artificielle", example: "Artificial intelligence systems can analyze complex data patterns and make predictions." },
    { word: "algorithm", translation: "algorithme", example: "The algorithm processes input data according to specific logical rules." },
    { word: "computational model", translation: "modèle computationnel", example: "The computational model simulates human reasoning processes." },
    { word: "neural network", translation: "réseau neuronal", example: "Neural networks mimic the interconnected structure of biological neurons." },
    { word: "symbolic AI", translation: "IA symbolique", example: "Symbolic AI manipulates abstract symbols to represent real-world entities and relationships." },
    { word: "computational complexity", translation: "complexité computationnelle", example: "Computational complexity measures the resources required to run an algorithm." },
    { word: "heuristic", translation: "heuristique", example: "Heuristics provide efficient but imperfect solutions to complex problems." },
    { word: "inference engine", translation: "moteur d'inférence", example: "The inference engine applies logical rules to derive conclusions from available data." },
    { word: "knowledge representation", translation: "représentation des connaissances", example: "Knowledge representation structures information for computational reasoning." },
    { word: "artificial general intelligence", translation: "intelligence artificielle générale", example: "Artificial general intelligence would match human versatility across tasks." },
    { word: "autonomous system", translation: "système autonome", example: "Autonomous systems operate without direct human intervention." },
    { word: "intelligent agent", translation: "agent intelligent", example: "Intelligent agents perceive environments and take actions toward goals." },
    { word: "computational intelligence", translation: "intelligence computationnelle", example: "Computational intelligence encompasses problem-solving methods inspired by natural processes." },
    { word: "expert system", translation: "système expert", example: "The expert system captures specialized knowledge for professional-level decision support." },
    { word: "cognitive architecture", translation: "architecture cognitive", example: "Cognitive architectures model human mental processes computationally." },
    { word: "Turing test", translation: "test de Turing", example: "The Turing test evaluates a machine's ability to exhibit human-like intelligence." },
    { word: "superintelligence", translation: "superintelligence", example: "Superintelligence would surpass human cognitive capabilities across all domains." },
    { word: "intelligence amplification", translation: "amplification de l'intelligence", example: "Intelligence amplification enhances human capabilities through technological augmentation." },
    { word: "pattern recognition", translation: "reconnaissance de formes", example: "Pattern recognition identifies regularities within complex datasets." },
    { word: "automated reasoning", translation: "raisonnement automatisé", example: "Automated reasoning systems draw logical conclusions from available information." },
    { word: "natural language processing", translation: "traitement du langage naturel", example: "Natural language processing enables computers to understand human language." },
    { word: "computer vision", translation: "vision par ordinateur", example: "Computer vision systems interpret and analyze visual information." },
    { word: "artificial neural network", translation: "réseau neuronal artificiel", example: "Artificial neural networks learn through exposure to training examples." },
    { word: "cognitive computing", translation: "informatique cognitive", example: "Cognitive computing systems simulate human thought processes to solve problems." },
    { word: "semantic network", translation: "réseau sémantique", example: "Semantic networks represent relationships between concepts in knowledge structures." },
    
    // Apprentissage automatique (25 mots)
    { word: "machine learning", translation: "apprentissage automatique", example: "Machine learning algorithms improve performance through experience." },
    { word: "supervised learning", translation: "apprentissage supervisé", example: "Supervised learning trains on labeled data to make predictions." },
    { word: "unsupervised learning", translation: "apprentissage non supervisé", example: "Unsupervised learning identifies patterns without labeled training data." },
    { word: "reinforcement learning", translation: "apprentissage par renforcement", example: "Reinforcement learning optimizes behavior through reward signals." },
    { word: "deep learning", translation: "apprentissage profond", example: "Deep learning uses multi-layered neural networks for complex pattern recognition." },
    { word: "training data", translation: "données d'entraînement", example: "High-quality training data is essential for effective model development." },
    { word: "feature extraction", translation: "extraction de caractéristiques", example: "Feature extraction identifies relevant attributes from raw data." },
    { word: "overfitting", translation: "surapprentissage", example: "Overfitting occurs when models perform well on training data but poorly on new examples." },
    { word: "underfitting", translation: "sous-apprentissage", example: "Underfitting happens when models fail to capture underlying data patterns." },
    { word: "cross-validation", translation: "validation croisée", example: "Cross-validation evaluates model performance across multiple data subsets." },
    { word: "hyperparameter", translation: "hyperparamètre", example: "Hyperparameters control aspects of model training and architecture." },
    { word: "gradient descent", translation: "descente de gradient", example: "Gradient descent optimizes model parameters by iteratively reducing error." },
    { word: "backpropagation", translation: "rétropropagation", example: "Backpropagation adjusts neural network weights based on prediction errors." },
    { word: "regularization", translation: "régularisation", example: "Regularization techniques prevent overfitting by constraining model complexity." },
    { word: "model generalization", translation: "généralisation du modèle", example: "Good model generalization ensures performance on previously unseen data." },
    { word: "classification algorithm", translation: "algorithme de classification", example: "Classification algorithms assign data points to predefined categories." },
    { word: "clustering algorithm", translation: "algorithme de regroupement", example: "Clustering algorithms identify natural groupings within unlabeled data." },
    { word: "regression analysis", translation: "analyse de régression", example: "Regression analysis predicts continuous values based on input variables." },
    { word: "ensemble method", translation: "méthode d'ensemble", example: "Ensemble methods combine multiple models to improve prediction accuracy." },
    { word: "feature engineering", translation: "ingénierie des caractéristiques", example: "Feature engineering transforms raw data into more effective model inputs." },
    { word: "decision tree", translation: "arbre de décision", example: "Decision trees classify data through a series of conditional splits." },
    { word: "bias-variance tradeoff", translation: "compromis biais-variance", example: "The bias-variance tradeoff balances model complexity against performance." },
    { word: "transfer learning", translation: "apprentissage par transfert", example: "Transfer learning applies knowledge from one domain to improve learning in another." },
    { word: "semi-supervised learning", translation: "apprentissage semi-supervisé", example: "Semi-supervised learning combines labeled and unlabeled training data." },
    { word: "neural network layer", translation: "couche de réseau neuronal", example: "Each neural network layer transforms representations of input data." },
    
    // Intelligence artificielle avancée (25 mots)
    { word: "generative model", translation: "modèle génératif", example: "Generative models create new content resembling their training data." },
    { word: "transformer architecture", translation: "architecture transformer", example: "Transformer architectures revolutionized natural language processing capabilities." },
    { word: "attention mechanism", translation: "mécanisme d'attention", example: "Attention mechanisms focus computational resources on relevant inputs." },
    { word: "diffusion model", translation: "modèle de diffusion", example: "Diffusion models generate images by reversing noise addition processes." },
    { word: "multimodal AI", translation: "IA multimodale", example: "Multimodal AI systems integrate and process multiple types of information." },
    { word: "large language model", translation: "grand modèle de langage", example: "Large language models generate human-like text from vast training datasets." },
    { word: "foundation model", translation: "modèle fondationnel", example: "Foundation models serve as adaptable bases for various downstream applications." },
    { word: "explainable AI", translation: "IA explicable", example: "Explainable AI provides understandable reasons for its decisions and predictions." },
    { word: "federated learning", translation: "apprentissage fédéré", example: "Federated learning trains models across decentralized devices without data sharing." },
    { word: "reinforcement learning from human feedback", translation: "apprentissage par renforcement à partir de retours humains", example: "Reinforcement learning from human feedback uses human evaluations to guide model training." },
    { word: "autonomous agent", translation: "agent autonome", example: "Autonomous agents perceive environments and take independent actions toward goals." },
    { word: "self-supervised learning", translation: "apprentissage auto-supervisé", example: "Self-supervised learning extracts supervision signals from unlabeled data." },
    { word: "neural architecture search", translation: "recherche d'architecture neuronale", example: "Neural architecture search automates the design of optimal network structures." },
    { word: "adversarial training", translation: "entraînement antagoniste", example: "Adversarial training improves model robustness against manipulated inputs." },
    { word: "zero-shot learning", translation: "apprentissage zéro-shot", example: "Zero-shot learning performs tasks without specific training examples." },
    { word: "few-shot learning", translation: "apprentissage à partir de peu d'exemples", example: "Few-shot learning generalizes effectively from minimal training data." },
    { word: "computational neuroscience", translation: "neuroscience computationnelle", example: "Computational neuroscience models brain functions to inspire AI approaches." },
    { word: "human-level AI", translation: "IA de niveau humain", example: "Human-level AI matches people's performance across multiple cognitive domains." },
    { word: "emergent behavior", translation: "comportement émergent", example: "Emergent behavior arises from simple rules leading to complex system properties." },
    { word: "prompt engineering", translation: "ingénierie de prompts", example: "Prompt engineering optimizes instructions to guide AI system outputs." },
    { word: "contrastive learning", translation: "apprentissage contrastif", example: "Contrastive learning differentiates between similar and dissimilar data points." },
    { word: "neuromorphic computing", translation: "informatique neuromorphique", example: "Neuromorphic computing implements brain-inspired hardware architectures." },
    { word: "synthetic data generation", translation: "génération de données synthétiques", example: "Synthetic data generation creates artificial examples for model training." },
    { word: "model distillation", translation: "distillation de modèle", example: "Model distillation transfers knowledge from complex models to simpler ones." },
    { word: "quantum machine learning", translation: "apprentissage automatique quantique", example: "Quantum machine learning leverages quantum computing for computational advantages." },
    
    // Éthique de l'IA (25 mots)
    { word: "AI ethics", translation: "éthique de l'IA", example: "AI ethics addresses moral implications of intelligent technologies." },
    { word: "algorithmic bias", translation: "biais algorithmique", example: "Algorithmic bias leads systems to discriminate against certain groups." },
    { word: "technological fairness", translation: "équité technologique", example: "Technological fairness ensures equal treatment across demographic groups." },
    { word: "value alignment", translation: "alignement des valeurs", example: "Value alignment ensures AI systems operate according to human values." },
    { word: "responsible AI", translation: "IA responsable", example: "Responsible AI practices minimize harmful impacts while maximizing benefits." },
    { word: "algorithmic accountability", translation: "responsabilité algorithmique", example: "Algorithmic accountability assigns responsibility for automated decisions." },
    { word: "ethical framework", translation: "cadre éthique", example: "Ethical frameworks guide development and deployment of AI technologies." },
    { word: "fairness metric", translation: "métrique d'équité", example: "Fairness metrics quantify disparate impacts across population groups." },
    { word: "algorithmic transparency", translation: "transparence algorithmique", example: "Algorithmic transparency reveals how systems make decisions." },
    { word: "ethical guidelines", translation: "directives éthiques", example: "Ethical guidelines establish principles for responsible technology development." },
    { word: "digital ethics", translation: "éthique numérique", example: "Digital ethics addresses moral questions arising from technological innovation." },
    { word: "trustworthy AI", translation: "IA digne de confiance", example: "Trustworthy AI combines technical robustness with ethical principles." },
    { word: "moral agency", translation: "agentivité morale", example: "Questions of moral agency arise when AI systems make impactful decisions." },
    { word: "ethical risk assessment", translation: "évaluation des risques éthiques", example: "Ethical risk assessment identifies potential harms before deployment." },
    { word: "human oversight", translation: "supervision humaine", example: "Human oversight ensures appropriate intervention in automated processes." },
    { word: "dual-use technology", translation: "technologie à double usage", example: "Dual-use technology can serve both beneficial and harmful purposes." },
    { word: "ethics by design", translation: "éthique dès la conception", example: "Ethics by design incorporates moral considerations throughout development." },
    { word: "digital rights", translation: "droits numériques", example: "Digital rights protect individual freedoms in technological contexts." },
    { word: "human autonomy", translation: "autonomie humaine", example: "Human autonomy must be preserved despite increasing automation." },
    { word: "existential risk", translation: "risque existentiel", example: "Advanced AI may pose existential risks requiring proactive governance." },
    { word: "ethical dilemma", translation: "dilemme éthique", example: "Autonomous vehicles face ethical dilemmas when harm cannot be avoided." },
    { word: "machine ethics", translation: "éthique machine", example: "Machine ethics explores moral decision-making by artificial systems." },
    { word: "value judgment", translation: "jugement de valeur", example: "AI systems implicitly make value judgments in their operations." },
    { word: "benefit distribution", translation: "distribution des bénéfices", example: "Benefit distribution concerns how AI advantages are shared across society." },
    { word: "ethical standard", translation: "norme éthique", example: "Ethical standards establish minimum requirements for responsible AI." },
    
    // Gouvernance des technologies (25 mots)
    { word: "technology governance", translation: "gouvernance technologique", example: "Technology governance establishes rules and norms for technological development." },
    { word: "regulatory framework", translation: "cadre réglementaire", example: "Regulatory frameworks define legal boundaries for emerging technologies." },
    { word: "technology policy", translation: "politique technologique", example: "Technology policy addresses societal impacts of innovation." },
    { word: "risk management", translation: "gestion des risques", example: "Risk management identifies and mitigates potential technological harms." },
    { word: "compliance requirement", translation: "exigence de conformité", example: "Compliance requirements establish standards for legal technology use." },
    { word: "global governance", translation: "gouvernance mondiale", example: "Global governance coordinates international technology regulation efforts." },
    { word: "multi-stakeholder approach", translation: "approche multipartite", example: "Multi-stakeholder approaches involve diverse perspectives in technology governance." },
    { word: "self-regulation", translation: "autorégulation", example: "Industry self-regulation establishes voluntary standards and practices." },
    { word: "hard law", translation: "droit contraignant", example: "Hard law imposes legally binding technology regulations." },
    { word: "soft law", translation: "droit souple", example: "Soft law includes non-binding guidelines and recommendations." },
    { word: "regulatory sandbox", translation: "bac à sable réglementaire", example: "Regulatory sandboxes enable controlled testing of innovative technologies." },
    { word: "technology assessment", translation: "évaluation technologique", example: "Technology assessment analyzes potential impacts before widespread deployment." },
    { word: "anticipatory governance", translation: "gouvernance anticipative", example: "Anticipatory governance addresses emerging issues before they become problematic." },
    { word: "risk-based regulation", translation: "réglementation basée sur les risques", example: "Risk-based regulation applies stricter oversight to higher-risk technologies." },
    { word: "certification standard", translation: "norme de certification", example: "Certification standards verify compliance with technical and ethical requirements." },
    { word: "accountability mechanism", translation: "mécanisme de responsabilisation", example: "Accountability mechanisms enforce regulatory compliance." },
    { word: "technology ethics board", translation: "comité d'éthique technologique", example: "Technology ethics boards review proposed innovations before implementation." },
    { word: "digital governance", translation: "gouvernance numérique", example: "Digital governance frameworks manage online platforms and services." },
    { word: "impact assessment", translation: "évaluation d'impact", example: "Impact assessments identify potential consequences of technological deployment." },
    { word: "governance gap", translation: "lacune de gouvernance", example: "Governance gaps leave emerging technologies inadequately regulated." },
    { word: "precautionary principle", translation: "principe de précaution", example: "The precautionary principle restricts technologies with uncertain risks." },
    { word: "innovation principle", translation: "principe d'innovation", example: "The innovation principle balances risk management with technological progress." },
    { word: "regulatory capture", translation: "captation réglementaire", example: "Regulatory capture occurs when regulators serve industry rather than public interests." },
    { word: "international standards", translation: "normes internationales", example: "International standards harmonize technology governance across borders." },
    { word: "adaptive regulation", translation: "réglementation adaptative", example: "Adaptive regulation evolves alongside technological development." },
    
    // Impact sociétal des technologies (25 mots)
    { word: "societal impact", translation: "impact sociétal", example: "AI technologies create profound societal impacts across multiple domains." },
    { word: "digital divide", translation: "fracture numérique", example: "The digital divide separates populations with and without technological access." },
    { word: "technological unemployment", translation: "chômage technologique", example: "Technological unemployment results from automation replacing human workers." },
    { word: "algorithmic discrimination", translation: "discrimination algorithmique", example: "Algorithmic discrimination unfairly affects marginalized communities." },
    { word: "technological determinism", translation: "déterminisme technologique", example: "Technological determinism views social change as driven primarily by innovation." },
    { word: "social media influence", translation: "influence des médias sociaux", example: "Social media influence shapes public opinion and political discourse." },
    { word: "digital inclusion", translation: "inclusion numérique", example: "Digital inclusion initiatives increase technology access for underserved communities." },
    { word: "information ecosystem", translation: "écosystème informationnel", example: "Healthy information ecosystems support informed democratic participation." },
    { word: "digital citizenship", translation: "citoyenneté numérique", example: "Digital citizenship encompasses rights and responsibilities in online spaces." },
    { word: "technological literacy", translation: "littératie technologique", example: "Technological literacy enables effective navigation of digital environments." },
    { word: "digital transformation", translation: "transformation numérique", example: "Digital transformation reshapes organizational structures and processes." },
    { word: "sociotechnical system", translation: "système sociotechnique", example: "Sociotechnical systems involve interdependent social and technological elements." },
    { word: "technology assessment", translation: "évaluation technologique", example: "Technology assessment analyzes potential societal implications of innovations." },
    { word: "human-centered technology", translation: "technologie centrée sur l'humain", example: "Human-centered technology prioritizes human needs and values." },
    { word: "information disorder", translation: "désordre informationnel", example: "Information disorder encompasses misinformation, disinformation, and malinformation." },
    { word: "digital well-being", translation: "bien-être numérique", example: "Digital well-being concerns healthy relationships with technology." },
    { word: "technological solutionism", translation: "solutionnisme technologique", example: "Technological solutionism assumes complex social problems have technological fixes." },
    { word: "digital labor", translation: "travail numérique", example: "Digital labor includes both visible and invisible work in technological systems." },
    { word: "platform governance", translation: "gouvernance des plateformes", example: "Platform governance addresses how digital services regulate user content and behavior." },
    { word: "technosocial disruption", translation: "perturbation technosociale", example: "Technosocial disruption transforms established institutional patterns." },
    { word: "technology ethics", translation: "éthique technologique", example: "Technology ethics examines moral implications of digital innovation." },
    { word: "participatory design", translation: "conception participative", example: "Participatory design involves users throughout technology development." },
    { word: "social infrastructure", translation: "infrastructure sociale", example: "Social infrastructure supports human relationships and community resilience." },
    { word: "environmental impact", translation: "impact environnemental", example: "The environmental impact of computing includes energy use and material requirements." },
    { word: "technocultural change", translation: "changement technoculturel", example: "Technocultural change transforms social norms and cultural practices." },
    
    // Confidentialité et sécurité des données (25 mots)
    { word: "data privacy", translation: "confidentialité des données", example: "Data privacy concerns the appropriate collection and use of personal information." },
    { word: "cybersecurity", translation: "cybersécurité", example: "Cybersecurity protects systems and data from unauthorized access and attacks." },
    { word: "privacy by design", translation: "protection de la vie privée dès la conception", example: "Privacy by design incorporates privacy protections throughout development processes." },
    { word: "data encryption", translation: "chiffrement des données", example: "Data encryption converts information into code to prevent unauthorized access." },
    { word: "information security", translation: "sécurité de l'information", example: "Information security preserves confidentiality, integrity, and availability of data." },
    { word: "data breach", translation: "violation de données", example: "Data breaches expose sensitive information to unauthorized parties." },
    { word: "data protection", translation: "protection des données", example: "Data protection frameworks establish legal requirements for information handling." },
    { word: "data sovereignty", translation: "souveraineté des données", example: "Data sovereignty concerns control over information based on geographic location." },
    { word: "privacy regulation", translation: "réglementation de la vie privée", example: "Privacy regulations establish legal frameworks for data protection." },
    { word: "data minimization", translation: "minimisation des données", example: "Data minimization restricts collection to necessary information." },
    { word: "threat model", translation: "modèle de menace", example: "Threat models identify potential vulnerabilities and attack vectors." },
    { word: "zero-trust security", translation: "sécurité zéro confiance", example: "Zero-trust security verifies every access request regardless of source." },
    { word: "data governance", translation: "gouvernance des données", example: "Data governance establishes policies for information management throughout its lifecycle." },
    { word: "security vulnerability", translation: "vulnérabilité de sécurité", example: "Security vulnerabilities provide potential entry points for attacks." },
    { word: "privacy impact assessment", translation: "évaluation d'impact sur la vie privée", example: "Privacy impact assessments identify and mitigate potential privacy risks." },
    { word: "information asymmetry", translation: "asymétrie d'information", example: "Information asymmetry exists when one party has more knowledge than another." },
    { word: "differential privacy", translation: "confidentialité différentielle", example: "Differential privacy protects individual data while allowing useful analysis." },
    { word: "digital surveillance", translation: "surveillance numérique", example: "Digital surveillance monitors online activities and communications." },
    { word: "privacy-enhancing technology", translation: "technologie renforçant la confidentialité", example: "Privacy-enhancing technologies protect personal information during processing." },
    { word: "security breach", translation: "atteinte à la sécurité", example: "Security breaches compromise system integrity or data confidentiality." },
    { word: "identity management", translation: "gestion de l'identité", example: "Identity management systems authenticate and authorize system users." },
    { word: "access control", translation: "contrôle d'accès", example: "Access control restricts system entry to authorized individuals." },
    { word: "data anonymization", translation: "anonymisation des données", example: "Data anonymization removes identifying information from datasets." },
    { word: "consent management", translation: "gestion du consentement", example: "Consent management systems track user permissions for data processing." },
    { word: "cryptographic protocol", translation: "protocole cryptographique", example: "Cryptographic protocols secure communications between parties." },
    
    // IA et prise de décision (25 mots)
    { word: "automated decision-making", translation: "prise de décision automatisée", example: "Automated decision-making applies algorithms to choices traditionally made by humans." },
    { word: "augmented intelligence", translation: "intelligence augmentée", example: "Augmented intelligence combines human and machine capabilities for better decisions." },
    { word: "decision support system", translation: "système d'aide à la décision", example: "Decision support systems provide information to assist human judgment." },
    { word: "algorithmic decision-making", translation: "prise de décision algorithmique", example: "Algorithmic decision-making applies computational procedures to choice processes." },
    { word: "expert system", translation: "système expert", example: "Expert systems capture specialized knowledge for decision support." },
    { word: "decision intelligence", translation: "intelligence décisionnelle", example: "Decision intelligence combines multiple disciplines to improve decision quality." },
    { word: "predictive analytics", translation: "analyse prédictive", example: "Predictive analytics forecasts outcomes to guide decision processes." },
    { word: "human-in-the-loop", translation: "humain dans la boucle", example: "Human-in-the-loop systems involve human judgment within automated processes." },
    { word: "decision threshold", translation: "seuil de décision", example: "Decision thresholds determine when systems take specific actions." },
    { word: "recommendation system", translation: "système de recommandation", example: "Recommendation systems suggest options based on historical preferences." },
    { word: "computational decision science", translation: "science computationnelle de la décision", example: "Computational decision science applies algorithms to choice processes." },
    { word: "cognitive bias", translation: "biais cognitif", example: "Cognitive biases affect both human and machine decision-making." },
    { word: "decision tree", translation: "arbre de décision", example: "Decision trees map possible choices and their consequences." },
    { word: "risk assessment", translation: "évaluation des risques", example: "Automated risk assessment calculates probabilities of negative outcomes." },
    { word: "decision automation", translation: "automatisation des décisions", example: "Decision automation implements choices without human intervention." },
    { word: "cognitive load", translation: "charge cognitive", example: "AI systems can reduce cognitive load during complex decisions." },
    { word: "human oversight", translation: "supervision humaine", example: "Human oversight ensures intervention capability in automated systems." },
    { word: "outcome prediction", translation: "prédiction des résultats", example: "Outcome prediction forecasts consequences of potential choices." },
    { word: "decision boundary", translation: "frontière de décision", example: "Decision boundaries separate different classification outcomes." },
    { word: "multi-criteria decision analysis", translation: "analyse décisionnelle multicritère", example: "Multi-criteria decision analysis balances competing objectives." },
    { word: "prescriptive analytics", translation: "analyse prescriptive", example: "Prescriptive analytics recommends actions based on predictive insights." },
    { word: "decision optimization", translation: "optimisation des décisions", example: "Decision optimization identifies best choices given constraints." },
    { word: "algorithmic recourse", translation: "recours algorithmique", example: "Algorithmic recourse provides paths to favorable decisions after rejection." },
    { word: "decision confidence", translation: "confiance décisionnelle", example: "Decision confidence metrics quantify certainty in automated judgments." },
    { word: "context-aware decision", translation: "décision contextuelle", example: "Context-aware decisions adapt to specific environmental conditions." },
    
    // IA et automatisation (25 mots)
    { word: "automation", translation: "automatisation", example: "Automation replaces human labor with technological systems." },
    { word: "robotic process automation", translation: "automatisation robotisée des processus", example: "Robotic process automation performs repetitive digital tasks." },
    { word: "intelligent automation", translation: "automatisation intelligente", example: "Intelligent automation combines AI capabilities with process automation." },
    { word: "autonomous system", translation: "système autonome", example: "Autonomous systems operate independently without human supervision." },
    { word: "human-machine collaboration", translation: "collaboration homme-machine", example: "Human-machine collaboration leverages complementary strengths of each." },
    { word: "workflow automation", translation: "automatisation des flux de travail", example: "Workflow automation coordinates sequences of tasks across systems." },
    { word: "autonomous vehicle", translation: "véhicule autonome", example: "Autonomous vehicles navigate without human drivers using AI systems." },
    { word: "labor displacement", translation: "déplacement de main-d'œuvre", example: "Labor displacement occurs when automation eliminates specific job categories." },
    { word: "cognitive automation", translation: "automatisation cognitive", example: "Cognitive automation applies AI to knowledge work processes." },
    { word: "automated manufacturing", translation: "fabrication automatisée", example: "Automated manufacturing uses robots and intelligent systems for production." },
    { word: "industrial robot", translation: "robot industriel", example: "Industrial robots perform physical tasks in manufacturing environments." },
    { word: "business process automation", translation: "automatisation des processus d'entreprise", example: "Business process automation streamlines organizational workflows." },
    { word: "job polarization", translation: "polarisation de l'emploi", example: "Job polarization concentrates work in high and low-skill categories." },
    { word: "task automation", translation: "automatisation des tâches", example: "Task automation replaces specific activities rather than entire jobs." },
    { word: "digital worker", translation: "travailleur numérique", example: "Digital workers perform automated tasks within organizational systems." },
    { word: "automation bias", translation: "biais d'automatisation", example: "Automation bias causes humans to favor machine-generated suggestions." },
    { word: "augmented workforce", translation: "main-d'œuvre augmentée", example: "The augmented workforce combines human and automated capabilities." },
    { word: "self-driving technology", translation: "technologie de conduite autonome", example: "Self-driving technology navigates vehicles through sensor data and AI." },
    { word: "automated decision system", translation: "système de décision automatisé", example: "Automated decision systems apply rules to make choices without human input." },
    { word: "machine operator", translation: "opérateur de machine", example: "Machine operators supervise and control automated equipment." },
    { word: "skills gap", translation: "écart de compétences", example: "Automation creates skills gaps between available and required workforce capabilities." },
    { word: "human-centered automation", translation: "automatisation centrée sur l'humain", example: "Human-centered automation designs systems around user needs and abilities." },
    { word: "automation strategy", translation: "stratégie d'automatisation", example: "Automation strategy identifies processes suitable for technological replacement." },
    { word: "technological unemployment", translation: "chômage technologique", example: "Technological unemployment results from automation eliminating jobs." },
    { word: "augmented intelligence", translation: "intelligence augmentée", example: "Augmented intelligence enhances rather than replaces human capabilities." },
    
    // Futur des technologies intelligentes (25 mots)
    { word: "artificial general intelligence", translation: "intelligence artificielle générale", example: "Artificial general intelligence would match human versatility across domains." },
    { word: "technological singularity", translation: "singularité technologique", example: "The technological singularity represents a hypothetical point of superintelligent self-improvement." },
    { word: "human enhancement", translation: "amélioration humaine", example: "Human enhancement technologies extend natural capabilities through technological means." },
    { word: "brain-computer interface", translation: "interface cerveau-ordinateur", example: "Brain-computer interfaces establish direct communication between brains and external devices." },
    { word: "autonomous system", translation: "système autonome", example: "Autonomous systems operate independently without human supervision." },
    { word: "artificial superintelligence", translation: "superintelligence artificielle", example: "Artificial superintelligence would surpass human capabilities across all domains." },
    { word: "transhumanism", translation: "transhumanisme", example: "Transhumanism advocates using technology to enhance human capabilities." },
    { word: "longtermism", translation: "longterminisme", example: "Longtermism prioritizes safeguarding humanity's long-term future." },
    { word: "existential risk", translation: "risque existentiel", example: "Advanced technologies may pose existential risks to humanity's survival." },
    { word: "AI alignment", translation: "alignement de l'IA", example: "AI alignment ensures artificial systems act according to human values." },
    { word: "cognitive architecture", translation: "architecture cognitive", example: "Advanced cognitive architectures may enable more human-like machine intelligence." },
    { word: "digital consciousness", translation: "conscience numérique", example: "Digital consciousness raises philosophical questions about machine sentience." },
    { word: "technological forecasting", translation: "prospective technologique", example: "Technological forecasting anticipates future innovation trajectories." },
    { word: "posthumanism", translation: "posthumanisme", example: "Posthumanism explores potential futures beyond traditional human limitations." },
    { word: "AI safety", translation: "sécurité de l'IA", example: "AI safety research develops methods to ensure beneficial advanced systems." },
    { word: "morphological freedom", translation: "liberté morphologique", example: "Morphological freedom encompasses rights to modify one's body through technology." },
    { word: "mind uploading", translation: "téléchargement de l'esprit", example: "Mind uploading would theoretically transfer consciousness to digital substrates." },
    { word: "beneficial AI", translation: "IA bénéfique", example: "Beneficial AI development prioritizes positive human outcomes." },
    { word: "transformative AI", translation: "IA transformatrice", example: "Transformative AI would fundamentally change civilization's trajectory." },
    { word: "future of work", translation: "avenir du travail", example: "Intelligent technologies will reshape employment patterns and occupations." },
    { word: "machine consciousness", translation: "conscience machinique", example: "Machine consciousness research explores potential for aware artificial systems." },
    { word: "ethical futurism", translation: "futurisme éthique", example: "Ethical futurism considers moral implications of emerging technologies." },
    { word: "digital afterlife", translation: "vie après la mort numérique", example: "Digital afterlife technologies might preserve aspects of personal identity." },
    { word: "intelligence explosion", translation: "explosion d'intelligence", example: "An intelligence explosion would involve rapidly self-improving AI systems." },
    { word: "technological convergence", translation: "convergence technologique", example: "Technological convergence integrates AI with biotechnology, nanotechnology, and other fields." }
  ]
};