export const vocab = {
  title: "Arts Visuels et Analyse Esthétique",
  words: [
    // Histoire de l'art (25 mots)
    { word: "art history", translation: "histoire de l'art", example: "Art history examines visual expression across cultures and time periods." },
    { word: "artistic movement", translation: "mouvement artistique", example: "The artistic movement emerged in response to rapid industrialization." },
    { word: "Renaissance", translation: "Renaissance", example: "The Renaissance reintroduced classical proportions and perspective." },
    { word: "Baroque", translation: "Baroque", example: "Baroque art creates dramatic movement and emotional intensity." },
    { word: "Impressionism", translation: "Impressionnisme", example: "Impressionism captured transient effects of light and atmosphere." },
    { word: "Cubism", translation: "Cubisme", example: "Cubism fragmented subjects into geometric forms from multiple viewpoints." },
    { word: "Surrealism", translation: "Surréalisme", example: "Surrealism explored unconscious associations and dreamlike juxtapositions." },
    { word: "Abstract Expressionism", translation: "Expressionnisme abstrait", example: "Abstract Expressionism emphasized spontaneous creation and emotional intensity." },
    { word: "Modernism", translation: "Modernisme", example: "Modernism broke from traditional representation toward experimentation." },
    { word: "Postmodernism", translation: "Postmodernisme", example: "Postmodernism questions grand narratives and embraces plurality." },
    { word: "art periodization", translation: "périodisation de l'art", example: "Art periodization categorizes works by stylistic era and cultural context." },
    { word: "provenance", translation: "provenance", example: "The painting's provenance traces ownership from the artist to current collection." },
    { word: "patronage", translation: "mécénat", example: "Royal patronage influenced artistic production throughout the 16th century." },
    { word: "iconography", translation: "iconographie", example: "Religious iconography contains symbolic visual language for the faithful." },
    { word: "artistic influence", translation: "influence artistique", example: "The exhibition examines artistic influence across generations." },
    { word: "cultural context", translation: "contexte culturel", example: "Understanding cultural context enriches interpretation of historical works." },
    { word: "art historiography", translation: "historiographie de l'art", example: "Art historiography examines how art history itself has been written." },
    { word: "chronology", translation: "chronologie", example: "The museum presents works in strict chronological sequence." },
    { word: "artistic development", translation: "développement artistique", example: "The retrospective traces the artist's development over six decades." },
    { word: "artistic legacy", translation: "héritage artistique", example: "The exhibition explores the artist's enduring legacy on contemporary practice." },
    { word: "art historical research", translation: "recherche en histoire de l'art", example: "Recent art historical research challenges traditional attributions." },
    { word: "stylistic analysis", translation: "analyse stylistique", example: "Stylistic analysis identified characteristic brushwork and composition." },
    { word: "visual culture", translation: "culture visuelle", example: "The department explores visual culture across media and time periods." },
    { word: "historical context", translation: "contexte historique", example: "Historical context provides essential background for interpretation." },
    { word: "artistic canon", translation: "canon artistique", example: "Recent scholarship has expanded the artistic canon beyond Western traditions." },
    
    // Techniques artistiques (25 mots)
    { word: "artistic technique", translation: "technique artistique", example: "The artist pioneered innovative artistic techniques using mixed media." },
    { word: "oil painting", translation: "peinture à l'huile", example: "Oil painting allows for luminous color and subtle blending effects." },
    { word: "watercolor", translation: "aquarelle", example: "Watercolor creates transparent washes of delicate pigment." },
    { word: "printmaking", translation: "gravure", example: "Printmaking encompasses etching, lithography, and relief processes." },
    { word: "sculpture", translation: "sculpture", example: "Contemporary sculpture explores unconventional materials and spatial relationships." },
    { word: "installation art", translation: "art d'installation", example: "The installation art transforms the gallery through immersive environments." },
    { word: "drawing", translation: "dessin", example: "Drawing serves both as preparatory study and finished artwork." },
    { word: "collage", translation: "collage", example: "Collage juxtaposes disparate elements to create new meanings." },
    { word: "mixed media", translation: "technique mixte", example: "Mixed media works combine diverse materials and processes." },
    { word: "photography", translation: "photographie", example: "Digital photography has transformed contemporary visual practice." },
    { word: "video art", translation: "art vidéo", example: "Video art explores time-based visual narratives and experiences." },
    { word: "performance art", translation: "art performance", example: "Performance art uses the artist's body as primary medium." },
    { word: "digital art", translation: "art numérique", example: "Digital art encompasses computer-generated and interactive works." },
    { word: "fresco", translation: "fresque", example: "Fresco painting applies pigment to wet plaster for permanent wall decoration." },
    { word: "lithography", translation: "lithographie", example: "Lithography creates prints through oil and water resistance." },
    { word: "etching", translation: "eau-forte", example: "Etching uses acid to incise designs on metal printing plates." },
    { word: "woodcut", translation: "gravure sur bois", example: "The woodcut tradition dates back to early Chinese printing methods." },
    { word: "mosaic", translation: "mosaïque", example: "Byzantine mosaics create luminous imagery from glass tesserae." },
    { word: "ceramic", translation: "céramique", example: "Contemporary ceramic practice extends beyond functional vessels." },
    { word: "textile art", translation: "art textile", example: "Textile art encompasses weaving, embroidery, and fiber construction." },
    { word: "assemblage", translation: "assemblage", example: "Assemblage creates three-dimensional compositions from found objects." },
    { word: "casting", translation: "moulage", example: "Bronze sculpture requires complex casting processes." },
    { word: "glazing", translation: "glaçage", example: "Glazing techniques build transparent layers of color in painting." },
    { word: "chiaroscuro", translation: "clair-obscur", example: "Chiaroscuro creates dramatic contrasts between light and shadow." },
    { word: "perspectival technique", translation: "technique perspectiviste", example: "Renaissance artists developed mathematical perspectival techniques." },
    
    // Analyse formelle (25 mots)
    { word: "formal analysis", translation: "analyse formelle", example: "Formal analysis examines visual elements and their relationships." },
    { word: "composition", translation: "composition", example: "The dynamic composition creates movement through diagonal arrangements." },
    { word: "line", translation: "ligne", example: "Expressive line quality conveys emotional intensity throughout the drawing." },
    { word: "shape", translation: "forme", example: "Organic shapes contrast with geometric elements in the composition." },
    { word: "color", translation: "couleur", example: "Complementary colors create visual vibration along contours." },
    { word: "texture", translation: "texture", example: "Impasto technique creates physical texture across the canvas surface." },
    { word: "value", translation: "valeur", example: "Dramatic value contrasts establish focal hierarchy within the image." },
    { word: "space", translation: "espace", example: "Overlapping forms create illusionistic space without linear perspective." },
    { word: "symmetry", translation: "symétrie", example: "Bilateral symmetry creates monumental stability in the façade design." },
    { word: "asymmetry", translation: "asymétrie", example: "Dynamic asymmetry generates visual tension throughout the composition." },
    { word: "proportion", translation: "proportion", example: "Classical proportion systems govern relationships between architectural elements." },
    { word: "scale", translation: "échelle", example: "Monumental scale creates an overwhelming viewer experience." },
    { word: "rhythm", translation: "rythme", example: "Visual rhythm guides the eye through repeating color patterns." },
    { word: "balance", translation: "équilibre", example: "Asymmetrical balance distributes visual weight across the composition." },
    { word: "focal point", translation: "point focal", example: "Color contrast establishes the central figure as the clear focal point." },
    { word: "unity", translation: "unité", example: "Compositional unity creates cohesive relationships between diverse elements." },
    { word: "variety", translation: "variété", example: "Textural variety maintains visual interest throughout the surface." },
    { word: "emphasis", translation: "accentuation", example: "Strategic emphasis directs attention to significant narrative elements." },
    { word: "pattern", translation: "motif", example: "Repeating patterns establish visual continuity across the installation." },
    { word: "contrast", translation: "contraste", example: "Sharp tonal contrast delineates foreground from background." },
    { word: "movement", translation: "mouvement", example: "Directional brushwork creates visual movement across the canvas." },
    { word: "harmony", translation: "harmonie", example: "Color harmony unifies diverse compositional elements." },
    { word: "visual weight", translation: "poids visuel", example: "Dark values create greater visual weight within the composition." },
    { word: "perspective", translation: "perspective", example: "Atmospheric perspective suggests spatial depth through color modulation." },
    { word: "geometric analysis", translation: "analyse géométrique", example: "Geometric analysis reveals underlying compositional structure." },
    
    // Critique d'art (25 mots)
    { word: "art criticism", translation: "critique d'art", example: "Contemporary art criticism engages with social and political contexts." },
    { word: "aesthetic judgment", translation: "jugement esthétique", example: "Aesthetic judgment evaluates artistic merit and significance." },
    { word: "critical interpretation", translation: "interprétation critique", example: "Critical interpretation reveals meanings beyond artist intention." },
    { word: "artistic evaluation", translation: "évaluation artistique", example: "Artistic evaluation considers both technical execution and conceptual depth." },
    { word: "cultural critique", translation: "critique culturelle", example: "The exhibition offers cultural critique through juxtaposition of artifacts." },
    { word: "critical framework", translation: "cadre critique", example: "Feminist critical frameworks reveal gendered aspects of representation." },
    { word: "contextual analysis", translation: "analyse contextuelle", example: "Contextual analysis situates artwork within specific historical moments." },
    { word: "comparative criticism", translation: "critique comparative", example: "Comparative criticism examines relationships between diverse works." },
    { word: "critical theory", translation: "théorie critique", example: "Critical theory provides analytical frameworks for examining cultural production." },
    { word: "evaluative criteria", translation: "critères d'évaluation", example: "The critic applies consistent evaluative criteria across exhibitions." },
    { word: "critical discourse", translation: "discours critique", example: "Critical discourse shapes reception and interpretation of artwork." },
    { word: "critical response", translation: "réponse critique", example: "The installation provoked divided critical response from reviewers." },
    { word: "critical analysis", translation: "analyse critique", example: "Critical analysis examines both form and content of visual works." },
    { word: "critical reception", translation: "réception critique", example: "Critical reception evolves significantly over time for avant-garde work." },
    { word: "critical perspective", translation: "perspective critique", example: "Each critic brings a distinctive critical perspective to interpretation." },
    { word: "exhibition review", translation: "critique d'exposition", example: "The exhibition review assessed curatorial choices and visitor experience." },
    { word: "artistic merit", translation: "mérite artistique", example: "Critics debated the artistic merit of conceptual installations." },
    { word: "critical assessment", translation: "évaluation critique", example: "Critical assessment weighs innovation against technical execution." },
    { word: "art writing", translation: "écriture sur l'art", example: "Contemporary art writing blends criticism with creative expression." },
    { word: "critical framework", translation: "cadre critique", example: "Postcolonial critical frameworks reveal imperialist assumptions in museum displays." },
    { word: "formalist criticism", translation: "critique formaliste", example: "Formalist criticism emphasizes visual properties over external context." },
    { word: "critical methodology", translation: "méthodologie critique", example: "The critic employs a consistent critical methodology across analyses." },
    { word: "interpretive strategy", translation: "stratégie interprétative", example: "Biographical interpretive strategies connect artwork to artists' lives." },
    { word: "critical dialogue", translation: "dialogue critique", example: "The panel fostered critical dialogue between diverse perspectives." },
    { word: "artistic significance", translation: "importance artistique", example: "Critics debate the artistic significance of digital art forms." },
    
    // Théories esthétiques (25 mots)
    { word: "aesthetic theory", translation: "théorie esthétique", example: "Aesthetic theory examines the nature of beauty and artistic value." },
    { word: "aesthetics", translation: "esthétique", example: "Philosophical aesthetics addresses fundamental questions about art's nature." },
    { word: "beauty", translation: "beauté", example: "Conceptions of beauty vary across historical periods and cultures." },
    { word: "sublime", translation: "sublime", example: "The sublime creates overwhelming aesthetic experiences through vastness or power." },
    { word: "representation", translation: "représentation", example: "Theories of representation examine how images relate to reality." },
    { word: "mimesis", translation: "mimesis", example: "Mimesis describes art's imitation of nature or reality." },
    { word: "formalism", translation: "formalisme", example: "Formalism prioritizes visual qualities over external meaning or context." },
    { word: "expressionism", translation: "expressionnisme", example: "Expressionist theory values emotional intensity and subjective experience." },
    { word: "aesthetic experience", translation: "expérience esthétique", example: "Aesthetic experience involves contemplative engagement with artworks." },
    { word: "aesthetic value", translation: "valeur esthétique", example: "Philosophers debate whether aesthetic value is subjective or objective." },
    { word: "aesthetic judgment", translation: "jugement esthétique", example: "Kant analyzed aesthetic judgment as distinct from practical reasoning." },
    { word: "aesthetic attitude", translation: "attitude esthétique", example: "Aesthetic attitude involves disinterested contemplation of formal qualities." },
    { word: "aesthetic property", translation: "propriété esthétique", example: "Unity represents a significant aesthetic property in classical composition." },
    { word: "taste", translation: "goût", example: "Theories of taste address standards for aesthetic judgment." },
    { word: "aesthetic response", translation: "réponse esthétique", example: "Aesthetic response combines sensory, emotional, and intellectual dimensions." },
    { word: "aesthetic distance", translation: "distance esthétique", example: "Aesthetic distance separates viewers from practical engagement with artworks." },
    { word: "disinterestedness", translation: "désintéressement", example: "Aesthetic disinterestedness involves appreciation beyond practical utility." },
    { word: "aesthetic education", translation: "éducation esthétique", example: "Schiller advocated aesthetic education for social harmony." },
    { word: "aesthetic category", translation: "catégorie esthétique", example: "The grotesque represents a distinct aesthetic category beyond beauty." },
    { word: "aesthetic interpretation", translation: "interprétation esthétique", example: "Aesthetic interpretation constructs meaning from visual elements." },
    { word: "aesthetic contemplation", translation: "contemplation esthétique", example: "Aesthetic contemplation involves sustained attention to artistic qualities." },
    { word: "aesthetic quality", translation: "qualité esthétique", example: "Formal harmony represents a traditional aesthetic quality in composition." },
    { word: "aesthetic theory of art", translation: "théorie esthétique de l'art", example: "Aesthetic theories of art identify essential properties of artwork." },
    { word: "aesthetic perception", translation: "perception esthétique", example: "Aesthetic perception involves heightened awareness of sensory qualities." },
    { word: "aesthetic emotion", translation: "émotion esthétique", example: "Aesthetic emotion arises from engagement with artistic form and content." },
    
    // Architecture et espace (25 mots)
    { word: "architectural design", translation: "conception architecturale", example: "Architectural design balances function, structure, and aesthetic expression." },
    { word: "spatial analysis", translation: "analyse spatiale", example: "Spatial analysis examines relationships between volumes and circulation." },
    { word: "built environment", translation: "environnement bâti", example: "The built environment shapes human experience and social interaction." },
    { word: "architectural theory", translation: "théorie architecturale", example: "Architectural theory addresses fundamental principles of design and space." },
    { word: "structural system", translation: "système structurel", example: "The innovative structural system enabled unprecedented interior spans." },
    { word: "spatial organization", translation: "organisation spatiale", example: "Spatial organization creates hierarchical relationships between functions." },
    { word: "architectural style", translation: "style architectural", example: "The building combines elements from distinct architectural styles." },
    { word: "architectural form", translation: "forme architecturale", example: "Sculptural architectural form creates dramatic visual impact." },
    { word: "urban design", translation: "design urbain", example: "Urban design considers relationships between buildings and public space." },
    { word: "spatial experience", translation: "expérience spatiale", example: "Sequential spatial experience unfolds as visitors move through the museum." },
    { word: "architectural context", translation: "contexte architectural", example: "The design responds sensitively to its architectural context." },
    { word: "architectural composition", translation: "composition architecturale", example: "Architectural composition balances proportion, rhythm, and scale." },
    { word: "building typology", translation: "typologie du bâtiment", example: "The project reimagines traditional building typology for contemporary use." },
    { word: "spatial sequence", translation: "séquence spatiale", example: "The spatial sequence creates narrative progression through the structure." },
    { word: "architectural program", translation: "programme architectural", example: "The architectural program organizes functional requirements into spatial relationships." },
    { word: "spatial hierarchy", translation: "hiérarchie spatiale", example: "Volumetric scale creates spatial hierarchy throughout the complex." },
    { word: "architectural character", translation: "caractère architectural", example: "Material selection contributes to distinctive architectural character." },
    { word: "spatial configuration", translation: "configuration spatiale", example: "The innovative spatial configuration maximizes natural illumination." },
    { word: "architectural concept", translation: "concept architectural", example: "The architectural concept responds to both site and cultural context." },
    { word: "spatial perception", translation: "perception spatiale", example: "Compressed entrances alter spatial perception of subsequent volumes." },
    { word: "architectural element", translation: "élément architectural", example: "Repetitive architectural elements create visual rhythm across the façade." },
    { word: "architectural scale", translation: "échelle architecturale", example: "Human architectural scale creates comfortable inhabitation." },
    { word: "spatial relationship", translation: "relation spatiale", example: "Complex spatial relationships generate continually changing perspectives." },
    { word: "architectural expression", translation: "expression architecturale", example: "Structural systems become explicit architectural expression." },
    { word: "spatial quality", translation: "qualité spatiale", example: "Diffused natural light enhances spatial quality throughout the interior." },
    
    // Arts contemporains (25 mots)
    { word: "contemporary art", translation: "art contemporain", example: "Contemporary art engages with urgent social and political questions." },
    { word: "conceptual art", translation: "art conceptuel", example: "Conceptual art prioritizes ideas over conventional aesthetic concerns." },
    { word: "installation art", translation: "art d'installation", example: "Installation art creates immersive environments that transform gallery spaces." },
    { word: "performance art", translation: "art de performance", example: "Performance art uses the artist's body as primary medium and subject." },
    { word: "video installation", translation: "installation vidéo", example: "The video installation projects multiple synchronized narratives." },
    { word: "new media art", translation: "art des nouveaux médias", example: "New media art explores digital technologies and virtual experiences." },
    { word: "site-specific art", translation: "art in situ", example: "Site-specific art responds directly to particular locations and contexts." },
    { word: "participatory art", translation: "art participatif", example: "Participatory art engages viewers as active co-creators." },
    { word: "social practice", translation: "pratique sociale", example: "Social practice art creates collaborative community engagement projects." },
    { word: "interdisciplinary art", translation: "art interdisciplinaire", example: "Interdisciplinary art combines techniques from diverse creative fields." },
    { word: "relational aesthetics", translation: "esthétique relationnelle", example: "Relational aesthetics focuses on human interactions and social context." },
    { word: "appropriation art", translation: "art d'appropriation", example: "Appropriation art repurposes existing images to create new meanings." },
    { word: "digital art", translation: "art numérique", example: "Digital art encompasses software-based and technologically mediated works." },
    { word: "bioart", translation: "bio-art", example: "Bioart utilizes living materials and biological processes as artistic media." },
    { word: "activist art", translation: "art militant", example: "Activist art addresses political causes through creative intervention." },
    { word: "institutional critique", translation: "critique institutionnelle", example: "Institutional critique examines power structures within art institutions." },
    { word: "ephemeral art", translation: "art éphémère", example: "Ephemeral art exists temporarily without permanent physical form." },
    { word: "postinternet art", translation: "art post-internet", example: "Postinternet art responds to ubiquitous digital connectivity and its effects." },
    { word: "artistic intervention", translation: "intervention artistique", example: "The artistic intervention disrupted everyday functions of public space." },
    { word: "immersive art", translation: "art immersif", example: "Immersive art surrounds viewers in multisensory environments." },
    { word: "artistic research", translation: "recherche artistique", example: "Artistic research generates knowledge through creative practice." },
    { word: "socially engaged art", translation: "art socialement engagé", example: "Socially engaged art collaborates with communities to address local issues." },
    { word: "experimental art", translation: "art expérimental", example: "Experimental art tests boundaries of conventional artistic practice." },
    { word: "contemporary artistic practice", translation: "pratique artistique contemporaine", example: "Contemporary artistic practice often blurs traditional disciplinary boundaries." },
    { word: "artistic discourse", translation: "discours artistique", example: "Artistic discourse connects visual practice with theoretical frameworks." },
    
    // Muséologie et commissariat (25 mots)
    { word: "museology", translation: "muséologie", example: "Museology studies theory and practice of museum functions and operations." },
    { word: "curatorial practice", translation: "pratique curatoriale", example: "Contemporary curatorial practice extends beyond traditional exhibition formats." },
    { word: "exhibition design", translation: "scénographie d'exposition", example: "Exhibition design creates spatial narratives for viewer experience." },
    { word: "art collection", translation: "collection d'art", example: "The museum's art collection encompasses diverse periods and cultures." },
    { word: "provenance research", translation: "recherche de provenance", example: "Provenance research traces ownership history of collection objects." },
    { word: "conservation", translation: "conservation", example: "Scientific conservation preserves artworks for future generations." },
    { word: "acquisition policy", translation: "politique d'acquisition", example: "The museum's acquisition policy prioritizes underrepresented artists." },
    { word: "deaccessioning", translation: "aliénation", example: "Controversial deaccessioning decisions financed operational expenses." },
    { word: "museum ethics", translation: "éthique muséale", example: "Museum ethics addresses responsible collection management and exhibition." },
    { word: "cultural heritage", translation: "patrimoine culturel", example: "Museums preserve cultural heritage through preservation and education." },
    { word: "museum studies", translation: "études muséales", example: "Museum studies programs address theoretical and practical aspects of the field." },
    { word: "exhibition narrative", translation: "récit d'exposition", example: "The exhibition narrative presented multiple perspectives on colonialism." },
    { word: "permanent collection", translation: "collection permanente", example: "The permanent collection display rotates periodically for conservation." },
    { word: "museum education", translation: "éducation muséale", example: "Museum education programs engage diverse audience constituencies." },
    { word: "curatorial statement", translation: "déclaration curatoriale", example: "The curatorial statement articulated the exhibition's conceptual framework." },
    { word: "art installation", translation: "installation d'art", example: "Art installation requires careful planning for each exhibition context." },
    { word: "cultural institution", translation: "institution culturelle", example: "The cultural institution serves multiple community functions." },
    { word: "viewer experience", translation: "expérience du visiteur", example: "Digital interactives enhance viewer experience through participation." },
    { word: "institutional critique", translation: "critique institutionnelle", example: "The exhibition incorporated institutional critique into its structure." },
    { word: "exhibition catalog", translation: "catalogue d'exposition", example: "The scholarly exhibition catalog includes commissioned essays." },
    { word: "collection management", translation: "gestion de collection", example: "Digital systems facilitate comprehensive collection management." },
    { word: "gallery space", translation: "espace d'exposition", example: "Flexible gallery space accommodates diverse installation requirements." },
    { word: "cultural representation", translation: "représentation culturelle", example: "The museum reexamined issues of cultural representation in displays." },
    { word: "interpretation strategy", translation: "stratégie d'interprétation", example: "The interpretation strategy included multilingual digital resources." },
    { word: "public engagement", translation: "engagement du public", example: "Innovative public engagement initiatives expanded audience demographics." },
    
    // Photographie et arts visuels numériques (25 mots)
    { word: "photography", translation: "photographie", example: "Digital photography has transformed contemporary visual production." },
    { word: "digital imaging", translation: "imagerie numérique", example: "Digital imaging enables unprecedented manipulation of visual information." },
    { word: "lens-based media", translation: "médias basés sur l'objectif", example: "Lens-based media encompasses film, video, and photography." },
    { word: "documentary photography", translation: "photographie documentaire", example: "Documentary photography engages with social and political realities." },
    { word: "photographic composition", translation: "composition photographique", example: "Photographic composition employs framing, perspective, and timing." },
    { word: "digital manipulation", translation: "manipulation numérique", example: "Digital manipulation raises questions about photographic truth." },
    { word: "photographic series", translation: "série photographique", example: "The photographic series explores variations on a central theme." },
    { word: "computational photography", translation: "photographie computationnelle", example: "Computational photography uses algorithms to enhance images." },
    { word: "photographic process", translation: "procédé photographique", example: "Historical photographic processes require specialized materials and techniques." },
    { word: "photographic theory", translation: "théorie photographique", example: "Photographic theory examines the medium's relationship to reality." },
    { word: "photographic archive", translation: "archive photographique", example: "The photographic archive preserves historical visual documentation." },
    { word: "photographic image", translation: "image photographique", example: "The photographic image possesses indexical relationship to its subject." },
    { word: "photographic reproduction", translation: "reproduction photographique", example: "Photographic reproduction transformed access to visual culture." },
    { word: "photographic representation", translation: "représentation photographique", example: "Photographic representation mediates our understanding of events." },
    { word: "digital platform", translation: "plateforme numérique", example: "Digital platforms democratize distribution of photographic work." },
    { word: "virtual reality", translation: "réalité virtuelle", example: "Virtual reality creates immersive three-dimensional environments." },
    { word: "augmented reality", translation: "réalité augmentée", example: "Augmented reality overlays digital information onto physical space." },
    { word: "3D modeling", translation: "modélisation 3D", example: "3D modeling constructs digital objects for various applications." },
    { word: "digital aesthetics", translation: "esthétique numérique", example: "Digital aesthetics addresses visual qualities specific to computational media." },
    { word: "projection mapping", translation: "projection mapping", example: "Projection mapping transforms architectural surfaces into dynamic displays." },
    { word: "immersive media", translation: "médias immersifs", example: "Immersive media creates multisensory environmental experiences." },
    { word: "interactive design", translation: "design interactif", example: "Interactive design creates responsive user experiences." },
    { word: "generative art", translation: "art génératif", example: "Generative art uses algorithms to create evolving visual compositions." },
    { word: "photographic practice", translation: "pratique photographique", example: "Contemporary photographic practice spans diverse approaches and technologies." },
    { word: "visual storytelling", translation: "narration visuelle", example: "Visual storytelling combines images into coherent narrative sequences." },
    
    // Marchés de l'art et industrie culturelle (25 mots)
    { word: "art market", translation: "marché de l'art", example: "The global art market encompasses auctions, galleries, and online platforms." },
    { word: "cultural industry", translation: "industrie culturelle", example: "The cultural industry commodifies creative expression for commercial distribution." },
    { word: "art valuation", translation: "évaluation d'art", example: "Art valuation considers provenance, condition, and market trends." },
    { word: "art auction", translation: "vente aux enchères d'art", example: "The art auction established a new record price for the artist." },
    { word: "art gallery", translation: "galerie d'art", example: "Commercial art galleries represent artists and mount regular exhibitions." },
    { word: "art dealer", translation: "marchand d'art", example: "The influential art dealer shaped collecting trends for decades." },
    { word: "art fair", translation: "foire d'art", example: "International art fairs attract collectors and institutions worldwide." },
    { word: "art investment", translation: "investissement artistique", example: "Art investment combines financial speculation with cultural capital." },
    { word: "art collection", translation: "collection d'art", example: "Building an art collection requires strategic acquisition decisions." },
    { word: "cultural economics", translation: "économie culturelle", example: "Cultural economics studies financial aspects of artistic production." },
    { word: "primary market", translation: "marché primaire", example: "Primary market sales occur when artwork first leaves the artist's studio." },
    { word: "secondary market", translation: "marché secondaire", example: "Secondary market resales often generate higher prices than primary sales." },
    { word: "art appraisal", translation: "expertise d'art", example: "Professional art appraisal provides official valuation for insurance purposes." },
    { word: "provenance", translation: "provenance", example: "Documented provenance significantly enhances market value." },
    { word: "art world", translation: "monde de l'art", example: "The contemporary art world encompasses global networks of institutions and individuals." },
    { word: "art philanthropy", translation: "philanthropie artistique", example: "Art philanthropy supports non-commercial creative innovation." },
    { word: "cultural capital", translation: "capital culturel", example: "Art collecting generates cultural capital beyond financial investment." },
    { word: "art speculation", translation: "spéculation artistique", example: "Art speculation treats artwork primarily as financial investment." },
    { word: "art commission", translation: "commission artistique", example: "The corporate art commission transformed the headquarters lobby." },
    { word: "art sponsorship", translation: "parrainage artistique", example: "Corporate art sponsorship supports exhibitions and institutional programming." },
    { word: "cultural funding", translation: "financement culturel", example: "Public cultural funding sustains institutions beyond market forces." },
    { word: "art insurance", translation: "assurance d'art", example: "Specialized art insurance covers transportation, exhibition, and storage risks." },
    { word: "art authentication", translation: "authentification d'art", example: "Scientific art authentication methods verify attribution and date." },
    { word: "cultural consumption", translation: "consommation culturelle", example: "Digital platforms have transformed patterns of cultural consumption." },
    { word: "art asset", translation: "actif artistique", example: "High-value collections manage artwork as significant financial assets." }
  ]
};