export const vocab = {
  title: "Expressions Idiomatiques Avancées",
  words: [
    // Expressions liées aux affaires et au monde professionnel (50 mots)
    { word: "to throw in the towel", translation: "jeter l'éponge", example: "After three failed attempts to secure funding, the startup finally threw in the towel." },
    { word: "to cut corners", translation: "faire des économies de bouts de chandelle", example: "The contractor was accused of cutting corners on building materials to increase profits." },
    { word: "to bite off more than one can chew", translation: "voir trop grand", example: "By expanding into three new markets simultaneously, the company bit off more than it could chew." },
    { word: "to hit the ground running", translation: "être opérationnel dès le début", example: "The new CEO hit the ground running, implementing changes within her first week." },
    { word: "to be in the red", translation: "être déficitaire", example: "Despite increased sales, the company remained in the red due to high operating costs." },
    { word: "to make a killing", translation: "faire fortune", example: "Early investors in the tech startup made a killing when it went public." },
    { word: "to climb the corporate ladder", translation: "gravir les échelons", example: "She climbed the corporate ladder remarkably quickly, becoming a director by age thirty." },
    { word: "to bring to the table", translation: "apporter comme contribution", example: "The new partnership manager brings extensive industry connections to the table." },
    { word: "to put all one's eggs in one basket", translation: "mettre tous ses œufs dans le même panier", example: "The investment advisor warned against putting all our eggs in one basket, regardless of how promising the opportunity seemed." },
    { word: "to think outside the box", translation: "sortir des sentiers battus", example: "Solving this market challenge will require thinking outside the box." },
    { word: "to burn bridges", translation: "brûler les ponts", example: "He burned bridges with former colleagues by speaking negatively about the company after his departure." },
    { word: "to separate the wheat from the chaff", translation: "séparer le bon grain de l'ivraie", example: "The rigorous interview process helps separate the wheat from the chaff among job applicants." },
    { word: "the elephant in the room", translation: "le sujet dont personne n'ose parler", example: "The company's financial troubles were the elephant in the room during the all-hands meeting." },
    { word: "to sweeten the deal", translation: "rendre l'offre plus attractive", example: "To convince the key executive to join, they sweetened the deal with substantial stock options." },
    { word: "to get down to brass tacks", translation: "entrer dans le vif du sujet", example: "After some pleasantries, the negotiators got down to brass tacks regarding pricing terms." },
    { word: "to hedge one's bets", translation: "ne pas mettre tous ses œufs dans le même panier", example: "The company hedged its bets by developing multiple product lines simultaneously." },
    { word: "to call the shots", translation: "prendre les décisions", example: "Though not the CEO, the founder still calls the shots on strategic direction." },
    { word: "to raise the bar", translation: "relever le niveau d'exigence", example: "Their innovative product raised the bar for the entire industry." },
    { word: "a ballpark figure", translation: "une estimation approximative", example: "I can't give you exact costs yet, but as a ballpark figure, implementation will require about $200,000." },
    { word: "to get the ball rolling", translation: "lancer les choses", example: "Let's get the ball rolling on this project by setting up an initial planning meeting." },
    { word: "to push the envelope", translation: "repousser les limites", example: "The R&D department continues to push the envelope with groundbreaking research." },
    { word: "to get one's foot in the door", translation: "se faire une place", example: "The internship helped her get her foot in the door at the prestigious consulting firm." },
    { word: "a hard sell", translation: "quelque chose de difficile à faire accepter", example: "Convincing conservative investors to fund such an experimental approach was a hard sell." },
    { word: "to keep someone in the loop", translation: "tenir quelqu'un informé", example: "Please keep me in the loop regarding any developments with the client negotiations." },
    { word: "to put something on the back burner", translation: "mettre quelque chose en attente", example: "We'll need to put the international expansion on the back burner until next quarter." },
    { word: "to pull the plug", translation: "arrêter les frais", example: "After two years of losses, investors finally pulled the plug on the venture." },
    { word: "to be on the same page", translation: "être sur la même longueur d'onde", example: "Before proceeding, I want to ensure we're all on the same page regarding the project objectives." },
    { word: "to have deep pockets", translation: "avoir beaucoup d'argent", example: "The startup succeeded partly because its founders had deep pockets to weather early setbacks." },
    { word: "to turn the tide", translation: "renverser la tendance", example: "The new marketing strategy helped turn the tide after three quarters of declining sales." },
    { word: "to read between the lines", translation: "lire entre les lignes", example: "Reading between the lines of the announcement, it seems layoffs may be imminent." },
    { word: "to test the waters", translation: "tâter le terrain", example: "Before fully committing to the Chinese market, they decided to test the waters with a limited product line." },
    { word: "to go back to the drawing board", translation: "tout reprendre à zéro", example: "After the prototype failed testing, the team went back to the drawing board." },
    { word: "to jump on the bandwagon", translation: "suivre le mouvement", example: "Many companies jumped on the sustainability bandwagon once they saw its marketing potential." },
    { word: "to give someone the green light", translation: "donner le feu vert", example: "The board gave the CEO the green light to proceed with the acquisition." },
    { word: "to cut to the chase", translation: "en venir au fait", example: "Let's cut to the chase—are you interested in the partnership or not?" },
    { word: "to miss the boat", translation: "rater le coche", example: "By delaying their digital transformation, the company missed the boat on crucial industry developments." },
    { word: "to move the goalposts", translation: "changer les règles en cours de route", example: "It's frustrating when clients move the goalposts after work has already begun." },
    { word: "to see eye to eye", translation: "être d'accord", example: "The marketing and sales departments don't always see eye to eye on campaign priorities." },
    { word: "to keep one's head above water", translation: "garder la tête hors de l'eau", example: "During the recession, many small businesses struggled just to keep their heads above water." },
    { word: "a cash cow", translation: "une vache à lait", example: "The printer ink business remains the company's cash cow, generating reliable profits." },
    { word: "to give someone a run for their money", translation: "donner du fil à retordre", example: "The new competitor is giving established firms a run for their money with innovative pricing." },
    { word: "to weather the storm", translation: "résister aux difficultés", example: "With adequate capital reserves, the company was able to weather the storm during the market downturn." },
    { word: "to be ahead of the curve", translation: "avoir une longueur d'avance", example: "Their early investment in artificial intelligence put them ahead of the curve in their industry." },
    { word: "to bite the bullet", translation: "prendre son courage à deux mains", example: "The company finally bit the bullet and discontinued its underperforming legacy product line." },
    { word: "to break even", translation: "atteindre le seuil de rentabilité", example: "The startup expects to break even by the end of its second year of operations." },
    { word: "to talk shop", translation: "parler métier", example: "Even at social gatherings, the colleagues couldn't help talking shop." },
    { word: "to pick someone's brain", translation: "demander l'avis de quelqu'un", example: "I'd like to pick your brain about the Asian market expansion strategy." },
    { word: "a shoestring budget", translation: "un budget très serré", example: "The team launched the product on a shoestring budget, relying heavily on organic marketing." },
    { word: "to put out fires", translation: "résoudre des problèmes urgents", example: "The new manager spent her first month putting out fires left by her predecessor." },
    { word: "to take the bull by the horns", translation: "prendre le taureau par les cornes", example: "Rather than delaying the difficult restructuring, the CEO took the bull by the horns." },
    
    // Expressions liées à la communication et aux relations (50 mots)
    { word: "to beat around the bush", translation: "tourner autour du pot", example: "Stop beating around the bush and tell me directly what happened with the client." },
    { word: "to put one's foot in one's mouth", translation: "faire un impair", example: "He put his foot in his mouth by asking about her pregnancy when she had simply gained weight." },
    { word: "to read someone like a book", translation: "cerner quelqu'un facilement", example: "After working together for years, she could read her business partner like a book." },
    { word: "to give someone the cold shoulder", translation: "battre froid à quelqu'un", example: "After the disagreement, several colleagues gave him the cold shoulder at the conference." },
    { word: "to hit a nerve", translation: "toucher un point sensible", example: "The journalist's question about executive compensation hit a nerve during the press conference." },
    { word: "to break the ice", translation: "briser la glace", example: "The team-building activity helped break the ice among the newly merged departments." },
    { word: "to get off on the wrong foot", translation: "mal commencer une relation", example: "They got off on the wrong foot when she criticized his proposal during their first meeting." },
    { word: "to see through someone", translation: "ne pas être dupe de quelqu'un", example: "Experienced negotiators can see through attempts at artificial time pressure." },
    { word: "to talk at cross purposes", translation: "ne pas parler de la même chose", example: "It became clear that the teams were talking at cross purposes regarding project objectives." },
    { word: "to let something slip", translation: "laisser échapper une information", example: "During the interview, the executive accidentally let slip information about the upcoming merger." },
    { word: "to speak volumes", translation: "être très révélateur", example: "The CEO's absence from the announcement speaks volumes about the company's direction." },
    { word: "to take something with a grain of salt", translation: "prendre avec des pincettes", example: "You should take market forecasts with a grain of salt, especially during volatile periods." },
    { word: "to sugarcoat something", translation: "enjoliver quelque chose", example: "The annual report sugarcoated the significant challenges facing the company." },
    { word: "to play devil's advocate", translation: "jouer l'avocat du diable", example: "Let me play devil's advocate for a moment—what if the competitor lowers their prices in response?" },
    { word: "to get to the point", translation: "en venir au fait", example: "After a lengthy introduction, the presenter finally got to the point of the proposal." },
    { word: "to put in a good word", translation: "recommander quelqu'un", example: "My former manager put in a good word for me during the interview process." },
    { word: "to hold one's tongue", translation: "se retenir de parler", example: "She held her tongue during the meeting, saving her criticisms for a private conversation later." },
    { word: "to save face", translation: "sauver les apparences", example: "The company offered the concession to allow their client to save face after the public disagreement." },
    { word: "to be on the fence", translation: "être indécis", example: "Several board members remain on the fence regarding the proposed acquisition." },
    { word: "to be in someone's shoes", translation: "être à la place de quelqu'un", example: "If I were in your shoes, I would request more information before making the commitment." },
    { word: "to keep tabs on", translation: "surveiller", example: "The project manager keeps tabs on all team members' progress through weekly reports." },
    { word: "to wear one's heart on one's sleeve", translation: "ne pas cacher ses sentiments", example: "As a leader, she wears her heart on her sleeve, sharing both enthusiasm and concerns openly." },
    { word: "to go over someone's head", translation: "s'adresser au supérieur de quelqu'un", example: "Instead of resolving the issue directly, he went over his manager's head to the director." },
    { word: "to lay one's cards on the table", translation: "mettre cartes sur table", example: "During the negotiation, she decided to lay her cards on the table about her company's limitations." },
    { word: "to put words in someone's mouth", translation: "faire dire à quelqu'un ce qu'il n'a pas dit", example: "Don't put words in my mouth—I never said we would guarantee those delivery dates." },
    { word: "to give someone the benefit of the doubt", translation: "accorder le bénéfice du doute", example: "Despite the missed deadline, the manager gave his team the benefit of the doubt due to extenuating circumstances." },
    { word: "to hit it off", translation: "bien s'entendre dès le début", example: "The two executives hit it off immediately, facilitating the partnership discussions." },
    { word: "to take someone under one's wing", translation: "prendre quelqu'un sous son aile", example: "The experienced consultant took several junior colleagues under her wing, offering valuable mentorship." },
    { word: "to ruffle feathers", translation: "froisser des sensibilités", example: "The new policy ruffled feathers among the senior staff who preferred the traditional approach." },
    { word: "to go through the motions", translation: "faire quelque chose sans conviction", example: "Some employees were merely going through the motions during the mandatory training." },
    { word: "to put someone on a pedestal", translation: "idéaliser quelqu'un", example: "The danger of putting industry leaders on a pedestal is that we overlook their strategic mistakes." },
    { word: "to get a word in edgewise", translation: "placer un mot", example: "The discussion was so dominated by the senior partner that others could barely get a word in edgewise." },
    { word: "to be all ears", translation: "être tout ouïe", example: "When the client began explaining their requirements, the consultants were all ears." },
    { word: "to read the room", translation: "sentir l'ambiance", example: "A good presenter knows how to read the room and adjust their approach accordingly." },
    { word: "to have a chip on one's shoulder", translation: "avoir une attitude défensive", example: "The new hire had a chip on his shoulder about his lack of formal education." },
    { word: "to call someone on the carpet", translation: "réprimander quelqu'un", example: "The CEO called the marketing director on the carpet after the failed product launch." },
    { word: "to step on someone's toes", translation: "marcher sur les plates-bandes de quelqu'un", example: "The new initiative inadvertently stepped on the toes of the established department." },
    { word: "to get wind of something", translation: "entendre parler de quelque chose", example: "When investors got wind of the potential acquisition, the stock price jumped." },
    { word: "to bury the hatchet", translation: "enterrer la hache de guerre", example: "The competing firms decided to bury the hatchet and explore collaboration opportunities." },
    { word: "to butter someone up", translation: "flatter quelqu'un de manière excessive", example: "He tried to butter up the client before asking for the contract extension." },
    { word: "to get one's wires crossed", translation: "avoir un malentendu", example: "We got our wires crossed about the meeting time, which is why I arrived an hour late." },
    { word: "to keep someone at arm's length", translation: "garder quelqu'un à distance", example: "The founder kept potential investors at arm's length until the prototype was completed." },
    { word: "to sing someone's praises", translation: "faire l'éloge de quelqu'un", example: "The director has been singing your praises after the successful project delivery." },
    { word: "to take something at face value", translation: "prendre quelque chose au pied de la lettre", example: "Experienced auditors never take financial statements at face value." },
    { word: "to wash one's hands of something", translation: "se désolidariser de quelque chose", example: "After raising concerns and being ignored, she washed her hands of the questionable project." },
    { word: "to make amends", translation: "réparer ses torts", example: "The company tried to make amends for the data breach by offering free credit monitoring." },
    { word: "to bend over backwards", translation: "se mettre en quatre", example: "The client success team bent over backwards to accommodate the high-profile customer's demands." },
    { word: "to stick one's neck out", translation: "prendre des risques", example: "The junior analyst stuck her neck out by questioning the executive's projections during the meeting." },
    { word: "to tread on thin ice", translation: "être en terrain glissant", example: "When discussing potential layoffs, managers need to recognize they're treading on thin ice." },
    
    // Expressions pour la prise de décision et les situations complexes (50 mots)
    { word: "to bite the bullet", translation: "prendre son courage à deux mains", example: "After months of deliberation, the board bit the bullet and approved the costly but necessary infrastructure upgrade." },
    { word: "to cross the Rubicon", translation: "franchir le Rubicon", example: "By going public with the allegations, the whistleblower had crossed the Rubicon—there was no turning back." },
    { word: "between a rock and a hard place", translation: "entre le marteau et l'enclume", example: "The CEO found himself between a rock and a hard place: cut jobs or risk bankruptcy." },
    { word: "to cut the Gordian knot", translation: "trancher le nœud gordien", example: "The mediator cut the Gordian knot by proposing a completely novel solution acceptable to both parties." },
    { word: "to face the music", translation: "affronter les conséquences", example: "After the failed project, the team had to face the music during the executive review." },
    { word: "to go out on a limb", translation: "prendre un risque", example: "The analyst went out on a limb with her contrary market prediction, which ultimately proved correct." },
    { word: "to grasp the nettle", translation: "prendre le taureau par les cornes", example: "Rather than delaying further, the new director grasped the nettle and initiated the difficult restructuring." },
    { word: "to have an ace up one's sleeve", translation: "avoir plus d'un tour dans son sac", example: "During the difficult negotiations, the company had an ace up its sleeve: a signed letter of intent from a major competitor." },
    { word: "to jump the gun", translation: "agir prématurément", example: "The marketing team jumped the gun by announcing features that were still in development." },
    { word: "to navigate uncharted waters", translation: "s'aventurer en terrain inconnu", example: "Entering the emerging market required the company to navigate uncharted waters." },
    { word: "to open a can of worms", translation: "ouvrir la boîte de Pandore", example: "The internal audit opened a can of worms regarding the previous accounting practices." },
    { word: "to play hardball", translation: "jouer dur", example: "When negotiations stalled, the acquiring company began playing hardball with aggressive deadlines." },
    { word: "to roll the dice", translation: "jouer le tout pour le tout", example: "With the new product launch, the struggling company was essentially rolling the dice on its future." },
    { word: "to stick to one's guns", translation: "camper sur ses positions", example: "Despite pressure from shareholders, the CEO stuck to her guns regarding the ethical sourcing policy." },
    { word: "to take the bull by the horns", translation: "prendre le taureau par les cornes", example: "The new manager took the bull by the horns and addressed the team's performance issues directly." },
    { word: "to throw caution to the wind", translation: "jeter la prudence aux orties", example: "With nothing left to lose, the startup threw caution to the wind with its disruptive business model." },
    { word: "to tread carefully", translation: "avancer avec prudence", example: "When restructuring international operations, the company needs to tread carefully regarding local regulations." },
    { word: "to venture into the lion's den", translation: "s'aventurer dans la fosse aux lions", example: "The spokesperson ventured into the lion's den by agreeing to an interview with the normally hostile media outlet." },
    { word: "to weather the storm", translation: "résister aux difficultés", example: "With adequate capital reserves, the company was able to weather the storm during the economic downturn." },
    { word: "to be caught between Scylla and Charybdis", translation: "être entre Charybde et Scylla", example: "The central bank was caught between Scylla and Charybdis: raise rates and risk recession, or maintain them and risk inflation." },
    { word: "to burn one's bridges", translation: "brûler ses vaisseaux", example: "By publicly criticizing the industry leader, the startup burned its bridges regarding potential partnership opportunities." },
    { word: "to cross the bridge when one comes to it", translation: "aviser en temps voulu", example: "Rather than worrying about potential regulatory changes, we'll cross that bridge when we come to it." },
    { word: "to have too many irons in the fire", translation: "courir plusieurs lièvres à la fois", example: "The company's poor performance stemmed from having too many irons in the fire and lacking focus." },
    { word: "to leave no stone unturned", translation: "ne négliger aucune piste", example: "The due diligence team left no stone unturned in their examination of the acquisition target." },
    { word: "to play devil's advocate", translation: "jouer l'avocat du diable", example: "To stress-test the strategy, the consultant played devil's advocate during the planning session." },
    { word: "to play one's cards close to one's chest", translation: "garder ses cartes près de son corps", example: "During negotiations, the investor played his cards close to his chest regarding his true budget." },
    { word: "to pull out all the stops", translation: "mettre le paquet", example: "For the critical product launch, the marketing team pulled out all the stops with a comprehensive campaign." },
    { word: "to put all one's eggs in one basket", translation: "mettre tous ses œufs dans le même panier", example: "The investment advisory warned against putting all our eggs in one basket, even with promising opportunities." },
    { word: "to rise to the occasion", translation: "être à la hauteur de la situation", example: "Despite being relatively inexperienced, the project manager rose to the occasion during the crisis." },
    { word: "to take a calculated risk", translation: "prendre un risque calculé", example: "Entering the emerging market was a calculated risk based on extensive research and controlled investment." },
    { word: "to take a leaf out of someone's book", translation: "s'inspirer de quelqu'un", example: "The startup took a leaf out of the tech giant's book by implementing a similar customer service approach." },
    { word: "to take a step back", translation: "prendre du recul", example: "Before making such a significant decision, we need to take a step back and consider all implications." },
    { word: "to think on one's feet", translation: "improviser", example: "When the presentation technology failed, the speaker had to think on her feet to engage the audience without slides." },
    { word: "to thread the needle", translation: "trouver le juste milieu", example: "The policy attempts to thread the needle between encouraging innovation and ensuring consumer protection." },
    { word: "to walk a fine line", translation: "jouer sur le fil du rasoir", example: "The diplomat walks a fine line between representing national interests and maintaining international relationships." },
    { word: "to fly by the seat of one's pants", translation: "improviser sans préparation", example: "Without clear market data, the expansion team was essentially flying by the seat of their pants." },
    { word: "to do some soul-searching", translation: "faire son examen de conscience", example: "After the project failure, the leadership team did some soul-searching about their risk assessment process." },
    { word: "to follow one's gut", translation: "suivre son instinct", example: "Despite contradictory data, the entrepreneur followed her gut and launched the product successfully." },
    { word: "to hang by a thread", translation: "ne tenir qu'à un fil", example: "After losing the major contract, the company's survival hung by a thread." },
    { word: "to have one's back against the wall", translation: "être dos au mur", example: "With creditors demanding payment, the company had its back against the wall and few options remaining." },
    { word: "to pass the buck", translation: "rejeter la responsabilité sur quelqu'un d'autre", example: "Rather than addressing the issue, the manager passed the buck to the IT department." },
    { word: "to pull the rug out from under someone", translation: "couper l'herbe sous le pied", example: "The sudden policy change pulled the rug out from under businesses that had invested based on previous guidelines." },
    { word: "to put the cart before the horse", translation: "mettre la charrue avant les bœufs", example: "Launching the marketing campaign before completing product testing is putting the cart before the horse." },
    { word: "to read the tea leaves", translation: "prédire l'avenir", example: "Investors are trying to read the tea leaves regarding future central bank actions." },
    { word: "to rock the boat", translation: "faire des vagues", example: "The new executive wasn't afraid to rock the boat by questioning long-established practices." },
    { word: "to see which way the wind blows", translation: "voir de quel côté le vent souffle", example: "Some committee members delayed their vote, preferring to see which way the wind blows first." },
    { word: "to take the plunge", translation: "se jeter à l'eau", example: "After months of deliberation, they finally took the plunge and invested in the expansion." },
    { word: "to turn over a new leaf", translation: "tourner la page", example: "Following the scandal, the organization pledged to turn over a new leaf with comprehensive ethical reforms." },
    { word: "to enter a minefield", translation: "s'engager en terrain miné", example: "Discussing compensation disparities is entering a minefield that requires careful navigation." },
    
    // Expressions reflétant des attitudes et valeurs (50 mots)
    { word: "actions speak louder than words", translation: "les actes en disent plus que les paroles", example: "The CEO talks about sustainability, but actions speak louder than words—the company needs concrete policies." },
    { word: "all that glitters is not gold", translation: "tout ce qui brille n'est pas or", example: "The startup had impressive growth metrics, but as investors discovered, all that glitters is not gold." },
    { word: "better late than never", translation: "mieux vaut tard que jamais", example: "The company finally implemented cybersecurity measures; better late than never, though the delay was costly." },
    { word: "don't put the cart before the horse", translation: "ne pas mettre la charrue avant les bœufs", example: "Let's complete the market research before designing the product—don't put the cart before the horse." },
    { word: "the early bird catches the worm", translation: "l'avenir appartient à ceux qui se lèvent tôt", example: "By entering the emerging market before competitors, they proved that the early bird catches the worm." },
    { word: "hindsight is 20/20", translation: "avec du recul, tout paraît évident", example: "Hindsight is 20/20, but at the time, diversification seemed the prudent strategy." },
    { word: "luck is what happens when preparation meets opportunity", translation: "la chance sourit aux esprits bien préparés", example: "Their 'overnight success' demonstrates that luck is what happens when preparation meets opportunity." },
    { word: "necessity is the mother of invention", translation: "la nécessité est mère de l'invention", example: "The pandemic proved that necessity is the mother of invention as businesses rapidly adapted their operations." },
    { word: "no pain, no gain", translation: "on n'a rien sans rien", example: "The difficult restructuring caused short-term disruption but confirmed the adage 'no pain, no gain'." },
    { word: "the proof of the pudding is in the eating", translation: "c'est au pied du mur qu'on voit le maçon", example: "The strategy looks good on paper, but the proof of the pudding is in the eating—we'll see how it performs." },
    { word: "there's no such thing as a free lunch", translation: "rien n'est gratuit dans la vie", example: "The 'free' software actually monetizes user data—there's no such thing as a free lunch." },
    { word: "time is money", translation: "le temps, c'est de l'argent", example: "The efficiency initiative reflects the understanding that time is money in manufacturing operations." },
    { word: "when in Rome, do as the Romans do", translation: "à Rome, fais comme les Romains", example: "Our international expansion follows the principle 'when in Rome, do as the Romans do' by adapting to local business practices." },
    { word: "you can't make an omelette without breaking eggs", translation: "on ne fait pas d'omelette sans casser des œufs", example: "The merger will inevitably cause some disruption—you can't make an omelette without breaking eggs." },
    { word: "a leopard cannot change its spots", translation: "chassez le naturel, il revient au galop", example: "Despite promises of reform, the company's repeated ethical violations suggest a leopard cannot change its spots." },
    { word: "don't cry over spilled milk", translation: "ce qui est fait est fait", example: "Rather than dwelling on the failed launch, let's not cry over spilled milk and focus on the next opportunity." },
    { word: "a chain is only as strong as its weakest link", translation: "une chaîne n'est pas plus solide que son maillon le plus faible", example: "The security breach demonstrated that a chain is only as strong as its weakest link—in this case, inadequate vendor protocols." },
    { word: "a bird in the hand is worth two in the bush", translation: "un tiens vaut mieux que deux tu l'auras", example: "We accepted the smaller but certain acquisition offer, believing a bird in the hand is worth two in the bush." },
    { word: "all roads lead to Rome", translation: "tous les chemins mènent à Rome", example: "The various analysis methods all reached similar conclusions, proving that all roads lead to Rome." },
    { word: "barking up the wrong tree", translation: "faire fausse route", example: "The investigators were barking up the wrong tree by focusing on the finance department when the issues originated in operations." },
    { word: "the devil is in the details", translation: "le diable se cache dans les détails", example: "The merger seemed straightforward until due diligence revealed that the devil is in the details." },
    { word: "don't judge a book by its cover", translation: "il ne faut pas juger sur les apparences", example: "The unassuming startup with modest offices proved that you shouldn't judge a book by its cover when they revealed their impressive technology." },
    { word: "every cloud has a silver lining", translation: "à quelque chose malheur est bon", example: "The market downturn has a silver lining—it allows acquisition of assets at favorable valuations." },
    { word: "it takes two to tango", translation: "il faut être deux pour danser le tango", example: "The failed partnership demonstrates that it takes two to tango—both organizations must be fully committed." },
    { word: "kill two birds with one stone", translation: "faire d'une pierre deux coups", example: "The new policy kills two birds with one stone by reducing costs and improving environmental compliance." },
    { word: "look before you leap", translation: "regarder avant de sauter", example: "The cautious approach to expansion reflects the wisdom to look before you leap into new markets." },
    { word: "make hay while the sun shines", translation: "il faut battre le fer pendant qu'il est chaud", example: "The company is making hay while the sun shines by expanding during favorable market conditions." },
    { word: "once bitten, twice shy", translation: "chat échaudé craint l'eau froide", example: "After the failed venture in Asia, the company is once bitten, twice shy about international expansion." },
    { word: "out of the frying pan into the fire", translation: "tomber de Charybde en Scylla", example: "By avoiding the regulatory scrutiny but facing new competitive pressures, the company went out of the frying pan into the fire." },
    { word: "penny wise, pound foolish", translation: "économiser des bouts de chandelle", example: "Cutting the training budget proved penny wise but pound foolish as productivity declined significantly." },
    { word: "the pot calling the kettle black", translation: "c'est l'hôpital qui se moque de la charité", example: "The corporation criticizing startup ethics is the pot calling the kettle black given their own compliance issues." },
    { word: "Rome wasn't built in a day", translation: "Rome ne s'est pas faite en un jour", example: "Creating a robust compliance program takes time—Rome wasn't built in a day." },
    { word: "strike while the iron is hot", translation: "battre le fer pendant qu'il est chaud", example: "With competitor weakness and available capital, now is the time to strike while the iron is hot with acquisitions." },
    { word: "too many cooks spoil the broth", translation: "trop de cuisiniers gâtent la sauce", example: "The project suffered from too many cooks spoiling the broth as multiple departments competed for influence." },
    { word: "when it rains, it pours", translation: "un malheur n'arrive jamais seul", example: "Following the product recall, the company faced litigation and regulatory investigations—when it rains, it pours." },
    { word: "you can't have your cake and eat it too", translation: "on ne peut pas avoir le beurre et l'argent du beurre", example: "The company wants growth without investment, but you can't have your cake and eat it too." },
    { word: "you can't teach an old dog new tricks", translation: "on ne change pas les vieilles habitudes", example: "The resistance to digital transformation showed that you can't easily teach old dogs new tricks in traditional industries." },
    { word: "the best of both worlds", translation: "le meilleur des deux mondes", example: "The hybrid work model offers the best of both worlds: flexibility for employees and collaboration opportunities." },
    { word: "a blessing in disguise", translation: "un mal pour un bien", example: "Losing the government contract forced diversification, which proved a blessing in disguise when public spending was cut." },
    { word: "cross that bridge when you come to it", translation: "on verra en temps voulu", example: "Rather than worrying about potential regulatory changes, we'll cross that bridge when we come to it." },
    { word: "cutting corners", translation: "faire des économies de bouts de chandelle", example: "The investigation revealed that cutting corners on safety protocols led to the industrial accident." },
    { word: "the elephant in the room", translation: "le sujet dont personne n'ose parler", example: "The company's unsustainable debt burden was the elephant in the room during strategic discussions." },
    { word: "get a taste of one's own medicine", translation: "goûter à sa propre médecine", example: "After years of aggressive tactics, the company got a taste of its own medicine when facing a hostile takeover." },
    { word: "hit the nail on the head", translation: "mettre dans le mille", example: "The analysis hit the nail on the head by identifying supply chain vulnerabilities as our primary risk." },
    { word: "leave no stone unturned", translation: "ne négliger aucune piste", example: "The audit team will leave no stone unturned in investigating the accounting discrepancies." },
    { word: "miss the boat", translation: "rater le coche", example: "By delaying their digital transformation, the retailer missed the boat on e-commerce growth." },
    { word: "the tip of the iceberg", translation: "la partie visible de l'iceberg", example: "The identified compliance issues are just the tip of the iceberg in terms of governance problems." },
    { word: "wait for the dust to settle", translation: "attendre que la poussière retombe", example: "Investors are waiting for the dust to settle after the market turbulence before making new commitments." },
    { word: "walk the talk", translation: "joindre le geste à la parole", example: "Leaders must walk the talk on diversity initiatives by implementing concrete changes, not just making statements." },
    { word: "weather the storm", translation: "résister à la tempête", example: "Companies with strong balance sheets can weather the storm during economic downturns." }
  ]
};