export const vocab = {
  title: "Santé Publique et Épidémiologie",
  words: [
    // Concepts fondamentaux en santé publique (50 mots)
    { word: "public health", translation: "santé publique", example: "Public health initiatives focus on population-level interventions rather than individual clinical care." },
    { word: "epidemiology", translation: "épidémiologie", example: "Epidemiology investigates patterns, causes, and effects of health conditions within defined populations." },
    { word: "health determinants", translation: "déterminants de la santé", example: "Social and economic factors often exert stronger influence as health determinants than healthcare access." },
    { word: "social determinants of health", translation: "déterminants sociaux de la santé", example: "Housing conditions represent critical social determinants of health affecting multiple outcomes." },
    { word: "health inequity", translation: "iniquité en santé", example: "Health inequity refers to systematic disparities in health outcomes that are avoidable and unjust." },
    { word: "health disparities", translation: "disparités en matière de santé", example: "Persistent health disparities exist across socioeconomic, racial, and geographic dimensions." },
    { word: "health equity", translation: "équité en matière de santé", example: "Health equity initiatives address structural barriers to optimal outcomes for marginalized populations." },
    { word: "population health", translation: "santé des populations", example: "Population health approaches consider multiple factors beyond medical care that influence outcomes." },
    { word: "health promotion", translation: "promotion de la santé", example: "Health promotion empowers individuals and communities to increase control over their well-being." },
    { word: "disease prevention", translation: "prévention des maladies", example: "Primary disease prevention focuses on averting initial occurrence through risk factor reduction." },
    { word: "primary prevention", translation: "prévention primaire", example: "Vaccination represents a classic primary prevention strategy against infectious diseases." },
    { word: "secondary prevention", translation: "prévention secondaire", example: "Secondary prevention through screening programs enables early disease detection and intervention." },
    { word: "tertiary prevention", translation: "prévention tertiaire", example: "Tertiary prevention aims to reduce complications and disability from established disease." },
    { word: "health surveillance", translation: "surveillance sanitaire", example: "Ongoing health surveillance monitors disease trends and emerging threats in populations." },
    { word: "disease surveillance", translation: "surveillance des maladies", example: "Global disease surveillance networks provide early warning of potential outbreaks." },
    { word: "syndromic surveillance", translation: "surveillance syndromique", example: "Syndromic surveillance monitors symptom patterns to detect outbreaks before laboratory confirmation." },
    { word: "community health", translation: "santé communautaire", example: "Community health approaches engage local populations as active participants rather than passive recipients." },
    { word: "community-based participatory research", translation: "recherche participative communautaire", example: "Community-based participatory research involves residents in study design, implementation, and dissemination." },
    { word: "health impact assessment", translation: "évaluation d'impact sur la santé", example: "Health impact assessment examines potential effects of policies across various sectors on population health." },
    { word: "health system", translation: "système de santé", example: "Resilient health systems maintain essential services during crises while addressing emergency needs." },
    { word: "public health infrastructure", translation: "infrastructure de santé publique", example: "Sustained investment in public health infrastructure is necessary for effective emergency response." },
    { word: "health policy", translation: "politique de santé", example: "Evidence-informed health policy balances scientific knowledge with contextual political realities." },
    { word: "health economics", translation: "économie de la santé", example: "Health economics evaluates efficiency and value in healthcare resource allocation." },
    { word: "burden of disease", translation: "charge de morbidité", example: "The global burden of disease study quantifies health loss from hundreds of conditions worldwide." },
    { word: "disability-adjusted life year", translation: "année de vie ajustée sur l'incapacité", example: "Disability-adjusted life years combine premature mortality and years lived with disability." },
    { word: "quality-adjusted life year", translation: "année de vie ajustée par la qualité", example: "Quality-adjusted life years incorporate both survival and health-related quality of life." },
    { word: "healthy life expectancy", translation: "espérance de vie en bonne santé", example: "Healthy life expectancy measures expected years of life in full health without disability." },
    { word: "health literacy", translation: "littératie en santé", example: "Limited health literacy contributes to preventable adverse outcomes and healthcare disparities." },
    { word: "health behavior", translation: "comportement de santé", example: "Health behavior change interventions address both individual and environmental influences." },
    { word: "behavioral determinants", translation: "déterminants comportementaux", example: "Effective interventions address multiple behavioral determinants beyond knowledge provision." },
    { word: "health risk factor", translation: "facteur de risque sanitaire", example: "Modifiable health risk factors include tobacco use, unhealthy diet, and physical inactivity." },
    { word: "non-communicable disease", translation: "maladie non transmissible", example: "Non-communicable diseases represent the leading cause of global mortality and disability." },
    { word: "communicable disease", translation: "maladie transmissible", example: "Communicable disease control requires understanding transmission dynamics and effective interventions." },
    { word: "disease outbreak", translation: "flambée épidémique", example: "Early disease outbreak detection enables rapid containment before widespread transmission." },
    { word: "epidemic", translation: "épidémie", example: "The epidemic spread rapidly due to high population density and limited control measures." },
    { word: "pandemic", translation: "pandémie", example: "Pandemic preparedness requires coordination across national boundaries and sectors." },
    { word: "endemic disease", translation: "maladie endémique", example: "Endemic diseases persist at baseline levels within specific geographic regions or populations." },
    { word: "zoonotic disease", translation: "zoonose", example: "Zoonotic diseases transmit between animals and humans, often resulting from ecological disruption." },
    { word: "vector-borne disease", translation: "maladie à transmission vectorielle", example: "Vector-borne disease distribution shifts with changing climate and land use patterns." },
    { word: "herd immunity", translation: "immunité collective", example: "Herd immunity protects vulnerable individuals when sufficient population immunity prevents transmission." },
    { word: "health security", translation: "sécurité sanitaire", example: "Global health security requires robust detection, prevention, and response capabilities across countries." },
    { word: "one health", translation: "une seule santé", example: "The One Health approach recognizes interconnections between human, animal, and environmental health." },
    { word: "planetary health", translation: "santé planétaire", example: "Planetary health examines human health impacts of anthropogenic environmental and ecosystem changes." },
    { word: "environmental health", translation: "santé environnementale", example: "Environmental health addresses physical, chemical, and biological factors affecting population well-being." },
    { word: "climate change and health", translation: "changement climatique et santé", example: "Climate change and health research examines both direct and indirect impacts on human well-being." },
    { word: "health in all policies", translation: "la santé dans toutes les politiques", example: "Health in all policies approaches integrate health considerations across governmental sectors." },
    { word: "global health", translation: "santé mondiale", example: "Global health addresses transnational health issues requiring collaborative solutions." },
    { word: "international health regulations", translation: "règlement sanitaire international", example: "International health regulations establish legally binding frameworks for disease control across borders." },
    { word: "universal health coverage", translation: "couverture sanitaire universelle", example: "Universal health coverage ensures all people receive needed services without financial hardship." },
    
    // Méthodes épidémiologiques et recherche (50 mots)
    { word: "epidemiological study", translation: "étude épidémiologique", example: "The epidemiological study examined associations between exposures and health outcomes in the population." },
    { word: "descriptive epidemiology", translation: "épidémiologie descriptive", example: "Descriptive epidemiology characterizes disease distribution by person, place, and time." },
    { word: "analytical epidemiology", translation: "épidémiologie analytique", example: "Analytical epidemiology investigates causal factors through comparisons between groups." },
    { word: "experimental epidemiology", translation: "épidémiologie expérimentale", example: "Experimental epidemiology tests interventions through controlled trials within populations." },
    { word: "disease surveillance", translation: "surveillance des maladies", example: "Effective disease surveillance provides timely information for public health action." },
    { word: "case definition", translation: "définition de cas", example: "A standardized case definition ensures consistent patient classification during outbreak investigations." },
    { word: "incidence", translation: "incidence", example: "Incidence measures the rate of new cases in a population during a specific time period." },
    { word: "prevalence", translation: "prévalence", example: "Prevalence indicates the proportion of a population affected by a condition at a specific point or period." },
    { word: "mortality rate", translation: "taux de mortalité", example: "Age-adjusted mortality rates enable fair comparisons between populations with different structures." },
    { word: "morbidity", translation: "morbidité", example: "Morbidity statistics quantify disease burden beyond mortality measures." },
    { word: "case-fatality rate", translation: "taux de létalité", example: "The case-fatality rate indicates the proportion of diagnosed cases resulting in death." },
    { word: "excess mortality", translation: "surmortalité", example: "Excess mortality measures deaths beyond expected baseline during specific events like pandemics." },
    { word: "life expectancy", translation: "espérance de vie", example: "Life expectancy calculations reflect current mortality patterns if applied throughout a population's lifetime." },
    { word: "age-adjusted rate", translation: "taux ajusté selon l'âge", example: "Age-adjusted rates control for demographic differences when comparing populations." },
    { word: "standardized mortality ratio", translation: "ratio standardisé de mortalité", example: "The standardized mortality ratio compares observed deaths with expected deaths based on reference population rates." },
    { word: "epidemiological transition", translation: "transition épidémiologique", example: "Epidemiological transition describes population health shifts from infectious to chronic disease predominance." },
    { word: "demographic transition", translation: "transition démographique", example: "Demographic transition reflects population changes in fertility, mortality, and age structure over time." },
    { word: "cohort study", translation: "étude de cohorte", example: "The prospective cohort study followed participants for 20 years to assess exposure-outcome relationships." },
    { word: "case-control study", translation: "étude cas-témoins", example: "The case-control study compared exposure histories between affected individuals and similar unaffected controls." },
    { word: "cross-sectional study", translation: "étude transversale", example: "The cross-sectional study measured both exposures and outcomes simultaneously in the population." },
    { word: "ecological study", translation: "étude écologique", example: "The ecological study analyzed relationships between environmental factors and disease rates across regions." },
    { word: "randomized controlled trial", translation: "essai contrôlé randomisé", example: "Randomized controlled trials provide strong evidence for causal relationships through experimental design." },
    { word: "cluster randomized trial", translation: "essai randomisé en grappes", example: "The cluster randomized trial assigned entire communities rather than individuals to intervention conditions." },
    { word: "natural experiment", translation: "expérience naturelle", example: "The natural experiment leveraged policy differences between regions to assess intervention effects." },
    { word: "prospective study", translation: "étude prospective", example: "The prospective study design measured exposures before outcome occurrence to establish temporal precedence." },
    { word: "retrospective study", translation: "étude rétrospective", example: "The retrospective study examined existing records to analyze past exposure-outcome relationships." },
    { word: "longitudinal study", translation: "étude longitudinale", example: "The longitudinal study tracked the same individuals over multiple years to detect health changes." },
    { word: "transmission dynamics", translation: "dynamique de transmission", example: "Mathematical models of transmission dynamics inform control strategy selection and implementation." },
    { word: "basic reproduction number", translation: "taux de reproduction de base", example: "The basic reproduction number (R0) indicates the average secondary cases from one infected person in a susceptible population." },
    { word: "effective reproduction number", translation: "taux de reproduction effectif", example: "The effective reproduction number accounts for immunity levels and control measures in ongoing outbreaks." },
    { word: "epidemic curve", translation: "courbe épidémique", example: "The epidemic curve's shape provides insights about transmission patterns and intervention effects." },
    { word: "contact tracing", translation: "recherche des contacts", example: "Thorough contact tracing identifies exposed individuals for monitoring and preventive interventions." },
    { word: "disease cluster", translation: "agrégat de cas", example: "The investigation examined whether the disease cluster represented random chance or a common source." },
    { word: "index case", translation: "cas index", example: "The investigation identified the index case who introduced the pathogen to the previously unaffected community." },
    { word: "super-spreader", translation: "super-propagateur", example: "A single super-spreader event resulted in dozens of secondary transmission chains." },
    { word: "attack rate", translation: "taux d'atteinte", example: "The attack rate measures the proportion of exposed population that develops the disease." },
    { word: "secondary attack rate", translation: "taux d'atteinte secondaire", example: "The secondary attack rate indicates transmission efficiency within household or close contact settings." },
    { word: "relative risk", translation: "risque relatif", example: "A relative risk of 3.5 indicates the exposed group had 3.5 times higher disease risk than the unexposed group." },
    { word: "odds ratio", translation: "rapport des cotes", example: "The odds ratio approximates relative risk in case-control studies when the disease is relatively rare." },
    { word: "absolute risk", translation: "risque absolu", example: "Absolute risk measures provide context for interpreting relative risk statistics." },
    { word: "population attributable risk", translation: "risque attribuable dans la population", example: "Population attributable risk estimates the proportion of disease burden preventable by eliminating an exposure." },
    { word: "confounding factor", translation: "facteur de confusion", example: "The analysis controlled for potential confounding factors including age, sex, and socioeconomic status." },
    { word: "bias", translation: "biais", example: "Careful study design minimized potential bias sources including selection and measurement error." },
    { word: "effect modification", translation: "modification d'effet", example: "The analysis revealed effect modification, with stronger associations in older populations." },
    { word: "dose-response relationship", translation: "relation dose-effet", example: "The study demonstrated a dose-response relationship between exposure duration and disease risk." },
    { word: "causal inference", translation: "inférence causale", example: "Causal inference requires consideration of temporal sequence, consistency, and alternative explanations." },
    { word: "counterfactual framework", translation: "cadre contrefactuel", example: "Causal inference compares observed outcomes with counterfactual scenarios under different exposures." },
    { word: "systematic review", translation: "revue systématique", example: "The systematic review synthesized evidence across all published studies meeting inclusion criteria." },
    { word: "meta-analysis", translation: "méta-analyse", example: "The meta-analysis statistically combined results from multiple studies to estimate overall effect size." },
    { word: "evidence synthesis", translation: "synthèse des données probantes", example: "Evidence synthesis integrated findings from diverse study designs to inform policy recommendations." },
    
    // Santé publique appliquée et interventions (50 mots)
    { word: "health intervention", translation: "intervention sanitaire", example: "Effective health interventions address multiple levels from individual to structural factors." },
    { word: "preventive intervention", translation: "intervention préventive", example: "Preventive interventions focus on reducing risk factors before disease development." },
    { word: "public health program", translation: "programme de santé publique", example: "The public health program combined education, policy change, and environmental modifications." },
    { word: "health education", translation: "éducation sanitaire", example: "Health education provides knowledge and skills enabling informed health decisions." },
    { word: "behavior change communication", translation: "communication pour le changement de comportement", example: "Effective behavior change communication addresses barriers beyond information gaps." },
    { word: "social marketing", translation: "marketing social", example: "The social marketing campaign applied commercial techniques to promote public health behaviors." },
    { word: "community mobilization", translation: "mobilisation communautaire", example: "Community mobilization engages local stakeholders as active partners in health initiatives." },
    { word: "capacity building", translation: "renforcement des capacités", example: "Capacity building develops sustainable local expertise and infrastructure for ongoing programs." },
    { word: "implementation science", translation: "science de la mise en œuvre", example: "Implementation science studies methods to promote evidence-based practice adoption in real-world settings." },
    { word: "intervention fidelity", translation: "fidélité d'intervention", example: "The evaluation assessed intervention fidelity—the degree of adherence to the original program design." },
    { word: "scalability", translation: "extensibilité", example: "Intervention scalability depends on resource requirements, adaptability, and implementation complexity." },
    { word: "sustainability", translation: "pérennité", example: "Program sustainability requires institutional integration and stable funding mechanisms." },
    { word: "evaluation", translation: "évaluation", example: "Comprehensive evaluation examines both implementation processes and outcome achievements." },
    { word: "process evaluation", translation: "évaluation du processus", example: "Process evaluation documents how interventions were actually implemented across sites." },
    { word: "outcome evaluation", translation: "évaluation des résultats", example: "Outcome evaluation assesses whether the intervention achieved its intended effects." },
    { word: "impact evaluation", translation: "évaluation d'impact", example: "Impact evaluation determines causal attribution between program activities and observed changes." },
    { word: "program effectiveness", translation: "efficacité du programme", example: "Real-world program effectiveness often differs from efficacy demonstrated in controlled settings." },
    { word: "cost-effectiveness analysis", translation: "analyse coût-efficacité", example: "Cost-effectiveness analysis compares interventions based on expenses per health outcome achieved." },
    { word: "quality improvement", translation: "amélioration de la qualité", example: "Quality improvement uses iterative methods to enhance system performance and outcomes." },
    { word: "health system strengthening", translation: "renforcement du système de santé", example: "Health system strengthening builds capacity across service delivery, workforce, and governance domains." },
    { word: "policy intervention", translation: "intervention politique", example: "Policy interventions create supportive environments that facilitate healthy behaviors." },
    { word: "health legislation", translation: "législation sanitaire", example: "Health legislation provides legal frameworks for public health authorities and regulations." },
    { word: "regulation", translation: "réglementation", example: "Evidence-based regulations address environment, product safety, and service quality standards." },
    { word: "fiscal intervention", translation: "intervention fiscale", example: "Fiscal interventions use taxation and subsidies to influence health-related behaviors." },
    { word: "population screening", translation: "dépistage dans la population", example: "Population screening programs detect diseases at earlier, more treatable stages." },
    { word: "vaccination program", translation: "programme de vaccination", example: "Successful vaccination programs require both high coverage and public confidence." },
    { word: "immunization coverage", translation: "couverture vaccinale", example: "Immunization coverage monitoring identifies vulnerable populations needing targeted outreach." },
    { word: "surveillance system", translation: "système de surveillance", example: "The integrated surveillance system provides real-time data across multiple health conditions." },
    { word: "epidemic preparedness", translation: "préparation aux épidémies", example: "Epidemic preparedness requires maintained infrastructure, trained personnel, and response plans." },
    { word: "emergency response", translation: "intervention d'urgence", example: "Coordinated emergency response mobilizes resources quickly during public health crises." },
    { word: "containment strategy", translation: "stratégie de confinement", example: "The containment strategy aimed to identify and isolate cases before widespread community transmission." },
    { word: "contact tracing", translation: "recherche des contacts", example: "Digital technologies enhanced traditional contact tracing methods during the outbreak." },
    { word: "quarantine", translation: "quarantaine", example: "Quarantine separates exposed individuals to prevent disease transmission during the incubation period." },
    { word: "isolation", translation: "isolement", example: "Isolation separates infected individuals from the susceptible population to reduce transmission." },
    { word: "non-pharmaceutical intervention", translation: "intervention non pharmaceutique", example: "Non-pharmaceutical interventions include physical distancing, masks, and ventilation improvements." },
    { word: "risk communication", translation: "communication des risques", example: "Effective risk communication provides actionable information without causing undue alarm." },
    { word: "infodemic management", translation: "gestion de l'infodémie", example: "Infodemic management addresses misinformation that undermines public health responses." },
    { word: "health advocacy", translation: "plaidoyer pour la santé", example: "Health advocacy campaigns mobilize political support for policy and resource allocation." },
    { word: "harm reduction", translation: "réduction des risques", example: "Harm reduction approaches pragmatically decrease negative consequences without requiring abstinence." },
    { word: "health protection", translation: "protection de la santé", example: "Health protection measures safeguard populations from environmental and infectious threats." },
    { word: "sanitation", translation: "assainissement", example: "Improved sanitation infrastructure prevents numerous infectious diseases through waste management." },
    { word: "safe water", translation: "eau potable", example: "Access to safe water remains a fundamental public health priority globally." },
    { word: "food safety", translation: "sécurité alimentaire", example: "Food safety systems monitor production, processing, and distribution chains for contamination risks." },
    { word: "occupational health", translation: "santé au travail", example: "Occupational health programs address workplace hazards through engineering, administrative, and protective measures." },
    { word: "injury prevention", translation: "prévention des blessures", example: "Comprehensive injury prevention addresses environmental modifications, education, and enforcement." },
    { word: "maternal and child health", translation: "santé maternelle et infantile", example: "Maternal and child health programs provide continuum of care from pregnancy through early childhood." },
    { word: "primary healthcare", translation: "soins de santé primaires", example: "Strong primary healthcare systems provide essential preventive and treatment services." },
    { word: "health workforce", translation: "personnel de santé", example: "Sufficient health workforce distribution ensures service availability in all communities." },
    { word: "community health worker", translation: "agent de santé communautaire", example: "Community health workers extend formal healthcare system reach into underserved areas." },
    
    // Défis sanitaires mondiaux et perspectives (50 mots)
    { word: "global health challenge", translation: "défi sanitaire mondial", example: "Antimicrobial resistance represents a critical global health challenge requiring coordinated action." },
    { word: "emerging infectious disease", translation: "maladie infectieuse émergente", example: "Emerging infectious disease surveillance focuses on novel pathogens and changing transmission patterns." },
    { word: "antimicrobial resistance", translation: "résistance aux antimicrobiens", example: "Antimicrobial resistance threatens to render previously treatable infections untreatable." },
    { word: "neglected tropical disease", translation: "maladie tropicale négligée", example: "Neglected tropical diseases affect billions but receive disproportionately little research attention." },
    { word: "non-communicable disease epidemic", translation: "épidémie de maladies non transmissibles", example: "The global non-communicable disease epidemic requires addressing shared risk factors across conditions." },
    { word: "chronic disease burden", translation: "fardeau des maladies chroniques", example: "Low-income countries increasingly face double burdens of infectious and chronic disease." },
    { word: "demographic aging", translation: "vieillissement démographique", example: "Demographic aging creates new public health challenges in healthcare delivery and financing." },
    { word: "urbanization and health", translation: "urbanisation et santé", example: "Rapid urbanization presents both opportunities and challenges for population health." },
    { word: "health and migration", translation: "santé et migration", example: "Health and migration policies must address both migrant needs and public health considerations." },
    { word: "humanitarian health", translation: "santé humanitaire", example: "Humanitarian health interventions provide essential services during complex emergencies." },
    { word: "climate change and health", translation: "changement climatique et santé", example: "Climate change health impacts include direct effects of extreme weather and indirect consequences of ecological disruption." },
    { word: "food security", translation: "sécurité alimentaire", example: "Food security encompasses both sufficient nutritional availability and sustainable production systems." },
    { word: "malnutrition", translation: "malnutrition", example: "Malnutrition manifests as both undernutrition and excessive consumption of nutrient-poor foods." },
    { word: "food system", translation: "système alimentaire", example: "Healthier food systems balance nutritional needs, environmental sustainability, and economic viability." },
    { word: "nutrition transition", translation: "transition nutritionnelle", example: "Nutrition transition describes population dietary shifts accompanying economic development." },
    { word: "water insecurity", translation: "insécurité hydrique", example: "Water insecurity increasingly affects population health through multiple direct and indirect pathways." },
    { word: "air pollution", translation: "pollution atmosphérique", example: "Air pollution contributes to numerous health conditions beyond respiratory diseases." },
    { word: "environmental degradation", translation: "dégradation environnementale", example: "Environmental degradation threatens health through multiple ecosystem service disruptions." },
    { word: "biodiversity loss", translation: "perte de biodiversité", example: "Biodiversity loss increases disease emergence risks through altered ecological relationships." },
    { word: "mental health burden", translation: "fardeau de la santé mentale", example: "The global mental health burden receives insufficient attention despite enormous disability impacts." },
    { word: "substance use disorders", translation: "troubles liés à l'usage de substances", example: "Substance use disorders require integrated prevention, treatment, and harm reduction approaches." },
    { word: "health inequalities", translation: "inégalités en santé", example: "Health inequalities between and within countries often reflect broader socioeconomic disparities." },
    { word: "vulnerable populations", translation: "populations vulnérables", example: "Public health interventions must prioritize vulnerable populations facing disproportionate health risks." },
    { word: "gender and health", translation: "genre et santé", example: "Gender and health analysis examines how social constructs affect exposure, care access, and outcomes." },
    { word: "commercial determinants of health", translation: "déterminants commerciaux de la santé", example: "Commercial determinants of health include corporate activities influencing consumption patterns and regulations." },
    { word: "political determinants of health", translation: "déterminants politiques de la santé", example: "Political determinants of health include governance structures and power distributions affecting health resources." },
    { word: "health financing", translation: "financement de la santé", example: "Sustainable health financing balances adequate resource mobilization with financial protection." },
    { word: "universal health coverage", translation: "couverture sanitaire universelle", example: "Universal health coverage progress requires both service expansion and financial protection." },
    { word: "healthcare access", translation: "accès aux soins de santé", example: "Healthcare access encompasses availability, affordability, acceptability, and quality dimensions." },
    { word: "primary healthcare", translation: "soins de santé primaires", example: "Strong primary healthcare systems provide first-contact, comprehensive, and coordinated services." },
    { word: "health system resilience", translation: "résilience du système de santé", example: "Health system resilience involves absorptive, adaptive, and transformative capacities during crises." },
    { word: "global health security", translation: "sécurité sanitaire mondiale", example: "Global health security requires coordinated surveillance, response, and preparedness capacities." },
    { word: "global health governance", translation: "gouvernance mondiale de la santé", example: "Effective global health governance balances national sovereignty with collective action needs." },
    { word: "health diplomacy", translation: "diplomatie sanitaire", example: "Health diplomacy leverages health collaboration for broader international relations objectives." },
    { word: "sustainable development goals", translation: "objectifs de développement durable", example: "Health-related sustainable development goals address both specific conditions and broader determinants." },
    { word: "health system strengthening", translation: "renforcement du système de santé", example: "Health system strengthening builds capacity across governance, financing, workforce, and service delivery domains." },
    { word: "health information system", translation: "système d'information sanitaire", example: "Robust health information systems provide timely, accurate data for decisions at all levels." },
    { word: "digital health", translation: "santé numérique", example: "Digital health technologies extend service reach while creating new privacy and equity considerations." },
    { word: "telehealth", translation: "télésanté", example: "Telehealth adoption accelerated dramatically during pandemic-related access restrictions." },
    { word: "health innovation", translation: "innovation en santé", example: "Health innovation encompasses technological, organizational, and delivery model advances." },
    { word: "implementation research", translation: "recherche sur la mise en œuvre", example: "Implementation research examines how interventions function in real-world contexts." },
    { word: "translational research", translation: "recherche translationnelle", example: "Translational research bridges laboratory discoveries and clinical applications with population impact." },
    { word: "health technology assessment", translation: "évaluation des technologies de la santé", example: "Health technology assessment examines clinical, economic, ethical, and social implications of interventions." },
    { word: "precision public health", translation: "santé publique de précision", example: "Precision public health applies advanced analytics to tailor interventions for specific populations." },
    { word: "genomic epidemiology", translation: "épidémiologie génomique", example: "Genomic epidemiology uses pathogen sequencing to track transmission networks and evolution." },
    { word: "predictive modeling", translation: "modélisation prédictive", example: "Predictive modeling forecasts disease trends and intervention impacts for planning." },
    { word: "participatory approaches", translation: "approches participatives", example: "Participatory approaches engage affected communities as active partners throughout public health processes." },
    { word: "multisectoral action", translation: "action multisectorielle", example: "Addressing complex health challenges requires coordinated multisectoral action beyond healthcare alone." },
    { word: "health resilience", translation: "résilience sanitaire", example: "Population health resilience depends on both individual and community-level adaptive capacities." },
    { word: "planetary health", translation: "santé planétaire", example: "Planetary health addresses human health impacts of anthropogenic environmental and ecological changes." }
  ]
};