export const vocab = {
  title: "Psychologie et Comportement Humain",
  words: [
    // Psychologie cognitive (25 mots)
    { word: "cognitive psychology", translation: "psychologie cognitive", example: "Cognitive psychology studies mental processes including perception, memory, and reasoning." },
    { word: "working memory", translation: "mémoire de travail", example: "Working memory temporarily stores and manipulates information for complex tasks." },
    { word: "long-term memory", translation: "mémoire à long terme", example: "Long-term memory stores information for extended periods, potentially indefinitely." },
    { word: "attention", translation: "attention", example: "Selective attention allows us to focus on relevant stimuli while ignoring distractions." },
    { word: "perception", translation: "perception", example: "Perception involves organizing and interpreting sensory information to understand the environment." },
    { word: "cognitive bias", translation: "biais cognitif", example: "Confirmation bias leads people to favor information supporting existing beliefs." },
    { word: "metacognition", translation: "métacognition", example: "Metacognition involves thinking about one's own thought processes." },
    { word: "problem-solving", translation: "résolution de problèmes", example: "Problem-solving requires identifying, analyzing, and overcoming obstacles to achieve goals." },
    { word: "decision-making", translation: "prise de décision", example: "Decision-making research examines how people evaluate options and make choices." },
    { word: "executive function", translation: "fonction exécutive", example: "Executive functions include cognitive processes that regulate thought and behavior." },
    { word: "cognitive load", translation: "charge cognitive", example: "High cognitive load reduces performance on simultaneous mental tasks." },
    { word: "schema", translation: "schéma", example: "Schemas are mental frameworks that organize knowledge about specific concepts." },
    { word: "heuristic", translation: "heuristique", example: "Heuristics are mental shortcuts that facilitate quick but sometimes inaccurate decisions." },
    { word: "cognitive dissonance", translation: "dissonance cognitive", example: "Cognitive dissonance occurs when holding contradictory beliefs causes psychological discomfort." },
    { word: "mental model", translation: "modèle mental", example: "Mental models represent how systems work in the real world." },
    { word: "cognitive processing", translation: "traitement cognitif", example: "Cognitive processing speed affects how quickly information can be analyzed." },
    { word: "information processing", translation: "traitement de l'information", example: "Information processing involves encoding, storing, and retrieving data." },
    { word: "cognitive flexibility", translation: "flexibilité cognitive", example: "Cognitive flexibility allows adaptation to changing task requirements." },
    { word: "reasoning", translation: "raisonnement", example: "Reasoning involves drawing conclusions from principles and evidence." },
    { word: "cognitive neuroscience", translation: "neuroscience cognitive", example: "Cognitive neuroscience explores neural mechanisms underlying mental processes." },
    { word: "cognitive architecture", translation: "architecture cognitive", example: "Cognitive architecture describes the structure of mental processes and representations." },
    { word: "cognitive development", translation: "développement cognitif", example: "Cognitive development traces how thinking evolves from childhood to adulthood." },
    { word: "prospective memory", translation: "mémoire prospective", example: "Prospective memory involves remembering to perform future actions." },
    { word: "episodic memory", translation: "mémoire épisodique", example: "Episodic memory stores autobiographical events and experiences." },
    { word: "semantic memory", translation: "mémoire sémantique", example: "Semantic memory contains general knowledge about the world." },
    
    // Neurosciences (25 mots)
    { word: "neuroscience", translation: "neuroscience", example: "Neuroscience investigates the structure and function of the nervous system." },
    { word: "neural network", translation: "réseau neuronal", example: "Neural networks process information through interconnected neurons." },
    { word: "neurotransmitter", translation: "neurotransmetteur", example: "Neurotransmitters communicate signals between neurons across synapses." },
    { word: "neuroplasticity", translation: "neuroplasticité", example: "Neuroplasticity allows the brain to reorganize itself by forming new neural connections." },
    { word: "neuroimaging", translation: "neuroimagerie", example: "Neuroimaging techniques visualize brain structure and activity." },
    { word: "functional MRI", translation: "IRM fonctionnelle", example: "Functional MRI detects brain activity by measuring blood flow changes." },
    { word: "synaptic transmission", translation: "transmission synaptique", example: "Synaptic transmission conveys signals between neurons through chemical messengers." },
    { word: "neural pathway", translation: "voie neuronale", example: "Neural pathways connect different brain regions for specific functions." },
    { word: "prefrontal cortex", translation: "cortex préfrontal", example: "The prefrontal cortex plays key roles in planning and decision-making." },
    { word: "neuronal firing", translation: "décharge neuronale", example: "Neuronal firing patterns encode and transmit information throughout the brain." },
    { word: "neurogenesis", translation: "neurogénèse", example: "Adult neurogenesis creates new neurons in specific brain regions." },
    { word: "neurodegenerative disease", translation: "maladie neurodégénérative", example: "Neurodegenerative diseases involve progressive neuronal damage and death." },
    { word: "neural correlate", translation: "corrélat neuronal", example: "Researchers identified neural correlates of conscious visual perception." },
    { word: "neurocognitive", translation: "neurocognitif", example: "Neurocognitive assessment evaluates cognitive functions and related brain activity." },
    { word: "neural substrate", translation: "substrat neuronal", example: "The experiment identified neural substrates underlying emotion regulation." },
    { word: "neurochemistry", translation: "neurochimie", example: "Neurochemistry examines chemical processes in the nervous system." },
    { word: "neuromodulation", translation: "neuromodulation", example: "Neuromodulation alters neural activity through targeted stimulation." },
    { word: "electrophysiology", translation: "électrophysiologie", example: "Electrophysiology measures electrical activity in neurons and neural tissues." },
    { word: "neuroimaging technique", translation: "technique de neuroimagerie", example: "Advanced neuroimaging techniques reveal brain connectivity patterns." },
    { word: "neurotransmission", translation: "neurotransmission", example: "Neurotransmission enables communication between neurons through chemical signals." },
    { word: "neural oscillation", translation: "oscillation neuronale", example: "Neural oscillations represent synchronized activity across brain regions." },
    { word: "neural circuit", translation: "circuit neuronal", example: "Neural circuits process specific types of information in the brain." },
    { word: "neural coding", translation: "codage neuronal", example: "Neural coding transforms sensory information into patterns of neuronal activity." },
    { word: "brain connectivity", translation: "connectivité cérébrale", example: "Brain connectivity studies examine connections between neural networks." },
    { word: "optogenetics", translation: "optogénétique", example: "Optogenetics controls neurons using light-responsive proteins." },
    
    // Psychologie sociale (25 mots)
    { word: "social psychology", translation: "psychologie sociale", example: "Social psychology examines how people's thoughts and behaviors are influenced by others." },
    { word: "social influence", translation: "influence sociale", example: "Social influence processes include conformity, compliance, and obedience." },
    { word: "group dynamics", translation: "dynamique de groupe", example: "Group dynamics involve patterns of interaction within and between social groups." },
    { word: "social cognition", translation: "cognition sociale", example: "Social cognition explores how people process, store, and apply information about others." },
    { word: "social identity", translation: "identité sociale", example: "Social identity derives from perceived membership in specific groups." },
    { word: "attitudes", translation: "attitudes", example: "Attitudes are evaluative responses toward people, objects, or ideas." },
    { word: "prejudice", translation: "préjugé", example: "Prejudice involves negative attitudes toward groups based on their characteristics." },
    { word: "stereotyping", translation: "stéréotypage", example: "Stereotyping applies oversimplified generalizations to social groups." },
    { word: "attribution theory", translation: "théorie de l'attribution", example: "Attribution theory examines how people explain causes of behavior and events." },
    { word: "self-concept", translation: "concept de soi", example: "Self-concept encompasses beliefs about one's own attributes and identity." },
    { word: "conformity", translation: "conformité", example: "Conformity occurs when people adjust behavior to match social norms." },
    { word: "social norm", translation: "norme sociale", example: "Social norms are implicit rules governing acceptable behavior in groups." },
    { word: "groupthink", translation: "pensée de groupe", example: "Groupthink happens when cohesive groups prioritize consensus over critical thinking." },
    { word: "social facilitation", translation: "facilitation sociale", example: "Social facilitation describes improved performance on simple tasks in others' presence." },
    { word: "social loafing", translation: "flânerie sociale", example: "Social loafing involves reduced individual effort when working in groups." },
    { word: "persuasion", translation: "persuasion", example: "Persuasion research examines factors that influence attitude change." },
    { word: "deindividuation", translation: "désindividuation", example: "Deindividuation describes reduced self-awareness in group situations." },
    { word: "bystander effect", translation: "effet du témoin", example: "The bystander effect reduces likelihood of helping when others are present." },
    { word: "implicit bias", translation: "biais implicite", example: "Implicit bias influences behavior unconsciously despite explicit beliefs." },
    { word: "social perception", translation: "perception sociale", example: "Social perception involves forming impressions of others' characteristics." },
    { word: "social dilemma", translation: "dilemme social", example: "Social dilemmas pit individual interests against collective welfare." },
    { word: "intergroup relations", translation: "relations intergroupes", example: "Intergroup relations research examines how groups interact with each other." },
    { word: "prosocial behavior", translation: "comportement prosocial", example: "Prosocial behavior benefits others without anticipated external rewards." },
    { word: "social exchange theory", translation: "théorie de l'échange social", example: "Social exchange theory views relationships as cost-benefit analyses." },
    { word: "collective behavior", translation: "comportement collectif", example: "Collective behavior emerges when groups act together without formal organization." },
    
    // Théories de la personnalité (25 mots)
    { word: "personality theory", translation: "théorie de la personnalité", example: "Personality theory explains consistent patterns in behavior, thought, and emotion." },
    { word: "trait theory", translation: "théorie des traits", example: "Trait theory identifies stable characteristics that predict behavior across situations." },
    { word: "Big Five personality traits", translation: "modèle des Big Five", example: "The Big Five personality traits include openness, conscientiousness, extraversion, agreeableness, and neuroticism." },
    { word: "psychoanalytic theory", translation: "théorie psychanalytique", example: "Psychoanalytic theory emphasizes unconscious processes influencing behavior." },
    { word: "humanistic psychology", translation: "psychologie humaniste", example: "Humanistic psychology focuses on personal growth and self-actualization." },
    { word: "behavioral theory", translation: "théorie behavioriste", example: "Behavioral theory explains personality development through learning and reinforcement." },
    { word: "social-cognitive theory", translation: "théorie sociocognitive", example: "Social-cognitive theory examines how personal factors interact with environment and behavior." },
    { word: "temperament", translation: "tempérament", example: "Temperament refers to biologically-based behavioral tendencies present from birth." },
    { word: "personality assessment", translation: "évaluation de la personnalité", example: "Personality assessment uses standardized measures to evaluate traits and characteristics." },
    { word: "self-concept", translation: "concept de soi", example: "Self-concept encompasses beliefs about one's own attributes and identity." },
    { word: "personality development", translation: "développement de la personnalité", example: "Personality development traces how individual characteristics evolve throughout life." },
    { word: "unconscious mind", translation: "inconscient", example: "Psychoanalytic approaches emphasize the unconscious mind's influence on personality." },
    { word: "defense mechanism", translation: "mécanisme de défense", example: "Defense mechanisms protect against anxiety and threatening impulses." },
    { word: "self-actualization", translation: "auto-actualisation", example: "Self-actualization involves realizing one's full potential and abilities." },
    { word: "locus of control", translation: "lieu de contrôle", example: "Locus of control reflects beliefs about internal versus external control over outcomes." },
    { word: "self-efficacy", translation: "auto-efficacité", example: "Self-efficacy represents confidence in one's ability to accomplish specific tasks." },
    { word: "dispositional trait", translation: "trait dispositionnel", example: "Dispositional traits are stable characteristics influencing behavior across situations." },
    { word: "psychodynamic theory", translation: "théorie psychodynamique", example: "Psychodynamic theory emphasizes unconscious motivations and early experiences." },
    { word: "person-situation debate", translation: "débat personne-situation", example: "The person-situation debate addresses whether personality or context better predicts behavior." },
    { word: "personal construct", translation: "construit personnel", example: "Personal constructs are individual frameworks for interpreting experience." },
    { word: "trait dimension", translation: "dimension de trait", example: "Trait dimensions represent continuous scales of personality characteristics." },
    { word: "collective unconscious", translation: "inconscient collectif", example: "The collective unconscious contains shared ancestral memories and archetypes." },
    { word: "ego development", translation: "développement de l'ego", example: "Ego development involves progressive integration of personality facets." },
    { word: "personality typology", translation: "typologie de personnalité", example: "Personality typologies classify people into distinct categories based on characteristics." },
    { word: "identity formation", translation: "formation de l'identité", example: "Identity formation establishes a coherent sense of self across contexts." },
    
    // Psychologie du développement (25 mots)
    { word: "developmental psychology", translation: "psychologie du développement", example: "Developmental psychology studies how people change throughout the lifespan." },
    { word: "cognitive development", translation: "développement cognitif", example: "Cognitive development traces how thinking abilities evolve from childhood to adulthood." },
    { word: "attachment theory", translation: "théorie de l'attachement", example: "Attachment theory examines emotional bonds between infants and caregivers." },
    { word: "socialization", translation: "socialisation", example: "Socialization is the process of learning to function within society's norms." },
    { word: "developmental milestone", translation: "étape du développement", example: "Developmental milestones represent significant achievements in growth and ability." },
    { word: "developmental stage", translation: "stade de développement", example: "Developmental stages represent distinct periods with characteristic challenges." },
    { word: "identity development", translation: "développement identitaire", example: "Identity development involves establishing a coherent sense of self." },
    { word: "moral development", translation: "développement moral", example: "Moral development traces how ethical reasoning evolves throughout life." },
    { word: "developmental trajectory", translation: "trajectoire développementale", example: "Individual developmental trajectories may deviate from typical patterns." },
    { word: "developmental transition", translation: "transition développementale", example: "Developmental transitions involve significant changes in cognitive or social function." },
    { word: "developmental task", translation: "tâche développementale", example: "Developmental tasks are challenges specific to particular life stages." },
    { word: "sensitive period", translation: "période sensible", example: "Sensitive periods represent optimal windows for developing specific abilities." },
    { word: "developmental context", translation: "contexte développemental", example: "Developmental context includes environmental factors influencing growth and maturation." },
    { word: "scaffolding", translation: "étayage", example: "Scaffolding provides temporary support to help children master new skills." },
    { word: "developmental psychopathology", translation: "psychopathologie développementale", example: "Developmental psychopathology examines disorder origins in normal development." },
    { word: "socioemotional development", translation: "développement socio-émotionnel", example: "Socioemotional development involves understanding and regulating emotions in social contexts." },
    { word: "developmental theory", translation: "théorie développementale", example: "Developmental theories explain patterns and mechanisms of human growth." },
    { word: "lifespan development", translation: "développement tout au long de la vie", example: "Lifespan development examines changes from conception through old age." },
    { word: "developmental neuroscience", translation: "neuroscience développementale", example: "Developmental neuroscience studies brain maturation and behavioral changes." },
    { word: "developmental delay", translation: "retard de développement", example: "Developmental delay indicates significantly slower achievement of milestones." },
    { word: "ecological systems theory", translation: "théorie des systèmes écologiques", example: "Ecological systems theory examines development within nested environmental contexts." },
    { word: "zone of proximal development", translation: "zone proximale de développement", example: "The zone of proximal development represents the gap between independent and assisted performance." },
    { word: "developmental plasticity", translation: "plasticité développementale", example: "Developmental plasticity allows adaptation to varied environmental conditions." },
    { word: "developmental resilience", translation: "résilience développementale", example: "Developmental resilience enables positive outcomes despite adverse circumstances." },
    { word: "developmental intervention", translation: "intervention développementale", example: "Developmental interventions address delays or optimize typical development." },
    
    // Psychopathologie (25 mots)
    { word: "psychopathology", translation: "psychopathologie", example: "Psychopathology studies mental disorders' origins, development, and manifestations." },
    { word: "mental disorder", translation: "trouble mental", example: "Mental disorders involve clinically significant disturbances in cognition, emotion, or behavior." },
    { word: "anxiety disorder", translation: "trouble anxieux", example: "Anxiety disorders feature excessive fear and related behavioral disturbances." },
    { word: "mood disorder", translation: "trouble de l'humeur", example: "Mood disorders involve persistent alterations in emotional state." },
    { word: "major depression", translation: "dépression majeure", example: "Major depression features persistent sadness and diminished interest in activities." },
    { word: "bipolar disorder", translation: "trouble bipolaire", example: "Bipolar disorder involves alternating episodes of mania and depression." },
    { word: "schizophrenia", translation: "schizophrénie", example: "Schizophrenia features distortions in thinking, perception, emotions, and behavior." },
    { word: "personality disorder", translation: "trouble de la personnalité", example: "Personality disorders involve enduring patterns of maladaptive behavior and experience." },
    { word: "obsessive-compulsive disorder", translation: "trouble obsessionnel-compulsif", example: "Obsessive-compulsive disorder features intrusive thoughts and repetitive behaviors." },
    { word: "post-traumatic stress disorder", translation: "trouble de stress post-traumatique", example: "Post-traumatic stress disorder develops following exposure to traumatic events." },
    { word: "clinical assessment", translation: "évaluation clinique", example: "Clinical assessment gathers information for diagnosis and treatment planning." },
    { word: "psychological disorder", translation: "trouble psychologique", example: "Psychological disorders significantly impair functioning and well-being." },
    { word: "comorbidity", translation: "comorbidité", example: "Comorbidity refers to the co-occurrence of multiple disorders in one individual." },
    { word: "symptomatology", translation: "symptomatologie", example: "Symptomatology describes characteristic manifestations of specific disorders." },
    { word: "psychological diagnosis", translation: "diagnostic psychologique", example: "Psychological diagnosis identifies disorders based on symptom patterns." },
    { word: "etiology", translation: "étiologie", example: "Etiology studies the causes and origins of psychological disorders." },
    { word: "psychotic disorder", translation: "trouble psychotique", example: "Psychotic disorders involve distortions in thought and perception." },
    { word: "psychosocial stressor", translation: "facteur de stress psychosocial", example: "Psychosocial stressors contribute to disorder development and exacerbation." },
    { word: "clinical presentation", translation: "présentation clinique", example: "Clinical presentation includes observable symptoms and subjective experiences." },
    { word: "neurodevelopmental disorder", translation: "trouble neurodéveloppemental", example: "Neurodevelopmental disorders emerge during developmental periods." },
    { word: "pathological", translation: "pathologique", example: "Pathological behaviors significantly deviate from normal functioning." },
    { word: "clinical significance", translation: "signification clinique", example: "Clinical significance distinguishes normal variation from disorder." },
    { word: "differential diagnosis", translation: "diagnostic différentiel", example: "Differential diagnosis distinguishes between disorders with similar presentations." },
    { word: "epidemiology", translation: "épidémiologie", example: "Psychiatric epidemiology studies disorder distribution and determinants." },
    { word: "psychiatric classification", translation: "classification psychiatrique", example: "Psychiatric classification systems organize disorders into diagnostic categories." },
    
    // Thérapies et traitements (25 mots)
    { word: "psychotherapy", translation: "psychothérapie", example: "Psychotherapy uses psychological methods to address mental disorders and well-being." },
    { word: "cognitive-behavioral therapy", translation: "thérapie cognitivo-comportementale", example: "Cognitive-behavioral therapy addresses dysfunctional thoughts, feelings, and behaviors." },
    { word: "psychoanalysis", translation: "psychanalyse", example: "Psychoanalysis explores unconscious motivations through techniques like free association." },
    { word: "humanistic therapy", translation: "thérapie humaniste", example: "Humanistic therapy emphasizes personal growth and self-actualization." },
    { word: "therapeutic alliance", translation: "alliance thérapeutique", example: "The therapeutic alliance between clinician and client facilitates treatment effectiveness." },
    { word: "exposure therapy", translation: "thérapie d'exposition", example: "Exposure therapy gradually confronts feared situations to reduce anxiety." },
    { word: "psychopharmacology", translation: "psychopharmacologie", example: "Psychopharmacology uses medications to treat mental disorders." },
    { word: "interpersonal therapy", translation: "thérapie interpersonnelle", example: "Interpersonal therapy addresses relationship issues underlying depression." },
    { word: "dialectical behavior therapy", translation: "thérapie comportementale dialectique", example: "Dialectical behavior therapy combines acceptance and change strategies." },
    { word: "mindfulness-based therapy", translation: "thérapie basée sur la pleine conscience", example: "Mindfulness-based therapy incorporates present-moment awareness practices." },
    { word: "clinical intervention", translation: "intervention clinique", example: "Clinical interventions address specific symptoms or behavioral patterns." },
    { word: "evidence-based practice", translation: "pratique fondée sur des preuves", example: "Evidence-based practice integrates research findings with clinical expertise." },
    { word: "therapeutic technique", translation: "technique thérapeutique", example: "The therapeutic technique helped clients recognize automatic negative thoughts." },
    { word: "therapeutic outcome", translation: "résultat thérapeutique", example: "Therapeutic outcome measures assess intervention effectiveness." },
    { word: "behavioral activation", translation: "activation comportementale", example: "Behavioral activation increases engagement in rewarding activities." },
    { word: "family therapy", translation: "thérapie familiale", example: "Family therapy addresses issues affecting the entire family system." },
    { word: "group therapy", translation: "thérapie de groupe", example: "Group therapy provides therapeutic support through shared experiences." },
    { word: "clinical formulation", translation: "formulation clinique", example: "Clinical formulation explains problems from a theoretical perspective." },
    { word: "therapeutic modality", translation: "modalité thérapeutique", example: "The therapeutic modality was selected based on presenting symptoms." },
    { word: "relapse prevention", translation: "prévention de la rechute", example: "Relapse prevention strategies maintain treatment gains long-term." },
    { word: "psychological treatment", translation: "traitement psychologique", example: "Psychological treatment effectiveness varies across disorders and individuals." },
    { word: "therapeutic process", translation: "processus thérapeutique", example: "The therapeutic process involves complex interpersonal dynamics." },
    { word: "insight-oriented therapy", translation: "thérapie axée sur la prise de conscience", example: "Insight-oriented therapy promotes understanding of unconscious patterns." },
    { word: "treatment planning", translation: "planification du traitement", example: "Treatment planning establishes intervention goals and methods." },
    { word: "therapeutic change", translation: "changement thérapeutique", example: "Therapeutic change involves complex psychological and behavioral processes." },
    
    // Psychologie positive et bien-être (25 mots)
    { word: "positive psychology", translation: "psychologie positive", example: "Positive psychology studies factors that enable individuals and communities to thrive." },
    { word: "well-being", translation: "bien-être", example: "Psychological well-being encompasses positive functioning across multiple life domains." },
    { word: "flourishing", translation: "épanouissement", example: "Flourishing represents optimal psychological and social functioning." },
    { word: "life satisfaction", translation: "satisfaction de vie", example: "Life satisfaction reflects subjective evaluation of overall life quality." },
    { word: "resilience", translation: "résilience", example: "Psychological resilience enables adaptation to stress, adversity, and trauma." },
    { word: "character strengths", translation: "forces de caractère", example: "Character strengths represent positive traits linked to well-being." },
    { word: "mindfulness", translation: "pleine conscience", example: "Mindfulness involves non-judgmental awareness of present moment experience." },
    { word: "flow", translation: "flux", example: "Flow describes complete absorption in optimally challenging activities." },
    { word: "subjective well-being", translation: "bien-être subjectif", example: "Subjective well-being includes both affective and cognitive evaluations of life." },
    { word: "positive emotion", translation: "émotion positive", example: "Positive emotions broaden attention and build personal resources." },
    { word: "psychological well-being", translation: "bien-être psychologique", example: "Psychological well-being involves autonomy, purpose, and personal growth." },
    { word: "meaning in life", translation: "sens de la vie", example: "Meaning in life contributes significantly to psychological well-being." },
    { word: "post-traumatic growth", translation: "croissance post-traumatique", example: "Post-traumatic growth describes positive psychological change following adversity." },
    { word: "optimism", translation: "optimisme", example: "Dispositional optimism involves positive expectations about the future." },
    { word: "gratitude", translation: "gratitude", example: "Gratitude practice enhances happiness and relationship satisfaction." },
    { word: "psychological capital", translation: "capital psychologique", example: "Psychological capital includes hope, efficacy, resilience, and optimism." },
    { word: "self-determination", translation: "autodétermination", example: "Self-determination theory identifies autonomy, competence, and relatedness as basic needs." },
    { word: "self-compassion", translation: "auto-compassion", example: "Self-compassion involves treating oneself with kindness during difficult times." },
    { word: "emotional intelligence", translation: "intelligence émotionnelle", example: "Emotional intelligence enables understanding and managing emotions effectively." },
    { word: "eudaimonic well-being", translation: "bien-être eudémonique", example: "Eudaimonic well-being emphasizes meaning and self-realization over pleasure." },
    { word: "hedonic well-being", translation: "bien-être hédonique", example: "Hedonic well-being focuses on pleasure and happiness." },
    { word: "positive relationships", translation: "relations positives", example: "Positive relationships provide social support and foster psychological health." },
    { word: "life purpose", translation: "but dans la vie", example: "Life purpose provides direction and meaning to long-term goals." },
    { word: "strengths-based approach", translation: "approche basée sur les forces", example: "Strengths-based approaches leverage existing capabilities rather than fixing deficits." },
    { word: "happiness intervention", translation: "intervention sur le bonheur", example: "Evidence-based happiness interventions enhance well-being through specific activities." },
    
    // Émotions et motivation (25 mots)
    { word: "emotion", translation: "émotion", example: "Emotions are complex psychological states involving subjective experience, expression, and physiology." },
    { word: "motivation", translation: "motivation", example: "Motivation directs behavior toward particular goals or outcomes." },
    { word: "emotional regulation", translation: "régulation émotionnelle", example: "Emotional regulation involves modifying emotional experiences and expressions." },
    { word: "emotional intelligence", translation: "intelligence émotionnelle", example: "Emotional intelligence enables understanding and managing emotions effectively." },
    { word: "basic emotion", translation: "émotion de base", example: "Basic emotions like fear and joy appear consistently across cultures." },
    { word: "emotional expression", translation: "expression émotionnelle", example: "Emotional expression communicates internal states through behavior and physiology." },
    { word: "intrinsic motivation", translation: "motivation intrinsèque", example: "Intrinsic motivation drives behavior through inherent satisfaction rather than external rewards." },
    { word: "extrinsic motivation", translation: "motivation extrinsèque", example: "Extrinsic motivation involves engaging in behavior for external rewards or outcomes." },
    { word: "emotional contagion", translation: "contagion émotionnelle", example: "Emotional contagion occurs when people unconsciously mimic others' emotional states." },
    { word: "incentive", translation: "incitation", example: "Incentives motivate behavior through anticipated rewards or consequences." },
    { word: "goal-directed behavior", translation: "comportement dirigé vers un but", example: "Goal-directed behavior involves actions intended to achieve specific outcomes." },
    { word: "affective science", translation: "science affective", example: "Affective science investigates emotional and motivational processes." },
    { word: "reward system", translation: "système de récompense", example: "Neural reward systems reinforce beneficial behaviors through positive feelings." },
    { word: "achievement motivation", translation: "motivation d'accomplissement", example: "Achievement motivation drives behavior aimed at mastering skills and attaining success." },
    { word: "cognitive appraisal", translation: "évaluation cognitive", example: "Cognitive appraisal theories propose that emotions result from evaluating situations." },
    { word: "approach motivation", translation: "motivation d'approche", example: "Approach motivation directs behavior toward positive stimuli or outcomes." },
    { word: "avoidance motivation", translation: "motivation d'évitement", example: "Avoidance motivation directs behavior away from negative stimuli or outcomes." },
    { word: "emotional dysregulation", translation: "dysrégulation émotionnelle", example: "Emotional dysregulation involves difficulty managing and responding to emotions." },
    { word: "self-determination theory", translation: "théorie de l'autodétermination", example: "Self-determination theory identifies autonomy, competence, and relatedness as basic needs." },
    { word: "drive theory", translation: "théorie des pulsions", example: "Drive theory proposes that internal tensions motivate behavior to restore equilibrium." },
    { word: "expectancy-value theory", translation: "théorie attente-valeur", example: "Expectancy-value theory suggests motivation depends on expected success and value placed on outcomes." },
    { word: "emotional valence", translation: "valence émotionnelle", example: "Emotional valence describes whether emotions are positive or negative." },
    { word: "emotional arousal", translation: "activation émotionnelle", example: "Emotional arousal reflects physiological and psychological intensity." },
    { word: "social motivation", translation: "motivation sociale", example: "Social motivation drives behavior aimed at establishing and maintaining relationships." },
    { word: "need hierarchy", translation: "hiérarchie des besoins", example: "Maslow's need hierarchy places physiological and safety needs before self-actualization." },
    
    // Psychologie appliquée (25 mots)
    { word: "applied psychology", translation: "psychologie appliquée", example: "Applied psychology uses psychological principles to solve practical problems." },
    { word: "organizational psychology", translation: "psychologie organisationnelle", example: "Organizational psychology improves workplace effectiveness and employee well-being." },
    { word: "clinical psychology", translation: "psychologie clinique", example: "Clinical psychology assesses and treats psychological disorders and distress." },
    { word: "health psychology", translation: "psychologie de la santé", example: "Health psychology examines psychological factors in health, illness, and healthcare." },
    { word: "educational psychology", translation: "psychologie de l'éducation", example: "Educational psychology applies psychological principles to learning and instruction." },
    { word: "forensic psychology", translation: "psychologie légale", example: "Forensic psychology applies psychological knowledge to legal issues and the justice system." },
    { word: "sports psychology", translation: "psychologie du sport", example: "Sports psychology enhances athletic performance and well-being." },
    { word: "consumer psychology", translation: "psychologie du consommateur", example: "Consumer psychology studies how thoughts, beliefs, and perceptions influence purchasing behavior." },
    { word: "environmental psychology", translation: "psychologie environnementale", example: "Environmental psychology examines relationships between people and physical settings." },
    { word: "behavior modification", translation: "modification du comportement", example: "Behavior modification applies learning principles to change maladaptive behaviors." },
    { word: "psychological assessment", translation: "évaluation psychologique", example: "Psychological assessment uses tests and observations to evaluate functioning." },
    { word: "psychological intervention", translation: "intervention psychologique", example: "Psychological interventions address specific problems or enhance functioning." },
    { word: "psychological consultation", translation: "consultation psychologique", example: "Psychological consultation provides expert advice to individuals or organizations." },
    { word: "evidence-based practice", translation: "pratique fondée sur des preuves", example: "Evidence-based practice integrates research evidence with clinical expertise." },
    { word: "effectiveness research", translation: "recherche sur l'efficacité", example: "Effectiveness research evaluates intervention outcomes in real-world settings." },
    { word: "coaching psychology", translation: "psychologie du coaching", example: "Coaching psychology facilitates goal achievement and performance enhancement." },
    { word: "human factors psychology", translation: "psychologie des facteurs humains", example: "Human factors psychology improves product and system design for human use." },
    { word: "psychological practice", translation: "pratique psychologique", example: "Ethical guidelines govern psychological practice across specialties." },
    { word: "psychological service", translation: "service psychologique", example: "Psychological services provide assessment, intervention, and consultation." },
    { word: "community psychology", translation: "psychologie communautaire", example: "Community psychology addresses social issues affecting psychological well-being." },
    { word: "behavior analysis", translation: "analyse du comportement", example: "Applied behavior analysis uses learning principles to improve socially significant behaviors." },
    { word: "industrial-organizational psychology", translation: "psychologie du travail et des organisations", example: "Industrial-organizational psychology enhances workplace productivity and quality of life." },
    { word: "rehabilitation psychology", translation: "psychologie de la réadaptation", example: "Rehabilitation psychology helps people with disabilities maximize function and well-being." },
    { word: "program evaluation", translation: "évaluation de programme", example: "Program evaluation assesses effectiveness of psychological interventions and services." },
    { word: "occupational health psychology", translation: "psychologie de la santé au travail", example: "Occupational health psychology promotes safety, health, and well-being in the workplace." }
  ]
};